/* Assamese.
 *
 * Written in the Bengali script, with ৰ and ৱ where Bengali uses র and ব — a
 * font that carries Bengali carries this, which is why locales.ts gives the two
 * the same stack and why this is not a separate script decision.
 *
 * One word per term: scholarship বৃত্তি, application আবেদন, document নথি,
 * disability দিব্যাংগতা, verified সত্যাপিত, eligible যোগ্য,
 * certificate প্ৰমাণপত্ৰ.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const asm: Dict = {
  'app.name': 'ইণ্ডিক এআই বৃত্তি',
  'app.tagline': 'দিব্যাং শিক্ষাৰ্থীসকলৰ বাবে',
  'app.yourApplication': 'আপোনাৰ আবেদন · {title}',

  'nav.find': 'বৃত্তি',
  'nav.how': 'এইটো কেনেকৈ কাম কৰে',
  'nav.matches': 'মোৰ মিল',
  'nav.applications': 'মোৰ আবেদন',
  'nav.documents': 'মোৰ নথি',
  'nav.profile': 'মোৰ প্ৰোফাইল',
  'nav.privacy': 'মোৰ তথ্য',
  'nav.account': 'মোৰ একাউণ্ট',
  'nav.register': 'ছাইন আপ',
  'nav.language': 'ভাষা',
  'footer.social': 'ইণ্ডিক এআই অন্যত্ৰ',
  'footer.sponsor': 'সহযোগিতাত',
  'footer.copyright': 'কপিৰাইট © {year} ইণ্ডিক এআই | সৰ্বস্বত্ব সংৰক্ষিত',
  'nav.signin': 'ছাইন ইন',
  'nav.signout': 'ছাইন আউট',
  'nav.skip': 'মূল বিষয়বস্তুলৈ যাওক',

  'public.title': 'আপুনি যোগ্য হোৱা বৃত্তি বিচাৰক',
  'public.lede': 'ইয়াত থকা প্ৰতিটো বৃত্তি দিব্যাং শিক্ষাৰ্থীসকলৰ বাবে মুকলি। চাবলৈ একাউণ্টৰ প্ৰয়োজন নাই।',
  'public.search': 'নাম বা শব্দৰে বিচাৰক',
  'public.filter.disability': 'দিব্যাংগতাৰ প্ৰকাৰ',
  'public.filter.qualification': 'যোগ্যতা',
  'public.filter.state': 'আপোনাৰ ৰাজ্য',
  'public.filter.provider': 'কোনে দিছে',
  'public.filter.any': 'যিকোনো',
  'public.filter.anyDisability': 'যিকোনো দিব্যাংগতা',
  'public.filter.anyQualification': 'যিকোনো যোগ্যতা',
  'public.filter.allStates': 'সকলো ৰাজ্য',
  'public.filter.gender': 'লিংগ',
  'public.filter.anyGender': 'যিকোনো লিংগ',
  'public.filter.course': 'পাঠ্যক্ৰম',
  'public.filter.anyCourse': 'যিকোনো পাঠ্যক্ৰম',
  'public.filter.where': 'আপুনি কোত পঢ়ে',
  'public.filter.anyWhere': 'ভাৰত বা বিদেশ',
  'public.filter.inIndia': 'ভাৰতত',
  'public.filter.abroad': 'বিদেশত অধ্যয়ন',
  'public.filters': 'ফিল্টাৰ',
  'public.clear': 'আঁতৰাওক',
  'public.results': 'বৃত্তি এতিয়া মুকলি',
  'public.searching': 'বিচাৰি থকা হৈছে…',
  'public.none': 'এই ফিল্টাৰবোৰৰ সৈতে কোনো বৃত্তি মিলা নাই',
  'public.none.hint': 'এটা ফিল্টাৰ আঁতৰাই চাওক। গোটেই বছৰ নতুন আঁচনি মুকলি হয়।',
  'public.none.clear': 'সকলো ফিল্টাৰ আঁতৰাওক',
  'public.empty': 'ইয়াত এতিয়ালৈকে কোনো বৃত্তি তালিকাভুক্ত হোৱা নাই',
  'public.empty.hint': 'প্ৰদানকাৰীসকলক এতিয়া যোগ কৰা হৈছে। ইয়াত একোৱে একাউণ্টৰ আঁৰত নাই — আঁচনি তালিকাভুক্ত হোলে ছাইন ইন নকৰাকৈয়ে দেখিব।',
  'public.whoFor': 'এইটো কাৰ বাবে',
  'public.about': 'এই বৃত্তিৰ বিষয়ে',
  'public.atAGlance': 'এনজৰত',
  'public.closes': 'বন্ধ হয়',
  'public.awardUnstated': 'ধনৰ পৰিমাণ কোৱা হোৱা নাই',
  'public.noClose': 'শেষ তাৰিখ নাই',
  'public.closesIn': '{n} দিনত বন্ধ',
  'public.closesToday': 'আজি বন্ধ হৈছে',
  'public.closed': 'বন্ধ',
  'public.award': 'ধনৰ পৰিমাণ',
  'public.renewable': 'প্ৰতি বছৰে নবীকৰণ কৰিব পাৰি',
  'public.offeredBy': 'প্ৰদান কৰিছে',
  'public.eligibility': 'যোগ্য হোবলৈ',
  'public.benefits': 'সুবিধা',
  'public.readMore': 'অধিক পঢ়ক',
  'public.viewDetails': 'বিৱৰণ চাওক',
  'public.applyNow': 'এতিয়াই আবেদন কৰক',
  'public.registerToApply': 'আবেদন কৰক',
  'public.registerToApplyHelp': 'আবেদন আপোনাৰ একাউণ্টৰ পৰা কৰা হয়। পঞ্জীয়ন কৰিলে আপুনি যোগ্য হোৱা প্ৰতিটো বৃত্তিও দেখা পাব।',
  'public.closedNote': 'এই আঁচনি বন্ধ হৈছে',
  'sheet.close': 'বন্ধ কৰক',
  'sheet.loading': 'বৃত্তিৰ বিৱৰণ',
  'public.benefitComponent': 'খাত',
  'public.benefitAmount': 'শিক্ষাৰ্থীয়ে কি পায়',
  'public.whatYouGet': 'আপুনি কি পাব',
  'public.eligibilityDetail': 'যোগ্যতা বিতংভাৱে',
  'public.documentsRequired': 'প্ৰয়োজনীয় নথি',
  'public.documentsHelp': 'প্ৰদানকাৰীয়ে এইবোৰ বিচাৰে। এইবোৰ আপুনি ইয়াত আপলোড নকৰে।',
  'public.howToApply': 'কেনেকৈ আবেদন কৰিব',
  'public.importantNotes': 'জনা ভাল',
  'public.academicYear': 'কোন বছৰৰ বাবে',
  'public.awardBasis': 'কিহৰ ভিত্তিত',
  'public.basis.MERIT': 'মেধা',
  'public.basis.NEED': 'আৰ্থিক প্ৰয়োজন',
  'public.basis.MERIT_CUM_MEANS': 'মেধা আৰু আয়',
  'public.basis.CATEGORY': 'শ্ৰেণী',
  'public.basis.OTHER': 'অন্যান্য',
  'public.cta': 'আপোনাৰ বাবে বৃত্তি বিচাৰক',
  'public.applyExternal': 'তেওঁলোকৰ ছাইটত আবেদন কৰক',
  'public.applyExternalHelp': 'আপুনি যাতে বিচাৰি পায় তাৰ বাবেই আমি এই বৃত্তিটো তালিকাভুক্ত কৰোঁ। {org}-এ ইয়াক চলায় আৰু নিজৰ ৱেবছাইটত আবেদন লয়, সেয়েহে এইটো ইয়াত আপোনাৰ আবেদনৰ তালিকাত দেখা নাযাব।',
  'public.applyExternalHelpPartner': '{org}-এ এই আবেদন নিজৰ ৱেবছাইটত লয়, সেয়েহে এইটো ইয়াত আপোনাৰ আবেদনৰ তালিকাত দেখা নাযাব।',
  'common.newTab': 'নতুন টেবত খোলে',
  'public.applyHelp': 'আমি প্ৰথমে আপোনাৰ প্ৰোফাইল আৰু নথি এই বৃত্তিৰ সৈতে মিলাই চাওঁ আৰু কিবা বাদ পৰিলে জনাওঁ। আপুনি নিশ্চিত নকৰালৈকে একোৱে পঠোৱা নহয়।',
  'public.ctaHelp': 'নিজৰ বিষয়ে এবাৰ কওক, আৰু আমি আপোনাক যোগ্য হোৱা প্ৰতিটো বৃত্তি দেখুৱাম।',
  'public.back': 'সকলো বৃত্তিলৈ উভতি যাওক',
  'notFound.title': 'আমি এই পৃষ্ঠাটো বিচাৰি নাপালোঁ',
  'notFound.body': 'ঠিকনাত টাইপৰ ভুল থাকিব পাৰে, বা পৃষ্ঠাটো আঁতৰোৱা হৈছে।',
  'notFound.home': 'হোম পৃষ্ঠালৈ যাওক',

  'nav.dashboard': 'ডেশ্ববোৰ্ড',
  'dash.title': 'আপোনাৰ ডেশ্ববোৰ্ড',
  'dash.lede': 'আপোনাৰ বৃত্তি, আবেদন আৰু নথি, সকলো এঠাইতে।',
  'dash.matches': 'যিবোৰ বৃত্তিত আপুনি আবেদন কৰিব পাৰে',
  'dash.matchesHint': 'আপুনি দিয়া তথ্যৰ ভিত্তিত।',
  'dash.matchesBlocked': '{n} আপোনাৰ পৰা আৰু এটা তথ্যৰ অপেক্ষাত।',
  'dash.applications': 'চলি থকা আবেদন',
  'dash.applicationsHint': '{approved} অনুমোদিত · {rejected} সফল হোৱা নাই',
  'dash.applicationsNone': 'এতিয়ালৈকে একো পঠোৱা হোৱা নাই।',
  'dash.documents': 'সত্যাপিত নথি',
  'dash.documentsHint': 'এবাৰ পৰীক্ষা কৰা। প্ৰতিটো আবেদনত ব্যৱহৃত।',
  'dash.funding': 'এতিয়ালৈকে পোৱা',
  'dash.fundingHint': 'মুঠ {sanctioned} মঞ্জুৰ।',
  'dash.recent': 'শেহতীয়া আবেদন',
  'dash.noApplications': 'এতিয়ালৈকে কোনো আবেদন নাই',
  'dash.noApplicationsHint': 'আপুনি যিটোৰ বাবেই আবেদন কৰক সেয়া ইয়াত দেখা যাব।',
  'dash.findScholarships': 'বৃত্তি বিচাৰক',
  'dash.profileTitle': 'আপোনাৰ প্ৰোফাইল',
  'dash.toGo': '{n}% বাকী',
  'dash.allApplications': 'সকলো চাওক',
  'dash.matchesGo': 'আপোনাৰ মিল চাওক',
  'dash.applicationsGo': 'আপোনাৰ আবেদন চাওক',
  'dash.documentsGo': 'নথি পৰিচালনা কৰক',
  'dash.draftsTitle': '{n}টা আবেদন পঠোৱা হোৱা নাই | {n}টা আবেদন পঠোৱা হোৱা নাই',
  'dash.draftsBody': 'আবেদন আৰম্ভ কৰিলেই সেয়া পঠোৱা নহয়। বৃত্তি বন্ধ হোৱাৰ আগতে শেষ কৰক।',
  'dash.draftsAction': 'এতিয়াই শেষ কৰক',
  'dash.expiringTitle': '{n}খন নথিৰ ম্যাদ সোনকালে শেষ | {n}খন নথিৰ ম্যাদ সোনকালে শেষ',
  'dash.expiringBody': 'এতিয়াই ইয়াক সলনি কৰক যাতে প্ৰতিটো আবেদনত কামত আহে। | এতিয়াই এইবোৰ সলনি কৰক যাতে প্ৰতিটো আবেদনত কামত আহে।',
  'dash.expiringAction': 'নথি চাওক',

  'auth.title': 'আপোনাৰ মোবাইল নম্বৰ দিয়ক',
  'auth.phone': 'মোবাইল নম্বৰ',
  'auth.phoneHint': 'আমি এই নম্বৰলৈ এছএমএছত ৬ সংখ্যাৰ এটা কোড পঠিয়াম। প্ৰতিবাৰ এই নম্বৰেই আপোনাক ছাইন ইন কৰাব।',
  'auth.phoneMissing': 'আগবাঢ়িবলৈ আপোনাৰ মোবাইল নম্বৰ দিয়ক।',
  'auth.phoneInvalid': 'এইটো শুদ্ধ যেন নালাগে। ভাৰতীয় মোবাইল নম্বৰ ১০ সংখ্যাৰ আৰু ৬, ৭, ৮ বা ৯ৰে আৰম্ভ হয়।',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'নতুন হওক বা উভতি আহক, একেটা নম্বৰেই কাম কৰে। একাউণ্ট নাথাকিলে আমি বনাই দিওঁ।',
  'auth.stepOf': 'পদক্ষেপ {n} / ২ · {name}',
  'auth.stepPhone': 'আপোনাৰ নম্বৰ',
  'auth.stepCode': 'আপোনাৰ OTP কোড',
  'auth.privacy': 'আপোনাৰ নম্বৰ কেৱল ছাইন ইন কৰাবলৈহে ব্যৱহাৰ হয়, আন একোৰ বাবে নহয়। মনত ৰখাৰ দৰে কোনো পাছৱৰ্ড নাই।',
  'auth.sendCode': 'কোড পঠিয়াওক',
  'auth.sending': 'পঠিওৱা হৈছে…',
  'auth.checking': 'পৰীক্ষা কৰা হৈছে…',
  'auth.welcomeBack': 'পুনৰ স্বাগতম। ছাইন ইন কৰিবলৈ কোডটো দিয়ক।',
  'auth.newHere': 'কোড দিলেই আমি আপোনাৰ একাউণ্ট বনাই দিম।',
  'auth.codeTitle': 'আমি পঠোৱা কোডটো দিয়ক',
  'auth.code': '৬ সংখ্যাৰ কোড',
  'auth.codeHint': 'বাৰ্তাটো সাধাৰণতে কেইছেকেণ্ডমানৰ ভিতৰতে আহে।',
  'auth.noCode': 'এতিয়াও বাৰ্তা অহা নাই? আন উপায় চাওক:',
  'auth.verify': 'সত্যাপন কৰক',
  'auth.viaSms': 'এছএমএছত পঠিয়াওক',
  'auth.viaWhatsapp': 'হোৱাটছএপত পঠিয়াওক',
  'auth.viaVoice': 'কোড কোবলৈ মোলৈ ফোন কৰক',
  'auth.resentVia.sms': 'এছএমএছত পঠোৱা হোল। আহিবলৈ অলপ সময় লাগিব পাৰে।',
  'auth.resentVia.whatsapp': 'হোৱাটছএপত পঠোৱা হোল। বাৰ্তাৰ বাবে হোৱাটছএপ চাওক।',
  'auth.resentVia.voice': 'কোড কোবলৈ এতিয়াই ফোন কৰা হৈছে। শুনিবলৈ ফোন ধৰক।',
  'auth.resendIn': '{n} ছেকেণ্ডত পুনৰ পঠিয়াওক',
  'auth.changeNumber': 'আন নম্বৰ ব্যৱহাৰ কৰক',
  'auth.change': 'সলনি কৰক',

  'profile.complete': '{n}% সম্পূৰ্ণ',
  'profile.viewLede': 'আপুনি আমাক যি যি কৈছে। যিকোনো উত্তৰ সলনি কৰক, তাৰ পিছৰ পৰা প্ৰতিটো বৃত্তিৰ বাবে সেইটোৱেই ব্যৱহৃত হোব।',
  'profile.notAnswered': 'এতিয়াও উত্তৰ দিয়া হোৱা নাই',
  'profile.verified': 'সত্যাপিত',
  'profile.continue': 'যোত এৰিছিল তোৰ পৰাই আগবাঢ়ক',
  'profile.start': 'আপোনাৰ প্ৰোফাইল আৰম্ভ কৰক',
  'profile.saved': 'সংৰক্ষিত',

  'match.title': 'আপোনাৰ বাবে বৃত্তি',
  'match.lede': 'আপোনাৰ প্ৰোফাইলৰ সৈতে মিলাই চোৱা। যিবোৰত আবেদন কৰিব পাৰে সেইবোৰ প্ৰথমে।',
  'match.eligible': 'আপুনি যোগ্য',
  'match.likely': 'আপুনি সম্ভৱতঃ যোগ্য',
  'match.blocked': 'আগতে এটা কাম',
  'match.actionable': 'আপোনাৰ বাবে মুকলি',
  'match.actionableHelp': 'কেইটামানৰ ক্ষেত্ৰত আবেদনৰ আগতে এখন নথি লাগিব পাৰে।',
  'match.ineligible': 'আপোনাৰ বাবে মুকলি নহয়',
  'match.eligibleHelp': 'আমি যি যি পৰীক্ষা কৰিলোঁ সকলোবোৰ সত্যাপিত।',
  'match.likelyHelp': 'আপুনি যি কৈছে তাৰ ভিত্তিত। সত্যাপিত কৰাই লোলে আপোনাৰ আবেদন আৰু শক্তিশালী হয়।',
  'match.blockedHelp': 'আপুনি ওচৰ পাইছে। এইটো কৰিলেই আবেদন কৰিব পাৰিব।',
  'match.ineligibleHelp': 'এই আঁচনিয়ে এনে কিবা বিচাৰে যিটো আপুনি সলনি কৰিব নোৱাৰে।',
  'match.apply': 'আবেদন কৰক',
  'match.applied': 'আপুনি আবেদন কৰিছে',
  'match.none': 'এতিয়ালৈকে কোনো মিল নাই',
  'match.noneHint': 'আপোনাৰ প্ৰোফাইল শেষ কৰক, আমি আপোনাৰ বাবে প্ৰতিটো বৃত্তি পৰীক্ষা কৰিম।',
  'match.figQualify': 'আপুনি যোগ্য',
  'match.figStep': 'এখোজ দূৰত',
  'match.figClosing': 'সোনকালে বন্ধ',
  'match.figNo': 'আপোনাৰ বাবে মুকলি নহয়',
  'match.filterLabel': 'কোনবোৰ বৃত্তি দেখুৱাব',
  'match.filterAll': 'সকলো',
  'match.filterQualify': 'আপুনি যোগ্য',
  'match.filterStep': 'এখোজ দূৰত',
  'match.filterClosing': 'সোনকালে বন্ধ',
  'match.filterNo': 'আপোনাৰ বাবে মুকলি নহয়',
  'match.filterEmpty': 'এই গোটত একো নাই। “সকলো” চাওক।',
  'match.moreWithProfile': 'আপুনি যিমানে পূৰণ কৰিব সিমানে বেছি বৃত্তি দেখা যাব।',
  'match.youQualify': 'আপোনাৰ প্ৰোফাইল অনুসৰি আপুনি চৰ্ত পূৰণ কৰে।',
  'match.yesTitle': 'আপুনি আবেদন কৰিব পাৰে',
  'match.blockedTitle': 'আগতে এটা কাম',
  'match.noTitle': 'যোগ্য নহয়',
  'match.appliedTitle': 'ইতিমধ্যে পঠোৱা',
  'match.seeDetails': 'চৰ্তবোৰ চাওক',
  'match.learnMore': 'অধিক জানক',
  'match.runBy': '{kind}-ৰ দ্বাৰা পৰিচালিত',
  'match.sortBy': 'সজাওক',
  'match.sortRecommended': 'পৰামৰ্শিত',
  'match.sortClosing': 'আটাইতকৈ আগতে বন্ধ হোব',
  'match.sortAward': 'আটাইতকৈ বেছি ধন',
  'match.applyAway': 'তেওঁলোকৰ ছাইটত আবেদন কৰক',
  'match.applyHere': 'ইয়াতেই আবেদন কৰক',
  'match.notOpenToYou': 'বৰ্তমান অৱস্থাত আপোনাৰ বাবে মুকলি নহয়।',
  'match.working': 'এতিয়া মুকলি কোনো আঁচনি আপুনি দিয়া তথ্যৰ সৈতে নিমিলে। প্ৰোফাইলত আৰু যোগ কৰিলেই এইটো সলনি হয়।',

  'doc.title': 'আপোনাৰ নথি',
  'doc.lede': 'এবাৰ নথি আপলোড কৰক। আপুনি যিটো বৃত্তিতেই আবেদন কৰক সি ইয়াক ব্যৱহাৰ কৰিব পাৰিব — আপোনাক আকৌ বিচৰা নহোব।',
  'doc.upload': 'নথি যোগ কৰক',
  'doc.type': 'এইখন কোনখন নথি?',
  'doc.file': 'ফাইল বাছক',
  'doc.fileHint': 'পিডিএফ বা পৰিষ্কাৰ ফটো। ১০ এমবিলৈকে।',
  'doc.verified': 'সত্যাপিত',
  'doc.verifiedBy': '{org}-ৰ দ্বাৰা সত্যাপিত',
  'doc.pending': 'সত্যাপনৰ অপেক্ষাত',
  'doc.expired': 'সত্যাপনৰ ম্যাদ শেষ',
  'doc.expiring': '{n} দিনত ম্যাদ শেষ',
  'doc.validUntil': '{date}লৈকে বৈধ',
  'doc.none': 'আপুনি এতিয়ালৈকে কোনো নথি যোগ কৰা নাই',
  'doc.uploading': 'আপলোড হৈ আছে…',
  'doc.remove': 'আঁতৰাওক',
  'doc.removing': 'আঁতৰোৱা হৈছে…',

  'apply.title': 'আবেদন কৰক',
  'apply.consent': 'মোৰ তথ্য এই প্ৰদানকাৰীৰ সৈতে ভাগ কৰক',
  'apply.consentBody': 'সিদ্ধান্ত লোবলৈ এই বৃত্তিৰ যি লাগে কেৱল সেয়াহে তেওঁলোকে দেখিব: {fields}. কোনে আপোনাৰ নথি চালে সেয়া আপুনি যিকোনো সময়তে চাব পাৰে।',
  'apply.consentBodyNoDocs': 'সিদ্ধান্ত লোবলৈ এই বৃত্তিৰ যি লাগে কেৱল সেয়াহে তেওঁলোকে দেখিব, আন একো নহয়। কোনে আপোনাৰ তথ্য চালে সেয়া আপুনি যিকোনো সময়তে চাব পাৰে।',
  'apply.submit': 'মোৰ আবেদন পঠিয়াওক',
  'apply.submitting': 'পঠিওৱা হৈছে…',
  'apply.blocked': 'আপুনি এতিয়াও আবেদন কৰিব নোৱাৰে',
  'apply.needProfile': 'আগতে আপোনাৰ প্ৰোফাইল',
  'apply.needProfileHint': 'আবেদন আপোনাৰ প্ৰোফাইলৰ পৰা পঠোৱা হয়, সেয়েহে আবেদনৰ আগতে সেয়া লাগে। ইয়াত কেইমিনিটমান লাগে, আৰু আপুনি আগতে যি কৈছে সেয়া পূৰণ কৰা থাকে।',
  'apply.elsewhereTitle': 'এইটোৰ আবেদন পৃষ্ঠপোষকৰ ৱেবছাইটত হয়',
  'apply.elsewhereBody': 'আপুনি যাতে বিচাৰি পায় তাৰ বাবেই আমি এই বৃত্তিটো তালিকাভুক্ত কৰোঁ, আৰু আবেদন পৃষ্ঠপোষকেই লয়। আপুনি আমাক যি কৈছে সেয়া সংৰক্ষিত থাকে, আৰু আমি যিবোৰ বৃত্তি চলাওঁ সেইবোৰৰ বাবে সেয়া আগতেই পূৰণ কৰা থাকে।',
  'apply.elsewhereBodyPartner': 'এই বৃত্তি ইয়াতেই চলে, কিন্তু পৃষ্ঠপোষকে আবেদন নিজৰ ৱেবছাইটত লয়। আপুনি আমাক যি কৈছে সেয়া সংৰক্ষিত থাকে, আৰু আমি পোনপটীয়াকৈ পোৱা আবেদনৰ বাবে সেয়া আগতেই পূৰণ কৰা থাকে।',
  'apply.bundleTitle': 'আপোনাৰ নথি লগত লৈ যাওক',
  'apply.bundleBody': 'এই বৃত্তিয়ে যিবোৰ নথি বিচাৰে সেইবোৰ আমি এটা ফাইলত ৰাখিব পাৰোঁ, তেওঁলোকৰ ৱেবছাইটত আপলোড কৰিবলৈ সাজু। তেওঁলোকে যি বিচাৰে অথচ আমাৰ ওচৰত এতিয়াও নাই, সেয়াও ইয়াত লিখা থাকে।',
  'apply.bundleAction': 'মোৰ নথি ডাউনলোড কৰক',
  'apply.bundleWorking': 'সাজু কৰা হৈছে…',
  'apply.bundleDone': 'আপোনাৰ নথি ডাউনলোড হোল।',
  'apply.docs': 'এই বৃত্তিৰ বাবে প্ৰয়োজনীয় নথি',

  'appl.title': 'আপোনাৰ আবেদন',
  'appl.none': 'আপুনি এতিয়ালৈকে একোৰে বাবে আবেদন কৰা নাই',
  'appl.noneHint': 'আপুনি যোগ্য হোৱা বৃত্তি বিচাৰিবলৈ আপোনাৰ মিল চাওক।',
  'appl.reference': 'ৰেফাৰেন্স',
  'appl.whatNext': 'ইয়াৰ পিছত কি হোব',
  'appl.history': 'ইতিহাস',
  'appl.needsYou': 'তেওঁলোকৰ আপোনাৰ পৰা কিবা লাগে',
  'track.label': 'এই আবেদনৰ অগ্ৰগতি',
  'track.sent': 'পঠোৱা হোল',
  'track.review': 'পৰ্যালোচনা',
  'track.decision': 'সিদ্ধান্ত',
  'track.doneSr': 'সম্পন্ন',
  'track.currentSr': 'এতিয়া চলি আছে',
  'track.todoSr': 'আৰম্ভ হোৱা নাই',
  'appl.sentOn': '{when} পঠোৱা হোল',
  'appl.decidedOn': '{when} সিদ্ধান্ত হোল',
  'appl.outcomeApproved': 'পাইছে',
  'appl.outcomeRejected': 'এইবাৰ পোৱা নাই',
  'appl.outcomeWithdrawn': 'আপুনি এইটো উঠাই লৈছে',
  'appl.inProgress': 'প্ৰদানকাৰীৰ ওচৰত',
  'appl.outcome': 'ফলাফল',
  'appl.award': 'ধনৰ পৰিমাণ',
  'appl.applied': 'আবেদন কৰা হোল',
  'appl.decided': 'সিদ্ধান্ত হোল',
  'appl.automatic': 'স্বয়ংক্ৰিয়',
  'appl.noHistory': 'এতিয়ালৈকে একো হোৱা নাই।',

  'ref.heading': 'তেওঁলোকৰ ৱেবছাইটলৈ পঠোৱা',
  'ref.blurb': 'এইবোৰৰ আবেদন প্ৰদানকাৰীৰ নিজা ছাইটত হয়, সেয়েহে কি হোল সেয়া আমি চাব নোৱাৰোঁ। আমাক জনাওক, আমি ইয়াক বাকীবোৰৰ সৈতে ৰাখিম।',
  'ref.sentOn': 'আপুনি এইটো {when} খুলিছিল',
  'ref.again': 'মুঠ {times} বাৰ',
  'ref.open': 'তেওঁলোকৰ ছাইট পুনৰ খোলক',
  'ref.what': 'কি হোল?',
  'ref.APPLIED': 'মই আবেদন কৰিলোঁ',
  'ref.AWARDED': 'মই এইটো পালোঁ',
  'ref.NOT_AWARDED': 'মই এইটো পোৱা নাই',
  'ref.DID_NOT_APPLY': 'মই আবেদন কৰা নাই',
  'ref.saidAPPLIED': 'আপুনি আবেদন কৰিছে',
  'ref.saidAWARDED': 'আপুনি এইটো পাইছে',
  'ref.saidNOT_AWARDED': 'আপুনি এইটো পোৱা নাই',
  'ref.saidDID_NOT_APPLY': 'আপুনি আবেদন কৰা নাই',
  'ref.youSaid': 'আপুনি আমাক কৈছে: {what}',
  'ref.change': 'সলনি কৰক',

  'privacy.title': 'আপোনাৰ তথ্য',
  'privacy.lede': 'আমাৰ ওচৰত কি আছে, কোনে চাইছে, আৰু ইয়াক কেনেকৈ ঘূৰাই লোব।',
  'privacy.access': 'কোনে আপোনাৰ নথি চাইছে',
  'privacy.accessNone': 'আপোনাৰ নিজৰ একাউণ্টৰ বাহিৰত কোনেও আপোনাৰ নথি খোলা নাই।',
  'privacy.consents': 'আপুনি কি ভাগ কৰিবলৈ সন্মতি দিছে',
  'privacy.withdraw': 'উঠাই লওক',
  'privacy.withdrawing': 'উঠাই লোৱা হৈছে…',
  'privacy.export': 'আমাৰ ওচৰত যি আছে সকলো ডাউনলোড কৰক',
  'privacy.exporting': 'আপোনাৰ প্ৰতিলিপি সাজু কৰা হৈছে…',
  'privacy.exportBody': 'আপোনাৰ তথ্যৰ সম্পূৰ্ণ যন্ত্ৰপাঠ্য প্ৰতিলিপি।',
  'privacy.erase': 'মোৰ তথ্য মচক',
  'privacy.erasing': 'অনুৰোধ কৰা হৈছে…',
  'privacy.eraseBody': 'আপোনাক দিয়া যিকোনো বৃত্তিৰ নথি আমি ৰাখিবই লাগিব। বাকী সকলো আঁতৰোৱা হয়।',
  'auth.closedTitle': 'আপোনাৰ একাউণ্ট এই মুহূৰ্তত বন্ধ।',
  'auth.closedHelp': 'সহায় লাগে নেকি? আমাৰ সহায় দলে আপোনাক বুজিবলৈ সহায় কৰিব পাৰে ',
  'auth.closedSoon': 'সহায় বিচাৰক (সোনকালে)',
  'reg.district': 'জিলা',
  'reg.districtHint': 'আপোনাৰ অঞ্চলত চলা আঁচনিৰ সৈতে মিলাবলৈ সহায় কৰে।',
  'privacy.requested': 'অনুৰোধ কৰা হোল',
  'privacy.window': 'এতিয়ালৈকে একোৱে মচা হোৱা নাই',
  'privacy.windowBody': 'আপোনাৰ তথ্য {date} মচি পেলোৱা হোব। তাৰ আগলৈকে আপুনি ',
  'privacy.cancel': 'এই অনুৰোধ বাতিল কৰক',
  'privacy.cancelling': 'বাতিল কৰা হৈছে…',
  'privacy.cancelled': 'আপোনাৰ অনুৰোধ বাতিল কৰা হোল। একোৱে মচা হোৱা নাই।',

  'common.loading': 'লোড হৈ আছে',
  'common.retry': 'পুনৰ চেষ্টা কৰক',
  'common.required': 'আৱশ্যক',
  'common.optional': 'ঐচ্ছিক',
  'common.error': 'কিবা ভুল হোল',
  'common.offline': 'আপুনি অফলাইনত আছে। আপোনাৰ কাম এই ডিভাইচত সংৰক্ষিত।',

  'slides.lead.was': '',
  'slides.lead.able': 'সক্ষমতাৰ পৰা',
  'slides.lead.dist': 'বিশিষ্টতালৈ',
  'slides.lead.body': 'আপুনি যোগ্য হোৱা প্ৰতিটো বৃত্তি — চৰকাৰী আৰু ব্যক্তিগত — আপোনাৰ প্ৰোফাইলৰ সৈতে মিলাই, আপোনাৰ ভাষাত, এঠাইতে।',
  'slides.lead.free': 'সম্পূৰ্ণ বিনামূলীয়া',
  'slides.lead.languages': '১৪টা ভাষা',
  'slides.lead.support': 'প্ৰতিটো খোজতে ব্যক্তিগত সহায়',
  'slides.label': 'ঘোষণা',
  'slides.position': '{total}ৰ ভিতৰত {n}',
  'slides.goto': '{name} দেখুৱাওক',
  'slides.watch': 'ভিডিঅোটো চাওক',
  'slides.external': 'আন ৱেবছাইট খোলে',

  'home.title': 'দিব্যাং শিক্ষাৰ্থীসকলৰ বাবে বৃত্তি, এঠাইতে',
  'home.lede': 'নিজৰ বিষয়ে এবাৰ কওক। আমি ইয়াৰ প্ৰতিটো বৃত্তিৰ সৈতে আপোনাক মিলাই চাওঁ আৰু কওঁ কোনবোৰত আপুনি যোগ্য — আৰু বাকীবোৰৰ বাবে ঠিক কি বাদ পৰিছে।',
  'home.search': 'বৃত্তি বিচাৰক',
  'home.searchPlaceholder': 'যেনে: ইঞ্জিনিয়াৰিং, দিল্লী, পোষ্ট-মেট্ৰিক',
  'home.searchGo': 'বিচাৰক',
  'home.browseAll': 'সকলো বৃত্তি চাওক',
  'home.openNow': 'বৃত্তি এতিয়া মুকলি',
  'home.noAccount': 'চাবলৈ একাউণ্টৰ প্ৰয়োজন নাই।',
  'home.openNone': 'ইয়াত এতিয়ালৈকে কোনো বৃত্তি তালিকাভুক্ত হোৱা নাই।',
  'home.openNoneBody': 'তালিকাখন এতিয়া সজা হৈ আছে। ইয়াত একোৱে একাউণ্টৰ আঁৰত নাই — আঁচনি তালিকাভুক্ত হোলে ছাইন ইন নকৰাকৈয়ে দেখিব।',
  'home.how': 'এইটো কেনেকৈ কাম কৰে',
  'home.howLede': 'পঞ্জীয়নৰ বাবে এটা মোবাইল নম্বৰ আৰু তালৈ পঠোৱা কোড লাগে। কোনো পাছৱৰ্ড নাই, আগতে পূৰণ কৰাৰ দৰে কোনো ছাইন-আপ ফৰ্মও নাই।',
  'home.step1': 'পঞ্জীয়ন টিপক',
  'home.step1Body': 'এই পৃষ্ঠাৰ ওপৰত। আগতে আহি থাকিলে কাষৰ লগইন ব্যৱহাৰ কৰক — দুয়োটাতে একেটা নম্বৰেই কাম কৰে।',
  'home.step2': 'আপোনাৰ মোবাইল নম্বৰ দিয়ক',
  'home.step2Body': 'দহটা সংখ্যা, +91 আগতেই বহুৱাই থোৱা। সেই নম্বৰলৈ ৬ সংখ্যাৰ এটা কোড যায়।',
  'home.step3': 'কোডটো দিয়ক',
  'home.step3Body': 'ছয়টা সংখ্যা লিখক আৰু আপুনি ভিতৰত। বাৰ্তা নাহিলে কোডটো হোৱাটছএপত বিচাৰক, বা আমাক ফোন কৰি পঢ়ি শুনাবলৈ কওক।',
  'home.step4': 'আপোনাৰ তথ্য পূৰণ কৰক',
  'home.step4Body': 'আপোনাৰ নাম, আপোনাৰ প্ৰমাণপত্ৰ আৰু কোত পঢ়ে — এবাৰত এটা প্ৰশ্ন, আৰু প্ৰতিটো উত্তৰ দিয়াৰ লগে লগেই সংৰক্ষিত হয়।',
  'home.step5': 'আপোনাৰ নথি আপলোড কৰক',
  'home.step5Body': 'দিব্যাংগতাৰ প্ৰমাণপত্ৰ, ইউডিআইডি কাৰ্ড, আয়ৰ প্ৰমাণপত্ৰ আৰু বাকীবোৰ। প্ৰতিখন এবাৰেই, প্ৰতিটো বৃত্তিৰ বাবে পৃথকে নহয়।',
  'home.step6': 'আপোনাৰ মিল চাওক',
  'home.step6Body': 'মোৰ মিলে সেইবোৰ বৃত্তি দেখুৱায় যিবোৰত আপুনি যোগ্য — আৰু কোনোটো আপোনাৰ বাবে বন্ধ হোলে কাৰণ কয়।',
  'home.step7': 'আবেদন কৰক',
  'home.step7Body': 'যিবোৰ বিচাৰে বাছি লওক। আপোনাৰ তথ্য আৰু নথি আবেদনৰ সৈতে যায়।',
  'home.assure': 'জানি থোৱা ভাল',
  'home.assure1': 'মনত ৰখাৰ দৰে কোনো পাছৱৰ্ড নাই',
  'home.assure2': 'পৃথক কোনো পঞ্জীয়ন ফৰ্ম নাই',
  'home.assure3': 'ৰৈ পিছত শেষ কৰিব পাৰে',
  'home.help': 'কোনো পদক্ষেপত আটকি গৈছে?',
  'home.helpBody': 'ফোন কৰক, কোনোবাই আপোনাক পাৰ কৰাই দিব।',
  'home.helpCall': '{number}লৈ ফোন কৰক',
  'home.closing': 'সোনকালে বন্ধ',
  'home.closingLede': 'আগতে এইবোৰত আবেদন কৰক।',
  'home.closingNext': 'পৰৱৰ্তী শেষ তাৰিখ',
  'home.closingNextLede': 'আটাইতকৈ আগতে বন্ধ হোব লগীয়া তিনিটা।',
  'home.allDeadlines': 'সকলো বৃত্তি চাওক',
  'home.browse': 'যিদৰে চাব',
  'home.browseWho': 'কোনে দিছে',
  'home.browseLevel': 'আপোনাৰ অধ্যয়নৰ স্তৰ',
  'home.cta': 'আপোনাৰ মিল চাবলৈ সাজু?',
  'home.ctaBody': 'একাউণ্ট বনাবলৈ এটা মোবাইল নম্বৰ বা এটা ইমেইল ঠিকনা লাগে। আন একো নহয়।',
  'home.ctaButton': 'একাউণ্ট বনাওক',
  'home.signedInCta': 'চাওক আপুনি কিহত যোগ্য',

  'reg.title': 'বৃত্তি বিচাৰিবলৈ পঞ্জীয়ন কৰক',
  'reg.editTitle': 'আপোনাৰ তথ্য সলনি কৰক',
  'reg.requiredNote': '* চিহ্নিত সকলো ঘৰ আৱশ্যক।',
  'reg.personal': 'ব্যক্তিগত তথ্য',
  'reg.disability': 'দিব্যাংগতাৰ তথ্য',
  'reg.education': 'শিক্ষাৰ তথ্য',
  'reg.name': 'সম্পূৰ্ণ নাম',
  'reg.namePlaceholder': 'আপোনাৰ সম্পূৰ্ণ নাম লিখক',
  'reg.phoneHint': 'আমি এই নম্বৰলৈ ৬ সংখ্যাৰ এটা কোড পঠিয়াওঁ। প্ৰতিবাৰ এই নম্বৰেই আপোনাক ছাইন ইন কৰাব।',
  'reg.sendOtp': 'ওটিপি পঠিয়াওক',
  'reg.otpPlaceholder': '৬ সংখ্যাৰ ওটিপি লিখক',
  'reg.verified': 'ফোন নম্বৰ সত্যাপিত',
  'reg.verifyFirst': 'পঞ্জীয়ন শেষ কৰিবলৈ আপোনাৰ ফোন নম্বৰ সত্যাপিত কৰক।',
  'reg.email': 'ইমেইল',
  'reg.emailHint': 'যাতে আমি শেষ তাৰিখৰ কথা মনত পেলাই দিব পাৰোঁ। আমি ইয়াক কেতিয়াও ভাগ নকৰোঁ।',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'লিংগ',
  'reg.genderHint': '(কিছুমান বৃত্তি কেৱল মহিলা বা ৰূপান্তৰকামী শিক্ষাৰ্থীৰ বাবে)',
  'reg.udid': 'ইউডিআইডি নম্বৰ',
  'reg.udidHint': 'আপোনাৰ ইউডিআইডি (অনন্য দিব্যাংগতা পৰিচয়) কাৰ্ডত লিখা নম্বৰ।',
  'reg.udidPlaceholder': 'আপোনাৰ ইউডিআইডি নম্বৰ লিখক',
  'reg.certificate': 'ইউডিআইডি প্ৰমাণপত্ৰ আপলোড কৰক',
  'reg.certificateHint': 'পিডিএফ বা ছবি, ৫ এমবি বা তোতকৈ কম।',
  'reg.fileType': 'সেই ফাইলটো পিডিএফ, জেপিইজি বা পিএনজি হোব লাগিব।',
  'reg.fileSize': 'সেই ফাইলটো ৫ এমবিতকৈ ডাঙৰ। ফোনত তোলা ছবি সাধাৰণতে সৰু হয় যদি ছবি নতুলি স্কেন কৰে।',
  'reg.fileLater': 'আপোনাৰ পঞ্জীয়ন হোল আৰু তথ্য সংৰক্ষিত হোল। প্ৰমাণপত্ৰখন আপলোড নহোল — মোৰ নথিৰ পৰা যোগ কৰি দিয়ক, আন একো নতুনকৈ কৰিব নালাগে।',
  'reg.disabilityType': 'দিব্যাংগতাৰ প্ৰকাৰ',
  'reg.percent': 'দিব্যাংগতাৰ শতাংশ',
  'reg.percentHint': 'আপোনাৰ প্ৰমাণপত্ৰত লিখা সংখ্যা। বহু বৃত্তিৰ বাবে ৪০% বা তাতকৈ বেছি লাগে।',
  'reg.percentPlaceholder': 'যেনে ৪০',
  'reg.percentRange': 'প্ৰমাণপত্ৰৰ শতাংশ ০ৰ পৰা ১০০ৰ ভিতৰত এটা পূৰ্ণসংখ্যা।',
  'reg.state': 'ৰাজ্য',
  'reg.statePlaceholder': 'আপোনাৰ ৰাজ্য বিচাৰিবলৈ লিখক…',
  'reg.program': 'আপোনাৰ পাঠ্যক্ৰম বাছক',
  'reg.graduation': 'স্নাতক',
  'reg.postgraduation': 'স্নাতকোত্তৰ / মাষ্টাৰ্ছ',
  'reg.year': 'বছৰ বাছক',
  'reg.yearAfterProgram': 'আগতে আপোনাৰ পাঠ্যক্ৰম বাছক',
  'reg.institution': 'বিদ্যালয় / মহাবিদ্যালয়ৰ নাম',
  'reg.institutionPlaceholder': 'আপোনাৰ প্ৰতিষ্ঠানৰ নাম লিখক',
  'reg.required': 'এইটো লাগে।',
  'reg.fix': 'কেইটামান উত্তৰত মন দিব লাগিব। প্ৰথমটো তলত বাছি থোৱা আছে।',
  'reg.cta': 'পঞ্জীয়ন কৰক আৰু বৃত্তি বিচাৰক',
  'reg.saveChanges': 'পৰিৱৰ্তন সংৰক্ষণ কৰক',
  'reg.saving': 'সংৰক্ষণ কৰা হৈছে…',
  'reg.done': 'পঞ্জীয়ন হোল। আপোনাৰ বৃত্তি বিচৰা হৈছে।',
  'reg.doneTitle': 'আপোনাৰ পঞ্জীয়ন হোল',
  'reg.already': 'আগতেই পঞ্জীয়ন কৰিছে?',
  'reg.login': 'ওটিপিৰে লগইন',
  'nav.registerCta': 'পঞ্জীয়ন',
  'nav.loginCta': 'লগইন',
  'profile.edit': 'আপোনাৰ তথ্য সলনি কৰক',
  'field.disability.BLINDNESS': 'দৃষ্টিহীনতা',
  'field.disability.LOW_VISION': 'ক্ষীণ দৃষ্টি',
  'field.disability.LEPROSY_CURED': 'কুষ্ঠ (আৰোগ্য হোৱা)',
  'field.disability.HEARING_IMPAIRMENT': 'শ্ৰৱণ প্ৰতিবন্ধকতা',
  'field.disability.LOCOMOTOR_DISABILITY': 'চলাচলৰ প্ৰতিবন্ধকতা',
  'field.disability.DWARFISM': 'খৰ্বাকৃতি',
  'field.disability.INTELLECTUAL_DISABILITY': 'বৌদ্ধিক প্ৰতিবন্ধকতা',
  'field.disability.MENTAL_ILLNESS': 'মানসিক অসুস্থতা',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'অটিজম স্পেকট্ৰাম ডিছঅৰ্ডাৰ',
  'field.disability.CEREBRAL_PALSY': 'ছেৰিব্ৰেল পালচি',
  'field.disability.MUSCULAR_DYSTROPHY': 'মাংসপেশীৰ ক্ষয়ৰোগ',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'দীৰ্ঘস্থায়ী স্নায়বিক অৱস্থা',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'নিৰ্দিষ্ট শিক্ষণ প্ৰতিবন্ধকতা',
  'field.disability.MULTIPLE_SCLEROSIS': 'মাল্টিপল স্ক্লেৰোচিছ',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'বাক আৰু ভাষা প্ৰতিবন্ধকতা',
  'field.disability.THALASSEMIA': 'থেলাচেমিয়া',
  'field.disability.HAEMOPHILIA': 'হিমোফিলিয়া',
  'field.disability.SICKLE_CELL_DISEASE': 'চিকল চেল ৰোগ',
  'field.disability.MULTIPLE_DISABILITIES': 'একাধিক প্ৰতিবন্ধকতা, দৃষ্টি-শ্ৰৱণ প্ৰতিবন্ধকতা সহ',
  'field.disability.ACID_ATTACK_VICTIM': 'এচিড আক্ৰমণৰ পৰা বাচি যোৱা',
  'field.disability.PARKINSONS_DISEASE': 'পাৰ্কিনচনোচ ৰোগ',

  'field.state.AN': 'আন্দামান আৰু নিকোবৰ দ্বীপপুঞ্জ',
  'field.state.AP': 'অন্ধ্ৰপ্ৰদেশ',
  'field.state.AR': 'অৰুণাচল প্ৰদেশ',
  'field.state.AS': 'অসম',
  'field.state.BR': 'বিহাৰ',
  'field.state.CH': 'চণ্ডীগড়',
  'field.state.CT': 'ছত্তীশগড়',
  'field.state.DL': 'দিল্লী',
  'field.state.DN': 'দাদ্ৰা আৰু নগৰ হাভেলী আৰু দমন আৰু দিউ',
  'field.state.GA': 'গোৱা',
  'field.state.GJ': 'গুজৰাট',
  'field.state.HP': 'হিমাচল প্ৰদেশ',
  'field.state.HR': 'হাৰিয়ানা',
  'field.state.JH': 'ঝাৰখণ্ড',
  'field.state.JK': 'জম্মু আৰু কাশ্মীৰ',
  'field.state.KA': 'কৰ্ণাটক',
  'field.state.KL': 'কেৰালা',
  'field.state.LA': 'লাডাখ',
  'field.state.LD': 'লক্ষদ্বীপ',
  'field.state.MH': 'মহাৰাষ্ট্ৰ',
  'field.state.ML': 'মেঘালয়',
  'field.state.MN': 'মণিপুৰ',
  'field.state.MP': 'মধ্যপ্ৰদেশ',
  'field.state.MZ': 'মিজোৰাম',
  'field.state.NL': 'নাগালেণ্ড',
  'field.state.OR': 'ওড়িশা',
  'field.state.PB': 'পঞ্জাৱ',
  'field.state.PY': 'পুডুচেৰী',
  'field.state.RJ': 'ৰাজস্থান',
  'field.state.SK': 'ছিকিম',
  'field.state.TG': 'তেলেংগানা',
  'field.state.TN': 'তামিলনাডু',
  'field.state.TR': 'ত্ৰিপুৰা',
  'field.state.UP': 'উত্তৰ প্ৰদেশ',
  'field.state.UT': 'উত্তৰাখণ্ড',
  'field.state.WB': 'পশ্চিমবংগ',

  'field.level.SCHOOL': 'বিদ্যালয়',
  'field.level.SCHOOL.sub': 'নৱম, দশম, একাদশ, দ্বাদশ শ্ৰেণী',
  'field.level.UNDERGRADUATE': 'স্নাতক',
  'field.level.UNDERGRADUATE.sub': 'বিএ, বিএচচি, বিটেক আৰু সদৃশ',
  'field.level.POSTGRADUATE': 'স্নাতকোত্তৰ',
  'field.level.POSTGRADUATE.sub': 'এমএ, এমএচচি, এমটেক আৰু সদৃশ',
  'field.level.DOCTORAL': 'ডক্টৰেট',
  'field.level.DOCTORAL.sub': 'পিএইচডি',

  'field.qual.SCHOOL': 'বিদ্যালয়',
  'field.qual.SCHOOL.sub': 'প্ৰথমৰ পৰা দ্বাদশ শ্ৰেণী',
  'field.qual.UNDERGRADUATE': 'স্নাতক',
  'field.qual.UNDERGRADUATE.sub': 'বিএ, বিএচচি, বিকম, বিই / বিটেক, এমবিবিএচ — আৰু ডিপ্লোমা বা আইটিআই',
  'field.qual.POSTGRADUATE': 'স্নাতকোত্তৰ',
  'field.qual.POSTGRADUATE.sub': 'এমএ, এমএচচি, এমটেক, এমবিএ আৰু সদৃশ',
  'field.qual.DOCTORAL': 'পিএইচডি / ডক্টৰেট',

  'field.subject.engineering': 'ইঞ্জিনিয়াৰিং',
  'field.subject.medical': 'চিকিৎসা',
  'field.subject.management': 'ব্যৱস্থাপনা',
  'field.subject.science': 'বিজ্ঞান',
  'field.subject.commerce': 'বাণিজ্য',
  'field.subject.arts': 'কলা আৰু মানৱিক বিদ্যা',
  'field.subject.vocational': 'বৃত্তিমূলক',
  'field.subject.fellowship': 'ফেলোশিপ',
  'field.subject.talent': 'প্ৰতিভা',
  'field.subject.sports': 'ক্ৰীড়া',

  'field.gender.FEMALE': 'মহিলা',
  'field.gender.MALE': 'পুৰুষ',
  'field.gender.TRANSGENDER': 'ৰূপান্তৰকামী',
  'field.gender.UNDISCLOSED': 'কোব নিবিচাৰোঁ',
  'field.genderFilter.TRANSGENDER': 'তৃতীয় লিংগ / ৰূপান্তৰকামী',

  'field.year.below9': 'নৱম শ্ৰেণীৰ তলত',
  'field.year.c9': 'নৱম শ্ৰেণী',
  'field.year.c10': 'দশম শ্ৰেণী',
  'field.year.c11': 'একাদশ শ্ৰেণী',
  'field.year.c12': 'দ্বাদশ শ্ৰেণী',
  'field.year.y1': 'প্ৰথম বৰ্ষ',
  'field.year.y2': 'দ্বিতীয় বৰ্ষ',
  'field.year.y3': 'তৃতীয় বৰ্ষ',
  'field.year.y4': 'চতুৰ্থ বৰ্ষ',
  'field.year.pg1': 'স্নাতকোত্তৰ ১ম বৰ্ষ',
  'field.year.pg2': 'স্নাতকোত্তৰ ২য় বৰ্ষ',

  'q.full_name': 'আপোনাৰ নাম কি?',
  'q.full_name.help': 'ঠিক যেনেকৈ আপোনাৰ দিব্যাংগতাৰ প্ৰমাণপত্ৰত লিখা আছে। প্ৰদানকাৰীসকলে দুয়োটা মিলাই চায়।',
  'q.gender': 'আপোনাৰ লিংগ কি?',
  'q.gender.help': 'কিছুমান বৃত্তি কেৱল মহিলাৰ বাবে, বা ৰূপান্তৰকামী শিক্ষাৰ্থীৰ বাবে। কোব নিবিচাৰিলে এৰি দিয়ক।',
  'q.disability_type': 'আপোনাৰ দিব্যাংগতা কি?',
  'q.disability_type.help': 'যেনেকৈ আপোনাৰ প্ৰমাণপত্ৰত লিখা আছে। বেছিভাগ বৃত্তিয়ে ইয়াৰ ওপৰতে বাছনি কৰে।',
  'q.disability_percent': 'আপোনাৰ প্ৰমাণপত্ৰত কিমান শতাংশ আছে?',
  'q.disability_percent.help': '০ৰ পৰা ১০০ৰ ভিতৰত এটা সংখ্যা। বহু বৃত্তিৰ বাবে ৪০% বা তাতকৈ বেছি লাগে।',
  'q.disability_percent.range': 'প্ৰমাণপত্ৰৰ শতাংশ ০ৰ পৰা ১০০ৰ ভিতৰত হয়।',
  'q.udid_number': 'আপোনাৰ ইউডিআইডি নম্বৰ কি?',
  'q.udid_number.help': 'আপোনাৰ ইউডিআইডি (অনন্য দিব্যাংগতা পৰিচয়) কাৰ্ডত লিখা নম্বৰ। এতিয়াও পোৱা নাই হোলে এৰি দিয়ক — ইয়াৰ দ্বাৰা আপুনি কিহত যোগ্য সেয়া নসলায়, আৰু পিছত যোগ কৰিব পাৰিব।',
  'q.date_of_birth': 'আপুনি কেতিয়া জন্মগ্ৰহণ কৰিছিল?',
  'q.date_of_birth.help': 'কিছুমান বৃত্তিত বয়সৰ সীমা থাকে।',
  'q.course_name': 'আপুনি কি পঢ়ি আছে?',
  'q.course_name.help': 'পঞ্জীয়নৰ সময়ত আপুনি বাছি লোৱা পাঠ্যক্ৰম।',
  'q.institution_name': 'আপুনি কোত পঢ়ে?',
  'q.institution_name.help': 'আপোনাৰ বিদ্যালয়, মহাবিদ্যালয় বা বিশ্ববিদ্যালয়ৰ নাম, যেনেকৈ আপোনাৰ বোনাফাইড প্ৰমাণপত্ৰত লিখা আছে। এতিয়াও আৰম্ভ কৰা নাই হোলে এৰি দিয়ক।',
  'q.institution_name.placeholder': 'আপোনাৰ বিদ্যালয় বা মহাবিদ্যালয়ৰ নাম',
  'q.state_code': 'আপুনি কোন ৰাজ্যত থাকে?',
  'q.state_code.help': 'বহু বৃত্তি কেৱল কিছু ৰাজ্যৰ বাসিন্দাৰ বাবে মুকলি।',
  'q.annual_family_income': 'আপোনাৰ পৰিয়ালৰ বাৰ্ষিক আয় কিমান?',
  'q.annual_family_income.help': 'টকাত, যেনেকৈ আপোনাৰ আয় প্ৰমাণপত্ৰত আছে। বেছিভাগ বৃত্তিত এটা সীমা থাকে।',
  'q.annual_family_income.range': 'আয় শূন্যতকৈ কম হোব নোৱাৰে।',
  'q.academic_percentage': 'আপোনাৰ শেষ পৰীক্ষাৰ নম্বৰ কিমান আছিল?',
  'q.academic_percentage.help': 'আপোনাৰ নম্বৰ-পত্ৰই যিদৰে সেয়া জনায় সেয়া বাছক, তাৰ পিছত সংখ্যাটো লিখক। বহু বৃত্তিয়ে এটা নিম্নতম বিচাৰে।',
  'field.orgKind.NGO': 'এনজিঅো',
  'field.orgKind.CORPORATE': 'কৰ্পোৰেট',
  'field.orgKind.GOVERNMENT': 'চৰকাৰী',
  'field.orgKind.PRIVATE': 'ব্যক্তিগত',

  'field.doc.DISABILITY_CERTIFICATE': 'দিব্যাংগতাৰ প্ৰমাণপত্ৰ',
  'field.doc.UDID_CARD': 'ইউডিআইডি কাৰ্ড',
  'field.doc.INCOME_CERTIFICATE': 'আয়ৰ প্ৰমাণপত্ৰ',
  'field.doc.DOMICILE_CERTIFICATE': 'বাসস্থানৰ প্ৰমাণপত্ৰ',
  'field.doc.CASTE_CERTIFICATE': 'শ্ৰেণীৰ প্ৰমাণপত্ৰ',
  'field.doc.MARKSHEET': 'নম্বৰ-পত্ৰ',
  'field.doc.ADMISSION_LETTER': 'নামভৰ্তিৰ চিঠি',
  'field.doc.BONAFIDE_CERTIFICATE': 'বোনাফাইড প্ৰমাণপত্ৰ',
  'field.doc.FEE_RECEIPT': 'মাচুলৰ ৰচিদ',
  'field.doc.BANK_PASSBOOK': 'বেংকৰ পাছবুক',
  'field.doc.IDENTITY_PROOF': 'পৰিচয়ৰ প্ৰমাণ',
  'field.doc.PHOTOGRAPH': 'ফটো',

  'appl.next.SUBMITTED': 'প্ৰদানকাৰীৰ ওচৰত আপোনাৰ আবেদন আছে। ইয়াৰ পিছত এজন পৰ্যালোচকে ইয়াক পঢ়িব।',
  'appl.next.UNDER_REVIEW': 'এজন পৰ্যালোচকে আপোনাৰ আবেদন পঢ়ি আছে। সাধাৰণতে এইটোৱেই আটাইতকৈ দীঘল পদক্ষেপ।',
  'appl.next.INFO_REQUESTED': 'তেওঁলোকে আপোনাৰ পৰা কিবা বিচাৰিছে। আপুনি উত্তৰ নিদিয়ালৈকে আবেদন ৰৈ থাকিব।',
  'appl.next.DOCUMENT_CHECK': 'আপোনাৰ আবেদন এজন পৰ্যালোচকৰ ওচৰত আছে। আপোনাৰ পৰা একো লাগে।',
  'appl.next.VERIFIED': 'আপোনাৰ আবেদন এজন পৰ্যালোচকৰ ওচৰত আছে। আপোনাৰ পৰা একো নালাগে।',
  'appl.next.SHORTLISTED': 'আপোনাৰ আবেদন এজন পৰ্যালোচকৰ ওচৰত আছে। ইয়াৰ পিছত সিদ্ধান্ত।',
  'appl.next.APPROVED': 'অনুমোদিত। প্ৰদানকাৰীয়ে মঞ্জুৰি লিপিবদ্ধ কৰিব, তাৰ পিছত ধন প্ৰদানৰ ব্যৱস্থা কৰিব।',
  'appl.next.SANCTIONED': 'ধন মঞ্জুৰ হোল। ধন প্ৰদান তেওঁলোকৰ বেংকৰ জৰিয়তে কৰা হয়।',
  'appl.next.DISBURSED': 'ধন প্ৰদান লিপিবদ্ধ হোল। কেইটামান কৰ্মদিৱসৰ ভিতৰত আপোনাৰ একাউণ্টলৈ নাহিলে অভিযোগ জনাওক।',
  'appl.next.REJECTED': 'এই আবেদন সফল নহোল। ইয়াৰ দ্বাৰা আপোনাৰ আন আবেদনবোৰত কোনো প্ৰভাৱ নপৰে।',
  'appl.next.CLOSED': 'এই আবেদন সম্পূৰ্ণ হোল।',
  'appl.next.WITHDRAWN': 'আপুনি এই আবেদন উঠাই লৈছিল।',
}

export default asm
