/* Bengali.
 *
 * One word per term throughout: scholarship বৃত্তি, application আবেদন,
 * document নথি, disability প্রতিবন্ধকতা, verified যাচাই করা, eligible যোগ্য,
 * certificate শংসাপত্র.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const bn: Dict = {
  'app.name': 'ইন্ডিক এআই বৃত্তি',
  'app.tagline': 'প্রতিবন্ধী শিক্ষার্থীদের জন্য',
  'app.yourApplication': 'আপনার আবেদন · {title}',

  'nav.find': 'বৃত্তি',
  'nav.how': 'এটি কীভাবে কাজ করে',
  'nav.matches': 'আমার মিল',
  'nav.applications': 'আমার আবেদন',
  'nav.documents': 'আমার নথি',
  'nav.profile': 'আমার প্রোফাইল',
  'nav.privacy': 'আমার তথ্য',
  'nav.account': 'আমার অ্যাকাউন্ট',
  'nav.register': 'সাইন আপ',
  'nav.language': 'ভাষা',
  'footer.social': 'ইন্ডিক এআই অন্যত্র',
  'footer.sponsor': 'সহযোগিতায়',
  'footer.copyright': 'কপিরাইট © {year} ইন্ডিক এআই | সর্বস্বত্ব সংরক্ষিত',
  'nav.signin': 'সাইন ইন',
  'nav.signout': 'সাইন আউট',
  'nav.skip': 'মূল বিষয়বস্তুতে যান',

  'public.title': 'এমন বৃত্তি খুঁজুন যার জন্য আপনি যোগ্য',
  'public.lede': 'এখানে থাকা প্রতিটি বৃত্তি প্রতিবন্ধী শিক্ষার্থীদের জন্য খোলা। দেখার জন্য অ্যাকাউন্ট লাগে না।',
  'public.search': 'নাম বা শব্দ দিয়ে খুঁজুন',
  'public.filter.disability': 'প্রতিবন্ধকতার ধরন',
  'public.filter.qualification': 'যোগ্যতা',
  'public.filter.state': 'আপনার রাজ্য',
  'public.filter.provider': 'কে দিচ্ছে',
  'public.filter.any': 'যে কোনো',
  'public.filter.anyDisability': 'যে কোনো প্রতিবন্ধকতা',
  'public.filter.anyQualification': 'যে কোনো যোগ্যতা',
  'public.filter.allStates': 'সব রাজ্য',
  'public.filter.gender': 'লিঙ্গ',
  'public.filter.anyGender': 'যে কোনো লিঙ্গ',
  'public.filter.course': 'কোর্স',
  'public.filter.anyCourse': 'যে কোনো কোর্স',
  'public.filter.where': 'আপনি কোথায় পড়েন',
  'public.filter.anyWhere': 'ভারত বা বিদেশ',
  'public.filter.inIndia': 'ভারতে',
  'public.filter.abroad': 'বিদেশে পড়াশোনা',
  'public.filters': 'ফিল্টার',
  'public.clear': 'সরান',
  'public.results': 'বৃত্তি এখন খোলা',
  'public.searching': 'খোঁজা হচ্ছে…',
  'public.none': 'এই ফিল্টারগুলির সঙ্গে কোনো বৃত্তি মেলেনি',
  'public.none.hint': 'একটি ফিল্টার সরিয়ে দেখুন। সারা বছর নতুন প্রকল্প খোলে।',
  'public.none.clear': 'সব ফিল্টার সরান',
  'public.empty': 'এখানে এখনও কোনো বৃত্তি তালিকাভুক্ত নেই',
  'public.empty.hint': 'প্রদানকারীদের এখন যোগ করা হচ্ছে। এখানে কিছুই অ্যাকাউন্টের আড়ালে নেই — প্রকল্প তালিকাভুক্ত হলে সাইন ইন না করেই দেখতে পাবেন।',
  'public.whoFor': 'এটি কাদের জন্য',
  'public.about': 'এই বৃত্তি সম্পর্কে',
  'public.atAGlance': 'এক নজরে',
  'public.closes': 'বন্ধ হয়',
  'public.awardUnstated': 'অর্থের পরিমাণ জানানো হয়নি',
  'public.noClose': 'শেষ তারিখ নেই',
  'public.closesIn': '{n} দিনে বন্ধ',
  'public.closesToday': 'আজ বন্ধ হচ্ছে',
  'public.closed': 'বন্ধ',
  'public.award': 'অর্থের পরিমাণ',
  'public.renewable': 'প্রতি বছর নবায়ন করা যায়',
  'public.offeredBy': 'প্রদান করছে',
  'public.eligibility': 'যোগ্য হতে হলে',
  'public.benefits': 'সুবিধা',
  'public.readMore': 'আরও পড়ুন',
  'public.viewDetails': 'বিস্তারিত দেখুন',
  'public.applyNow': 'এখনই আবেদন করুন',
  'public.registerToApply': 'আবেদন করুন',
  'public.registerToApplyHelp': 'আবেদন আপনার অ্যাকাউন্ট থেকে করা হয়। নিবন্ধন করলে আপনি যোগ্য এমন প্রতিটি বৃত্তিও দেখতে পাবেন।',
  'public.closedNote': 'এই প্রকল্পটি বন্ধ',
  'sheet.close': 'বন্ধ করুন',
  'sheet.loading': 'বৃত্তির বিবরণ',
  'public.benefitComponent': 'খাত',
  'public.benefitAmount': 'শিক্ষার্থী কী পান',
  'public.whatYouGet': 'আপনি কী পাবেন',
  'public.eligibilityDetail': 'যোগ্যতা বিস্তারিত',
  'public.documentsRequired': 'প্রয়োজনীয় নথি',
  'public.documentsHelp': 'প্রদানকারী এগুলি চান। এগুলি আপনি এখানে আপলোড করেন না।',
  'public.howToApply': 'কীভাবে আবেদন করবেন',
  'public.importantNotes': 'জানা দরকার',
  'public.academicYear': 'কোন বছরের জন্য',
  'public.awardBasis': 'কীসের ভিত্তিতে',
  'public.basis.MERIT': 'মেধা',
  'public.basis.NEED': 'আর্থিক প্রয়োজন',
  'public.basis.MERIT_CUM_MEANS': 'মেধা ও আয়',
  'public.basis.CATEGORY': 'শ্রেণি',
  'public.basis.OTHER': 'অন্যান্য',
  'public.cta': 'আপনার জন্য বৃত্তি খুঁজুন',
  'public.applyExternal': 'তাঁদের সাইটে আবেদন করুন',
  'public.applyExternalHelp': 'আপনি যাতে খুঁজে পান তাই আমরা এই বৃত্তিটি তালিকাভুক্ত করি। {org} এটি চালায় এবং নিজেদের ওয়েবসাইটে আবেদন নেয়, তাই এটি এখানে আপনার আবেদনের তালিকায় দেখা যাবে না।',
  'public.applyExternalHelpPartner': '{org} এই আবেদন নিজেদের ওয়েবসাইটে নেয়, তাই এটি এখানে আপনার আবেদনের তালিকায় দেখা যাবে না।',
  'common.newTab': 'নতুন ট্যাবে খোলে',
  'public.applyHelp': 'আমরা প্রথমে আপনার প্রোফাইল ও নথি এই বৃত্তির সঙ্গে মিলিয়ে দেখি এবং কিছু বাদ পড়লে জানাই। আপনি নিশ্চিত না করা পর্যন্ত কিছুই পাঠানো হয় না।',
  'public.ctaHelp': 'নিজের সম্পর্কে একবার বলুন, আর আমরা আপনাকে যোগ্য এমন প্রতিটি বৃত্তি দেখাব।',
  'public.back': 'সব বৃত্তিতে ফিরুন',
  'notFound.title': 'আমরা এই পেজটি খুঁজে পাইনি',
  'notFound.body': 'ঠিকানায় টাইপের ভুল থাকতে পারে, অথবা পেজটি সরানো হয়েছে।',
  'notFound.home': 'হোম পেজে যান',

  'nav.dashboard': 'ড্যাশবোর্ড',
  'dash.title': 'আপনার ড্যাশবোর্ড',
  'dash.lede': 'আপনার বৃত্তি, আবেদন ও নথি, সব এক জায়গায়।',
  'dash.matches': 'যে বৃত্তিগুলিতে আপনি আবেদন করতে পারেন',
  'dash.matchesHint': 'আপনার দেওয়া তথ্যের ভিত্তিতে।',
  'dash.matchesBlocked': '{n} আপনার কাছ থেকে আর একটি তথ্যের অপেক্ষায়।',
  'dash.applications': 'চলমান আবেদন',
  'dash.applicationsHint': '{approved} অনুমোদিত · {rejected} সফল হয়নি',
  'dash.applicationsNone': 'এখনও কিছু পাঠানো হয়নি।',
  'dash.documents': 'যাচাই করা নথি',
  'dash.documentsHint': 'একবার পরীক্ষা করা। প্রতিটি আবেদনে ব্যবহৃত।',
  'dash.funding': 'এ পর্যন্ত প্রাপ্ত',
  'dash.fundingHint': 'মোট {sanctioned} মঞ্জুর।',
  'dash.recent': 'সাম্প্রতিক আবেদন',
  'dash.noApplications': 'এখনও কোনো আবেদন নেই',
  'dash.noApplicationsHint': 'আপনি যার জন্যই আবেদন করুন তা এখানে দেখা যাবে।',
  'dash.findScholarships': 'বৃত্তি খুঁজুন',
  'dash.profileTitle': 'আপনার প্রোফাইল',
  'dash.toGo': '{n}% বাকি',
  'dash.allApplications': 'সব দেখুন',
  'dash.matchesGo': 'আপনার মিল দেখুন',
  'dash.applicationsGo': 'আপনার আবেদন দেখুন',
  'dash.documentsGo': 'নথি পরিচালনা করুন',
  'dash.draftsTitle': '{n}টি আবেদন পাঠানো হয়নি | {n}টি আবেদন পাঠানো হয়নি',
  'dash.draftsBody': 'আবেদন শুরু করলেই তা পাঠানো হয় না। বৃত্তি বন্ধ হওয়ার আগে শেষ করুন।',
  'dash.draftsAction': 'এখনই শেষ করুন',
  'dash.expiringTitle': '{n}টি নথির মেয়াদ শীঘ্রই শেষ | {n}টি নথির মেয়াদ শীঘ্রই শেষ',
  'dash.expiringBody': 'এখনই এটি বদলে নিন যাতে প্রতিটি আবেদনে কাজে লাগে। | এখনই এগুলি বদলে নিন যাতে প্রতিটি আবেদনে কাজে লাগে।',
  'dash.expiringAction': 'নথি দেখুন',

  'auth.title': 'আপনার মোবাইল নম্বর দিন',
  'auth.phone': 'মোবাইল নম্বর',
  'auth.phoneHint': 'আমরা এই নম্বরে এসএমএসে ৬ সংখ্যার একটি কোড পাঠাব। প্রতিবার এই নম্বরেই আপনি সাইন ইন করবেন।',
  'auth.phoneMissing': 'এগিয়ে যেতে আপনার মোবাইল নম্বর দিন।',
  'auth.phoneInvalid': 'এটি ঠিক মনে হচ্ছে না। ভারতীয় মোবাইল নম্বর ১০ সংখ্যার এবং ৬, ৭, ৮ বা ৯ দিয়ে শুরু হয়।',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'নতুন হোন বা ফিরে আসুন, একই নম্বর কাজ করে। অ্যাকাউন্ট না থাকলে আমরা তৈরি করে দিই।',
  'auth.stepOf': 'ধাপ {n} / ২ · {name}',
  'auth.stepPhone': 'আপনার নম্বর',
  'auth.stepCode': 'আপনার OTP কোড',
  'auth.privacy': 'আপনার নম্বর কেবল সাইন ইন করানোর জন্য ব্যবহৃত হয়, আর কিছুর জন্য নয়। মনে রাখার মতো কোনো পাসওয়ার্ড নেই।',
  'auth.sendCode': 'কোড পাঠান',
  'auth.sending': 'পাঠানো হচ্ছে…',
  'auth.checking': 'পরীক্ষা করা হচ্ছে…',
  'auth.welcomeBack': 'আবার স্বাগতম। সাইন ইন করতে কোডটি দিন।',
  'auth.newHere': 'কোড দিলেই আমরা আপনার অ্যাকাউন্ট তৈরি করে দেব।',
  'auth.codeTitle': 'আমরা যে কোড পাঠিয়েছি তা দিন',
  'auth.code': '৬ সংখ্যার কোড',
  'auth.codeHint': 'বার্তাটি সাধারণত কয়েক সেকেন্ডের মধ্যে আসে।',
  'auth.noCode': 'এখনও বার্তা আসেনি? অন্য উপায় দেখুন:',
  'auth.verify': 'যাচাই করুন',
  'auth.viaSms': 'এসএমএসে পাঠান',
  'auth.viaWhatsapp': 'হোয়াটসঅ্যাপে পাঠান',
  'auth.viaVoice': 'কোড বলতে আমাকে ফোন করুন',
  'auth.resentVia.sms': 'এসএমএসে পাঠানো হয়েছে। আসতে একটু সময় লাগতে পারে।',
  'auth.resentVia.whatsapp': 'হোয়াটসঅ্যাপে পাঠানো হয়েছে। বার্তার জন্য হোয়াটসঅ্যাপ দেখুন।',
  'auth.resentVia.voice': 'কোড বলতে এখনই ফোন করা হচ্ছে। শুনতে ফোন ধরুন।',
  'auth.resendIn': '{n} সেকেন্ডে আবার পাঠান',
  'auth.changeNumber': 'অন্য নম্বর ব্যবহার করুন',
  'auth.change': 'বদলান',

  'profile.complete': '{n}% সম্পূর্ণ',
  'profile.viewLede': 'আপনি আমাদের যা যা বলেছেন। যে কোনো উত্তর বদলান, তারপর থেকে প্রতিটি বৃত্তির জন্য সেটিই ব্যবহৃত হবে।',
  'profile.notAnswered': 'এখনও উত্তর দেওয়া হয়নি',
  'profile.verified': 'যাচাই করা',
  'profile.continue': 'যেখানে ছেড়েছিলেন সেখান থেকে চালিয়ে যান',
  'profile.start': 'আপনার প্রোফাইল শুরু করুন',
  'profile.saved': 'সংরক্ষিত',

  'match.title': 'আপনার জন্য বৃত্তি',
  'match.lede': 'আপনার প্রোফাইলের সঙ্গে মিলিয়ে দেখা। যেগুলিতে আবেদন করতে পারেন সেগুলি প্রথমে।',
  'match.eligible': 'আপনি যোগ্য',
  'match.likely': 'আপনি সম্ভবত যোগ্য',
  'match.blocked': 'আগে একটি কাজ',
  'match.actionable': 'আপনার জন্য খোলা',
  'match.actionableHelp': 'কয়েকটির ক্ষেত্রে আবেদনের আগে একটি নথি লাগতে পারে।',
  'match.ineligible': 'আপনার জন্য খোলা নয়',
  'match.eligibleHelp': 'আমরা যা যা পরীক্ষা করেছি সবই যাচাই করা।',
  'match.likelyHelp': 'আপনি যা বলেছেন তার ভিত্তিতে। যাচাই করিয়ে নিলে আপনার আবেদন আরও শক্ত হয়।',
  'match.blockedHelp': 'আপনি কাছাকাছি আছেন। এটি করলেই আবেদন করতে পারবেন।',
  'match.ineligibleHelp': 'এই প্রকল্প এমন কিছু চায় যা আপনি বদলাতে পারবেন না।',
  'match.apply': 'আবেদন করুন',
  'match.applied': 'আপনি আবেদন করেছেন',
  'match.none': 'এখনও কোনো মিল নেই',
  'match.noneHint': 'আপনার প্রোফাইল শেষ করুন, আমরা আপনার জন্য প্রতিটি বৃত্তি পরীক্ষা করব।',
  'match.figQualify': 'আপনি যোগ্য',
  'match.figStep': 'এক ধাপ দূরে',
  'match.figClosing': 'শীঘ্রই বন্ধ',
  'match.figNo': 'আপনার জন্য খোলা নয়',
  'match.filterLabel': 'কোন বৃত্তিগুলি দেখাবে',
  'match.filterAll': 'সব',
  'match.filterQualify': 'আপনি যোগ্য',
  'match.filterStep': 'এক ধাপ দূরে',
  'match.filterClosing': 'শীঘ্রই বন্ধ',
  'match.filterNo': 'আপনার জন্য খোলা নয়',
  'match.filterEmpty': 'এই দলে কিছু নেই। “সব” দেখুন।',
  'match.moreWithProfile': 'আপনি যত পূরণ করবেন তত বেশি বৃত্তি দেখা যাবে।',
  'match.youQualify': 'আপনার প্রোফাইল অনুযায়ী আপনি শর্ত পূরণ করেন।',
  'match.yesTitle': 'আপনি আবেদন করতে পারেন',
  'match.blockedTitle': 'আগে একটি কাজ',
  'match.noTitle': 'যোগ্য নন',
  'match.appliedTitle': 'ইতিমধ্যেই পাঠানো',
  'match.seeDetails': 'শর্তগুলি দেখুন',
  'match.learnMore': 'আরও জানুন',
  'match.runBy': '{kind} দ্বারা পরিচালিত',
  'match.sortBy': 'সাজান',
  'match.sortRecommended': 'প্রস্তাবিত',
  'match.sortClosing': 'সবার আগে বন্ধ হবে',
  'match.sortAward': 'সবচেয়ে বেশি অর্থ',
  'match.applyAway': 'তাঁদের সাইটে আবেদন করুন',
  'match.applyHere': 'এখানেই আবেদন করুন',
  'match.notOpenToYou': 'বর্তমান অবস্থায় আপনার জন্য খোলা নয়।',
  'match.working': 'এখন খোলা কোনো প্রকল্প আপনার দেওয়া তথ্যের সঙ্গে মেলে না। প্রোফাইলে আরও যোগ করলেই এটি বদলায়।',

  'doc.title': 'আপনার নথি',
  'doc.lede': 'একবার নথি আপলোড করুন। আপনি যে বৃত্তিতেই আবেদন করুন তা এটি ব্যবহার করতে পারবে — আপনাকে আর চাওয়া হবে না।',
  'doc.upload': 'নথি যোগ করুন',
  'doc.type': 'এটি কোন নথি?',
  'doc.file': 'ফাইল বাছুন',
  'doc.fileHint': 'পিডিএফ বা পরিষ্কার ছবি। ১০ এমবি পর্যন্ত।',
  'doc.verified': 'যাচাই করা',
  'doc.verifiedBy': '{org} দ্বারা যাচাই করা',
  'doc.pending': 'যাচাইয়ের অপেক্ষায়',
  'doc.expired': 'যাচাইয়ের মেয়াদ শেষ',
  'doc.expiring': '{n} দিনে মেয়াদ শেষ',
  'doc.validUntil': '{date} পর্যন্ত বৈধ',
  'doc.none': 'আপনি এখনও কোনো নথি যোগ করেননি',
  'doc.uploading': 'আপলোড হচ্ছে…',
  'doc.remove': 'সরান',
  'doc.removing': 'সরানো হচ্ছে…',

  'apply.title': 'আবেদন করুন',
  'apply.consent': 'আমার তথ্য এই প্রদানকারীর সঙ্গে ভাগ করুন',
  'apply.consentBody': 'সিদ্ধান্ত নিতে এই বৃত্তির যা দরকার কেবল তা-ই তাঁরা দেখবেন: {fields}. কে আপনার নথি দেখেছেন তা আপনি যে কোনো সময় দেখতে পারেন।',
  'apply.consentBodyNoDocs': 'সিদ্ধান্ত নিতে এই বৃত্তির যা দরকার কেবল তা-ই তাঁরা দেখবেন, আর কিছু নয়। কে আপনার তথ্য দেখেছেন তা আপনি যে কোনো সময় দেখতে পারেন।',
  'apply.submit': 'আমার আবেদন পাঠান',
  'apply.submitting': 'পাঠানো হচ্ছে…',
  'apply.blocked': 'আপনি এখনও আবেদন করতে পারবেন না',
  'apply.needProfile': 'আগে আপনার প্রোফাইল',
  'apply.needProfileHint': 'আবেদন আপনার প্রোফাইল থেকে পাঠানো হয়, তাই আবেদনের আগে সেটি দরকার। এতে কয়েক মিনিট লাগে, আর আপনি আগে যা বলেছেন তা পূরণ করা থাকে।',
  'apply.elsewhereTitle': 'এটির আবেদন পৃষ্ঠপোষকের ওয়েবসাইটে হয়',
  'apply.elsewhereBody': 'আপনি যাতে খুঁজে পান তাই আমরা এই বৃত্তিটি তালিকাভুক্ত করি, আর আবেদন পৃষ্ঠপোষক নিজেই নেন। আপনি আমাদের যা বলেছেন তা সংরক্ষিত থাকে, এবং আমরা যে বৃত্তিগুলি চালাই সেগুলির জন্য তা আগেই পূরণ করা থাকে।',
  'apply.elsewhereBodyPartner': 'এই বৃত্তি এখানেই চলে, তবে পৃষ্ঠপোষক আবেদন নিজেদের ওয়েবসাইটে নেন। আপনি আমাদের যা বলেছেন তা সংরক্ষিত থাকে, এবং আমরা যে আবেদনগুলি সরাসরি পাই সেগুলির জন্য তা আগেই পূরণ করা থাকে।',
  'apply.bundleTitle': 'আপনার নথি সঙ্গে নিয়ে যান',
  'apply.bundleBody': 'এই বৃত্তি যে নথিগুলি চায় সেগুলি আমরা একটি ফাইলে রাখতে পারি, তাঁদের ওয়েবসাইটে আপলোড করার জন্য তৈরি। তাঁরা যা চান অথচ আমাদের কাছে এখনও নেই, তাও এতে লেখা থাকে।',
  'apply.bundleAction': 'আমার নথি ডাউনলোড করুন',
  'apply.bundleWorking': 'প্রস্তুত করা হচ্ছে…',
  'apply.bundleDone': 'আপনার নথি ডাউনলোড হয়েছে।',
  'apply.docs': 'এই বৃত্তির জন্য প্রয়োজনীয় নথি',

  'appl.title': 'আপনার আবেদন',
  'appl.none': 'আপনি এখনও কিছুর জন্য আবেদন করেননি',
  'appl.noneHint': 'আপনি যোগ্য এমন বৃত্তি খুঁজতে আপনার মিল দেখুন।',
  'appl.reference': 'রেফারেন্স',
  'appl.whatNext': 'এরপর কী হবে',
  'appl.history': 'ইতিহাস',
  'appl.needsYou': 'তাঁদের আপনার কাছ থেকে কিছু দরকার',
  'track.label': 'এই আবেদনের অগ্রগতি',
  'track.sent': 'পাঠানো হয়েছে',
  'track.review': 'পর্যালোচনা',
  'track.decision': 'সিদ্ধান্ত',
  'track.doneSr': 'সম্পন্ন',
  'track.currentSr': 'এখন চলছে',
  'track.todoSr': 'শুরু হয়নি',
  'appl.sentOn': '{when} পাঠানো হয়েছে',
  'appl.decidedOn': '{when} সিদ্ধান্ত হয়েছে',
  'appl.outcomeApproved': 'পেয়েছেন',
  'appl.outcomeRejected': 'এবার পাননি',
  'appl.outcomeWithdrawn': 'আপনি এটি প্রত্যাহার করেছেন',
  'appl.inProgress': 'প্রদানকারীর কাছে',
  'appl.outcome': 'ফলাফল',
  'appl.award': 'অর্থের পরিমাণ',
  'appl.applied': 'আবেদন করা হয়েছে',
  'appl.decided': 'সিদ্ধান্ত হয়েছে',
  'appl.automatic': 'স্বয়ংক্রিয়',
  'appl.noHistory': 'এখনও কিছু ঘটেনি।',

  'ref.heading': 'তাঁদের ওয়েবসাইটে পাঠানো',
  'ref.blurb': 'এগুলির আবেদন প্রদানকারীর নিজস্ব সাইটে হয়, তাই কী হয়েছে তা আমরা দেখতে পাই না। আমাদের জানান, আমরা এটি বাকিগুলির সঙ্গে রেখে দেব।',
  'ref.sentOn': 'আপনি এটি {when} খুলেছিলেন',
  'ref.again': 'মোট {times} বার',
  'ref.open': 'তাঁদের সাইট আবার খুলুন',
  'ref.what': 'কী হয়েছিল?',
  'ref.APPLIED': 'আমি আবেদন করেছি',
  'ref.AWARDED': 'আমি এটি পেয়েছি',
  'ref.NOT_AWARDED': 'আমি এটি পাইনি',
  'ref.DID_NOT_APPLY': 'আমি আবেদন করিনি',
  'ref.saidAPPLIED': 'আপনি আবেদন করেছেন',
  'ref.saidAWARDED': 'আপনি এটি পেয়েছেন',
  'ref.saidNOT_AWARDED': 'আপনি এটি পাননি',
  'ref.saidDID_NOT_APPLY': 'আপনি আবেদন করেননি',
  'ref.youSaid': 'আপনি আমাদের বলেছেন: {what}',
  'ref.change': 'বদলান',

  'privacy.title': 'আপনার তথ্য',
  'privacy.lede': 'আমাদের কাছে কী আছে, কে দেখেছে, এবং কীভাবে ফিরিয়ে নেবেন।',
  'privacy.access': 'কারা আপনার নথি দেখেছেন',
  'privacy.accessNone': 'আপনার নিজের অ্যাকাউন্টের বাইরে কেউ আপনার নথি খোলেননি।',
  'privacy.consents': 'আপনি কী ভাগ করতে সম্মত হয়েছেন',
  'privacy.withdraw': 'প্রত্যাহার করুন',
  'privacy.withdrawing': 'প্রত্যাহার করা হচ্ছে…',
  'privacy.export': 'আমাদের কাছে যা আছে সব ডাউনলোড করুন',
  'privacy.exporting': 'আপনার প্রতিলিপি প্রস্তুত করা হচ্ছে…',
  'privacy.exportBody': 'আপনার তথ্যের সম্পূর্ণ যন্ত্রপাঠ্য প্রতিলিপি।',
  'privacy.erase': 'আমার তথ্য মুছুন',
  'privacy.erasing': 'অনুরোধ করা হচ্ছে…',
  'privacy.eraseBody': 'আপনাকে দেওয়া যে কোনো বৃত্তির নথি আমাদের রাখতেই হয়। বাকি সব সরিয়ে ফেলা হয়।',
  'auth.closedTitle': 'আপনার অ্যাকাউন্ট এই মুহূর্তে বন্ধ।',
  'auth.closedHelp': 'সাহায্য দরকার? আমাদের সহায়তা দল আপনাকে বুঝতে সাহায্য করতে পারে ',
  'auth.closedSoon': 'সহায়তা চান (শীঘ্রই)',
  'reg.district': 'জেলা',
  'reg.districtHint': 'আপনার এলাকায় চলা প্রকল্পের সঙ্গে মেলাতে সাহায্য করে।',
  'privacy.requested': 'অনুরোধ করা হয়েছে',
  'privacy.window': 'এখনও কিছুই মোছা হয়নি',
  'privacy.windowBody': 'আপনার তথ্য {date} মুছে ফেলা হবে। তার আগে পর্যন্ত আপনি ',
  'privacy.cancel': 'এই অনুরোধ বাতিল করুন',
  'privacy.cancelling': 'বাতিল করা হচ্ছে…',
  'privacy.cancelled': 'আপনার অনুরোধ বাতিল করা হয়েছে। কিছুই মোছা হয়নি।',

  'common.loading': 'লোড হচ্ছে',
  'common.retry': 'আবার চেষ্টা করুন',
  'common.required': 'আবশ্যক',
  'common.optional': 'ঐচ্ছিক',
  'common.error': 'কিছু ভুল হয়েছে',
  'common.offline': 'আপনি অফলাইনে আছেন। আপনার কাজ এই ডিভাইসে সংরক্ষিত।',

  'slides.lead.was': '',
  'slides.lead.able': 'সক্ষমতা থেকে',
  'slides.lead.dist': 'বিশিষ্টতায়',
  'slides.lead.body': 'আপনি যোগ্য এমন প্রতিটি বৃত্তি — সরকারি ও বেসরকারি — আপনার প্রোফাইলের সঙ্গে মিলিয়ে, আপনার ভাষায়, এক জায়গায়।',
  'slides.lead.free': 'সম্পূর্ণ বিনামূল্যে',
  'slides.lead.languages': '১৪টি ভাষা',
  'slides.lead.support': 'প্রতিটি ধাপে ব্যক্তিগত সহায়তা',
  'slides.label': 'ঘোষণা',
  'slides.position': '{total}-এর মধ্যে {n}',
  'slides.goto': '{name} দেখান',
  'slides.watch': 'ভিডিওটি দেখুন',
  'slides.external': 'অন্য ওয়েবসাইট খোলে',

  'home.title': 'প্রতিবন্ধী শিক্ষার্থীদের জন্য বৃত্তি, এক জায়গায়',
  'home.lede': 'নিজের সম্পর্কে একবার বলুন। আমরা এখানকার প্রতিটি বৃত্তির সঙ্গে আপনাকে মিলিয়ে দেখি এবং বলি কোনগুলিতে আপনি যোগ্য — আর বাকিগুলির জন্য ঠিক কী বাদ পড়ছে।',
  'home.search': 'বৃত্তি খুঁজুন',
  'home.searchPlaceholder': 'যেমন: ইঞ্জিনিয়ারিং, দিল্লি, পোস্ট-ম্যাট্রিক',
  'home.searchGo': 'খুঁজুন',
  'home.browseAll': 'সব বৃত্তি দেখুন',
  'home.openNow': 'বৃত্তি এখন খোলা',
  'home.noAccount': 'দেখার জন্য অ্যাকাউন্ট লাগে না।',
  'home.openNone': 'এখানে এখনও কোনো বৃত্তি তালিকাভুক্ত নেই।',
  'home.openNoneBody': 'তালিকাটি এখন তৈরি হচ্ছে। এখানে কিছুই অ্যাকাউন্টের আড়ালে নেই — প্রকল্প তালিকাভুক্ত হলে সাইন ইন না করেই দেখতে পাবেন।',
  'home.how': 'এটি কীভাবে কাজ করে',
  'home.howLede': 'নিবন্ধনের জন্য একটি মোবাইল নম্বর আর তাতে পাঠানো কোড লাগে। কোনো পাসওয়ার্ড নেই, আগে ভরার মতো কোনো সাইন-আপ ফর্মও নেই।',
  'home.step1': 'নিবন্ধন চাপুন',
  'home.step1Body': 'এই পাতার উপরে। আগে এসে থাকলে পাশের লগইন ব্যবহার করুন — দুটিতেই একই নম্বর কাজ করে।',
  'home.step2': 'আপনার মোবাইল নম্বর দিন',
  'home.step2Body': 'দশটি সংখ্যা, +91 আগে থেকেই বসানো। সেই নম্বরে ৬ সংখ্যার একটি কোড যায়।',
  'home.step3': 'কোডটি দিন',
  'home.step3Body': 'ছয়টি সংখ্যা লিখুন, আপনি ভিতরে। বার্তা না এলে কোডটি হোয়াটসঅ্যাপে চান, বা আমাদের ফোন করে পড়ে শোনাতে বলুন।',
  'home.step4': 'আপনার তথ্য পূরণ করুন',
  'home.step4Body': 'আপনার নাম, আপনার শংসাপত্র এবং কোথায় পড়েন — একবারে একটি প্রশ্ন, আর প্রতিটি উত্তর দেওয়ার সঙ্গে সঙ্গেই সংরক্ষিত হয়।',
  'home.step5': 'আপনার নথি আপলোড করুন',
  'home.step5Body': 'প্রতিবন্ধকতার শংসাপত্র, ইউডিআইডি কার্ড, আয়ের শংসাপত্র এবং বাকিগুলি। প্রতিটি একবারই, প্রতিটি বৃত্তির জন্য আলাদা করে নয়।',
  'home.step6': 'আপনার মিল দেখুন',
  'home.step6Body': 'আমার মিল সেই বৃত্তিগুলি দেখায় যেগুলিতে আপনি যোগ্য — আর কোনোটি আপনার জন্য বন্ধ হলে কারণ জানায়।',
  'home.step7': 'আবেদন করুন',
  'home.step7Body': 'যেগুলি চান বেছে নিন। আপনার তথ্য ও নথি আবেদনের সঙ্গে যায়।',
  'home.assure': 'জেনে রাখা ভালো',
  'home.assure1': 'মনে রাখার মতো কোনো পাসওয়ার্ড নেই',
  'home.assure2': 'আলাদা কোনো নিবন্ধন ফর্ম নেই',
  'home.assure3': 'থেমে পরে শেষ করতে পারেন',
  'home.help': 'কোনো ধাপে আটকে গেছেন?',
  'home.helpBody': 'ফোন করুন, কেউ আপনাকে পার করে দেবেন।',
  'home.helpCall': '{number}-এ ফোন করুন',
  'home.closing': 'শীঘ্রই বন্ধ',
  'home.closingLede': 'আগে এগুলিতে আবেদন করুন।',
  'home.closingNext': 'পরবর্তী শেষ তারিখ',
  'home.closingNextLede': 'সবার আগে বন্ধ হবে এমন তিনটি।',
  'home.allDeadlines': 'সব বৃত্তি দেখুন',
  'home.browse': 'যেভাবে দেখবেন',
  'home.browseWho': 'কে দিচ্ছে',
  'home.browseLevel': 'আপনার পড়াশোনার স্তর',
  'home.cta': 'আপনার মিল দেখতে প্রস্তুত?',
  'home.ctaBody': 'অ্যাকাউন্ট তৈরি করতে একটি মোবাইল নম্বর বা একটি ইমেল ঠিকানা লাগে। আর কিছু নয়।',
  'home.ctaButton': 'অ্যাকাউন্ট তৈরি করুন',
  'home.signedInCta': 'দেখুন আপনি কীসে যোগ্য',

  'reg.title': 'বৃত্তি খুঁজতে নিবন্ধন করুন',
  'reg.editTitle': 'আপনার তথ্য হালনাগাদ করুন',
  'reg.requiredNote': '* চিহ্নিত সব ঘর আবশ্যক।',
  'reg.personal': 'ব্যক্তিগত তথ্য',
  'reg.disability': 'প্রতিবন্ধকতার তথ্য',
  'reg.education': 'শিক্ষার তথ্য',
  'reg.name': 'পুরো নাম',
  'reg.namePlaceholder': 'আপনার পুরো নাম লিখুন',
  'reg.phoneHint': 'আমরা এই নম্বরে ৬ সংখ্যার একটি কোড পাঠাই। প্রতিবার এই নম্বরেই আপনি সাইন ইন করবেন।',
  'reg.sendOtp': 'ওটিপি পাঠান',
  'reg.otpPlaceholder': '৬ সংখ্যার ওটিপি লিখুন',
  'reg.verified': 'ফোন নম্বর যাচাই করা হয়েছে',
  'reg.verifyFirst': 'নিবন্ধন শেষ করতে আপনার ফোন নম্বর যাচাই করুন।',
  'reg.email': 'ইমেল',
  'reg.emailHint': 'যাতে আমরা শেষ তারিখের কথা মনে করিয়ে দিতে পারি। আমরা কখনও এটি ভাগ করি না।',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'লিঙ্গ',
  'reg.genderHint': '(কিছু বৃত্তি কেবল নারী বা রূপান্তরকামী শিক্ষার্থীদের জন্য)',
  'reg.udid': 'ইউডিআইডি নম্বর',
  'reg.udidHint': 'আপনার ইউডিআইডি (অনন্য প্রতিবন্ধকতা পরিচয়) কার্ডে লেখা নম্বর।',
  'reg.udidPlaceholder': 'আপনার ইউডিআইডি নম্বর লিখুন',
  'reg.certificate': 'ইউডিআইডি শংসাপত্র আপলোড করুন',
  'reg.certificateHint': 'পিডিএফ বা ছবি, ৫ এমবি বা তার কম।',
  'reg.fileType': 'সেই ফাইলটি পিডিএফ, জেপিইজি বা পিএনজি হতে হবে।',
  'reg.fileSize': 'সেই ফাইলটি ৫ এমবি-র বড়। ফোনে তোলা ছবি সাধারণত ছোট হয় যদি ছবি না তুলে স্ক্যান করেন।',
  'reg.fileLater': 'আপনার নিবন্ধন হয়ে গেছে এবং তথ্য সংরক্ষিত। শংসাপত্রটি আপলোড হয়নি — আমার নথি থেকে যোগ করে দিন, আর কিছুই নতুন করে করতে হবে না।',
  'reg.disabilityType': 'প্রতিবন্ধকতার ধরন',
  'reg.percent': 'প্রতিবন্ধকতার শতাংশ',
  'reg.percentHint': 'আপনার শংসাপত্রে লেখা সংখ্যা। অনেক বৃত্তির জন্য ৪০% বা তার বেশি লাগে।',
  'reg.percentPlaceholder': 'যেমন ৪০',
  'reg.percentRange': 'শংসাপত্রের শতাংশ ০ থেকে ১০০-র মধ্যে একটি পূর্ণসংখ্যা।',
  'reg.state': 'রাজ্য',
  'reg.statePlaceholder': 'আপনার রাজ্য খুঁজতে লিখুন…',
  'reg.program': 'আপনার কোর্স বাছুন',
  'reg.graduation': 'স্নাতক',
  'reg.postgraduation': 'স্নাতকোত্তর / মাস্টার্স',
  'reg.year': 'বছর বাছুন',
  'reg.yearAfterProgram': 'আগে আপনার কোর্স বাছুন',
  'reg.institution': 'স্কুল / কলেজের নাম',
  'reg.institutionPlaceholder': 'আপনার প্রতিষ্ঠানের নাম লিখুন',
  'reg.required': 'এটি দরকার।',
  'reg.fix': 'কয়েকটি উত্তরে নজর দেওয়া দরকার। প্রথমটি নিচে বাছা আছে।',
  'reg.cta': 'নিবন্ধন করুন এবং বৃত্তি খুঁজুন',
  'reg.saveChanges': 'পরিবর্তন সংরক্ষণ করুন',
  'reg.saving': 'সংরক্ষণ করা হচ্ছে…',
  'reg.done': 'নিবন্ধন হয়েছে। আপনার বৃত্তি খোঁজা হচ্ছে।',
  'reg.doneTitle': 'আপনার নিবন্ধন হয়ে গেছে',
  'reg.already': 'আগেই নিবন্ধিত?',
  'reg.login': 'ওটিপি দিয়ে লগইন',
  'nav.registerCta': 'নিবন্ধন',
  'nav.loginCta': 'লগইন',
  'profile.edit': 'আপনার তথ্য হালনাগাদ করুন',
  'field.disability.BLINDNESS': 'দৃষ্টিহীনতা',
  'field.disability.LOW_VISION': 'ক্ষীণ দৃষ্টি',
  'field.disability.LEPROSY_CURED': 'কুষ্ঠ (নিরাময় হয়েছে)',
  'field.disability.HEARING_IMPAIRMENT': 'শ্রবণ প্রতিবন্ধকতা',
  'field.disability.LOCOMOTOR_DISABILITY': 'চলাফেরার প্রতিবন্ধকতা',
  'field.disability.DWARFISM': 'খর্বাকৃতি',
  'field.disability.INTELLECTUAL_DISABILITY': 'বৌদ্ধিক প্রতিবন্ধকতা',
  'field.disability.MENTAL_ILLNESS': 'মানসিক অসুস্থতা',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'অটিজম স্পেকট্রাম ডিসঅর্ডার',
  'field.disability.CEREBRAL_PALSY': 'সেরিব্রাল পালসি',
  'field.disability.MUSCULAR_DYSTROPHY': 'পেশি ক্ষয়রোগ',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'দীর্ঘস্থায়ী স্নায়বিক অবস্থা',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'নির্দিষ্ট শিখন প্রতিবন্ধকতা',
  'field.disability.MULTIPLE_SCLEROSIS': 'মাল্টিপল স্ক্লেরোসিস',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'বাক ও ভাষা প্রতিবন্ধকতা',
  'field.disability.THALASSEMIA': 'থ্যালাসেমিয়া',
  'field.disability.HAEMOPHILIA': 'হিমোফিলিয়া',
  'field.disability.SICKLE_CELL_DISEASE': 'সিকল সেল রোগ',
  'field.disability.MULTIPLE_DISABILITIES': 'একাধিক প্রতিবন্ধকতা, দৃষ্টি-শ্রবণ প্রতিবন্ধকতা সহ',
  'field.disability.ACID_ATTACK_VICTIM': 'অ্যাসিড আক্রমণ থেকে বেঁচে যাওয়া',
  'field.disability.PARKINSONS_DISEASE': 'পারকিনসন্স রোগ',

  'field.state.AN': 'আন্দামান ও নিকোবর দ্বীপপুঞ্জ',
  'field.state.AP': 'অন্ধ্রপ্রদেশ',
  'field.state.AR': 'অরুণাচল প্রদেশ',
  'field.state.AS': 'আসাম',
  'field.state.BR': 'বিহার',
  'field.state.CH': 'চণ্ডীগড়',
  'field.state.CT': 'ছত্তীসগঢ়',
  'field.state.DL': 'দিল্লি',
  'field.state.DN': 'দাদরা ও নগর হাভেলি এবং দমন ও দিউ',
  'field.state.GA': 'গোয়া',
  'field.state.GJ': 'গুজরাট',
  'field.state.HP': 'হিমাচল প্রদেশ',
  'field.state.HR': 'হরিয়ানা',
  'field.state.JH': 'ঝাড়খণ্ড',
  'field.state.JK': 'জম্মু ও কাশ্মীর',
  'field.state.KA': 'কর্ণাটক',
  'field.state.KL': 'কেরল',
  'field.state.LA': 'লাদাখ',
  'field.state.LD': 'লক্ষদ্বীপ',
  'field.state.MH': 'মহারাষ্ট্র',
  'field.state.ML': 'মেঘালয়',
  'field.state.MN': 'মণিপুর',
  'field.state.MP': 'মধ্যপ্রদেশ',
  'field.state.MZ': 'মিজোরাম',
  'field.state.NL': 'নাগাল্যান্ড',
  'field.state.OR': 'ওড়িশা',
  'field.state.PB': 'পাঞ্জাব',
  'field.state.PY': 'পুদুচেরি',
  'field.state.RJ': 'রাজস্থান',
  'field.state.SK': 'সিকিম',
  'field.state.TG': 'তেলঙ্গানা',
  'field.state.TN': 'তামিলনাড়ু',
  'field.state.TR': 'ত্রিপুরা',
  'field.state.UP': 'উত্তরপ্রদেশ',
  'field.state.UT': 'উত্তরাখণ্ড',
  'field.state.WB': 'পশ্চিমবঙ্গ',

  'field.level.SCHOOL': 'বিদ্যালয়',
  'field.level.SCHOOL.sub': 'নবম, দশম, একাদশ, দ্বাদশ শ্রেণি',
  'field.level.UNDERGRADUATE': 'স্নাতক',
  'field.level.UNDERGRADUATE.sub': 'বিএ, বিএসসি, বিটেক এবং অনুরূপ',
  'field.level.POSTGRADUATE': 'স্নাতকোত্তর',
  'field.level.POSTGRADUATE.sub': 'এমএ, এমএসসি, এমটেক এবং অনুরূপ',
  'field.level.DOCTORAL': 'ডক্টরেট',
  'field.level.DOCTORAL.sub': 'পিএইচডি',

  'field.qual.SCHOOL': 'বিদ্যালয়',
  'field.qual.SCHOOL.sub': 'প্রথম থেকে দ্বাদশ শ্রেণি',
  'field.qual.UNDERGRADUATE': 'স্নাতক',
  'field.qual.UNDERGRADUATE.sub': 'বিএ, বিএসসি, বিকম, বিই / বিটেক, এমবিবিএস — এবং ডিপ্লোমা বা আইটিআই',
  'field.qual.POSTGRADUATE': 'স্নাতকোত্তর',
  'field.qual.POSTGRADUATE.sub': 'এমএ, এমএসসি, এমটেক, এমবিএ এবং অনুরূপ',
  'field.qual.DOCTORAL': 'পিএইচডি / ডক্টরেট',

  'field.subject.engineering': 'ইঞ্জিনিয়ারিং',
  'field.subject.medical': 'চিকিৎসা',
  'field.subject.management': 'ব্যবস্থাপনা',
  'field.subject.science': 'বিজ্ঞান',
  'field.subject.commerce': 'বাণিজ্য',
  'field.subject.arts': 'কলা ও মানবিক বিদ্যা',
  'field.subject.vocational': 'বৃত্তিমূলক',
  'field.subject.fellowship': 'ফেলোশিপ',
  'field.subject.talent': 'প্রতিভা',
  'field.subject.sports': 'ক্রীড়া',

  'field.gender.FEMALE': 'মহিলা',
  'field.gender.MALE': 'পুরুষ',
  'field.gender.TRANSGENDER': 'রূপান্তরকামী',
  'field.gender.UNDISCLOSED': 'বলতে চাই না',
  'field.genderFilter.TRANSGENDER': 'তৃতীয় লিঙ্গ / রূপান্তরকামী',

  'field.year.below9': 'নবম শ্রেণির নিচে',
  'field.year.c9': 'নবম শ্রেণি',
  'field.year.c10': 'দশম শ্রেণি',
  'field.year.c11': 'একাদশ শ্রেণি',
  'field.year.c12': 'দ্বাদশ শ্রেণি',
  'field.year.y1': 'প্রথম বর্ষ',
  'field.year.y2': 'দ্বিতীয় বর্ষ',
  'field.year.y3': 'তৃতীয় বর্ষ',
  'field.year.y4': 'চতুর্থ বর্ষ',
  'field.year.pg1': 'স্নাতকোত্তর ১ম বর্ষ',
  'field.year.pg2': 'স্নাতকোত্তর ২য় বর্ষ',

  'q.full_name': 'আপনার নাম কী?',
  'q.full_name.help': 'ঠিক যেমনটি আপনার প্রতিবন্ধকতার শংসাপত্রে লেখা আছে। প্রদানকারীরা দুটি মিলিয়ে দেখেন।',
  'q.gender': 'আপনার লিঙ্গ কী?',
  'q.gender.help': 'কিছু বৃত্তি কেবল মহিলাদের জন্য, বা রূপান্তরকামী শিক্ষার্থীদের জন্য। বলতে না চাইলে ছেড়ে দিন।',
  'q.disability_type': 'আপনার প্রতিবন্ধকতা কী?',
  'q.disability_type.help': 'যেমনটি আপনার শংসাপত্রে লেখা আছে। বেশিরভাগ বৃত্তি এর উপরেই বাছাই করে।',
  'q.disability_percent': 'আপনার শংসাপত্রে কত শতাংশ আছে?',
  'q.disability_percent.help': '০ থেকে ১০০-র মধ্যে একটি সংখ্যা। অনেক বৃত্তির জন্য ৪০% বা তার বেশি লাগে।',
  'q.disability_percent.range': 'শংসাপত্রের শতাংশ ০ থেকে ১০০-র মধ্যে হয়।',
  'q.udid_number': 'আপনার ইউডিআইডি নম্বর কী?',
  'q.udid_number.help': 'আপনার ইউডিআইডি (অনন্য প্রতিবন্ধকতা পরিচয়) কার্ডে লেখা নম্বর। এখনও না পেয়ে থাকলে ছেড়ে দিন — এতে আপনি কীসের যোগ্য তার কোনও বদল হয় না, এবং পরে যোগ করতে পারবেন।',
  'q.date_of_birth': 'আপনার জন্ম কবে?',
  'q.date_of_birth.help': 'কিছু বৃত্তিতে বয়সের সীমা থাকে।',
  'q.course_name': 'আপনি কী পড়ছেন?',
  'q.course_name.help': 'নিবন্ধনের সময় আপনি যে কোর্সটি বেছেছিলেন।',
  'q.institution_name': 'আপনি কোথায় পড়েন?',
  'q.institution_name.help': 'আপনার স্কুল, কলেজ বা বিশ্ববিদ্যালয়ের নাম, যেমনটি আপনার বোনাফাইড শংসাপত্রে লেখা আছে। এখনও শুরু না করে থাকলে ছেড়ে দিন।',
  'q.institution_name.placeholder': 'আপনার স্কুল বা কলেজের নাম',
  'q.state_code': 'আপনি কোন রাজ্যে থাকেন?',
  'q.state_code.help': 'অনেক বৃত্তি কেবল কিছু রাজ্যের বাসিন্দাদের জন্য খোলা।',
  'q.annual_family_income': 'আপনার পরিবারের বার্ষিক আয় কত?',
  'q.annual_family_income.help': 'টাকায়, যেমনটি আপনার আয়ের শংসাপত্রে আছে। বেশিরভাগ বৃত্তিতে একটি ঊর্ধ্বসীমা থাকে।',
  'q.annual_family_income.range': 'আয় শূন্যের কম হতে পারে না।',
  'q.academic_percentage': 'আপনার শেষ পরীক্ষার নম্বর কত ছিল?',
  'q.academic_percentage.help': 'আপনার মার্কশিট যেভাবে সেগুলি জানায় তা বেছে নিন, তারপর সংখ্যাটি লিখুন। অনেক বৃত্তি একটি ন্যূনতম চায়।',
  'field.orgKind.NGO': 'এনজিও',
  'field.orgKind.CORPORATE': 'কর্পোরেট',
  'field.orgKind.GOVERNMENT': 'সরকারি',
  'field.orgKind.PRIVATE': 'বেসরকারি',

  'field.doc.DISABILITY_CERTIFICATE': 'প্রতিবন্ধকতার শংসাপত্র',
  'field.doc.UDID_CARD': 'ইউডিআইডি কার্ড',
  'field.doc.INCOME_CERTIFICATE': 'আয়ের শংসাপত্র',
  'field.doc.DOMICILE_CERTIFICATE': 'বাসস্থানের শংসাপত্র',
  'field.doc.CASTE_CERTIFICATE': 'শ্রেণির শংসাপত্র',
  'field.doc.MARKSHEET': 'মার্কশিট',
  'field.doc.ADMISSION_LETTER': 'ভর্তির চিঠি',
  'field.doc.BONAFIDE_CERTIFICATE': 'বোনাফাইড শংসাপত্র',
  'field.doc.FEE_RECEIPT': 'ফি-র রসিদ',
  'field.doc.BANK_PASSBOOK': 'ব্যাঙ্কের পাসবই',
  'field.doc.IDENTITY_PROOF': 'পরিচয়ের প্রমাণ',
  'field.doc.PHOTOGRAPH': 'ছবি',

  'appl.next.SUBMITTED': 'প্রদানকারীর কাছে আপনার আবেদন আছে। এরপর একজন পর্যালোচক সেটি পড়বেন।',
  'appl.next.UNDER_REVIEW': 'একজন পর্যালোচক আপনার আবেদন পড়ছেন। সাধারণত এটিই দীর্ঘতম ধাপ।',
  'appl.next.INFO_REQUESTED': 'তাঁরা আপনার কাছে কিছু চেয়েছেন। আপনি উত্তর না দেওয়া পর্যন্ত আবেদনটি অপেক্ষা করবে।',
  'appl.next.DOCUMENT_CHECK': 'আপনার আবেদন একজন পর্যালোচকের কাছে আছে। আপনার কাছ থেকে কিছু দরকার নেই।',
  'appl.next.VERIFIED': 'আপনার আবেদন একজন পর্যালোচকের কাছে আছে। আপনার কাছ থেকে কিছু দরকার নেই।',
  'appl.next.SHORTLISTED': 'আপনার আবেদন একজন পর্যালোচকের কাছে আছে। এরপর সিদ্ধান্ত।',
  'appl.next.APPROVED': 'অনুমোদিত। প্রদানকারী মঞ্জুরি নথিভুক্ত করবেন, তারপর অর্থপ্রদানের ব্যবস্থা করবেন।',
  'appl.next.SANCTIONED': 'অর্থ মঞ্জুর হয়েছে। অর্থপ্রদান তাঁদের ব্যাঙ্কের মাধ্যমে করা হয়।',
  'appl.next.DISBURSED': 'অর্থপ্রদান নথিভুক্ত হয়েছে। কয়েক কর্মদিবসের মধ্যে আপনার অ্যাকাউন্টে না পৌঁছালে অভিযোগ জানান।',
  'appl.next.REJECTED': 'এই আবেদনটি সফল হয়নি। এতে আপনার অন্য আবেদনগুলিতে কোনও প্রভাব পড়ে না।',
  'appl.next.CLOSED': 'এই আবেদনটি সম্পূর্ণ।',
  'appl.next.WITHDRAWN': 'আপনি এই আবেদনটি প্রত্যাহার করেছিলেন।',
}

export default bn
