/* Gujarati.
 *
 * One word per term: scholarship શિષ્યવૃત્તિ, application અરજી,
 * document દસ્તાવેજ, disability દિવ્યાંગતા (the RPwD Act's word), verified
 * ચકાસાયેલ, eligible પાત્ર, certificate પ્રમાણપત્ર, profile પ્રોફાઇલ.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const gu: Dict = {
  'app.name': 'ઇન્ડિક એઆઈ શિષ્યવૃત્તિ',
  'app.tagline': 'દિવ્યાંગ વિદ્યાર્થીઓ માટે',
  'app.yourApplication': 'તમારી અરજી · {title}',

  'nav.find': 'શિષ્યવૃત્તિઓ',
  'nav.how': 'આ કેવી રીતે કામ કરે છે',
  'nav.matches': 'મારા મેળ',
  'nav.applications': 'મારી અરજીઓ',
  'nav.documents': 'મારા દસ્તાવેજો',
  'nav.profile': 'મારી પ્રોફાઇલ',
  'nav.privacy': 'મારી માહિતી',
  'nav.account': 'મારું ખાતું',
  'nav.register': 'સાઇન અપ',
  'nav.language': 'ભાષા',
  'footer.social': 'ઇન્ડિક એઆઈ અન્યત્ર',
  'footer.sponsor': 'સહયોગથી',
  'footer.copyright': 'કૉપીરાઇટ © {year} ઇન્ડિક એઆઈ | સર્વ હક્ક સ્વાધીન',
  'nav.signin': 'સાઇન ઇન',
  'nav.signout': 'સાઇન આઉટ',
  'nav.skip': 'મુખ્ય સામગ્રી પર જાઓ',

  'public.title': 'તમે જેના માટે પાત્ર હો તે શિષ્યવૃત્તિ શોધો',
  'public.lede': 'અહીંની દરેક શિષ્યવૃત્તિ દિવ્યાંગ વિદ્યાર્થીઓ માટે ખુલ્લી છે. જોવા માટે ખાતું જરૂરી નથી.',
  'public.search': 'નામ કે શબ્દથી શોધો',
  'public.filter.disability': 'દિવ્યાંગતાનો પ્રકાર',
  'public.filter.qualification': 'લાયકાત',
  'public.filter.state': 'તમારું રાજ્ય',
  'public.filter.provider': 'કોણ આપે છે',
  'public.filter.any': 'કોઈપણ',
  'public.filter.anyDisability': 'કોઈપણ દિવ્યાંગતા',
  'public.filter.anyQualification': 'કોઈપણ લાયકાત',
  'public.filter.allStates': 'બધાં રાજ્યો',
  'public.filter.gender': 'લિંગ',
  'public.filter.anyGender': 'કોઈપણ લિંગ',
  'public.filter.course': 'અભ્યાસક્રમ',
  'public.filter.anyCourse': 'કોઈપણ અભ્યાસક્રમ',
  'public.filter.where': 'તમે ક્યાં ભણો છો',
  'public.filter.anyWhere': 'ભારત કે વિદેશ',
  'public.filter.inIndia': 'ભારતમાં',
  'public.filter.abroad': 'વિદેશમાં અભ્યાસ',
  'public.filters': 'ફિલ્ટર',
  'public.clear': 'દૂર કરો',
  'public.results': 'શિષ્યવૃત્તિઓ અત્યારે ખુલ્લી છે',
  'public.searching': 'શોધી રહ્યા છીએ…',
  'public.none': 'આ ફિલ્ટરો સાથે કોઈ શિષ્યવૃત્તિ મેળ ખાતી નથી',
  'public.none.hint': 'એક ફિલ્ટર દૂર કરીને જુઓ. આખું વર્ષ નવી યોજનાઓ ખૂલે છે.',
  'public.none.clear': 'બધાં ફિલ્ટર દૂર કરો',
  'public.empty': 'અહીં હજી કોઈ શિષ્યવૃત્તિ યાદીમાં નથી',
  'public.empty.hint': 'પ્રદાતાઓ હમણાં ઉમેરાઈ રહ્યા છે. અહીં કશું ખાતાની પાછળ નથી — યોજનાઓ યાદીમાં આવશે ત્યારે સાઇન ઇન કર્યા વગર જ દેખાશે.',
  'public.whoFor': 'આ કોના માટે છે',
  'public.about': 'આ શિષ્યવૃત્તિ વિશે',
  'public.atAGlance': 'એક નજરે',
  'public.closes': 'બંધ થાય છે',
  'public.awardUnstated': 'રકમ જણાવી નથી',
  'public.noClose': 'છેલ્લી તારીખ નથી',
  'public.closesIn': '{n} દિવસોમાં બંધ',
  'public.closesToday': 'આજે બંધ થાય છે',
  'public.closed': 'બંધ',
  'public.award': 'રકમ',
  'public.renewable': 'દર વર્ષે નવીકરણ કરી શકાય',
  'public.offeredBy': 'આપનાર',
  'public.eligibility': 'પાત્ર થવા માટે',
  'public.benefits': 'લાભ',
  'public.readMore': 'વધુ વાંચો',
  'public.viewDetails': 'વિગતો જુઓ',
  'public.applyNow': 'હમણાં અરજી કરો',
  'public.registerToApply': 'અરજી કરો',
  'public.registerToApplyHelp': 'અરજીઓ તમારા ખાતા દ્વારા થાય છે. નોંધણી કરવાથી તમે જેના માટે પાત્ર હો તે દરેક શિષ્યવૃત્તિ પણ દેખાશે.',
  'public.closedNote': 'આ યોજના બંધ થઈ ગઈ છે',
  'sheet.close': 'બંધ કરો',
  'sheet.loading': 'શિષ્યવૃત્તિની વિગતો',
  'public.benefitComponent': 'ઘટક',
  'public.benefitAmount': 'વિદ્યાર્થીને શું મળે છે',
  'public.whatYouGet': 'તમને શું મળશે',
  'public.eligibilityDetail': 'પાત્રતા વિગતે',
  'public.documentsRequired': 'જરૂરી દસ્તાવેજો',
  'public.documentsHelp': 'પ્રદાતા આ માગે છે. આ તમે અહીં અપલોડ કરતા નથી.',
  'public.howToApply': 'કેવી રીતે અરજી કરવી',
  'public.importantNotes': 'જાણવા જેવું',
  'public.academicYear': 'કયા વર્ષ માટે',
  'public.awardBasis': 'કયા આધારે',
  'public.basis.MERIT': 'ગુણવત્તા',
  'public.basis.NEED': 'આર્થિક જરૂરિયાત',
  'public.basis.MERIT_CUM_MEANS': 'ગુણવત્તા અને આવક',
  'public.basis.CATEGORY': 'શ્રેણી',
  'public.basis.OTHER': 'અન્ય',
  'public.cta': 'તમારા માટે શિષ્યવૃત્તિઓ શોધો',
  'public.applyExternal': 'તેમની સાઇટ પર અરજી કરો',
  'public.applyExternalHelp': 'તમે શોધી શકો એ માટે જ અમે આ શિષ્યવૃત્તિ યાદીમાં મૂકીએ છીએ. {org} તે ચલાવે છે અને પોતાની વેબસાઇટ પર જ અરજીઓ લે છે, તેથી તે અહીં તમારી અરજીઓમાં દેખાશે નહીં.',
  'public.applyExternalHelpPartner': '{org} આ અરજી પોતાની વેબસાઇટ પર જ લે છે, તેથી તે અહીં તમારી અરજીઓમાં દેખાશે નહીં.',
  'common.newTab': 'નવા ટૅબમાં ખૂલે છે',
  'public.applyHelp': 'અમે પહેલાં તમારી પ્રોફાઇલ અને દસ્તાવેજો આ શિષ્યવૃત્તિ સામે તપાસીએ છીએ અને કંઈ ખૂટતું હોય તો જણાવીએ છીએ. તમે ખાતરી ન કરો ત્યાં સુધી કશું મોકલાતું નથી.',
  'public.ctaHelp': 'તમારા વિશે એકવાર જણાવો અને અમે તમને દરેક શિષ્યવૃત્તિ બતાવીશું જેના માટે તમે પાત્ર છો.',
  'public.back': 'બધી શિષ્યવૃત્તિઓ પર પાછા',
  'notFound.title': 'અમને આ પેજ મળ્યું નહીં',
  'notFound.body': 'સરનામામાં ટાઇપિંગની ભૂલ હોઈ શકે, અથવા પેજ ખસેડાયું હોઈ શકે.',
  'notFound.home': 'હોમ પેજ પર જાઓ',

  'nav.dashboard': 'ડૅશબોર્ડ',
  'dash.title': 'તમારું ડૅશબોર્ડ',
  'dash.lede': 'તમારી શિષ્યવૃત્તિઓ, અરજીઓ અને દસ્તાવેજો, બધું એક જગ્યાએ.',
  'dash.matches': 'જે શિષ્યવૃત્તિઓ માટે તમે અરજી કરી શકો',
  'dash.matchesHint': 'તમે આપેલી વિગતોના આધારે.',
  'dash.matchesBlocked': '{n} તમારી પાસેથી એક વધુ વિગતની રાહ જુએ છે.',
  'dash.applications': 'ચાલુ અરજીઓ',
  'dash.applicationsHint': '{approved} મંજૂર · {rejected} સફળ નહીં',
  'dash.applicationsNone': 'હજી કશું મોકલાયું નથી.',
  'dash.documents': 'ચકાસાયેલા દસ્તાવેજો',
  'dash.documentsHint': 'એકવાર તપાસેલા. દરેક અરજીમાં કામ લાગે છે.',
  'dash.funding': 'અત્યાર સુધી મળેલું',
  'dash.fundingHint': 'કુલ {sanctioned} મંજૂર.',
  'dash.recent': 'તાજેતરની અરજીઓ',
  'dash.noApplications': 'હજી કોઈ અરજી નથી',
  'dash.noApplicationsHint': 'તમે જેના માટે પણ અરજી કરશો તે અહીં દેખાશે.',
  'dash.findScholarships': 'શિષ્યવૃત્તિઓ શોધો',
  'dash.profileTitle': 'તમારી પ્રોફાઇલ',
  'dash.toGo': '{n}% બાકી',
  'dash.allApplications': 'બધું જુઓ',
  'dash.matchesGo': 'તમારા મેળ જુઓ',
  'dash.applicationsGo': 'તમારી અરજીઓ પર નજર રાખો',
  'dash.documentsGo': 'દસ્તાવેજો સંભાળો',
  'dash.draftsTitle': '{n} અરજી મોકલાઈ નથી | {n} અરજીઓ મોકલાઈ નથી',
  'dash.draftsBody': 'અરજી શરૂ કરવાથી તે મોકલાઈ જતી નથી. શિષ્યવૃત્તિ બંધ થાય તે પહેલાં પૂરી કરો.',
  'dash.draftsAction': 'હમણાં પૂરી કરો',
  'dash.expiringTitle': '{n} દસ્તાવેજની મુદત ટૂંક સમયમાં પૂરી થાય છે | {n} દસ્તાવેજોની મુદત ટૂંક સમયમાં પૂરી થાય છે',
  'dash.expiringBody': 'દરેક અરજીમાં કામ લાગે તે માટે હમણાં જ તે બદલો. | દરેક અરજીમાં કામ લાગે તે માટે હમણાં જ તે બદલો.',
  'dash.expiringAction': 'દસ્તાવેજો તપાસો',

  'auth.title': 'તમારો મોબાઇલ નંબર આપો',
  'auth.phone': 'મોબાઇલ નંબર',
  'auth.phoneHint': 'અમે આ નંબર પર SMS દ્વારા 6 આંકડાનો કોડ મોકલીશું. દર વખતે આ જ નંબર તમને સાઇન ઇન કરાવે છે.',
  'auth.phoneMissing': 'આગળ વધવા તમારો મોબાઇલ નંબર આપો.',
  'auth.phoneInvalid': 'આ બરાબર લાગતું નથી. ભારતીય મોબાઇલ નંબર 10 આંકડાના હોય છે અને 6, 7, 8 કે 9 થી શરૂ થાય છે.',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'નવા હો કે પાછા આવતા હો, એ જ નંબર કામ કરે છે. તમારું ખાતું ન હોય તો અમે બનાવી આપીએ છીએ.',
  'auth.stepOf': 'પગલું {n} / 2 · {name}',
  'auth.stepPhone': 'તમારો નંબર',
  'auth.stepCode': 'તમારો OTP કોડ',
  'auth.privacy': 'તમારો નંબર માત્ર તમને સાઇન ઇન કરાવવા વપરાય છે, બીજા કશા માટે નહીં. યાદ રાખવા માટે કોઈ પાસવર્ડ નથી.',
  'auth.sendCode': 'કોડ મોકલો',
  'auth.sending': 'મોકલાઈ રહ્યું છે…',
  'auth.checking': 'તપાસી રહ્યા છીએ…',
  'auth.welcomeBack': 'ફરી સ્વાગત છે. સાઇન ઇન કરવા કોડ આપો.',
  'auth.newHere': 'કોડ આપતાં જ અમે તમારું ખાતું બનાવી દઈશું.',
  'auth.codeTitle': 'અમે મોકલેલો કોડ આપો',
  'auth.code': '6 આંકડાનો કોડ',
  'auth.codeHint': 'સંદેશ સામાન્ય રીતે થોડી જ સેકન્ડમાં આવી જાય છે.',
  'auth.noCode': 'હજી સંદેશ આવ્યો નથી? બીજો રસ્તો અજમાવો:',
  'auth.verify': 'ચકાસો',
  'auth.viaSms': 'SMS થી મોકલો',
  'auth.viaWhatsapp': 'વૉટ્સઍપ પર મોકલો',
  'auth.viaVoice': 'કોડ કહેવા મને ફોન કરો',
  'auth.resentVia.sms': 'SMS થી મોકલ્યો. આવતાં થોડી વાર લાગી શકે.',
  'auth.resentVia.whatsapp': 'વૉટ્સઍપ પર મોકલ્યો. સંદેશ માટે વૉટ્સઍપ જુઓ.',
  'auth.resentVia.voice': 'કોડ કહેવા હમણાં ફોન કરી રહ્યા છીએ. સાંભળવા ફોન ઉપાડો.',
  'auth.resendIn': '{n} સેકન્ડમાં ફરી મોકલો',
  'auth.changeNumber': 'બીજો નંબર વાપરો',
  'auth.change': 'બદલો',

  'profile.complete': '{n}% પૂર્ણ',
  'profile.viewLede': 'તમે અમને જે કહ્યું તે બધું. કોઈપણ જવાબ બદલો અને ત્યારથી દરેક શિષ્યવૃત્તિ માટે તે જ વપરાશે.',
  'profile.notAnswered': 'હજી જવાબ આપ્યો નથી',
  'profile.verified': 'ચકાસાયેલ',
  'profile.continue': 'જ્યાં છોડ્યું ત્યાંથી આગળ વધો',
  'profile.start': 'તમારી પ્રોફાઇલ શરૂ કરો',
  'profile.saved': 'સાચવ્યું',

  'match.title': 'તમારા માટે શિષ્યવૃત્તિઓ',
  'match.lede': 'તમારી પ્રોફાઇલ સામે ચકાસેલી. જેના માટે અરજી કરી શકો તે પહેલાં.',
  'match.eligible': 'તમે પાત્ર છો',
  'match.likely': 'તમે કદાચ પાત્ર છો',
  'match.blocked': 'પહેલાં એક કામ',
  'match.actionable': 'તમારા માટે ખુલ્લી',
  'match.actionableHelp': 'કેટલીક માટે અરજી પહેલાં એક દસ્તાવેજ જોઈએ.',
  'match.ineligible': 'તમારા માટે ખુલ્લી નથી',
  'match.eligibleHelp': 'અમે જે તપાસ્યું તે બધું ચકાસાયેલું છે.',
  'match.likelyHelp': 'તમે જે કહ્યું તેના આધારે. ચકાસણી કરાવવાથી તમારી અરજી મજબૂત બને છે.',
  'match.blockedHelp': 'તમે નજીક છો. આ કરી લો એટલે અરજી કરી શકશો.',
  'match.ineligibleHelp': 'આ યોજના એવું કંઈક માગે છે જે તમે બદલી શકતા નથી.',
  'match.apply': 'અરજી કરો',
  'match.applied': 'તમે અરજી કરી છે',
  'match.none': 'હજી કોઈ મેળ નથી',
  'match.noneHint': 'તમારી પ્રોફાઇલ પૂરી કરો અને અમે તમારા માટે દરેક શિષ્યવૃત્તિ તપાસીશું.',
  'match.figQualify': 'તમે પાત્ર છો',
  'match.figStep': 'એક પગલું દૂર',
  'match.figClosing': 'ટૂંક સમયમાં બંધ',
  'match.figNo': 'તમારા માટે ખુલ્લી નથી',
  'match.filterLabel': 'કઈ શિષ્યવૃત્તિઓ બતાવવી',
  'match.filterAll': 'બધી',
  'match.filterQualify': 'તમે પાત્ર છો',
  'match.filterStep': 'એક પગલું દૂર',
  'match.filterClosing': 'ટૂંક સમયમાં બંધ',
  'match.filterNo': 'તમારા માટે ખુલ્લી નથી',
  'match.filterEmpty': 'આ જૂથમાં કશું નથી. “બધી” અજમાવો.',
  'match.moreWithProfile': 'તમે જેમ જેમ ભરશો તેમ વધુ શિષ્યવૃત્તિઓ દેખાશે.',
  'match.youQualify': 'તમારી પ્રોફાઇલ પ્રમાણે તમે શરતો પૂરી કરો છો.',
  'match.yesTitle': 'તમે અરજી કરી શકો છો',
  'match.blockedTitle': 'પહેલાં એક કામ',
  'match.noTitle': 'પાત્ર નથી',
  'match.appliedTitle': 'પહેલેથી મોકલાયેલી',
  'match.seeDetails': 'નિયમો જુઓ',
  'match.learnMore': 'વધુ જાણો',
  'match.runBy': '{kind} દ્વારા સંચાલિત',
  'match.sortBy': 'ક્રમ',
  'match.sortRecommended': 'ભલામણ કરેલી',
  'match.sortClosing': 'સૌથી પહેલાં બંધ થતી',
  'match.sortAward': 'સૌથી મોટી રકમ',
  'match.applyAway': 'તેમની સાઇટ પર અરજી કરો',
  'match.applyHere': 'અહીં જ અરજી કરો',
  'match.notOpenToYou': 'હાલની સ્થિતિમાં તમારા માટે ખુલ્લી નથી.',
  'match.working': 'અત્યારે ખુલ્લી કોઈ યોજના તમે આપેલી વિગતો સાથે મેળ ખાતી નથી. પ્રોફાઇલમાં વધુ ઉમેરવાથી આ બદલાય છે.',

  'doc.title': 'તમારા દસ્તાવેજો',
  'doc.lede': 'એક દસ્તાવેજ એકવાર અપલોડ કરો. તમે જે પણ શિષ્યવૃત્તિ માટે અરજી કરો તે તેનો ઉપયોગ કરી શકે — તમને ફરી નહીં પુછાય.',
  'doc.upload': 'દસ્તાવેજ ઉમેરો',
  'doc.type': 'આ કયો દસ્તાવેજ છે?',
  'doc.file': 'ફાઇલ પસંદ કરો',
  'doc.fileHint': 'PDF કે સ્પષ્ટ ફોટો. 10 MB સુધી.',
  'doc.verified': 'ચકાસાયેલ',
  'doc.verifiedBy': '{org} દ્વારા ચકાસાયેલ',
  'doc.pending': 'ચકાસણીની રાહમાં',
  'doc.expired': 'ચકાસણીની મુદત પૂરી',
  'doc.expiring': '{n} દિવસમાં મુદત પૂરી',
  'doc.validUntil': '{date} સુધી માન્ય',
  'doc.none': 'તમે હજી કોઈ દસ્તાવેજ ઉમેર્યો નથી',
  'doc.uploading': 'અપલોડ થઈ રહ્યું છે…',
  'doc.remove': 'દૂર કરો',
  'doc.removing': 'દૂર કરી રહ્યા છીએ…',

  'apply.title': 'અરજી કરો',
  'apply.consent': 'મારી વિગતો આ પ્રદાતા સાથે વહેંચો',
  'apply.consentBody': 'નિર્ણય લેવા માટે આ શિષ્યવૃત્તિને જે જોઈએ તે જ તેઓ જોશે: {fields}. તમારા દસ્તાવેજો કોણે જોયા તે તમે ગમે ત્યારે જોઈ શકો છો.',
  'apply.consentBodyNoDocs': 'નિર્ણય લેવા માટે આ શિષ્યવૃત્તિને જે જોઈએ તે જ તેઓ જોશે, બીજું કશું નહીં. તમારી વિગતો કોણે જોઈ તે તમે ગમે ત્યારે જોઈ શકો છો.',
  'apply.submit': 'મારી અરજી મોકલો',
  'apply.submitting': 'મોકલાઈ રહ્યું છે…',
  'apply.blocked': 'તમે હજી અરજી કરી શકતા નથી',
  'apply.needProfile': 'પહેલાં તમારી પ્રોફાઇલ',
  'apply.needProfileHint': 'અરજી તમારી પ્રોફાઇલમાંથી મોકલાય છે, તેથી અરજી પહેલાં તે જોઈએ. તેમાં થોડી જ મિનિટ લાગે છે, અને તમે પહેલાં જે કહ્યું છે તે ભરેલું મળશે.',
  'apply.elsewhereTitle': 'આના માટે અરજી પ્રાયોજકની વેબસાઇટ પર થાય છે',
  'apply.elsewhereBody': 'તમે શોધી શકો એ માટે જ અમે આ શિષ્યવૃત્તિ યાદીમાં મૂકીએ છીએ, અને અરજીઓ પ્રાયોજક પોતે લે છે. તમે અમને જે કહ્યું છે તે સાચવેલું રહે છે, અને અમે જે શિષ્યવૃત્તિઓ ચલાવીએ છીએ તેના માટે પહેલેથી ભરેલું હોય છે.',
  'apply.elsewhereBodyPartner': 'આ શિષ્યવૃત્તિ અહીં જ ચાલે છે, પણ પ્રાયોજક અરજીઓ પોતાની વેબસાઇટ પર લે છે. તમે અમને જે કહ્યું છે તે સાચવેલું રહે છે, અને અમને સીધી મળતી અરજીઓ માટે પહેલેથી ભરેલું હોય છે.',
  'apply.bundleTitle': 'તમારા દસ્તાવેજો સાથે લઈ જાઓ',
  'apply.bundleBody': 'આ શિષ્યવૃત્તિ જે દસ્તાવેજો માગે છે તે અમે એક ફાઇલમાં મૂકી શકીએ, તેમની વેબસાઇટ પર અપલોડ કરવા તૈયાર. તેઓ જે માગે છે અને અમારી પાસે હજી નથી તે પણ તેમાં લખેલું હોય છે.',
  'apply.bundleAction': 'મારા દસ્તાવેજો ડાઉનલોડ કરો',
  'apply.bundleWorking': 'તૈયાર કરી રહ્યા છીએ…',
  'apply.bundleDone': 'તમારા દસ્તાવેજો ડાઉનલોડ થઈ ગયા છે.',
  'apply.docs': 'આ શિષ્યવૃત્તિ માટે જરૂરી દસ્તાવેજો',

  'appl.title': 'તમારી અરજીઓ',
  'appl.none': 'તમે હજી કશા માટે અરજી કરી નથી',
  'appl.noneHint': 'તમે જેના માટે પાત્ર હો તે શિષ્યવૃત્તિઓ શોધવા તમારા મેળ જુઓ.',
  'appl.reference': 'સંદર્ભ',
  'appl.whatNext': 'હવે શું થશે',
  'appl.history': 'ઇતિહાસ',
  'appl.needsYou': 'તેમને તમારી પાસેથી કંઈક જોઈએ છે',
  'track.label': 'આ અરજીની પ્રગતિ',
  'track.sent': 'મોકલાયેલી',
  'track.review': 'સમીક્ષા',
  'track.decision': 'નિર્ણય',
  'track.doneSr': 'પૂર્ણ',
  'track.currentSr': 'હમણાં ચાલુ છે',
  'track.todoSr': 'શરૂ થયું નથી',
  'appl.sentOn': '{when} મોકલાઈ',
  'appl.decidedOn': '{when} નિર્ણય થયો',
  'appl.outcomeApproved': 'મળી',
  'appl.outcomeRejected': 'આ વખતે નથી મળી',
  'appl.outcomeWithdrawn': 'તમે આ પાછી ખેંચી',
  'appl.inProgress': 'પ્રદાતા પાસે',
  'appl.outcome': 'પરિણામ',
  'appl.award': 'રકમ',
  'appl.applied': 'અરજી કરી',
  'appl.decided': 'નિર્ણય થયો',
  'appl.automatic': 'આપોઆપ',
  'appl.noHistory': 'હજી કશું થયું નથી.',

  'ref.heading': 'તેમની વેબસાઇટ પર મોકલાયેલી',
  'ref.blurb': 'આના માટે અરજી પ્રદાતાની પોતાની સાઇટ પર થાય છે, તેથી શું થયું તે અમે જોઈ શકતા નથી. અમને જણાવો અને અમે તેને બાકીની સાથે રાખીશું.',
  'ref.sentOn': 'તમે આ {when} ખોલી હતી',
  'ref.again': 'કુલ {times} વાર',
  'ref.open': 'તેમની સાઇટ ફરી ખોલો',
  'ref.what': 'શું થયું?',
  'ref.APPLIED': 'મેં અરજી કરી',
  'ref.AWARDED': 'મને મળી',
  'ref.NOT_AWARDED': 'મને નથી મળી',
  'ref.DID_NOT_APPLY': 'મેં અરજી નથી કરી',
  'ref.saidAPPLIED': 'તમે અરજી કરી',
  'ref.saidAWARDED': 'તમને મળી',
  'ref.saidNOT_AWARDED': 'તમને નથી મળી',
  'ref.saidDID_NOT_APPLY': 'તમે અરજી નથી કરી',
  'ref.youSaid': 'તમે અમને કહ્યું: {what}',
  'ref.change': 'બદલો',

  'privacy.title': 'તમારી માહિતી',
  'privacy.lede': 'અમારી પાસે શું છે, કોણે જોયું છે, અને તે પાછી કેવી રીતે લેવી.',
  'privacy.access': 'તમારા દસ્તાવેજો કોણે જોયા છે',
  'privacy.accessNone': 'તમારા પોતાના ખાતા બહાર કોઈએ તમારા દસ્તાવેજો ખોલ્યા નથી.',
  'privacy.consents': 'તમે શું વહેંચવા સંમતિ આપી છે',
  'privacy.withdraw': 'પાછી ખેંચો',
  'privacy.withdrawing': 'પાછી ખેંચાઈ રહી છે…',
  'privacy.export': 'અમારી પાસે જે છે તે બધું ડાઉનલોડ કરો',
  'privacy.exporting': 'તમારી નકલ તૈયાર કરી રહ્યા છીએ…',
  'privacy.exportBody': 'તમારી માહિતીની સંપૂર્ણ, યંત્ર-વાંચનીય નકલ.',
  'privacy.erase': 'મારી માહિતી કાઢી નાખો',
  'privacy.erasing': 'વિનંતી કરી રહ્યા છીએ…',
  'privacy.eraseBody': 'તમને ચૂકવાયેલી કોઈપણ શિષ્યવૃત્તિની નોંધ અમારે રાખવી પડે છે. બાકી બધું દૂર કરાય છે.',
  'auth.closedTitle': 'તમારું ખાતું અત્યારે બંધ છે.',
  'auth.closedHelp': 'મદદ જોઈએ છે? અમારી સહાય ટીમ તમને સમજવામાં મદદ કરી શકે ',
  'auth.closedSoon': 'સહાય માગો (ટૂંક સમયમાં)',
  'reg.district': 'જિલ્લો',
  'reg.districtHint': 'તમારા વિસ્તારમાં ચાલતી યોજનાઓ સાથે મેળ કરવામાં મદદ કરે છે.',
  'privacy.requested': 'વિનંતી કરેલી',
  'privacy.window': 'હજી કશું કાઢી નખાયું નથી',
  'privacy.windowBody': 'તમારી માહિતી {date} ના રોજ કાઢી નખાશે. ત્યાં સુધી તમે ',
  'privacy.cancel': 'આ વિનંતી રદ કરો',
  'privacy.cancelling': 'રદ કરી રહ્યા છીએ…',
  'privacy.cancelled': 'તમારી વિનંતી રદ કરાઈ છે. કશું કાઢી નખાયું નથી.',

  'common.loading': 'લોડ થઈ રહ્યું છે',
  'common.retry': 'ફરી પ્રયાસ કરો',
  'common.required': 'જરૂરી',
  'common.optional': 'વૈકલ્પિક',
  'common.error': 'કંઈક ખોટું થયું',
  'common.offline': 'તમે ઑફલાઇન છો. તમારું કામ આ ઉપકરણ પર સચવાયેલું છે.',

  'slides.lead.was': '',
  'slides.lead.able': 'ક્ષમતાથી',
  'slides.lead.dist': 'વિશિષ્ટતા સુધી',
  'slides.lead.body': 'તમે જેના માટે પાત્ર હો તે દરેક શિષ્યવૃત્તિ — સરકારી અને ખાનગી — તમારી પ્રોફાઇલ સાથે મેળવીને, તમારી ભાષામાં, એક જગ્યાએ.',
  'slides.lead.free': 'સંપૂર્ણ મફત',
  'slides.lead.languages': '14 ભાષાઓ',
  'slides.lead.support': 'દરેક પગલે વ્યક્તિગત સહાય',
  'slides.label': 'જાહેરાતો',
  'slides.position': '{total} માંથી {n}',
  'slides.goto': '{name} બતાવો',
  'slides.watch': 'વીડિયો જુઓ',
  'slides.external': 'બીજી વેબસાઇટ ખોલે છે',

  'home.title': 'દિવ્યાંગ વિદ્યાર્થીઓ માટે શિષ્યવૃત્તિઓ, એક જગ્યાએ',
  'home.lede': 'તમારા વિશે એકવાર જણાવો. અમે અહીંની દરેક શિષ્યવૃત્તિ સામે તમને તપાસીએ છીએ અને કહીએ છીએ કે તમે કઈ માટે પાત્ર છો — અને બાકીની માટે બરાબર શું ખૂટે છે.',
  'home.search': 'શિષ્યવૃત્તિઓ શોધો',
  'home.searchPlaceholder': 'જેમ કે: એન્જિનિયરિંગ, દિલ્હી, પોસ્ટ-મેટ્રિક',
  'home.searchGo': 'શોધો',
  'home.browseAll': 'બધી શિષ્યવૃત્તિઓ જુઓ',
  'home.openNow': 'શિષ્યવૃત્તિઓ અત્યારે ખુલ્લી છે',
  'home.noAccount': 'જોવા માટે ખાતું જરૂરી નથી.',
  'home.openNone': 'અહીં હજી કોઈ શિષ્યવૃત્તિ યાદીમાં નથી.',
  'home.openNoneBody': 'યાદી હમણાં ભરાઈ રહી છે. અહીં કશું ખાતાની પાછળ નથી — યોજનાઓ યાદીમાં આવશે ત્યારે સાઇન ઇન કર્યા વગર જ દેખાશે.',
  'home.how': 'આ કેવી રીતે કામ કરે છે',
  'home.howLede': 'નોંધણી માટે એક મોબાઇલ નંબર અને તેના પર મોકલેલો કોડ જોઈએ. કોઈ પાસવર્ડ નથી, અને પહેલાં ભરવાનું કોઈ સાઇન-અપ ફૉર્મ પણ નથી.',
  'home.step1': 'નોંધણી દબાવો',
  'home.step1Body': 'આ પાનાની ઉપર. પહેલાં આવી ચૂક્યા હો તો બાજુમાં લૉગિન વાપરો — બંનેમાં એ જ નંબર કામ કરે છે.',
  'home.step2': 'તમારો મોબાઇલ નંબર આપો',
  'home.step2Body': 'દસ આંકડા, +91 પહેલેથી ભરેલું. તે નંબર પર 6 આંકડાનો કોડ જાય છે.',
  'home.step3': 'કોડ આપો',
  'home.step3Body': 'છ આંકડા લખો અને તમે અંદર. સંદેશ ન આવે તો કોડ વૉટ્સઍપ પર માગો, અથવા અમને ફોન કરીને વાંચી સંભળાવવા કહો.',
  'home.step4': 'તમારી વિગતો ભરો',
  'home.step4Body': 'તમારું નામ, તમારું પ્રમાણપત્ર અને તમે ક્યાં ભણો છો — એક સમયે એક પ્રશ્ન, અને દરેક જવાબ આપતાં જ સચવાય છે.',
  'home.step5': 'તમારા દસ્તાવેજો અપલોડ કરો',
  'home.step5Body': 'દિવ્યાંગતા પ્રમાણપત્ર, UDID કાર્ડ, આવકનું પ્રમાણપત્ર અને બાકીના. દરેક એકવાર, દરેક શિષ્યવૃત્તિ માટે અલગથી નહીં.',
  'home.step6': 'તમારા મેળ જુઓ',
  'home.step6Body': 'મારા મેળ તે શિષ્યવૃત્તિઓ બતાવે છે જેના માટે તમે પાત્ર છો — અને કોઈ તમારા માટે બંધ હોય તો કારણ પણ કહે છે.',
  'home.step7': 'અરજી કરો',
  'home.step7Body': 'જે જોઈએ તે પસંદ કરો. તમારી વિગતો અને દસ્તાવેજો અરજી સાથે જાય છે.',
  'home.assure': 'જાણવા જેવું',
  'home.assure1': 'યાદ રાખવા કોઈ પાસવર્ડ નથી',
  'home.assure2': 'અલગ નોંધણી ફૉર્મ નથી',
  'home.assure3': 'અટકીને પછી પૂરું કરી શકો છો',
  'home.help': 'કોઈ પગલે અટકી ગયા?',
  'home.helpBody': 'ફોન કરો, કોઈ તમને પાર ઉતારશે.',
  'home.helpCall': '{number} પર ફોન કરો',
  'home.closing': 'ટૂંક સમયમાં બંધ',
  'home.closingLede': 'પહેલાં આના માટે અરજી કરો.',
  'home.closingNext': 'આગામી છેલ્લી તારીખો',
  'home.closingNextLede': 'સૌથી પહેલાં બંધ થતી ત્રણ.',
  'home.allDeadlines': 'બધી શિષ્યવૃત્તિઓ જુઓ',
  'home.browse': 'આ પ્રમાણે જુઓ',
  'home.browseWho': 'કોણ આપે છે',
  'home.browseLevel': 'તમારું અભ્યાસ સ્તર',
  'home.cta': 'તમારા મેળ જોવા તૈયાર છો?',
  'home.ctaBody': 'ખાતું બનાવવા એક મોબાઇલ નંબર કે ઈમેલ સરનામું જોઈએ. બીજું કશું નહીં.',
  'home.ctaButton': 'ખાતું બનાવો',
  'home.signedInCta': 'જુઓ તમે કઈ માટે પાત્ર છો',

  'reg.title': 'શિષ્યવૃત્તિઓ શોધવા નોંધણી કરો',
  'reg.editTitle': 'તમારી વિગતો અપડેટ કરો',
  'reg.requiredNote': '* નિશાનીવાળાં બધાં ખાનાં જરૂરી છે.',
  'reg.personal': 'વ્યક્તિગત વિગતો',
  'reg.disability': 'દિવ્યાંગતાની વિગતો',
  'reg.education': 'શિક્ષણની વિગતો',
  'reg.name': 'પૂરું નામ',
  'reg.namePlaceholder': 'તમારું પૂરું નામ લખો',
  'reg.phoneHint': 'અમે આ નંબર પર 6 આંકડાનો કોડ મોકલીએ છીએ. દર વખતે આ જ નંબર તમને સાઇન ઇન કરાવે છે.',
  'reg.sendOtp': 'OTP મોકલો',
  'reg.otpPlaceholder': '6 આંકડાનો OTP લખો',
  'reg.verified': 'ફોન નંબર ચકાસાયો',
  'reg.verifyFirst': 'નોંધણી પૂરી કરવા તમારો ફોન નંબર ચકાસો.',
  'reg.email': 'ઈમેલ',
  'reg.emailHint': 'જેથી અમે છેલ્લી તારીખ યાદ કરાવી શકીએ. અમે તે ક્યારેય વહેંચતા નથી.',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'લિંગ',
  'reg.genderHint': '(કેટલીક શિષ્યવૃત્તિઓ માત્ર મહિલા કે ટ્રાન્સજેન્ડર વિદ્યાર્થીઓ માટે છે)',
  'reg.udid': 'UDID નંબર',
  'reg.udidHint': 'તમારા UDID (વિશિષ્ટ દિવ્યાંગતા ઓળખ) કાર્ડ પરનો નંબર.',
  'reg.udidPlaceholder': 'તમારો UDID નંબર લખો',
  'reg.certificate': 'UDID પ્રમાણપત્ર અપલોડ કરો',
  'reg.certificateHint': 'PDF કે ચિત્ર, 5 MB કે તેથી ઓછું.',
  'reg.fileType': 'તે ફાઇલ PDF, JPEG કે PNG હોવી જોઈએ.',
  'reg.fileSize': 'તે ફાઇલ 5 MB થી મોટી છે. ફોનથી લીધેલો ફોટો સામાન્ય રીતે નાનો હોય છે જો તમે ફોટો પાડવાને બદલે સ્કૅન કરો.',
  'reg.fileLater': 'તમારી નોંધણી થઈ ગઈ છે અને વિગતો સચવાઈ છે. પ્રમાણપત્ર અપલોડ થયું નથી — મારા દસ્તાવેજોમાંથી ઉમેરી દો, બીજું કશું ફરી કરવાનું નથી.',
  'reg.disabilityType': 'દિવ્યાંગતાનો પ્રકાર',
  'reg.percent': 'દિવ્યાંગતાની ટકાવારી',
  'reg.percentHint': 'તમારા પ્રમાણપત્ર પરનો આંકડો. ઘણી શિષ્યવૃત્તિઓ માટે 40% કે વધુ જોઈએ.',
  'reg.percentPlaceholder': 'દા.ત. 40',
  'reg.percentRange': 'પ્રમાણપત્રની ટકાવારી 0 અને 100 વચ્ચેનો પૂર્ણાંક છે.',
  'reg.state': 'રાજ્ય',
  'reg.statePlaceholder': 'તમારું રાજ્ય શોધવા લખો…',
  'reg.program': 'તમારો અભ્યાસક્રમ પસંદ કરો',
  'reg.graduation': 'સ્નાતક',
  'reg.postgraduation': 'અનુસ્નાતક / માસ્ટર્સ',
  'reg.year': 'વર્ષ પસંદ કરો',
  'reg.yearAfterProgram': 'પહેલાં તમારો અભ્યાસક્રમ પસંદ કરો',
  'reg.institution': 'શાળા / કૉલેજનું નામ',
  'reg.institutionPlaceholder': 'તમારી સંસ્થાનું નામ લખો',
  'reg.required': 'આ જરૂરી છે.',
  'reg.fix': 'થોડા જવાબો પર ધ્યાન જોઈએ. પહેલો નીચે પસંદ કરેલો છે.',
  'reg.cta': 'નોંધણી કરો અને શિષ્યવૃત્તિઓ શોધો',
  'reg.saveChanges': 'ફેરફારો સાચવો',
  'reg.saving': 'સાચવી રહ્યા છીએ…',
  'reg.done': 'નોંધણી થઈ. તમારી શિષ્યવૃત્તિઓ શોધી રહ્યા છીએ.',
  'reg.doneTitle': 'તમારી નોંધણી થઈ ગઈ છે',
  'reg.already': 'પહેલેથી નોંધણી કરેલી છે?',
  'reg.login': 'OTP થી લૉગિન',
  'nav.registerCta': 'નોંધણી',
  'nav.loginCta': 'લૉગિન',
  'profile.edit': 'તમારી વિગતો અપડેટ કરો',
  'field.disability.BLINDNESS': 'અંધત્વ',
  'field.disability.LOW_VISION': 'ઓછી દૃષ્ટિ',
  'field.disability.LEPROSY_CURED': 'રક્તપિત્ત (મટી ગયેલ)',
  'field.disability.HEARING_IMPAIRMENT': 'શ્રવણ ક્ષતિ',
  'field.disability.LOCOMOTOR_DISABILITY': 'હલનચલનની દિવ્યાંગતા',
  'field.disability.DWARFISM': 'વામનતા',
  'field.disability.INTELLECTUAL_DISABILITY': 'બૌદ્ધિક દિવ્યાંગતા',
  'field.disability.MENTAL_ILLNESS': 'માનસિક બીમારી',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ઓટિઝમ સ્પેક્ટ્રમ ડિસઓર્ડર',
  'field.disability.CEREBRAL_PALSY': 'સેરેબ્રલ પાલ્સી',
  'field.disability.MUSCULAR_DYSTROPHY': 'સ્નાયુ ક્ષય',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'દીર્ઘકાલીન ચેતાતંત્રની સ્થિતિ',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'વિશિષ્ટ અધ્યયન દિવ્યાંગતા',
  'field.disability.MULTIPLE_SCLEROSIS': 'મલ્ટિપલ સ્ક્લેરોસિસ',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'વાણી અને ભાષાની દિવ્યાંગતા',
  'field.disability.THALASSEMIA': 'થેલેસેમિયા',
  'field.disability.HAEMOPHILIA': 'હીમોફીલિયા',
  'field.disability.SICKLE_CELL_DISEASE': 'સિકલ સેલ રોગ',
  'field.disability.MULTIPLE_DISABILITIES': 'બહુવિધ દિવ્યાંગતા, જેમાં દૃષ્ટિ-શ્રવણ ક્ષતિ પણ',
  'field.disability.ACID_ATTACK_VICTIM': 'એસિડ હુમલામાંથી બચેલ',
  'field.disability.PARKINSONS_DISEASE': 'પાર્કિન્સન્સ રોગ',

  'field.state.AN': 'આંદામાન અને નિકોબાર ટાપુઓ',
  'field.state.AP': 'આંધ્રપ્રદેશ',
  'field.state.AR': 'અરુણાચલ પ્રદેશ',
  'field.state.AS': 'આસામ',
  'field.state.BR': 'બિહાર',
  'field.state.CH': 'ચંડીગઢ',
  'field.state.CT': 'છત્તીસગઢ',
  'field.state.DL': 'દિલ્હી',
  'field.state.DN': 'દાદરા અને નગર હવેલી અને દમણ અને દીવ',
  'field.state.GA': 'ગોવા',
  'field.state.GJ': 'ગુજરાત',
  'field.state.HP': 'હિમાચલ પ્રદેશ',
  'field.state.HR': 'હરિયાણા',
  'field.state.JH': 'ઝારખંડ',
  'field.state.JK': 'જમ્મુ અને કાશ્મીર',
  'field.state.KA': 'કર્ણાટક',
  'field.state.KL': 'કેરળ',
  'field.state.LA': 'લદ્દાખ',
  'field.state.LD': 'લક્ષદ્વીપ',
  'field.state.MH': 'મહારાષ્ટ્ર',
  'field.state.ML': 'મેઘાલય',
  'field.state.MN': 'મણિપુર',
  'field.state.MP': 'મધ્યપ્રદેશ',
  'field.state.MZ': 'મિઝોરમ',
  'field.state.NL': 'નાગાલેન્ડ',
  'field.state.OR': 'ઓડિશા',
  'field.state.PB': 'પંજાબ',
  'field.state.PY': 'પુડુચેરી',
  'field.state.RJ': 'રાજસ્થાન',
  'field.state.SK': 'સિક્કિમ',
  'field.state.TG': 'તેલંગાણા',
  'field.state.TN': 'તમિલનાડુ',
  'field.state.TR': 'ત્રિપુરા',
  'field.state.UP': 'ઉત્તર પ્રદેશ',
  'field.state.UT': 'ઉત્તરાખંડ',
  'field.state.WB': 'પશ્ચિમ બંગાળ',

  'field.level.SCHOOL': 'શાળા',
  'field.level.SCHOOL.sub': 'ધોરણ 9, 10, 11, 12',
  'field.level.UNDERGRADUATE': 'સ્નાતક',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech અને એવા',
  'field.level.POSTGRADUATE': 'અનુસ્નાતક',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech અને એવા',
  'field.level.DOCTORAL': 'ડોક્ટરેટ',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'શાળા',
  'field.qual.SCHOOL.sub': 'ધોરણ 1 થી 12',
  'field.qual.UNDERGRADUATE': 'સ્નાતક',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — અને ડિપ્લોમા કે ITI',
  'field.qual.POSTGRADUATE': 'અનુસ્નાતક',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA અને એવા',
  'field.qual.DOCTORAL': 'PhD / ડોક્ટરેટ',

  'field.subject.engineering': 'ઇજનેરી',
  'field.subject.medical': 'તબીબી',
  'field.subject.management': 'વ્યવસ્થાપન',
  'field.subject.science': 'વિજ્ઞાન',
  'field.subject.commerce': 'વાણિજ્ય',
  'field.subject.arts': 'કલા અને માનવવિદ્યા',
  'field.subject.vocational': 'વ્યાવસાયિક',
  'field.subject.fellowship': 'ફેલોશિપ',
  'field.subject.talent': 'પ્રતિભા',
  'field.subject.sports': 'રમતગમત',

  'field.gender.FEMALE': 'સ્ત્રી',
  'field.gender.MALE': 'પુરુષ',
  'field.gender.TRANSGENDER': 'ટ્રાન્સજેન્ડર',
  'field.gender.UNDISCLOSED': 'કહેવા માગતા નથી',
  'field.genderFilter.TRANSGENDER': 'ત્રીજી જાતિ / ટ્રાન્સજેન્ડર',

  'field.year.below9': 'ધોરણ 9 થી નીચે',
  'field.year.c9': 'ધોરણ 9',
  'field.year.c10': 'ધોરણ 10',
  'field.year.c11': 'ધોરણ 11',
  'field.year.c12': 'ધોરણ 12',
  'field.year.y1': 'પ્રથમ વર્ષ',
  'field.year.y2': 'બીજું વર્ષ',
  'field.year.y3': 'ત્રીજું વર્ષ',
  'field.year.y4': 'ચોથું વર્ષ',
  'field.year.pg1': 'અનુસ્નાતક વર્ષ 1',
  'field.year.pg2': 'અનુસ્નાતક વર્ષ 2',

  'q.full_name': 'તમારું નામ શું છે?',
  'q.full_name.help': 'બરાબર જેમ તમારા દિવ્યાંગતા પ્રમાણપત્ર પર લખ્યું છે. પ્રદાતાઓ બંને મળે છે કે નહીં તે તપાસે છે.',
  'q.gender': 'તમારું લિંગ શું છે?',
  'q.gender.help': 'કેટલીક શિષ્યવૃત્તિઓ ફક્ત મહિલાઓ માટે છે, અથવા ટ્રાન્સજેન્ડર વિદ્યાર્થીઓ માટે. કહેવા ન માગતા હો તો છોડી દો.',
  'q.disability_type': 'તમારી દિવ્યાંગતા શું છે?',
  'q.disability_type.help': 'જેમ તમારા પ્રમાણપત્ર પર લખ્યું છે. મોટાભાગની શિષ્યવૃત્તિઓ આના આધારે જ ગાળે છે.',
  'q.disability_percent': 'તમારા પ્રમાણપત્ર પર કેટલા ટકા છે?',
  'q.disability_percent.help': '0 અને 100 વચ્ચેનો આંકડો. ઘણી શિષ્યવૃત્તિઓ માટે 40% કે વધુ જોઈએ.',
  'q.disability_percent.range': 'પ્રમાણપત્રની ટકાવારી 0 અને 100 વચ્ચે હોય છે.',
  'q.udid_number': 'તમારો UDID નંબર શું છે?',
  'q.udid_number.help': 'તમારા UDID (વિશિષ્ટ દિવ્યાંગતા ઓળખ) કાર્ડ પરનો નંબર. હજી મળ્યો ન હોય તો છોડી દો — તમે શેના માટે પાત્ર છો તેમાં આનાથી કોઈ ફરક પડતો નથી, અને પછીથી ઉમેરી શકો છો.',
  'q.date_of_birth': 'તમારો જન્મ ક્યારે થયો?',
  'q.date_of_birth.help': 'કેટલીક શિષ્યવૃત્તિઓમાં ઉંમરની મર્યાદા હોય છે.',
  'q.course_name': 'તમે શું ભણો છો?',
  'q.course_name.help': 'નોંધણી વખતે તમે પસંદ કરેલો અભ્યાસક્રમ.',
  'q.institution_name': 'તમે ક્યાં ભણો છો?',
  'q.institution_name.help': 'તમારી શાળા, કૉલેજ કે યુનિવર્સિટીનું નામ, જેમ તમારા બોનાફાઇડ પ્રમાણપત્ર પર લખ્યું છે. હજી શરૂ ન કર્યું હોય તો છોડી દો.',
  'q.institution_name.placeholder': 'તમારી શાળા કે કૉલેજનું નામ',
  'q.state_code': 'તમે કયા રાજ્યમાં રહો છો?',
  'q.state_code.help': 'ઘણી શિષ્યવૃત્તિઓ ફક્ત અમુક રાજ્યોના રહેવાસીઓ માટે ખુલ્લી છે.',
  'q.annual_family_income': 'તમારા પરિવારની વાર્ષિક આવક કેટલી છે?',
  'q.annual_family_income.help': 'રૂપિયામાં, જેમ તમારા આવકના પ્રમાણપત્ર પર છે. મોટાભાગની શિષ્યવૃત્તિઓમાં એક મર્યાદા હોય છે.',
  'q.annual_family_income.range': 'આવક શૂન્યથી ઓછી ન હોઈ શકે.',
  'q.academic_percentage': 'તમારી છેલ્લી પરીક્ષાના ગુણ કેટલા હતા?',
  'q.academic_percentage.help': 'તમારી માર્કશીટ જે રીતે તે જણાવે છે તે પસંદ કરો, પછી આંકડો લખો. ઘણી શિષ્યવૃત્તિઓ ન્યૂનતમ ગુણ માગે છે.',
  'field.orgKind.NGO': 'એનજીઓ',
  'field.orgKind.CORPORATE': 'કોર્પોરેટ',
  'field.orgKind.GOVERNMENT': 'સરકારી',
  'field.orgKind.PRIVATE': 'ખાનગી',

  'field.doc.DISABILITY_CERTIFICATE': 'દિવ્યાંગતા પ્રમાણપત્ર',
  'field.doc.UDID_CARD': 'UDID કાર્ડ',
  'field.doc.INCOME_CERTIFICATE': 'આવકનું પ્રમાણપત્ર',
  'field.doc.DOMICILE_CERTIFICATE': 'રહેઠાણનું પ્રમાણપત્ર',
  'field.doc.CASTE_CERTIFICATE': 'જાતિનું પ્રમાણપત્ર',
  'field.doc.MARKSHEET': 'માર્કશીટ',
  'field.doc.ADMISSION_LETTER': 'પ્રવેશ પત્ર',
  'field.doc.BONAFIDE_CERTIFICATE': 'બોનાફાઇડ પ્રમાણપત્ર',
  'field.doc.FEE_RECEIPT': 'ફીની પહોંચ',
  'field.doc.BANK_PASSBOOK': 'બેંક પાસબુક',
  'field.doc.IDENTITY_PROOF': 'ઓળખનો પુરાવો',
  'field.doc.PHOTOGRAPH': 'ફોટો',

  'appl.next.SUBMITTED': 'પ્રદાતા પાસે તમારી અરજી છે. હવે પછી એક સમીક્ષક તે વાંચશે.',
  'appl.next.UNDER_REVIEW': 'એક સમીક્ષક તમારી અરજી વાંચી રહ્યા છે. સામાન્ય રીતે આ જ સૌથી લાંબું પગલું હોય છે.',
  'appl.next.INFO_REQUESTED': 'તેમણે તમારી પાસે કંઈક માગ્યું છે. તમે જવાબ ન આપો ત્યાં સુધી અરજી રાહ જુએ છે.',
  'appl.next.DOCUMENT_CHECK': 'તમારી અરજી સમીક્ષક પાસે છે. તમારી પાસેથી કશું જોઈતું નથી.',
  'appl.next.VERIFIED': 'તમારી અરજી સમીક્ષક પાસે છે. તમારી પાસેથી કશું જોઈતું નથી.',
  'appl.next.SHORTLISTED': 'તમારી અરજી સમીક્ષક પાસે છે. હવે પછી નિર્ણય આવશે.',
  'appl.next.APPROVED': 'મંજૂર. પ્રદાતા મંજૂરી નોંધશે, પછી ચુકવણીની વ્યવસ્થા કરશે.',
  'appl.next.SANCTIONED': 'રકમ મંજૂર થઈ ગઈ છે. ચુકવણી તેમની બેંક મારફતે થાય છે.',
  'appl.next.DISBURSED': 'ચુકવણી નોંધાઈ ગઈ છે. થોડા કામકાજના દિવસોમાં તમારા ખાતામાં ન પહોંચે તો ફરિયાદ કરો.',
  'appl.next.REJECTED': 'આ અરજી સફળ રહી નથી. તેની તમારી બીજી અરજીઓ પર કોઈ અસર થતી નથી.',
  'appl.next.CLOSED': 'આ અરજી પૂર્ણ થઈ છે.',
  'appl.next.WITHDRAWN': 'તમે આ અરજી પાછી ખેંચી હતી.',
}

export default gu
