/* Hindi.
 *
 * Terms are held to one word each throughout, because a student comparing two
 * screens should not have to work out whether छात्रवृत्ति and स्कॉलरशिप are the
 * same thing: scholarship छात्रवृत्ति, application आवेदन, document दस्तावेज़,
 * disability दिव्यांगता (the RPwD Act's word, not विकलांगता), verified सत्यापित,
 * eligible पात्र.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const hi: Dict = {
  'app.name': 'छात्रवृत्ति पोर्टल',
  'app.tagline': 'दिव्यांग विद्यार्थियों के लिए',
  'app.yourApplication': 'आपका आवेदन · {title}',

  'nav.find': 'छात्रवृत्तियाँ',
  'nav.how': 'यह कैसे काम करता है',
  'nav.matches': 'मेरे मिलान',
  'nav.applications': 'मेरे आवेदन',
  'nav.documents': 'मेरे दस्तावेज़',
  'nav.profile': 'मेरी प्रोफ़ाइल',
  'nav.privacy': 'मेरा डेटा',
  'nav.account': 'मेरा खाता',
  'nav.register': 'साइन अप',
  'nav.language': 'भाषा',
  'footer.social': 'इंडिक एआई अन्यत्र',
  'footer.sponsor': 'सहयोग से',
  'footer.copyright': 'कॉपीराइट © {year} इंडिक एआई | सर्वाधिकार सुरक्षित',
  'nav.signin': 'साइन इन',
  'nav.signout': 'साइन आउट',
  'nav.skip': 'मुख्य सामग्री पर जाएँ',

  'public.title': 'ऐसी छात्रवृत्ति खोजें जिसके आप पात्र हैं',
  'public.lede': 'यहाँ दी गई हर छात्रवृत्ति दिव्यांग विद्यार्थियों के लिए खुली है। देखने के लिए खाता बनाने की ज़रूरत नहीं है।',
  'public.search': 'नाम या कीवर्ड से खोजें',
  'public.filter.disability': 'दिव्यांगता का प्रकार',
  'public.filter.qualification': 'योग्यता',
  'public.filter.state': 'आपका राज्य',
  'public.filter.provider': 'कौन दे रहा है',
  'public.filter.any': 'कोई भी',
  'public.filter.anyDisability': 'कोई भी दिव्यांगता',
  'public.filter.anyQualification': 'कोई भी योग्यता',
  'public.filter.allStates': 'सभी राज्य',
  'public.filter.gender': 'लिंग',
  'public.filter.anyGender': 'कोई भी लिंग',
  'public.filter.course': 'पाठ्यक्रम',
  'public.filter.anyCourse': 'कोई भी पाठ्यक्रम',
  'public.filter.where': 'आप कहाँ पढ़ते हैं',
  'public.filter.anyWhere': 'भारत या विदेश',
  'public.filter.inIndia': 'भारत में',
  'public.filter.abroad': 'विदेश में अध्ययन',
  'public.filters': 'फ़िल्टर',
  'public.clear': 'हटाएँ',
  'public.results': 'छात्रवृत्तियाँ अभी खुली हैं',
  'public.searching': 'खोज रहे हैं…',
  'public.none': 'इन फ़िल्टरों से कोई छात्रवृत्ति मेल नहीं खाती',
  'public.none.hint': 'कोई एक फ़िल्टर हटाकर देखें। साल भर नई योजनाएँ खुलती रहती हैं।',
  'public.none.clear': 'सभी फ़िल्टर हटाएँ',
  'public.empty': 'यहाँ अभी कोई छात्रवृत्ति सूचीबद्ध नहीं है',
  'public.empty.hint': 'संस्थाएँ अभी जोड़ी जा रही हैं। यहाँ कुछ भी खाते के पीछे नहीं है — जब योजनाएँ सूचीबद्ध होंगी, आप उन्हें बिना साइन इन किए देख सकेंगे।',
  'public.whoFor': 'यह किसके लिए है',
  'public.about': 'इस छात्रवृत्ति के बारे में',
  'public.atAGlance': 'एक नज़र में',
  'public.closes': 'बंद होती है',
  'public.awardUnstated': 'राशि नहीं बताई गई',
  'public.noClose': 'कोई अंतिम तिथि नहीं',
  'public.closesIn': '{n} दिनों में बंद',
  'public.closesToday': 'आज बंद हो रही है',
  'public.closed': 'बंद',
  'public.award': 'राशि',
  'public.renewable': 'हर साल नवीनीकृत की जा सकती है',
  'public.offeredBy': 'देने वाली संस्था',
  'public.eligibility': 'पात्रता के लिए',
  'public.benefits': 'लाभ',
  'public.readMore': 'और पढ़ें',
  'public.viewDetails': 'विवरण देखें',
  'public.applyNow': 'अभी आवेदन करें',
  'public.registerToApply': 'आवेदन करें',
  'public.registerToApplyHelp': 'आवेदन आपके खाते से किए जाते हैं। पंजीकरण करने पर आपको हर वह छात्रवृत्ति भी दिखेगी जिसके आप पात्र हैं।',
  'public.closedNote': 'यह योजना बंद हो चुकी है',
  'share.title': 'किसी को इसके बारे में बताएँ',
  'share.native': 'शेयर करें',
  'share.whatsapp': 'व्हाट्सऐप',
  'share.email': 'ईमेल',
  'share.copy': 'लिंक कॉपी करें',
  'share.copied': 'लिंक कॉपी हो गया',
  'share.qr': 'क्यूआर कोड',
  'share.qrAlt': '{title} का क्यूआर कोड। इसे स्कैन करने पर यह छात्रवृत्ति खुलती है।',
  'share.qrHint': 'इस छात्रवृत्ति को खोलने के लिए फ़ोन के कैमरे से स्कैन करें।',
  'sheet.close': 'बंद करें',
  'sheet.loading': 'छात्रवृत्ति का विवरण',
  'public.benefitComponent': 'मद',
  'public.benefitAmount': 'विद्यार्थी को क्या मिलता है',
  'public.whatYouGet': 'आपको क्या मिलेगा',
  'public.eligibilityDetail': 'पात्रता विस्तार से',
  'public.documentsRequired': 'आवश्यक दस्तावेज़',
  'public.documentsHelp': 'संस्था ये दस्तावेज़ माँगती है। इन्हें आप यहाँ अपलोड नहीं करते।',
  'public.howToApply': 'आवेदन कैसे करें',
  'public.importantNotes': 'जानने योग्य बातें',
  'public.academicYear': 'किस वर्ष के लिए',
  'public.awardBasis': 'किस आधार पर',
  'public.basis.MERIT': 'मेधा',
  'public.basis.NEED': 'आर्थिक आवश्यकता',
  'public.basis.MERIT_CUM_MEANS': 'मेधा सह आय',
  'public.basis.CATEGORY': 'श्रेणी',
  'public.basis.OTHER': 'अन्य',
  'public.cta': 'अपने लिए छात्रवृत्तियाँ खोजें',
  'public.applyExternal': 'उनकी साइट पर आवेदन करें',
  'public.applyExternalHelp': 'हम यह छात्रवृत्ति इसलिए सूचीबद्ध करते हैं ताकि आप इसे खोज सकें। इसे {org} चलाती है और आवेदन अपनी वेबसाइट पर लेती है, इसलिए यह यहाँ आपके आवेदनों में नहीं दिखेगी।',
  'public.applyExternalHelpPartner': '{org} इस आवेदन को अपनी वेबसाइट पर लेती है, इसलिए यह यहाँ आपके आवेदनों में नहीं दिखेगा।',
  'common.newTab': 'नए टैब में खुलता है',
  'public.applyHelp': 'हम पहले आपकी प्रोफ़ाइल और दस्तावेज़ों को इस छात्रवृत्ति के विरुद्ध जाँचते हैं और बताते हैं कि कुछ छूट तो नहीं रहा। आपकी पुष्टि से पहले कुछ नहीं भेजा जाता।',
  'public.ctaHelp': 'अपने बारे में एक बार बताइए और हम आपको हर वह छात्रवृत्ति दिखाएँगे जिसके आप पात्र हैं।',
  'public.back': 'सभी छात्रवृत्तियों पर वापस',
  'notFound.title': 'हमें यह पेज नहीं मिला',
  'notFound.body': 'हो सकता है पते में टाइपिंग की गलती हो, या पेज कहीं और चला गया हो।',
  'notFound.home': 'होम पेज पर जाएँ',

  'nav.dashboard': 'डैशबोर्ड',
  'dash.title': 'आपका डैशबोर्ड',
  'dash.lede': 'आपकी छात्रवृत्तियाँ, आवेदन और दस्तावेज़, सब एक जगह।',
  'dash.matches': 'जिन छात्रवृत्तियों के लिए आप आवेदन कर सकते हैं',
  'dash.matchesHint': 'आपके दिए विवरण के आधार पर।',
  'dash.matchesBlocked': '{n} आपसे एक और जानकारी की प्रतीक्षा में।',
  'dash.applications': 'चल रहे आवेदन',
  'dash.applicationsHint': '{approved} स्वीकृत · {rejected} असफल',
  'dash.applicationsNone': 'अभी कुछ नहीं भेजा गया।',
  'dash.documents': 'सत्यापित दस्तावेज़',
  'dash.documentsHint': 'एक बार जाँचे गए। हर आवेदन में काम आते हैं।',
  'dash.funding': 'अब तक प्राप्त',
  'dash.fundingHint': 'कुल {sanctioned} स्वीकृत।',
  'dash.recent': 'हाल के आवेदन',
  'dash.noApplications': 'अभी कोई आवेदन नहीं',
  'dash.noApplicationsHint': 'आप जिसके लिए भी आवेदन करेंगे वह यहाँ दिखेगा।',
  'dash.findScholarships': 'छात्रवृत्तियाँ खोजें',
  'dash.profileTitle': 'आपकी प्रोफ़ाइल',
  'dash.toGo': '{n}% बाकी',
  'dash.allApplications': 'सभी देखें',
  'dash.matchesGo': 'अपने मिलान देखें',
  'dash.applicationsGo': 'अपने आवेदन देखें',
  'dash.documentsGo': 'दस्तावेज़ प्रबंधित करें',
  'dash.draftsTitle': '{n} आवेदन नहीं भेजा गया | {n} आवेदन नहीं भेजे गए',
  'dash.draftsBody': 'आवेदन शुरू करने से वह भेजा नहीं जाता। छात्रवृत्ति बंद होने से पहले पूरा कीजिए।',
  'dash.draftsAction': 'अभी पूरा करें',
  'dash.expiringTitle': '{n} दस्तावेज़ जल्द समाप्त हो रहा है | {n} दस्तावेज़ जल्द समाप्त हो रहे हैं',
  'dash.expiringBody': 'इसे अभी बदल दीजिए ताकि यह हर आवेदन में काम आए। | इन्हें अभी बदल दीजिए ताकि ये हर आवेदन में काम आएँ।',
  'dash.expiringAction': 'दस्तावेज़ जाँचें',

  'auth.title': 'अपना मोबाइल नंबर भरिए',
  'auth.phone': 'मोबाइल नंबर',
  'auth.phoneHint': 'हम इस नंबर पर एसएमएस से 6 अंकों का कोड भेजेंगे। हर बार यही नंबर आपको साइन इन कराता है।',
  'auth.phoneMissing': 'आगे बढ़ने के लिए अपना मोबाइल नंबर भरिए।',
  'auth.phoneInvalid': 'यह ठीक नहीं लग रहा। भारतीय मोबाइल नंबर 10 अंकों के होते हैं और 6, 7, 8 या 9 से शुरू होते हैं।',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'नए हों या लौट रहे हों, वही नंबर काम करता है। यदि आपका खाता नहीं है तो हम बना देंगे।',
  'auth.stepOf': 'चरण {n} / 2 · {name}',
  'auth.stepPhone': 'आपका नंबर',
  'auth.stepCode': 'आपका OTP कोड',
  'auth.privacy': 'आपका नंबर केवल आपको साइन इन कराने के लिए इस्तेमाल होता है, और किसी काम के लिए नहीं। याद रखने के लिए कोई पासवर्ड नहीं है।',
  'auth.sendCode': 'कोड भेजें',
  'auth.sending': 'भेजा जा रहा है…',
  'auth.checking': 'जाँचा जा रहा है…',
  'auth.welcomeBack': 'वापस स्वागत है। साइन इन करने के लिए कोड भरिए।',
  'auth.newHere': 'कोड भरते ही हम आपका खाता बना देंगे।',
  'auth.codeTitle': 'हमने जो कोड भेजा है वह भरिए',
  'auth.code': '6 अंकों का कोड',
  'auth.codeHint': 'संदेश आम तौर पर कुछ ही सेकंड में आ जाता है।',
  'auth.noCode': 'अभी तक संदेश नहीं आया? कोई और तरीका आज़माएँ:',
  'auth.verify': 'सत्यापित करें',
  'auth.viaSms': 'एसएमएस से भेजें',
  'auth.viaWhatsapp': 'व्हाट्सऐप पर भेजें',
  'auth.viaVoice': 'कोड बताने के लिए मुझे कॉल करें',
  'auth.resentVia.sms': 'एसएमएस से भेज दिया। आने में थोड़ा समय लग सकता है।',
  'auth.resentVia.whatsapp': 'व्हाट्सऐप पर भेज दिया। संदेश के लिए व्हाट्सऐप देखिए।',
  'auth.resentVia.voice': 'कोड बताने के लिए अभी कॉल कर रहे हैं। सुनने के लिए कॉल उठाइए।',
  'auth.resendIn': '{n} सेकंड में फिर भेजें',
  'auth.changeNumber': 'दूसरा नंबर इस्तेमाल करें',
  'auth.change': 'बदलें',

  'profile.complete': '{n}% पूरी',
  'profile.viewLede': 'आपने हमें जो कुछ बताया है। कोई भी उत्तर बदलिए और वह उसके बाद हर छात्रवृत्ति के लिए इस्तेमाल होगा।',
  'profile.notAnswered': 'अभी उत्तर नहीं दिया',
  'profile.verified': 'सत्यापित',
  'profile.refused': 'सुधार आवश्यक',
  'profile.refusedTitle': 'कृपया {n} उत्तर सुधारें | कृपया {n} उत्तर सुधारें',
  'profile.refusedLede': 'हमने इन्हें आपके दस्तावेज़ों से मिलाया और इनकी पुष्टि नहीं कर सके। इन्हें सुधारें, फिर इनकी दोबारा जाँच होगी।',
  'profile.refusedFix': 'मेरे उत्तर सुधारें',
  'profile.continue': 'जहाँ छोड़ा था वहीं से जारी रखें',
  'profile.start': 'अपनी प्रोफ़ाइल शुरू करें',
  'profile.saved': 'सहेज लिया',

  'match.title': 'आपके लिए छात्रवृत्तियाँ',
  'match.lede': 'आपकी प्रोफ़ाइल से जाँची गईं। जिनके लिए आप आवेदन कर सकते हैं वे पहले हैं।',
  'match.eligible': 'आप पात्र हैं',
  'match.likely': 'आप शायद पात्र हैं',
  'match.blocked': 'पहले एक काम',
  'match.actionable': 'आपके लिए खुली',
  'match.actionableHelp': 'कुछ के लिए आवेदन से पहले एक दस्तावेज़ की ज़रूरत हो सकती है।',
  'match.ineligible': 'आपके लिए खुली नहीं',
  'match.eligibleHelp': 'हमने जो कुछ जाँचा वह सत्यापित है।',
  'match.likelyHelp': 'आपने जो बताया उसके आधार पर। सत्यापन करा लेने से आपका आवेदन मज़बूत होता है।',
  'match.blockedHelp': 'आप करीब हैं। यह कर लीजिए और आवेदन कर सकते हैं।',
  'match.ineligibleHelp': 'यह योजना ऐसी चीज़ माँगती है जिसे आप बदल नहीं सकते।',
  'match.apply': 'आवेदन करें',
  'match.applied': 'आपने आवेदन कर दिया है',
  'match.none': 'अभी कोई मिलान नहीं',
  'match.noneHint': 'अपनी प्रोफ़ाइल पूरी कीजिए और हम आपके लिए हर छात्रवृत्ति जाँचेंगे।',
  'match.figQualify': 'आप पात्र हैं',
  'match.figStep': 'एक कदम दूर',
  'match.figClosing': 'जल्द बंद',
  'match.figNo': 'आपके लिए खुली नहीं',
  'match.filterLabel': 'कौन सी छात्रवृत्तियाँ दिखाएँ',
  'match.filterAll': 'सभी',
  'match.filterQualify': 'आप पात्र हैं',
  'match.filterStep': 'एक कदम दूर',
  'match.filterClosing': 'जल्द बंद',
  'match.filterNo': 'आपके लिए खुली नहीं',
  'match.filterEmpty': 'इस समूह में कुछ नहीं। “सभी” आज़माएँ।',
  'match.moreWithProfile': 'जैसे-जैसे आप इसे भरेंगे और छात्रवृत्तियाँ दिखेंगी।',
  'match.youQualify': 'आपकी प्रोफ़ाइल के अनुसार आप शर्तें पूरी करते हैं।',
  'match.yesTitle': 'आप आवेदन कर सकते हैं',
  'match.blockedTitle': 'पहले एक काम',
  'match.noTitle': 'पात्र नहीं',
  'match.appliedTitle': 'भेजा जा चुका',
  'match.seeDetails': 'नियम देखें',
  'match.learnMore': 'और जानें',
  'match.runBy': '{kind} द्वारा संचालित',
  'match.sortBy': 'क्रम',
  'match.sortRecommended': 'सुझाए गए',
  'match.sortClosing': 'सबसे पहले बंद होने वाली',
  'match.sortAward': 'सबसे बड़ी राशि',
  'match.applyAway': 'उनकी साइट पर आवेदन करें',
  'match.applyHere': 'यहीं आवेदन करें',
  'match.notOpenToYou': 'अभी की स्थिति में आपके लिए खुली नहीं।',
  'match.working': 'अभी खुली कोई भी योजना आपके दिए विवरण से मेल नहीं खाती। प्रोफ़ाइल में और जोड़ने से यह बदलता है।',

  'doc.title': 'आपके दस्तावेज़',
  'doc.lede': 'दस्तावेज़ एक बार अपलोड कीजिए। आप जिस भी छात्रवृत्ति के लिए आवेदन करें वह इसका उपयोग कर सकती है — आपसे दोबारा नहीं माँगा जाएगा।',
  'doc.upload': 'दस्तावेज़ जोड़ें',
  'doc.type': 'यह कौन सा दस्तावेज़ है?',
  'doc.file': 'फ़ाइल चुनें',
  'doc.fileHint': 'पीडीएफ़ या साफ़ फ़ोटो। 10 एमबी तक।',
  'doc.verified': 'सत्यापित',
  'doc.verifiedBy': '{org} द्वारा सत्यापित',
  'doc.pending': 'सत्यापन की प्रतीक्षा में',
  'doc.expired': 'सत्यापन समाप्त',
  'doc.expiring': '{n} दिन में समाप्त',
  'doc.validUntil': '{date} तक मान्य',
  'doc.none': 'आपने अभी कोई दस्तावेज़ नहीं जोड़ा है',
  'doc.uploading': 'अपलोड हो रहा है…',
  'doc.remove': 'हटाएँ',
  'doc.removing': 'हटाया जा रहा है…',

  'apply.title': 'आवेदन करें',
  'apply.consent': 'मेरा विवरण इस संस्था के साथ साझा करें',
  'apply.consentBody': 'वे केवल वही देखेंगे जो इस छात्रवृत्ति को निर्णय लेने के लिए चाहिए: {fields}. आपके दस्तावेज़ किसने देखे, यह आप कभी भी देख सकते हैं।',
  'apply.consentBodyNoDocs': 'वे केवल वही देखेंगे जो इस छात्रवृत्ति को निर्णय लेने के लिए चाहिए, और कुछ नहीं। आपका विवरण किसने देखा, यह आप कभी भी देख सकते हैं।',
  'apply.submit': 'मेरा आवेदन भेजें',
  'apply.submitting': 'भेजा जा रहा है…',
  'apply.blocked': 'आप अभी आवेदन नहीं कर सकते',
  'apply.needProfile': 'पहले आपकी प्रोफ़ाइल',
  'apply.needProfileHint': 'आवेदन आपकी प्रोफ़ाइल से भेजा जाता है, इसलिए आवेदन से पहले वह चाहिए। इसमें कुछ ही मिनट लगते हैं, और आपने जो पहले बताया है वह भरा हुआ मिलेगा।',
  'apply.elsewhereTitle': 'इसके लिए आवेदन प्रायोजक की वेबसाइट पर होता है',
  'apply.elsewhereBody': 'हम यह छात्रवृत्ति इसलिए सूचीबद्ध करते हैं ताकि आप इसे खोज सकें, और आवेदन प्रायोजक स्वयं लेते हैं। आपने हमें जो बताया है वह सहेजा रहता है, और जो छात्रवृत्तियाँ हम चलाते हैं उनके लिए पहले से भरा रहता है।',
  'apply.elsewhereBodyPartner': 'यह छात्रवृत्ति यहीं चलती है, पर प्रायोजक आवेदन अपनी वेबसाइट पर लेते हैं। आपने हमें जो बताया है वह सहेजा रहता है, और जो आवेदन हमें सीधे मिलते हैं उनके लिए पहले से भरा रहता है।',
  'apply.bundleTitle': 'अपने दस्तावेज़ साथ ले जाइए',
  'apply.bundleBody': 'यह छात्रवृत्ति जो दस्तावेज़ माँगती है उन्हें हम एक फ़ाइल में रख सकते हैं, उनकी वेबसाइट पर अपलोड करने के लिए तैयार। इसमें वह भी लिखा होता है जो वे चाहते हैं और हमारे पास अभी नहीं है।',
  'apply.bundleAction': 'मेरे दस्तावेज़ डाउनलोड करें',
  'apply.bundleWorking': 'तैयार किया जा रहा है…',
  'apply.bundleDone': 'आपके दस्तावेज़ डाउनलोड हो गए हैं।',
  'apply.docs': 'इस छात्रवृत्ति के लिए आवश्यक दस्तावेज़',

  'appl.title': 'आपके आवेदन',
  'appl.none': 'आपने अभी किसी के लिए आवेदन नहीं किया है',
  'appl.noneHint': 'जिन छात्रवृत्तियों के आप पात्र हैं उन्हें खोजने के लिए अपने मिलान देखिए।',
  'appl.reference': 'संदर्भ',
  'appl.whatNext': 'आगे क्या होगा',
  'appl.history': 'इतिहास',
  'appl.needsYou': 'उन्हें आपसे कुछ चाहिए',
  'track.label': 'इस आवेदन की प्रगति',
  'track.sent': 'भेजा गया',
  'track.review': 'समीक्षा',
  'track.decision': 'निर्णय',
  'track.doneSr': 'पूरा',
  'track.currentSr': 'अभी चल रहा है',
  'track.todoSr': 'शुरू नहीं हुआ',
  'appl.sentOn': '{when} को भेजा गया',
  'appl.decidedOn': '{when} को निर्णय हुआ',
  'appl.outcomeApproved': 'मिल गई',
  'appl.outcomeRejected': 'इस बार नहीं मिली',
  'appl.outcomeWithdrawn': 'आपने इसे वापस ले लिया',
  'appl.inProgress': 'संस्था के पास',
  'appl.outcome': 'परिणाम',
  'appl.award': 'राशि',
  'appl.applied': 'आवेदन किया',
  'appl.decided': 'निर्णय हुआ',
  'appl.automatic': 'स्वचालित',
  'appl.noHistory': 'अभी कुछ नहीं हुआ है।',

  'ref.heading': 'उनकी वेबसाइट पर भेजा गया',
  'ref.blurb': 'इनके लिए आवेदन संस्था की अपनी साइट पर होता है, इसलिए हम नहीं देख सकते कि क्या हुआ। हमें बताइए और हम इसे बाकी के साथ रख लेंगे।',
  'ref.sentOn': 'आपने इसे {when} को खोला था',
  'ref.again': 'कुल {times} बार',
  'ref.open': 'उनकी साइट फिर खोलें',
  'ref.what': 'क्या हुआ?',
  'ref.APPLIED': 'मैंने आवेदन किया',
  'ref.AWARDED': 'मुझे यह मिली',
  'ref.NOT_AWARDED': 'मुझे यह नहीं मिली',
  'ref.DID_NOT_APPLY': 'मैंने आवेदन नहीं किया',
  'ref.saidAPPLIED': 'आपने आवेदन किया',
  'ref.saidAWARDED': 'आपको यह मिली',
  'ref.saidNOT_AWARDED': 'आपको यह नहीं मिली',
  'ref.saidDID_NOT_APPLY': 'आपने आवेदन नहीं किया',
  'ref.youSaid': 'आपने हमें बताया: {what}',
  'ref.change': 'बदलें',

  'privacy.title': 'आपका डेटा',
  'privacy.lede': 'हमारे पास क्या है, किसने देखा है, और इसे वापस कैसे लें।',
  'privacy.access': 'आपके दस्तावेज़ किसने देखे हैं',
  'privacy.accessNone': 'आपके अपने खाते के बाहर किसी ने आपके दस्तावेज़ नहीं खोले हैं।',
  'privacy.consents': 'आपने क्या साझा करने की सहमति दी है',
  'privacy.withdraw': 'वापस लें',
  'privacy.withdrawing': 'वापस लिया जा रहा है…',
  'privacy.export': 'हमारे पास जो कुछ है वह डाउनलोड करें',
  'privacy.exporting': 'आपकी प्रति तैयार की जा रही है…',
  'privacy.exportBody': 'आपके डेटा की पूरी मशीन-पठनीय प्रति।',
  'privacy.erase': 'मेरा डेटा मिटाएँ',
  'privacy.erasing': 'अनुरोध किया जा रहा है…',
  'privacy.eraseBody': 'आपको दी गई किसी भी छात्रवृत्ति का अभिलेख हमें रखना पड़ता है। बाकी सब हटा दिया जाता है।',
  'auth.closedTitle': 'आपका खाता इस समय बंद है।',
  'auth.closedHelp': 'मदद चाहिए? हमारी सहायता टीम आपको समझा सकती है कि ',
  'auth.closedSoon': 'सहायता माँगें (जल्द)',
  'reg.district': 'ज़िला',
  'reg.districtHint': 'आपके क्षेत्र में चलने वाली योजनाओं से मिलान में मदद करता है।',
  'privacy.requested': 'अनुरोध किया गया',
  'privacy.window': 'अभी कुछ भी मिटाया नहीं गया है',
  'privacy.windowBody': 'आपका डेटा {date} को मिटा दिया जाएगा। तब तक आप ',
  'privacy.cancel': 'यह अनुरोध रद्द करें',
  'privacy.cancelling': 'रद्द किया जा रहा है…',
  'privacy.cancelled': 'आपका अनुरोध रद्द कर दिया गया है। कुछ भी नहीं मिटाया गया।',

  'common.loading': 'लोड हो रहा है',
  'common.retry': 'फिर कोशिश करें',
  'common.required': 'आवश्यक',
  'common.optional': 'वैकल्पिक',
  'common.error': 'कुछ गड़बड़ हो गई',
  'common.offline': 'आप ऑफ़लाइन हैं। आपका काम इस डिवाइस पर सहेजा गया है।',

  'slides.lead.was': '',
  'slides.lead.able': 'क्षमता से',
  'slides.lead.dist': 'विशिष्टता तक',
  'slides.lead.body': 'हर वह छात्रवृत्ति जिसके आप पात्र हैं — सरकारी और निजी — आपकी प्रोफ़ाइल से मिलान करके, आपकी भाषा में, एक जगह।',
  'slides.lead.free': 'पूरी तरह निःशुल्क',
  'slides.lead.languages': '14 भाषाएँ',
  'slides.lead.support': 'हर कदम पर व्यक्तिगत सहायता',
  'slides.label': 'घोषणाएँ',
  'slides.position': '{total} में से {n}',
  'slides.goto': '{name} दिखाएँ',
  'slides.watch': 'वीडियो देखें',
  'slides.external': 'दूसरी वेबसाइट खोलता है',

  'home.title': 'दिव्यांग विद्यार्थियों के लिए छात्रवृत्तियाँ, एक जगह',
  'home.lede': 'अपने बारे में एक बार बताइए। हम आपको यहाँ की हर छात्रवृत्ति से जाँचते हैं और बताते हैं कि आप किनके पात्र हैं — और बाकी के लिए ठीक-ठीक क्या छूट रहा है।',
  'home.search': 'छात्रवृत्तियाँ खोजें',
  'home.searchPlaceholder': 'जैसे: इंजीनियरिंग, दिल्ली, पोस्ट-मैट्रिक',
  'home.searchGo': 'खोजें',
  'home.browseAll': 'सभी छात्रवृत्तियाँ देखें',
  'home.openNow': 'छात्रवृत्तियाँ अभी खुली हैं',
  'home.noAccount': 'देखने के लिए खाते की ज़रूरत नहीं।',
  'home.openNone': 'यहाँ अभी कोई छात्रवृत्ति सूचीबद्ध नहीं है।',
  'home.openNoneBody': 'निर्देशिका अभी भरी जा रही है। यहाँ कुछ भी खाते के पीछे नहीं है — जब योजनाएँ सूचीबद्ध होंगी, आप उन्हें बिना साइन इन किए देख सकेंगे।',
  'home.how': 'यह कैसे काम करता है',
  'home.howLede': 'पंजीकरण के लिए एक मोबाइल नंबर और उस पर भेजा गया कोड चाहिए। कोई पासवर्ड नहीं, और पहले भरने के लिए कोई साइन-अप फ़ॉर्म नहीं।',
  'home.step1': 'पंजीकरण दबाइए',
  'home.step1Body': 'इस पृष्ठ के ऊपर। यदि आप पहले आ चुके हैं तो बगल में लॉगिन इस्तेमाल कीजिए — दोनों में वही नंबर काम करता है।',
  'home.step2': 'अपना मोबाइल नंबर भरिए',
  'home.step2Body': 'दस अंक, +91 पहले से भरा हुआ। उस नंबर पर 6 अंकों का कोड जाता है।',
  'home.step3': 'कोड भरिए',
  'home.step3Body': 'छह अंक टाइप कीजिए और आप अंदर हैं। यदि कोई संदेश न आए, तो कोड व्हाट्सऐप पर माँगिए, या हमसे कॉल करके सुनवाने को कहिए।',
  'home.step4': 'अपना विवरण भरिए',
  'home.step4Body': 'आपका नाम, आपका प्रमाण पत्र और आप कहाँ पढ़ते हैं — एक बार में एक प्रश्न, और हर उत्तर देते ही सहेज लिया जाता है।',
  'home.step5': 'अपने दस्तावेज़ अपलोड कीजिए',
  'home.step5Body': 'दिव्यांगता प्रमाण पत्र, यूडीआईडी कार्ड, आय प्रमाण पत्र और बाकी। हर एक बस एक बार, हर छात्रवृत्ति के लिए अलग से नहीं।',
  'home.step6': 'अपने मिलान देखिए',
  'home.step6Body': 'मेरे मिलान उन छात्रवृत्तियों को दिखाता है जिनके आप पात्र हैं — और जहाँ कोई आपके लिए बंद है, वहाँ कारण बताता है।',
  'home.step7': 'आवेदन कीजिए',
  'home.step7Body': 'जो चाहें वे चुनिए। आपका विवरण और आपके दस्तावेज़ आवेदन के साथ जाते हैं।',
  'home.assure': 'जानने योग्य',
  'home.assure1': 'याद रखने के लिए कोई पासवर्ड नहीं',
  'home.assure2': 'कोई अलग पंजीकरण फ़ॉर्म नहीं',
  'home.assure3': 'आप रुककर बाद में पूरा कर सकते हैं',
  'home.help': 'किसी चरण पर अटक गए?',
  'home.helpBody': 'कॉल कीजिए और कोई आपको पूरा करा देगा।',
  'home.helpCall': '{number} पर कॉल करें',
  'home.closing': 'जल्द बंद',
  'home.closingLede': 'पहले इनके लिए आवेदन कीजिए।',
  'home.closingNext': 'अगली अंतिम तिथियाँ',
  'home.closingNextLede': 'सबसे पहले बंद होने वाली तीन।',
  'home.allDeadlines': 'सभी छात्रवृत्तियाँ देखें',
  'home.browse': 'इसके अनुसार देखें',
  'home.browseWho': 'कौन दे रहा है',
  'home.browseLevel': 'आपका अध्ययन स्तर',
  'home.cta': 'अपने मिलान देखने के लिए तैयार हैं?',
  'home.ctaBody': 'खाता बनाने के लिए एक मोबाइल नंबर या एक ईमेल पता चाहिए। और कुछ नहीं।',
  'home.ctaButton': 'खाता बनाएँ',
  'home.signedInCta': 'देखिए आप किसके पात्र हैं',

  'reg.title': 'छात्रवृत्तियाँ खोजने के लिए पंजीकरण कीजिए',
  'reg.editTitle': 'अपना विवरण अद्यतन कीजिए',
  'reg.requiredNote': '* वाले सभी क्षेत्र आवश्यक हैं।',
  'reg.personal': 'व्यक्तिगत विवरण',
  'reg.disability': 'दिव्यांगता का विवरण',
  'reg.education': 'शिक्षा का विवरण',
  'reg.name': 'पूरा नाम',
  'reg.namePlaceholder': 'अपना पूरा नाम भरिए',
  'reg.phoneHint': 'हम इस नंबर पर 6 अंकों का कोड भेजते हैं। हर बार यही नंबर आपको साइन इन कराता है।',
  'reg.sendOtp': 'ओटीपी भेजें',
  'reg.otpPlaceholder': '6 अंकों का ओटीपी भरिए',
  'reg.verified': 'फ़ोन नंबर सत्यापित',
  'reg.verifyFirst': 'पंजीकरण पूरा करने के लिए अपना फ़ोन नंबर सत्यापित कीजिए।',
  'reg.email': 'ईमेल',
  'reg.emailHint': 'ताकि हम आपको अंतिम तिथि की याद दिला सकें। हम इसे कभी साझा नहीं करते।',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'लिंग',
  'reg.genderHint': '(कुछ छात्रवृत्तियाँ केवल महिला या ट्रांसजेंडर विद्यार्थियों के लिए हैं)',
  'reg.udid': 'यूडीआईडी संख्या',
  'reg.udidHint': 'आपके यूडीआईडी (विशिष्ट दिव्यांगता पहचान) कार्ड पर लिखी संख्या।',
  'reg.udidPlaceholder': 'अपनी यूडीआईडी संख्या भरिए',
  'reg.certificate': 'यूडीआईडी प्रमाण पत्र अपलोड कीजिए',
  'reg.certificateHint': 'पीडीएफ़ या चित्र, 5 एमबी या उससे कम।',
  'reg.fileType': 'वह फ़ाइल पीडीएफ़, जेपीईजी या पीएनजी होनी चाहिए।',
  'reg.fileSize': 'वह फ़ाइल 5 एमबी से बड़ी है। फ़ोन से ली गई फ़ोटो आम तौर पर छोटी होती है यदि आप उसे खींचने के बजाय स्कैन करें।',
  'reg.fileLater': 'आपका पंजीकरण हो गया और विवरण सहेज लिया गया। प्रमाण पत्र अपलोड नहीं हुआ — उसे मेरे दस्तावेज़ से जोड़ दीजिए, बाकी कुछ दोबारा नहीं करना है।',
  'reg.disabilityType': 'दिव्यांगता का प्रकार',
  'reg.percent': 'दिव्यांगता प्रतिशत',
  'reg.percentHint': 'आपके प्रमाण पत्र पर लिखा आँकड़ा। कई छात्रवृत्तियों के लिए 40% या अधिक चाहिए।',
  'reg.percentPlaceholder': 'जैसे 40',
  'reg.percentRange': 'प्रमाण पत्र का प्रतिशत 0 और 100 के बीच पूर्ण संख्या होती है।',
  'reg.state': 'राज्य',
  'reg.statePlaceholder': 'अपना राज्य खोजने के लिए टाइप कीजिए…',
  'reg.program': 'अपना पाठ्यक्रम चुनिए',
  'reg.graduation': 'स्नातक',
  'reg.postgraduation': 'स्नातकोत्तर / मास्टर्स',
  'reg.year': 'वर्ष चुनिए',
  'reg.yearAfterProgram': 'पहले अपना पाठ्यक्रम चुनिए',
  'reg.institution': 'विद्यालय / महाविद्यालय का नाम',
  'reg.institutionPlaceholder': 'अपने संस्थान का नाम भरिए',
  'reg.required': 'यह ज़रूरी है।',
  'reg.fix': 'कुछ उत्तरों पर ध्यान चाहिए। पहला नीचे चुना हुआ है।',
  'reg.cta': 'पंजीकरण कीजिए और छात्रवृत्तियाँ खोजिए',
  'reg.saveChanges': 'बदलाव सहेजें',
  'reg.saving': 'सहेजा जा रहा है…',
  'reg.done': 'पंजीकरण हो गया। आपकी छात्रवृत्तियाँ खोजी जा रही हैं।',
  'reg.doneTitle': 'आपका पंजीकरण हो गया है',
  'reg.already': 'पहले से पंजीकृत हैं?',
  'reg.login': 'ओटीपी से लॉगिन',
  'nav.registerCta': 'पंजीकरण',
  'nav.loginCta': 'लॉगिन',
  'profile.edit': 'अपना विवरण अद्यतन कीजिए',
  'field.disability.BLINDNESS': 'दृष्टिहीनता',
  'field.disability.LOW_VISION': 'अल्प दृष्टि',
  'field.disability.LEPROSY_CURED': 'कुष्ठ रोग (ठीक हुआ)',
  'field.disability.HEARING_IMPAIRMENT': 'श्रवण बाधिता',
  'field.disability.LOCOMOTOR_DISABILITY': 'चलन दिव्यांगता',
  'field.disability.DWARFISM': 'बौनापन',
  'field.disability.INTELLECTUAL_DISABILITY': 'बौद्धिक दिव्यांगता',
  'field.disability.MENTAL_ILLNESS': 'मानसिक रुग्णता',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'स्वलीनता (ऑटिज़्म) स्पेक्ट्रम विकार',
  'field.disability.CEREBRAL_PALSY': 'प्रमस्तिष्क घात',
  'field.disability.MUSCULAR_DYSTROPHY': 'मांसपेशीय दुर्विकास',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'दीर्घकालिक तंत्रिका संबंधी स्थिति',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'विशिष्ट अधिगम दिव्यांगता',
  'field.disability.MULTIPLE_SCLEROSIS': 'मल्टीपल स्क्लेरोसिस',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'वाणी और भाषा दिव्यांगता',
  'field.disability.THALASSEMIA': 'थैलेसीमिया',
  'field.disability.HAEMOPHILIA': 'हीमोफीलिया',
  'field.disability.SICKLE_CELL_DISEASE': 'सिकल सेल रोग',
  'field.disability.MULTIPLE_DISABILITIES': 'बहु दिव्यांगता, जिसमें दृष्टि-श्रवण बाधिता भी',
  'field.disability.ACID_ATTACK_VICTIM': 'तेज़ाब हमले से उत्तरजीवी',
  'field.disability.PARKINSONS_DISEASE': 'पार्किंसंस रोग',

  'field.state.AN': 'अंडमान और निकोबार द्वीपसमूह',
  'field.state.AP': 'आंध्र प्रदेश',
  'field.state.AR': 'अरुणाचल प्रदेश',
  'field.state.AS': 'असम',
  'field.state.BR': 'बिहार',
  'field.state.CH': 'चंडीगढ़',
  'field.state.CT': 'छत्तीसगढ़',
  'field.state.DL': 'दिल्ली',
  'field.state.DN': 'दादरा और नगर हवेली और दमन और दीव',
  'field.state.GA': 'गोवा',
  'field.state.GJ': 'गुजरात',
  'field.state.HP': 'हिमाचल प्रदेश',
  'field.state.HR': 'हरियाणा',
  'field.state.JH': 'झारखंड',
  'field.state.JK': 'जम्मू और कश्मीर',
  'field.state.KA': 'कर्नाटक',
  'field.state.KL': 'केरल',
  'field.state.LA': 'लद्दाख',
  'field.state.LD': 'लक्षद्वीप',
  'field.state.MH': 'महाराष्ट्र',
  'field.state.ML': 'मेघालय',
  'field.state.MN': 'मणिपुर',
  'field.state.MP': 'मध्य प्रदेश',
  'field.state.MZ': 'मिज़ोरम',
  'field.state.NL': 'नागालैंड',
  'field.state.OR': 'ओडिशा',
  'field.state.PB': 'पंजाब',
  'field.state.PY': 'पुदुचेरी',
  'field.state.RJ': 'राजस्थान',
  'field.state.SK': 'सिक्किम',
  'field.state.TG': 'तेलंगाना',
  'field.state.TN': 'तमिलनाडु',
  'field.state.TR': 'त्रिपुरा',
  'field.state.UP': 'उत्तर प्रदेश',
  'field.state.UT': 'उत्तराखंड',
  'field.state.WB': 'पश्चिम बंगाल',

  'field.level.SCHOOL': 'विद्यालय',
  'field.level.SCHOOL.sub': 'कक्षा 9, कक्षा 10, कक्षा 11, कक्षा 12',
  'field.level.UNDERGRADUATE': 'स्नातक',
  'field.level.UNDERGRADUATE.sub': 'बीए, बीएससी, बीटेक और ऐसे ही',
  'field.level.POSTGRADUATE': 'स्नातकोत्तर',
  'field.level.POSTGRADUATE.sub': 'एमए, एमएससी, एमटेक और ऐसे ही',
  'field.level.DOCTORAL': 'डॉक्टरेट',
  'field.level.DOCTORAL.sub': 'पीएचडी',

  'field.qual.SCHOOL': 'विद्यालय',
  'field.qual.SCHOOL.sub': 'कक्षा 1 से 12',
  'field.qual.UNDERGRADUATE': 'स्नातक',
  'field.qual.UNDERGRADUATE.sub': 'बीए, बीएससी, बीकॉम, बीई / बीटेक, एमबीबीएस — और डिप्लोमा या आईटीआई',
  'field.qual.POSTGRADUATE': 'स्नातकोत्तर',
  'field.qual.POSTGRADUATE.sub': 'एमए, एमएससी, एमटेक, एमबीए और ऐसे ही',
  'field.qual.DOCTORAL': 'पीएचडी / डॉक्टरेट',

  'field.subject.engineering': 'इंजीनियरिंग',
  'field.subject.medical': 'चिकित्सा',
  'field.subject.management': 'प्रबंधन',
  'field.subject.science': 'विज्ञान',
  'field.subject.commerce': 'वाणिज्य',
  'field.subject.arts': 'कला और मानविकी',
  'field.subject.vocational': 'व्यावसायिक',
  'field.subject.fellowship': 'फ़ेलोशिप',
  'field.subject.talent': 'प्रतिभा',
  'field.subject.sports': 'खेल',

  'field.gender.FEMALE': 'महिला',
  'field.gender.MALE': 'पुरुष',
  'field.gender.TRANSGENDER': 'ट्रांसजेंडर',
  'field.gender.UNDISCLOSED': 'बताना नहीं चाहते',
  'field.genderFilter.TRANSGENDER': 'तृतीय लिंग / ट्रांसजेंडर',

  'field.year.below9': 'कक्षा 9 से नीचे',
  'field.year.c9': 'कक्षा 9',
  'field.year.c10': 'कक्षा 10',
  'field.year.c11': 'कक्षा 11',
  'field.year.c12': 'कक्षा 12',
  'field.year.y1': 'पहला वर्ष',
  'field.year.y2': 'दूसरा वर्ष',
  'field.year.y3': 'तीसरा वर्ष',
  'field.year.y4': 'चौथा वर्ष',
  'field.year.pg1': 'स्नातकोत्तर वर्ष 1',
  'field.year.pg2': 'स्नातकोत्तर वर्ष 2',

  'q.full_name': 'आपका नाम क्या है?',
  'q.full_name.help': 'ठीक वैसे ही जैसे आपके दिव्यांगता प्रमाण पत्र पर लिखा है। संस्थाएँ दोनों का मिलान करती हैं।',
  'q.gender': 'आपका लिंग क्या है?',
  'q.gender.help': 'कुछ छात्रवृत्तियाँ केवल महिलाओं के लिए हैं, या ट्रांसजेंडर विद्यार्थियों के लिए। न बताना चाहें तो छोड़ दीजिए।',
  'q.disability_type': 'आपकी दिव्यांगता क्या है?',
  'q.disability_type.help': 'जैसा आपके प्रमाण पत्र पर लिखा है। अधिकतर छात्रवृत्तियाँ इसी पर छाँटती हैं।',
  'q.disability_percent': 'आपके प्रमाण पत्र पर कितना प्रतिशत है?',
  'q.disability_percent.help': '0 और 100 के बीच की संख्या। कई छात्रवृत्तियों के लिए 40% या अधिक चाहिए।',
  'q.disability_percent.range': 'प्रमाण पत्र का प्रतिशत 0 और 100 के बीच होता है।',
  'q.udid_number': 'आपकी यूडीआईडी संख्या क्या है?',
  'q.udid_number.help': 'आपके यूडीआईडी (विशिष्ट दिव्यांगता पहचान) कार्ड पर लिखी संख्या। यदि अभी जारी नहीं हुआ है तो छोड़ दीजिए — इससे आपकी पात्रता में कोई अंतर नहीं पड़ता, और आप इसे बाद में जोड़ सकते हैं।',
  'q.date_of_birth': 'आपका जन्म कब हुआ?',
  'q.date_of_birth.help': 'कुछ छात्रवृत्तियों में आयु सीमा होती है।',
  'q.course_name': 'आप क्या पढ़ रहे हैं?',
  'q.course_name.help': 'वही पाठ्यक्रम जो आपने पंजीकरण के समय चुना था।',
  'q.institution_name': 'आप कहाँ पढ़ते हैं?',
  'q.institution_name.help': 'आपके विद्यालय, महाविद्यालय या विश्वविद्यालय का नाम, जैसा आपके बोनाफाइड प्रमाण पत्र पर लिखा है। अभी शुरू नहीं किया है तो छोड़ दीजिए।',
  'q.institution_name.placeholder': 'आपके विद्यालय या महाविद्यालय का नाम',
  'q.state_code': 'आप किस राज्य में रहते हैं?',
  'q.state_code.help': 'कई छात्रवृत्तियाँ केवल कुछ राज्यों के निवासियों के लिए खुली हैं।',
  'q.annual_family_income': 'आपके परिवार की वार्षिक आय कितनी है?',
  'q.annual_family_income.help': 'रुपयों में, जैसा आपके आय प्रमाण पत्र पर है। अधिकतर छात्रवृत्तियों में एक सीमा होती है।',
  'q.annual_family_income.range': 'आय शून्य से कम नहीं हो सकती।',
  'q.academic_percentage': 'आपकी पिछली परीक्षा के अंक क्या थे?',
  'q.academic_percentage.help': 'जिस तरह आपकी अंकतालिका उन्हें बताती है वह चुनिए, फिर संख्या भरिए। कई छात्रवृत्तियाँ न्यूनतम अंक माँगती हैं।',
  'field.orgKind.NGO': 'एनजीओ',
  'field.orgKind.CORPORATE': 'कॉर्पोरेट',
  'field.orgKind.GOVERNMENT': 'सरकारी',
  'field.orgKind.PRIVATE': 'निजी',

  'field.doc.DISABILITY_CERTIFICATE': 'दिव्यांगता प्रमाण पत्र',
  'field.doc.UDID_CARD': 'यूडीआईडी कार्ड',
  'field.doc.INCOME_CERTIFICATE': 'आय प्रमाण पत्र',
  'field.doc.DOMICILE_CERTIFICATE': 'निवास प्रमाण पत्र',
  'field.doc.CASTE_CERTIFICATE': 'श्रेणी प्रमाण पत्र',
  'field.doc.MARKSHEET': 'अंकतालिका',
  'field.doc.ADMISSION_LETTER': 'प्रवेश पत्र',
  'field.doc.BONAFIDE_CERTIFICATE': 'बोनाफाइड प्रमाण पत्र',
  'field.doc.FEE_RECEIPT': 'शुल्क रसीद',
  'field.doc.BANK_PASSBOOK': 'बैंक पासबुक',
  'field.doc.IDENTITY_PROOF': 'पहचान प्रमाण',
  'field.doc.PHOTOGRAPH': 'फ़ोटो',

  'appl.next.SUBMITTED': 'संस्था के पास आपका आवेदन है। अगला कदम यह है कि कोई समीक्षक इसे पढ़ेगा।',
  'appl.next.UNDER_REVIEW': 'एक समीक्षक आपका आवेदन पढ़ रहा है। आम तौर पर यही सबसे लंबा चरण होता है।',
  'appl.next.INFO_REQUESTED': 'उन्होंने आपसे कुछ माँगा है। जब तक आप उत्तर नहीं देते, आपका आवेदन रुका रहेगा।',
  'appl.next.DOCUMENT_CHECK': 'आपका आवेदन समीक्षक के पास है। आपसे कुछ नहीं चाहिए।',
  'appl.next.VERIFIED': 'आपका आवेदन समीक्षक के पास है। आपसे कुछ नहीं चाहिए।',
  'appl.next.SHORTLISTED': 'आपका आवेदन समीक्षक के पास है। अगला कदम निर्णय है।',
  'appl.next.APPROVED': 'स्वीकृत। संस्था स्वीकृति दर्ज करेगी, फिर भुगतान की व्यवस्था करेगी।',
  'appl.next.SANCTIONED': 'राशि स्वीकृत हो गई है। भुगतान उनके बैंक के माध्यम से किया जाता है।',
  'appl.next.DISBURSED': 'भुगतान दर्ज हो गया है। यदि कुछ कार्यदिवसों में आपके खाते में न पहुँचे, तो शिकायत दर्ज कीजिए।',
  'appl.next.REJECTED': 'यह आवेदन सफल नहीं रहा। इससे आपके दूसरे आवेदनों पर कोई असर नहीं पड़ता।',
  'appl.next.CLOSED': 'यह आवेदन पूरा हो चुका है।',
  'appl.next.WITHDRAWN': 'आपने यह आवेदन वापस ले लिया था।',

  /* Read Aloud's sample sentence, in the language the voice will read. */
  'a11y.voiceSample': 'पढ़कर सुनाएँ की आवाज़ ऐसी सुनाई देगी। आप सूची से दूसरी आवाज़ भी चुन सकते हैं।',
}

export default hi
