/* Kannada.
 *
 * One word per term: scholarship ವಿದ್ಯಾರ್ಥಿವೇತನ, application ಅರ್ಜಿ,
 * document ದಾಖಲೆ, disability ವಿಕಲಚೇತನ (Karnataka's own term, in preference
 * to ಅಂಗವಿಕಲತೆ), verified ಪರಿಶೀಲಿಸಲಾಗಿದೆ, eligible ಅರ್ಹ,
 * certificate ಪ್ರಮಾಣಪತ್ರ, profile ಪ್ರೊಫೈಲ್.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const kn: Dict = {
  'app.name': 'ವಿದ್ಯಾರ್ಥಿವೇತನ ಪೋರ್ಟಲ್',
  'app.tagline': 'ವಿಕಲಚೇತನ ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ',
  'app.yourApplication': 'ನಿಮ್ಮ ಅರ್ಜಿ · {title}',

  'nav.find': 'ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು',
  'nav.how': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
  'nav.matches': 'ನನ್ನ ಹೊಂದಾಣಿಕೆಗಳು',
  'nav.applications': 'ನನ್ನ ಅರ್ಜಿಗಳು',
  'nav.documents': 'ನನ್ನ ದಾಖಲೆಗಳು',
  'nav.profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
  'nav.privacy': 'ನನ್ನ ಮಾಹಿತಿ',
  'nav.account': 'ನನ್ನ ಖಾತೆ',
  'nav.register': 'ಸೈನ್ ಅಪ್',
  'nav.language': 'ಭಾಷೆ',
  'footer.social': 'ಇಂಡಿಕ್ ಎಐ ಬೇರೆಡೆ',
  'footer.sponsor': 'ಬೆಂಬಲದೊಂದಿಗೆ',
  'footer.copyright': 'ಕೃತಿಸ್ವಾಮ್ಯ © {year} ಇಂಡಿಕ್ ಎಐ | ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ',
  'nav.signin': 'ಸೈನ್ ಇನ್',
  'nav.signout': 'ಸೈನ್ ಔಟ್',
  'nav.skip': 'ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ಹೋಗಿ',

  'public.title': 'ನೀವು ಅರ್ಹರಾಗಿರುವ ವಿದ್ಯಾರ್ಥಿವೇತನವನ್ನು ಹುಡುಕಿ',
  'public.lede': 'ಇಲ್ಲಿರುವ ಪ್ರತಿಯೊಂದು ವಿದ್ಯಾರ್ಥಿವೇತನವೂ ವಿಕಲಚೇತನ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮುಕ್ತವಾಗಿದೆ. ನೋಡಲು ಖಾತೆ ಬೇಕಿಲ್ಲ.',
  'public.search': 'ಹೆಸರು ಅಥವಾ ಪದದಿಂದ ಹುಡುಕಿ',
  'public.filter.disability': 'ವಿಕಲಚೇತನದ ಬಗೆ',
  'public.filter.qualification': 'ಅರ್ಹತೆ',
  'public.filter.state': 'ನಿಮ್ಮ ರಾಜ್ಯ',
  'public.filter.provider': 'ಯಾರು ನೀಡುತ್ತಾರೆ',
  'public.filter.any': 'ಯಾವುದಾದರೂ',
  'public.filter.anyDisability': 'ಯಾವುದೇ ವಿಕಲಚೇತನ',
  'public.filter.anyQualification': 'ಯಾವುದೇ ಅರ್ಹತೆ',
  'public.filter.allStates': 'ಎಲ್ಲ ರಾಜ್ಯಗಳು',
  'public.filter.gender': 'ಲಿಂಗ',
  'public.filter.anyGender': 'ಯಾವುದೇ ಲಿಂಗ',
  'public.filter.course': 'ಕೋರ್ಸ್',
  'public.filter.anyCourse': 'ಯಾವುದೇ ಕೋರ್ಸ್',
  'public.filter.where': 'ನೀವು ಎಲ್ಲಿ ಓದುತ್ತಿದ್ದೀರಿ',
  'public.filter.anyWhere': 'ಭಾರತ ಅಥವಾ ವಿದೇಶ',
  'public.filter.inIndia': 'ಭಾರತದಲ್ಲಿ',
  'public.filter.abroad': 'ವಿದೇಶಿ ಶಿಕ್ಷಣ',
  'public.filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
  'public.clear': 'ತೆಗೆದುಹಾಕಿ',
  'public.results': 'ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಈಗ ತೆರೆದಿವೆ',
  'public.searching': 'ಹುಡುಕುತ್ತಿದೆ…',
  'public.none': 'ಈ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಯಾವ ವಿದ್ಯಾರ್ಥಿವೇತನವೂ ಹೊಂದಲಿಲ್ಲ',
  'public.none.hint': 'ಒಂದು ಫಿಲ್ಟರ್ ತೆಗೆದು ನೋಡಿ. ವರ್ಷವಿಡೀ ಹೊಸ ಯೋಜನೆಗಳು ತೆರೆಯುತ್ತವೆ.',
  'public.none.clear': 'ಎಲ್ಲ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಿ',
  'public.empty': 'ಇಲ್ಲಿ ಇನ್ನೂ ಯಾವ ವಿದ್ಯಾರ್ಥಿವೇತನವೂ ಪಟ್ಟಿಯಾಗಿಲ್ಲ',
  'public.empty.hint': 'ಪೂರೈಕೆದಾರರನ್ನು ಈಗ ಸೇರಿಸಲಾಗುತ್ತಿದೆ. ಇಲ್ಲಿ ಯಾವುದೂ ಖಾತೆಯ ಹಿಂದೆ ಇಲ್ಲ — ಯೋಜನೆಗಳು ಪಟ್ಟಿಯಾದ ಮೇಲೆ ಸೈನ್ ಇನ್ ಮಾಡದೆಯೇ ನೋಡಬಹುದು.',
  'public.whoFor': 'ಇದು ಯಾರಿಗಾಗಿ',
  'public.about': 'ಈ ವಿದ್ಯಾರ್ಥಿವೇತನದ ಬಗ್ಗೆ',
  'public.atAGlance': 'ಒಂದು ನೋಟದಲ್ಲಿ',
  'public.closes': 'ಮುಗಿಯುತ್ತದೆ',
  'public.awardUnstated': 'ಮೊತ್ತ ತಿಳಿಸಿಲ್ಲ',
  'public.noClose': 'ಕೊನೆಯ ದಿನಾಂಕವಿಲ್ಲ',
  'public.closesIn': '{n} ದಿನಗಳಲ್ಲಿ ಮುಗಿಯುತ್ತದೆ',
  'public.closesToday': 'ಇಂದು ಮುಗಿಯುತ್ತದೆ',
  'public.closed': 'ಮುಗಿದಿದೆ',
  'public.award': 'ಮೊತ್ತ',
  'public.renewable': 'ಪ್ರತಿ ವರ್ಷ ನವೀಕರಿಸಬಹುದು',
  'public.offeredBy': 'ನೀಡುವವರು',
  'public.eligibility': 'ಅರ್ಹರಾಗಲು',
  'public.benefits': 'ಪ್ರಯೋಜನಗಳು',
  'public.readMore': 'ಇನ್ನಷ್ಟು ಓದಿ',
  'public.viewDetails': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
  'public.applyNow': 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'public.registerToApply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'public.registerToApplyHelp': 'ಅರ್ಜಿಗಳು ನಿಮ್ಮ ಖಾತೆಯ ಮೂಲಕ ಸಲ್ಲಿಕೆಯಾಗುತ್ತವೆ. ನೋಂದಾಯಿಸಿದರೆ ನೀವು ಅರ್ಹರಾಗಿರುವ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನವೂ ಕಾಣಿಸುತ್ತದೆ.',
  'public.closedNote': 'ಈ ಯೋಜನೆ ಮುಗಿದಿದೆ',
  'sheet.close': 'ಮುಚ್ಚಿ',
  'sheet.loading': 'ವಿದ್ಯಾರ್ಥಿವೇತನದ ವಿವರಗಳು',
  'public.benefitComponent': 'ಅಂಶ',
  'public.benefitAmount': 'ವಿದ್ಯಾರ್ಥಿಗೆ ಏನು ಸಿಗುತ್ತದೆ',
  'public.whatYouGet': 'ನಿಮಗೆ ಏನು ಸಿಗುತ್ತದೆ',
  'public.eligibilityDetail': 'ಅರ್ಹತೆ ವಿವರವಾಗಿ',
  'public.documentsRequired': 'ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು',
  'public.documentsHelp': 'ಪೂರೈಕೆದಾರರು ಇವುಗಳನ್ನು ಕೇಳುತ್ತಾರೆ. ಇವನ್ನು ನೀವು ಇಲ್ಲಿ ಅಪ್‌ಲೋಡ್ ಮಾಡುವುದಿಲ್ಲ.',
  'public.howToApply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು ಹೇಗೆ',
  'public.importantNotes': 'ತಿಳಿದಿರಬೇಕಾದದ್ದು',
  'public.academicYear': 'ಯಾವ ವರ್ಷಕ್ಕೆ',
  'public.awardBasis': 'ಯಾವ ಆಧಾರದ ಮೇಲೆ',
  'public.basis.MERIT': 'ಪ್ರತಿಭೆ',
  'public.basis.NEED': 'ಆರ್ಥಿಕ ಅಗತ್ಯ',
  'public.basis.MERIT_CUM_MEANS': 'ಪ್ರತಿಭೆ ಮತ್ತು ಆದಾಯ',
  'public.basis.CATEGORY': 'ವರ್ಗ',
  'public.basis.OTHER': 'ಇತರೆ',
  'public.cta': 'ನಿಮಗಾಗಿ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕಿ',
  'public.applyExternal': 'ಅವರ ಸೈಟ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'public.applyExternalHelp': 'ನೀವು ಹುಡುಕಲು ಸಾಧ್ಯವಾಗಲೆಂದೇ ನಾವು ಈ ವಿದ್ಯಾರ್ಥಿವೇತನವನ್ನು ಪಟ್ಟಿ ಮಾಡುತ್ತೇವೆ. {org} ಇದನ್ನು ನಡೆಸುತ್ತದೆ ಮತ್ತು ತಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲೇ ಅರ್ಜಿಗಳನ್ನು ಸ್ವೀಕರಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಇದು ಇಲ್ಲಿ ನಿಮ್ಮ ಅರ್ಜಿಗಳಲ್ಲಿ ಕಾಣಿಸುವುದಿಲ್ಲ.',
  'public.applyExternalHelpPartner': '{org} ಈ ಅರ್ಜಿಯನ್ನು ತಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲೇ ಸ್ವೀಕರಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಇದು ಇಲ್ಲಿ ನಿಮ್ಮ ಅರ್ಜಿಗಳಲ್ಲಿ ಕಾಣಿಸುವುದಿಲ್ಲ.',
  'common.newTab': 'ಹೊಸ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ',
  'public.applyHelp': 'ನಾವು ಮೊದಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಈ ವಿದ್ಯಾರ್ಥಿವೇತನದೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ, ಏನಾದರೂ ಕೊರತೆಯಿದ್ದರೆ ತಿಳಿಸುತ್ತೇವೆ. ನೀವು ಖಚಿತಪಡಿಸುವವರೆಗೆ ಏನೂ ಕಳುಹಿಸುವುದಿಲ್ಲ.',
  'public.ctaHelp': 'ನಿಮ್ಮ ಬಗ್ಗೆ ಒಮ್ಮೆ ಹೇಳಿ, ನೀವು ಅರ್ಹರಾಗಿರುವ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನವನ್ನೂ ತೋರಿಸುತ್ತೇವೆ.',
  'public.back': 'ಎಲ್ಲ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
  'notFound.title': 'ನಮಗೆ ಈ ಪುಟ ಸಿಗಲಿಲ್ಲ',
  'notFound.body': 'ವಿಳಾಸದಲ್ಲಿ ಟೈಪಿಂಗ್ ತಪ್ಪು ಇರಬಹುದು, ಅಥವಾ ಪುಟವನ್ನು ಸ್ಥಳಾಂತರಿಸಿರಬಹುದು.',
  'notFound.home': 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ',

  'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  'dash.title': 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  'dash.lede': 'ನಿಮ್ಮ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು, ಅರ್ಜಿಗಳು ಮತ್ತು ದಾಖಲೆಗಳು — ಎಲ್ಲವೂ ಒಂದೇ ಕಡೆ.',
  'dash.matches': 'ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದಾದ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು',
  'dash.matchesHint': 'ನೀವು ನೀಡಿದ ವಿವರಗಳ ಆಧಾರದ ಮೇಲೆ.',
  'dash.matchesBlocked': '{n} ನಿಮ್ಮಿಂದ ಇನ್ನೊಂದು ವಿವರಕ್ಕಾಗಿ ಕಾಯುತ್ತಿವೆ.',
  'dash.applications': 'ನಡೆಯುತ್ತಿರುವ ಅರ್ಜಿಗಳು',
  'dash.applicationsHint': '{approved} ಅನುಮೋದಿತ · {rejected} ಯಶಸ್ವಿಯಾಗಲಿಲ್ಲ',
  'dash.applicationsNone': 'ಇನ್ನೂ ಏನೂ ಕಳುಹಿಸಿಲ್ಲ.',
  'dash.documents': 'ಪರಿಶೀಲಿಸಿದ ದಾಖಲೆಗಳು',
  'dash.documentsHint': 'ಒಮ್ಮೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ. ಪ್ರತಿ ಅರ್ಜಿಗೂ ಬಳಕೆಯಾಗುತ್ತವೆ.',
  'dash.funding': 'ಇಲ್ಲಿಯವರೆಗೆ ಸಿಕ್ಕಿದ್ದು',
  'dash.fundingHint': 'ಒಟ್ಟು {sanctioned} ಮಂಜೂರು.',
  'dash.recent': 'ಇತ್ತೀಚಿನ ಅರ್ಜಿಗಳು',
  'dash.noApplications': 'ಇನ್ನೂ ಅರ್ಜಿಗಳಿಲ್ಲ',
  'dash.noApplicationsHint': 'ನೀವು ಯಾವುದಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿದರೂ ಅದು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
  'dash.findScholarships': 'ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕಿ',
  'dash.profileTitle': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
  'dash.toGo': '{n}% ಬಾಕಿ',
  'dash.allApplications': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
  'dash.matchesGo': 'ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಿ',
  'dash.applicationsGo': 'ನಿಮ್ಮ ಅರ್ಜಿಗಳನ್ನು ಗಮನಿಸಿ',
  'dash.documentsGo': 'ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
  'dash.draftsTitle': '{n} ಅರ್ಜಿ ಕಳುಹಿಸಿಲ್ಲ | {n} ಅರ್ಜಿಗಳು ಕಳುಹಿಸಿಲ್ಲ',
  'dash.draftsBody': 'ಅರ್ಜಿ ಆರಂಭಿಸುವುದೆಂದರೆ ಕಳುಹಿಸಿದಂತಲ್ಲ. ವಿದ್ಯಾರ್ಥಿವೇತನ ಮುಗಿಯುವ ಮೊದಲು ಪೂರ್ಣಗೊಳಿಸಿ.',
  'dash.draftsAction': 'ಈಗಲೇ ಪೂರ್ಣಗೊಳಿಸಿ',
  'dash.expiringTitle': '{n} ದಾಖಲೆಯ ಅವಧಿ ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುತ್ತದೆ | {n} ದಾಖಲೆಗಳ ಅವಧಿ ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುತ್ತದೆ',
  'dash.expiringBody': 'ಪ್ರತಿ ಅರ್ಜಿಗೂ ಬಳಕೆಯಾಗುವಂತೆ ಇದನ್ನು ಈಗಲೇ ಬದಲಿಸಿ. | ಪ್ರತಿ ಅರ್ಜಿಗೂ ಬಳಕೆಯಾಗುವಂತೆ ಇವನ್ನು ಈಗಲೇ ಬದಲಿಸಿ.',
  'dash.expiringAction': 'ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',

  'auth.title': 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'auth.phone': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  'auth.phoneHint': 'ಈ ಸಂಖ್ಯೆಗೆ 6 ಅಂಕಿಯ ಕೋಡ್ ಅನ್ನು SMS ಮೂಲಕ ಕಳುಹಿಸುತ್ತೇವೆ. ಪ್ರತಿ ಬಾರಿಯೂ ಇದೇ ಸಂಖ್ಯೆ ನಿಮ್ಮನ್ನು ಸೈನ್ ಇನ್ ಮಾಡಿಸುತ್ತದೆ.',
  'auth.phoneMissing': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',
  'auth.phoneInvalid': 'ಇದು ಸರಿ ಕಾಣುತ್ತಿಲ್ಲ. ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗಳು 10 ಅಂಕಿಗಳು, 6, 7, 8 ಅಥವಾ 9ರಿಂದ ಆರಂಭವಾಗುತ್ತವೆ.',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'ಹೊಸಬರಾಗಿರಲಿ, ಮರಳಿ ಬಂದವರಾಗಿರಲಿ, ಅದೇ ಸಂಖ್ಯೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ನಿಮಗೆ ಖಾತೆ ಇಲ್ಲದಿದ್ದರೆ ನಾವು ಸೃಷ್ಟಿಸುತ್ತೇವೆ.',
  'auth.stepOf': 'ಹಂತ {n} / 2 · {name}',
  'auth.stepPhone': 'ನಿಮ್ಮ ಸಂಖ್ಯೆ',
  'auth.stepCode': 'ನಿಮ್ಮ OTP ಕೋಡ್',
  'auth.privacy': 'ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ನಿಮ್ಮನ್ನು ಸೈನ್ ಇನ್ ಮಾಡಿಸಲು ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ, ಬೇರೇನಕ್ಕೂ ಅಲ್ಲ. ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು ಯಾವ ಪಾಸ್‌ವರ್ಡ್ ಕೂಡ ಇಲ್ಲ.',
  'auth.sendCode': 'ಕೋಡ್ ಕಳುಹಿಸಿ',
  'auth.sending': 'ಕಳುಹಿಸುತ್ತಿದೆ…',
  'auth.checking': 'ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
  'auth.welcomeBack': 'ಮತ್ತೆ ಸ್ವಾಗತ. ಸೈನ್ ಇನ್ ಮಾಡಲು ಕೋಡ್ ನಮೂದಿಸಿ.',
  'auth.newHere': 'ಕೋಡ್ ನಮೂದಿಸಿದ ಕೂಡಲೇ ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಸೃಷ್ಟಿಸುತ್ತೇವೆ.',
  'auth.codeTitle': 'ನಾವು ಕಳುಹಿಸಿದ ಕೋಡ್ ನಮೂದಿಸಿ',
  'auth.code': '6 ಅಂಕಿಯ ಕೋಡ್',
  'auth.codeHint': 'ಸಂದೇಶ ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಬರುತ್ತದೆ.',
  'auth.noCode': 'ಇನ್ನೂ ಸಂದೇಶ ಬಂದಿಲ್ಲವೇ? ಬೇರೊಂದು ದಾರಿ ನೋಡಿ:',
  'auth.verify': 'ಪರಿಶೀಲಿಸಿ',
  'auth.viaSms': 'SMS ಮೂಲಕ ಕಳುಹಿಸಿ',
  'auth.viaWhatsapp': 'ವಾಟ್ಸ್‌ಆ್ಯಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಿ',
  'auth.viaVoice': 'ಕೋಡ್ ಹೇಳಲು ನನಗೆ ಕರೆ ಮಾಡಿ',
  'auth.resentVia.sms': 'SMS ಮೂಲಕ ಕಳುಹಿಸಲಾಗಿದೆ. ಬರಲು ಸ್ವಲ್ಪ ಸಮಯ ಹಿಡಿಯಬಹುದು.',
  'auth.resentVia.whatsapp': 'ವಾಟ್ಸ್‌ಆ್ಯಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಲಾಗಿದೆ. ಸಂದೇಶಕ್ಕಾಗಿ ವಾಟ್ಸ್‌ಆ್ಯಪ್ ನೋಡಿ.',
  'auth.resentVia.voice': 'ಕೋಡ್ ಹೇಳಲು ಈಗಲೇ ಕರೆ ಮಾಡುತ್ತಿದ್ದೇವೆ. ಕೇಳಲು ಕರೆ ಸ್ವೀಕರಿಸಿ.',
  'auth.resendIn': '{n} ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಮತ್ತೆ ಕಳುಹಿಸಿ',
  'auth.changeNumber': 'ಬೇರೆ ಸಂಖ್ಯೆ ಬಳಸಿ',
  'auth.change': 'ಬದಲಿಸಿ',

  'profile.complete': '{n}% ಪೂರ್ಣ',
  'profile.viewLede': 'ನೀವು ನಮಗೆ ಹೇಳಿದ್ದೆಲ್ಲ. ಯಾವುದೇ ಉತ್ತರವನ್ನು ಬದಲಿಸಿ, ಅಲ್ಲಿಂದ ಮುಂದೆ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನಕ್ಕೂ ಅದೇ ಬಳಕೆಯಾಗುತ್ತದೆ.',
  'profile.notAnswered': 'ಇನ್ನೂ ಉತ್ತರಿಸಿಲ್ಲ',
  'profile.verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  'profile.continue': 'ನಿಲ್ಲಿಸಿದಲ್ಲಿಂದ ಮುಂದುವರಿಸಿ',
  'profile.start': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆರಂಭಿಸಿ',
  'profile.saved': 'ಉಳಿಸಲಾಗಿದೆ',

  'match.title': 'ನಿಮಗಾಗಿ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು',
  'match.lede': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನೊಂದಿಗೆ ಹೊಂದಿಸಲಾಗಿದೆ. ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದಾದವು ಮೊದಲು.',
  'match.eligible': 'ನೀವು ಅರ್ಹರು',
  'match.likely': 'ನೀವು ಬಹುಶಃ ಅರ್ಹರು',
  'match.blocked': 'ಮೊದಲು ಒಂದು ಕೆಲಸ',
  'match.actionable': 'ನಿಮಗೆ ಮುಕ್ತ',
  'match.actionableHelp': 'ಕೆಲವಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ಒಂದು ದಾಖಲೆ ಬೇಕಾಗಬಹುದು.',
  'match.ineligible': 'ನಿಮಗೆ ಮುಕ್ತವಿಲ್ಲ',
  'match.eligibleHelp': 'ನಾವು ಪರಿಶೀಲಿಸಿದ್ದೆಲ್ಲವೂ ದೃಢಪಟ್ಟಿದೆ.',
  'match.likelyHelp': 'ನೀವು ಹೇಳಿದ್ದರ ಆಧಾರದ ಮೇಲೆ. ಪರಿಶೀಲಿಸಿಕೊಂಡರೆ ನಿಮ್ಮ ಅರ್ಜಿ ಬಲವಾಗುತ್ತದೆ.',
  'match.blockedHelp': 'ನೀವು ಹತ್ತಿರದಲ್ಲಿದ್ದೀರಿ. ಇದನ್ನು ಮಾಡಿದರೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು.',
  'match.ineligibleHelp': 'ನೀವು ಬದಲಿಸಲಾಗದ ಒಂದನ್ನು ಈ ಯೋಜನೆ ಕೇಳುತ್ತದೆ.',
  'match.apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'match.applied': 'ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ್ದೀರಿ',
  'match.none': 'ಇನ್ನೂ ಹೊಂದಾಣಿಕೆಗಳಿಲ್ಲ',
  'match.noneHint': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ, ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನವನ್ನೂ ನಿಮಗಾಗಿ ಪರಿಶೀಲಿಸುತ್ತೇವೆ.',
  'match.figQualify': 'ನೀವು ಅರ್ಹರು',
  'match.figStep': 'ಒಂದು ಹೆಜ್ಜೆ ದೂರ',
  'match.figClosing': 'ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುತ್ತದೆ',
  'match.figNo': 'ನಿಮಗೆ ಮುಕ್ತವಿಲ್ಲ',
  'match.filterLabel': 'ಯಾವ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ತೋರಿಸಬೇಕು',
  'match.filterAll': 'ಎಲ್ಲವೂ',
  'match.filterQualify': 'ನೀವು ಅರ್ಹರು',
  'match.filterStep': 'ಒಂದು ಹೆಜ್ಜೆ ದೂರ',
  'match.filterClosing': 'ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುತ್ತದೆ',
  'match.filterNo': 'ನಿಮಗೆ ಮುಕ್ತವಿಲ್ಲ',
  'match.filterEmpty': 'ಈ ಗುಂಪಿನಲ್ಲಿ ಏನೂ ಇಲ್ಲ. “ಎಲ್ಲವೂ” ನೋಡಿ.',
  'match.moreWithProfile': 'ನೀವು ತುಂಬುತ್ತಾ ಹೋದಂತೆ ಇನ್ನಷ್ಟು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಕಾಣಿಸುತ್ತವೆ.',
  'match.youQualify': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪ್ರಕಾರ ನೀವು ಷರತ್ತುಗಳನ್ನು ಪೂರೈಸುತ್ತೀರಿ.',
  'match.yesTitle': 'ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು',
  'match.blockedTitle': 'ಮೊದಲು ಒಂದು ಕೆಲಸ',
  'match.noTitle': 'ಅರ್ಹರಲ್ಲ',
  'match.appliedTitle': 'ಈಗಾಗಲೇ ಕಳುಹಿಸಲಾಗಿದೆ',
  'match.seeDetails': 'ನಿಯಮಗಳನ್ನು ನೋಡಿ',
  'match.learnMore': 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
  'match.runBy': '{kind} ನಡೆಸುತ್ತಿದೆ',
  'match.sortBy': 'ಕ್ರಮ',
  'match.sortRecommended': 'ಶಿಫಾರಸು ಮಾಡಿದವು',
  'match.sortClosing': 'ಮೊದಲು ಮುಗಿಯುವವು',
  'match.sortAward': 'ಅತಿ ದೊಡ್ಡ ಮೊತ್ತ',
  'match.applyAway': 'ಅವರ ಸೈಟ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'match.applyHere': 'ಇಲ್ಲಿಯೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'match.notOpenToYou': 'ಈಗಿನ ಸ್ಥಿತಿಯಲ್ಲಿ ನಿಮಗೆ ಮುಕ್ತವಿಲ್ಲ.',
  'match.working': 'ಈಗ ತೆರೆದಿರುವ ಯಾವ ಯೋಜನೆಯೂ ನೀವು ನೀಡಿದ ವಿವರಗಳಿಗೆ ಹೊಂದುತ್ತಿಲ್ಲ. ಪ್ರೊಫೈಲ್‌ಗೆ ಇನ್ನಷ್ಟು ಸೇರಿಸಿದರೆ ಇದು ಬದಲಾಗುತ್ತದೆ.',

  'doc.title': 'ನಿಮ್ಮ ದಾಖಲೆಗಳು',
  'doc.lede': 'ಒಂದು ದಾಖಲೆಯನ್ನು ಒಮ್ಮೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನವೂ ಅದನ್ನು ಬಳಸಬಹುದು — ನಿಮ್ಮನ್ನು ಮತ್ತೆ ಕೇಳುವುದಿಲ್ಲ.',
  'doc.upload': 'ದಾಖಲೆ ಸೇರಿಸಿ',
  'doc.type': 'ಇದು ಯಾವ ದಾಖಲೆ?',
  'doc.file': 'ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಿ',
  'doc.fileHint': 'PDF ಅಥವಾ ಸ್ಪಷ್ಟ ಫೋಟೋ. 10 MB ವರೆಗೆ.',
  'doc.verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  'doc.verifiedBy': '{org} ಪರಿಶೀಲಿಸಿದೆ',
  'doc.pending': 'ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
  'doc.expired': 'ಪರಿಶೀಲನೆಯ ಅವಧಿ ಮುಗಿದಿದೆ',
  'doc.expiring': '{n} ದಿನಗಳಲ್ಲಿ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ',
  'doc.validUntil': '{date} ವರೆಗೆ ಮಾನ್ಯ',
  'doc.none': 'ನೀವು ಇನ್ನೂ ಯಾವ ದಾಖಲೆಯನ್ನೂ ಸೇರಿಸಿಲ್ಲ',
  'doc.uploading': 'ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
  'doc.remove': 'ತೆಗೆದುಹಾಕಿ',
  'doc.removing': 'ತೆಗೆದುಹಾಕುತ್ತಿದೆ…',

  'apply.title': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'apply.consent': 'ನನ್ನ ವಿವರಗಳನ್ನು ಈ ಪೂರೈಕೆದಾರರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ',
  'apply.consentBody': 'ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಲು ಈ ವಿದ್ಯಾರ್ಥಿವೇತನಕ್ಕೆ ಬೇಕಾದದ್ದನ್ನು ಮಾತ್ರ ಅವರು ನೋಡುತ್ತಾರೆ: {fields}. ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಯಾರು ನೋಡಿದರು ಎಂಬುದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ನೋಡಬಹುದು.',
  'apply.consentBodyNoDocs': 'ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಲು ಈ ವಿದ್ಯಾರ್ಥಿವೇತನಕ್ಕೆ ಬೇಕಾದದ್ದನ್ನು ಮಾತ್ರ ಅವರು ನೋಡುತ್ತಾರೆ, ಬೇರೇನೂ ಅಲ್ಲ. ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಯಾರು ನೋಡಿದರು ಎಂಬುದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ನೋಡಬಹುದು.',
  'apply.submit': 'ನನ್ನ ಅರ್ಜಿಯನ್ನು ಕಳುಹಿಸಿ',
  'apply.submitting': 'ಕಳುಹಿಸುತ್ತಿದೆ…',
  'apply.blocked': 'ನೀವು ಇನ್ನೂ ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗದು',
  'apply.needProfile': 'ಮೊದಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
  'apply.needProfileHint': 'ಅರ್ಜಿ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಿಂದಲೇ ಕಳುಹಿಸಲ್ಪಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಅರ್ಜಿಗೆ ಮೊದಲು ಅದು ಬೇಕು. ಇದಕ್ಕೆ ಕೆಲವೇ ನಿಮಿಷ ಸಾಕು, ನೀವು ಈಗಾಗಲೇ ಹೇಳಿದ್ದೆಲ್ಲ ತುಂಬಿರುತ್ತದೆ.',
  'apply.elsewhereTitle': 'ಇದಕ್ಕೆ ಪ್ರಾಯೋಜಕರ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಬೇಕು',
  'apply.elsewhereBody': 'ನೀವು ಹುಡುಕಲು ಸಾಧ್ಯವಾಗಲೆಂದೇ ನಾವು ಈ ವಿದ್ಯಾರ್ಥಿವೇತನವನ್ನು ಪಟ್ಟಿ ಮಾಡುತ್ತೇವೆ, ಅರ್ಜಿಗಳನ್ನು ಪ್ರಾಯೋಜಕರೇ ಸ್ವೀಕರಿಸುತ್ತಾರೆ. ನೀವು ನಮಗೆ ಹೇಳಿದ್ದೆಲ್ಲ ಉಳಿದಿರುತ್ತದೆ, ನಾವು ನಡೆಸುವ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ ಅದು ಮೊದಲೇ ತುಂಬಿರುತ್ತದೆ.',
  'apply.elsewhereBodyPartner': 'ಈ ವಿದ್ಯಾರ್ಥಿವೇತನ ಇಲ್ಲಿಯೇ ನಡೆಯುತ್ತದೆ, ಆದರೆ ಪ್ರಾಯೋಜಕರು ಅರ್ಜಿಗಳನ್ನು ತಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲೇ ಸ್ವೀಕರಿಸುತ್ತಾರೆ. ನೀವು ನಮಗೆ ಹೇಳಿದ್ದೆಲ್ಲ ಉಳಿದಿರುತ್ತದೆ, ನಮಗೆ ನೇರವಾಗಿ ಬರುವ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ ಅದು ಮೊದಲೇ ತುಂಬಿರುತ್ತದೆ.',
  'apply.bundleTitle': 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಜೊತೆಗೆ ಕೊಂಡೊಯ್ಯಿರಿ',
  'apply.bundleBody': 'ಈ ವಿದ್ಯಾರ್ಥಿವೇತನ ಕೇಳುವ ದಾಖಲೆಗಳನ್ನು ಒಂದೇ ಫೈಲ್‌ನಲ್ಲಿ ಸೇರಿಸಿ ಕೊಡಬಲ್ಲೆವು, ಅವರ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಸಿದ್ಧವಾಗಿ. ಅವರು ಕೇಳುವ, ನಮ್ಮ ಬಳಿ ಇನ್ನೂ ಇಲ್ಲದವುಗಳನ್ನೂ ಅದು ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ.',
  'apply.bundleAction': 'ನನ್ನ ದಾಖಲೆಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  'apply.bundleWorking': 'ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ…',
  'apply.bundleDone': 'ನಿಮ್ಮ ದಾಖಲೆಗಳು ಡೌನ್‌ಲೋಡ್ ಆಗಿವೆ.',
  'apply.docs': 'ಈ ವಿದ್ಯಾರ್ಥಿವೇತನಕ್ಕೆ ಬೇಕಾದ ದಾಖಲೆಗಳು',

  'appl.title': 'ನಿಮ್ಮ ಅರ್ಜಿಗಳು',
  'appl.none': 'ನೀವು ಇನ್ನೂ ಯಾವುದಕ್ಕೂ ಅರ್ಜಿ ಸಲ್ಲಿಸಿಲ್ಲ',
  'appl.noneHint': 'ನೀವು ಅರ್ಹರಾಗಿರುವ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕಲು ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಿ.',
  'appl.reference': 'ಉಲ್ಲೇಖ',
  'appl.whatNext': 'ಮುಂದೇನಾಗುತ್ತದೆ',
  'appl.history': 'ಇತಿಹಾಸ',
  'appl.needsYou': 'ಅವರಿಗೆ ನಿಮ್ಮಿಂದ ಏನೋ ಬೇಕು',
  'track.label': 'ಈ ಅರ್ಜಿಯ ಪ್ರಗತಿ',
  'track.sent': 'ಕಳುಹಿಸಲಾಗಿದೆ',
  'track.review': 'ಪರಿಶೀಲನೆ',
  'track.decision': 'ನಿರ್ಧಾರ',
  'track.doneSr': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
  'track.currentSr': 'ಈಗ ನಡೆಯುತ್ತಿದೆ',
  'track.todoSr': 'ಆರಂಭವಾಗಿಲ್ಲ',
  'appl.sentOn': '{when} ಕಳುಹಿಸಲಾಗಿದೆ',
  'appl.decidedOn': '{when} ನಿರ್ಧರಿಸಲಾಗಿದೆ',
  'appl.outcomeApproved': 'ದೊರೆತಿದೆ',
  'appl.outcomeRejected': 'ಈ ಬಾರಿ ದೊರೆಯಲಿಲ್ಲ',
  'appl.outcomeWithdrawn': 'ನೀವು ಇದನ್ನು ಹಿಂಪಡೆದಿದ್ದೀರಿ',
  'appl.inProgress': 'ಪೂರೈಕೆದಾರರ ಬಳಿ',
  'appl.outcome': 'ಫಲಿತಾಂಶ',
  'appl.award': 'ಮೊತ್ತ',
  'appl.applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
  'appl.decided': 'ನಿರ್ಧರಿಸಲಾಗಿದೆ',
  'appl.automatic': 'ಸ್ವಯಂಚಾಲಿತ',
  'appl.noHistory': 'ಇನ್ನೂ ಏನೂ ನಡೆದಿಲ್ಲ.',

  'ref.heading': 'ಅವರ ವೆಬ್‌ಸೈಟ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
  'ref.blurb': 'ಇವುಗಳಿಗೆ ಪೂರೈಕೆದಾರರ ಸ್ವಂತ ಸೈಟ್‌ನಲ್ಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಬೇಕು, ಆದ್ದರಿಂದ ಏನಾಯಿತೆಂದು ನಮಗೆ ಕಾಣಿಸುವುದಿಲ್ಲ. ನಮಗೆ ತಿಳಿಸಿ, ಉಳಿದವುಗಳೊಂದಿಗೆ ಇಟ್ಟುಕೊಳ್ಳುತ್ತೇವೆ.',
  'ref.sentOn': 'ನೀವು ಇದನ್ನು {when} ತೆರೆದಿರಿ',
  'ref.again': 'ಒಟ್ಟು {times} ಬಾರಿ',
  'ref.open': 'ಅವರ ಸೈಟ್ ಮತ್ತೆ ತೆರೆಯಿರಿ',
  'ref.what': 'ಏನಾಯಿತು?',
  'ref.APPLIED': 'ನಾನು ಅರ್ಜಿ ಸಲ್ಲಿಸಿದೆ',
  'ref.AWARDED': 'ನನಗೆ ದೊರೆಯಿತು',
  'ref.NOT_AWARDED': 'ನನಗೆ ದೊರೆಯಲಿಲ್ಲ',
  'ref.DID_NOT_APPLY': 'ನಾನು ಅರ್ಜಿ ಸಲ್ಲಿಸಲಿಲ್ಲ',
  'ref.saidAPPLIED': 'ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸಿದಿರಿ',
  'ref.saidAWARDED': 'ನಿಮಗೆ ದೊರೆಯಿತು',
  'ref.saidNOT_AWARDED': 'ನಿಮಗೆ ದೊರೆಯಲಿಲ್ಲ',
  'ref.saidDID_NOT_APPLY': 'ನೀವು ಅರ್ಜಿ ಸಲ್ಲಿಸಲಿಲ್ಲ',
  'ref.youSaid': 'ನೀವು ನಮಗೆ ಹೇಳಿದ್ದು: {what}',
  'ref.change': 'ಬದಲಿಸಿ',

  'privacy.title': 'ನಿಮ್ಮ ಮಾಹಿತಿ',
  'privacy.lede': 'ನಮ್ಮ ಬಳಿ ಏನಿದೆ, ಯಾರು ನೋಡಿದ್ದಾರೆ, ಅದನ್ನು ಹಿಂಪಡೆಯುವುದು ಹೇಗೆ.',
  'privacy.access': 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಯಾರು ನೋಡಿದ್ದಾರೆ',
  'privacy.accessNone': 'ನಿಮ್ಮ ಸ್ವಂತ ಖಾತೆಯ ಹೊರಗೆ ಯಾರೂ ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ತೆರೆದಿಲ್ಲ.',
  'privacy.consents': 'ಹಂಚಿಕೊಳ್ಳಲು ನೀವು ಒಪ್ಪಿದ್ದು',
  'privacy.withdraw': 'ಹಿಂಪಡೆಯಿರಿ',
  'privacy.withdrawing': 'ಹಿಂಪಡೆಯುತ್ತಿದೆ…',
  'privacy.export': 'ನಮ್ಮ ಬಳಿ ಇರುವುದೆಲ್ಲವನ್ನೂ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  'privacy.exporting': 'ನಿಮ್ಮ ಪ್ರತಿಯನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ…',
  'privacy.exportBody': 'ನಿಮ್ಮ ಮಾಹಿತಿಯ ಸಂಪೂರ್ಣ, ಯಂತ್ರ-ಓದಬಲ್ಲ ಪ್ರತಿ.',
  'privacy.erase': 'ನನ್ನ ಮಾಹಿತಿಯನ್ನು ಅಳಿಸಿ',
  'privacy.erasing': 'ವಿನಂತಿಸುತ್ತಿದೆ…',
  'privacy.eraseBody': 'ನಿಮಗೆ ಪಾವತಿಸಿದ ಯಾವುದೇ ವಿದ್ಯಾರ್ಥಿವೇತನದ ದಾಖಲೆಗಳನ್ನು ನಾವು ಇಟ್ಟುಕೊಳ್ಳಲೇಬೇಕು. ಉಳಿದೆಲ್ಲವನ್ನೂ ತೆಗೆದುಹಾಕಲಾಗುತ್ತದೆ.',
  'auth.closedTitle': 'ನಿಮ್ಮ ಖಾತೆ ಸದ್ಯಕ್ಕೆ ಮುಚ್ಚಲಾಗಿದೆ.',
  'auth.closedHelp': 'ಸಹಾಯ ಬೇಕೇ? ನಮ್ಮ ಬೆಂಬಲ ತಂಡ ನಿಮಗೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಬಲ್ಲದು ',
  'auth.closedSoon': 'ಬೆಂಬಲ ಕೋರಿ (ಶೀಘ್ರದಲ್ಲೇ)',
  'reg.district': 'ಜಿಲ್ಲೆ',
  'reg.districtHint': 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ನಡೆಯುವ ಯೋಜನೆಗಳಿಗೆ ಹೊಂದಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
  'privacy.requested': 'ವಿನಂತಿಸಲಾಗಿದೆ',
  'privacy.window': 'ಇನ್ನೂ ಏನೂ ಅಳಿಸಲಾಗಿಲ್ಲ',
  'privacy.windowBody': 'ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು {date} ರಂದು ಅಳಿಸಲಾಗುತ್ತದೆ. ಅಲ್ಲಿಯವರೆಗೆ ನೀವು ',
  'privacy.cancel': 'ಈ ವಿನಂತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ',
  'privacy.cancelling': 'ರದ್ದುಗೊಳಿಸುತ್ತಿದೆ…',
  'privacy.cancelled': 'ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ಏನೂ ಅಳಿಸಲಾಗಿಲ್ಲ.',

  'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ',
  'common.retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  'common.required': 'ಅಗತ್ಯ',
  'common.optional': 'ಐಚ್ಛಿಕ',
  'common.error': 'ಏನೋ ತಪ್ಪಾಯಿತು',
  'common.offline': 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ. ನಿಮ್ಮ ಕೆಲಸ ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ.',

  'slides.lead.was': '',
  'slides.lead.able': 'ಸಾಮರ್ಥ್ಯದಿಂದ',
  'slides.lead.dist': 'ವಿಶಿಷ್ಟತೆಯವರೆಗೆ',
  'slides.lead.body': 'ನೀವು ಅರ್ಹರಾಗಿರುವ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನ — ಸರ್ಕಾರಿ ಮತ್ತು ಖಾಸಗಿ — ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದಿಸಿ, ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ, ಒಂದೇ ಕಡೆ.',
  'slides.lead.free': 'ಸಂಪೂರ್ಣ ಉಚಿತ',
  'slides.lead.languages': '14 ಭಾಷೆಗಳು',
  'slides.lead.support': 'ಪ್ರತಿ ಹೆಜ್ಜೆಯಲ್ಲೂ ವೈಯಕ್ತಿಕ ನೆರವು',
  'slides.label': 'ಪ್ರಕಟಣೆಗಳು',
  'slides.position': '{total} ರಲ್ಲಿ {n}',
  'slides.goto': '{name} ತೋರಿಸಿ',
  'slides.watch': 'ವಿಡಿಯೊ ನೋಡಿ',
  'slides.external': 'ಬೇರೊಂದು ವೆಬ್‌ಸೈಟ್ ತೆರೆಯುತ್ತದೆ',

  'home.title': 'ವಿಕಲಚೇತನ ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು, ಒಂದೇ ಕಡೆ',
  'home.lede': 'ನಿಮ್ಮ ಬಗ್ಗೆ ಒಮ್ಮೆ ಹೇಳಿ. ಇಲ್ಲಿನ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನದೊಂದಿಗೆ ನಿಮ್ಮನ್ನು ಪರಿಶೀಲಿಸಿ, ನೀವು ಯಾವುದಕ್ಕೆ ಅರ್ಹರೆಂದು ಹೇಳುತ್ತೇವೆ — ಉಳಿದವುಗಳಿಗೆ ನಿಖರವಾಗಿ ಏನು ಕೊರತೆಯೆಂದೂ ಹೇಳುತ್ತೇವೆ.',
  'home.search': 'ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕಿ',
  'home.searchPlaceholder': 'ಉದಾ: ಇಂಜಿನಿಯರಿಂಗ್, ದೆಹಲಿ, ಪೋಸ್ಟ್-ಮೆಟ್ರಿಕ್',
  'home.searchGo': 'ಹುಡುಕಿ',
  'home.browseAll': 'ಎಲ್ಲ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ನೋಡಿ',
  'home.openNow': 'ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಈಗ ತೆರೆದಿವೆ',
  'home.noAccount': 'ನೋಡಲು ಖಾತೆ ಬೇಕಿಲ್ಲ.',
  'home.openNone': 'ಇಲ್ಲಿ ಇನ್ನೂ ಯಾವ ವಿದ್ಯಾರ್ಥಿವೇತನವೂ ಪಟ್ಟಿಯಾಗಿಲ್ಲ.',
  'home.openNoneBody': 'ಪಟ್ಟಿಯನ್ನು ಈಗ ತುಂಬಲಾಗುತ್ತಿದೆ. ಇಲ್ಲಿ ಯಾವುದೂ ಖಾತೆಯ ಹಿಂದೆ ಇಲ್ಲ — ಯೋಜನೆಗಳು ಪಟ್ಟಿಯಾದ ಮೇಲೆ ಸೈನ್ ಇನ್ ಮಾಡದೆಯೇ ನೋಡಬಹುದು.',
  'home.how': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
  'home.howLede': 'ನೋಂದಣಿಗೆ ಒಂದು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಮತ್ತು ಅದಕ್ಕೆ ನಾವು ಕಳುಹಿಸುವ ಕೋಡ್ ಸಾಕು. ಪಾಸ್‌ವರ್ಡ್ ಇಲ್ಲ, ಮೊದಲು ತುಂಬಬೇಕಾದ ಸೈನ್-ಅಪ್ ನಮೂನೆಯೂ ಇಲ್ಲ.',
  'home.step1': 'ನೋಂದಣಿ ಒತ್ತಿ',
  'home.step1Body': 'ಈ ಪುಟದ ಮೇಲ್ಭಾಗದಲ್ಲಿ. ಮೊದಲು ಬಂದಿದ್ದರೆ ಪಕ್ಕದ ಲಾಗಿನ್ ಬಳಸಿ — ಎರಡರಲ್ಲೂ ಅದೇ ಸಂಖ್ಯೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
  'home.step2': 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'home.step2Body': 'ಹತ್ತು ಅಂಕಿಗಳು, +91 ಮೊದಲೇ ತುಂಬಿರುತ್ತದೆ. ಆ ಸಂಖ್ಯೆಗೆ 6 ಅಂಕಿಯ ಕೋಡ್ ಹೋಗುತ್ತದೆ.',
  'home.step3': 'ಕೋಡ್ ನಮೂದಿಸಿ',
  'home.step3Body': 'ಆರು ಅಂಕಿಗಳನ್ನು ಟೈಪ್ ಮಾಡಿದರೆ ಒಳಗೆ ಬಂದಿರುತ್ತೀರಿ. ಸಂದೇಶ ಬರದಿದ್ದರೆ ಕೋಡ್ ಅನ್ನು ವಾಟ್ಸ್‌ಆ್ಯಪ್‌ನಲ್ಲಿ ಕೇಳಿ, ಅಥವಾ ನಾವು ಕರೆ ಮಾಡಿ ಓದಿ ಹೇಳುವಂತೆ ಹೇಳಿ.',
  'home.step4': 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ತುಂಬಿ',
  'home.step4Body': 'ನಿಮ್ಮ ಹೆಸರು, ನಿಮ್ಮ ಪ್ರಮಾಣಪತ್ರ ಮತ್ತು ನೀವು ಎಲ್ಲಿ ಓದುತ್ತಿದ್ದೀರಿ — ಒಂದೊಂದೇ ಪ್ರಶ್ನೆ, ಪ್ರತಿ ಉತ್ತರವೂ ನೀಡಿದ ಕೂಡಲೇ ಉಳಿಸಲ್ಪಡುತ್ತದೆ.',
  'home.step5': 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'home.step5Body': 'ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರ, UDID ಕಾರ್ಡ್, ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ ಮತ್ತು ಉಳಿದವು. ಪ್ರತಿಯೊಂದೂ ಒಮ್ಮೆ ಮಾತ್ರ, ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿವೇತನಕ್ಕೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಅಲ್ಲ.',
  'home.step6': 'ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಿ',
  'home.step6Body': 'ನನ್ನ ಹೊಂದಾಣಿಕೆಗಳು ನೀವು ಅರ್ಹರಾಗಿರುವ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ — ಯಾವುದಾದರೂ ನಿಮಗೆ ಮುಚ್ಚಿದ್ದರೆ ಏಕೆಂದೂ ಹೇಳುತ್ತದೆ.',
  'home.step7': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  'home.step7Body': 'ಬೇಕಾದವುಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. ನಿಮ್ಮ ವಿವರಗಳು ಮತ್ತು ದಾಖಲೆಗಳು ಅರ್ಜಿಯೊಂದಿಗೆ ಹೋಗುತ್ತವೆ.',
  'home.assure': 'ತಿಳಿದಿರಲಿ',
  'home.assure1': 'ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು ಪಾಸ್‌ವರ್ಡ್ ಇಲ್ಲ',
  'home.assure2': 'ಪ್ರತ್ಯೇಕ ನೋಂದಣಿ ನಮೂನೆ ಇಲ್ಲ',
  'home.assure3': 'ನಿಲ್ಲಿಸಿ ನಂತರ ಪೂರ್ಣಗೊಳಿಸಬಹುದು',
  'home.help': 'ಯಾವುದಾದರೂ ಹಂತದಲ್ಲಿ ಸಿಕ್ಕಿಕೊಂಡಿರಾ?',
  'home.helpBody': 'ಕರೆ ಮಾಡಿ, ಯಾರಾದರೂ ನಿಮಗೆ ದಾರಿ ತೋರಿಸುತ್ತಾರೆ.',
  'home.helpCall': '{number} ಗೆ ಕರೆ ಮಾಡಿ',
  'home.closing': 'ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯುತ್ತದೆ',
  'home.closingLede': 'ಮೊದಲು ಇವುಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
  'home.closingNext': 'ಮುಂದಿನ ಕೊನೆಯ ದಿನಾಂಕಗಳು',
  'home.closingNextLede': 'ಮೊದಲು ಮುಗಿಯುವ ಮೂರು.',
  'home.allDeadlines': 'ಎಲ್ಲ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ನೋಡಿ',
  'home.browse': 'ಇದರ ಪ್ರಕಾರ ನೋಡಿ',
  'home.browseWho': 'ಯಾರು ನೀಡುತ್ತಾರೆ',
  'home.browseLevel': 'ನಿಮ್ಮ ಓದಿನ ಹಂತ',
  'home.cta': 'ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಲು ಸಿದ್ಧರೇ?',
  'home.ctaBody': 'ಖಾತೆ ಸೃಷ್ಟಿಸಲು ಒಂದು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಇಮೇಲ್ ವಿಳಾಸ ಸಾಕು. ಬೇರೇನೂ ಅಲ್ಲ.',
  'home.ctaButton': 'ಖಾತೆ ಸೃಷ್ಟಿಸಿ',
  'home.signedInCta': 'ನೀವು ಯಾವುದಕ್ಕೆ ಅರ್ಹರೆಂದು ನೋಡಿ',

  'reg.title': 'ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕಲು ನೋಂದಾಯಿಸಿ',
  'reg.editTitle': 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ',
  'reg.requiredNote': '* ಗುರುತಿರುವ ಎಲ್ಲ ಕ್ಷೇತ್ರಗಳೂ ಅಗತ್ಯ.',
  'reg.personal': 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
  'reg.disability': 'ವಿಕಲಚೇತನ ವಿವರಗಳು',
  'reg.education': 'ಶಿಕ್ಷಣ ವಿವರಗಳು',
  'reg.name': 'ಪೂರ್ಣ ಹೆಸರು',
  'reg.namePlaceholder': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
  'reg.phoneHint': 'ಈ ಸಂಖ್ಯೆಗೆ 6 ಅಂಕಿಯ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ. ಪ್ರತಿ ಬಾರಿಯೂ ಇದೇ ಸಂಖ್ಯೆ ನಿಮ್ಮನ್ನು ಸೈನ್ ಇನ್ ಮಾಡಿಸುತ್ತದೆ.',
  'reg.sendOtp': 'OTP ಕಳುಹಿಸಿ',
  'reg.otpPlaceholder': '6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
  'reg.verified': 'ಫೋನ್ ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  'reg.verifyFirst': 'ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಲು ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.',
  'reg.email': 'ಇಮೇಲ್',
  'reg.emailHint': 'ಕೊನೆಯ ದಿನಾಂಕವನ್ನು ನೆನಪಿಸಲು. ಇದನ್ನು ನಾವು ಎಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'ಲಿಂಗ',
  'reg.genderHint': '(ಕೆಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಮಹಿಳಾ ಅಥವಾ ತೃತೀಯಲಿಂಗಿ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮಾತ್ರ)',
  'reg.udid': 'UDID ಸಂಖ್ಯೆ',
  'reg.udidHint': 'ನಿಮ್ಮ UDID (ವಿಶಿಷ್ಟ ವಿಕಲಚೇತನ ಗುರುತು) ಕಾರ್ಡ್‌ನಲ್ಲಿರುವ ಸಂಖ್ಯೆ.',
  'reg.udidPlaceholder': 'ನಿಮ್ಮ UDID ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'reg.certificate': 'UDID ಪ್ರಮಾಣಪತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'reg.certificateHint': 'PDF ಅಥವಾ ಚಿತ್ರ, 5 MB ಅಥವಾ ಅದಕ್ಕಿಂತ ಕಡಿಮೆ.',
  'reg.fileType': 'ಆ ಫೈಲ್ PDF, JPEG ಅಥವಾ PNG ಆಗಿರಬೇಕು.',
  'reg.fileSize': 'ಆ ಫೈಲ್ 5 MB ಗಿಂತ ದೊಡ್ಡದು. ಫೋನ್‌ನಲ್ಲಿ ತೆಗೆದ ಚಿತ್ರವನ್ನು ಫೋಟೋ ತೆಗೆಯುವ ಬದಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿದರೆ ಸಾಮಾನ್ಯವಾಗಿ ಚಿಕ್ಕದಾಗಿರುತ್ತದೆ.',
  'reg.fileLater': 'ನಿಮ್ಮ ನೋಂದಣಿಯಾಗಿದೆ ಮತ್ತು ವಿವರಗಳು ಉಳಿಸಲ್ಪಟ್ಟಿವೆ. ಪ್ರಮಾಣಪತ್ರ ಅಪ್‌ಲೋಡ್ ಆಗಲಿಲ್ಲ — ನನ್ನ ದಾಖಲೆಗಳಿಂದ ಸೇರಿಸಿ, ಬೇರೇನನ್ನೂ ಮತ್ತೆ ಮಾಡಬೇಕಿಲ್ಲ.',
  'reg.disabilityType': 'ವಿಕಲಚೇತನದ ಬಗೆ',
  'reg.percent': 'ವಿಕಲಚೇತನದ ಶೇಕಡಾವಾರು',
  'reg.percentHint': 'ನಿಮ್ಮ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿರುವ ಸಂಖ್ಯೆ. ಹಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ 40% ಅಥವಾ ಹೆಚ್ಚು ಬೇಕು.',
  'reg.percentPlaceholder': 'ಉದಾ. 40',
  'reg.percentRange': 'ಪ್ರಮಾಣಪತ್ರದ ಶೇಕಡಾವಾರು 0 ಮತ್ತು 100 ನಡುವಿನ ಪೂರ್ಣಸಂಖ್ಯೆ.',
  'reg.state': 'ರಾಜ್ಯ',
  'reg.statePlaceholder': 'ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಹುಡುಕಲು ಟೈಪ್ ಮಾಡಿ…',
  'reg.program': 'ನಿಮ್ಮ ಕೋರ್ಸ್ ಆಯ್ಕೆ ಮಾಡಿ',
  'reg.graduation': 'ಪದವಿ',
  'reg.postgraduation': 'ಸ್ನಾತಕೋತ್ತರ / ಮಾಸ್ಟರ್ಸ್',
  'reg.year': 'ವರ್ಷ ಆಯ್ಕೆ ಮಾಡಿ',
  'reg.yearAfterProgram': 'ಮೊದಲು ನಿಮ್ಮ ಕೋರ್ಸ್ ಆಯ್ಕೆ ಮಾಡಿ',
  'reg.institution': 'ಶಾಲೆ / ಕಾಲೇಜಿನ ಹೆಸರು',
  'reg.institutionPlaceholder': 'ನಿಮ್ಮ ಸಂಸ್ಥೆಯ ಹೆಸರು ನಮೂದಿಸಿ',
  'reg.required': 'ಇದು ಬೇಕು.',
  'reg.fix': 'ಕೆಲವು ಉತ್ತರಗಳಿಗೆ ಗಮನ ಬೇಕು. ಮೊದಲನೆಯದು ಕೆಳಗೆ ಆಯ್ಕೆಯಾಗಿದೆ.',
  'reg.cta': 'ನೋಂದಾಯಿಸಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕಿ',
  'reg.saveChanges': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
  'reg.saving': 'ಉಳಿಸುತ್ತಿದೆ…',
  'reg.done': 'ನೋಂದಣಿಯಾಗಿದೆ. ನಿಮ್ಮ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇವೆ.',
  'reg.doneTitle': 'ನಿಮ್ಮ ನೋಂದಣಿಯಾಗಿದೆ',
  'reg.already': 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿದ್ದೀರಾ?',
  'reg.login': 'OTP ಮೂಲಕ ಲಾಗಿನ್',
  'nav.registerCta': 'ನೋಂದಣಿ',
  'nav.loginCta': 'ಲಾಗಿನ್',
  'profile.edit': 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ',
  'field.disability.BLINDNESS': 'ಅಂಧತ್ವ',
  'field.disability.LOW_VISION': 'ಕಡಿಮೆ ದೃಷ್ಟಿ',
  'field.disability.LEPROSY_CURED': 'ಕುಷ್ಠರೋಗ (ಗುಣವಾಗಿದೆ)',
  'field.disability.HEARING_IMPAIRMENT': 'ಶ್ರವಣ ದೋಷ',
  'field.disability.LOCOMOTOR_DISABILITY': 'ಚಲನ ವಿಕಲಚೇತನ',
  'field.disability.DWARFISM': 'ಕುಬ್ಜತೆ',
  'field.disability.INTELLECTUAL_DISABILITY': 'ಬೌದ್ಧಿಕ ವಿಕಲಚೇತನ',
  'field.disability.MENTAL_ILLNESS': 'ಮಾನಸಿಕ ಅಸ್ವಸ್ಥತೆ',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ಸ್ವಲೀನತೆ (ಆಟಿಸಂ) ಸ್ಪೆಕ್ಟ್ರಮ್ ಅಸ್ವಸ್ಥತೆ',
  'field.disability.CEREBRAL_PALSY': 'ಸೆರೆಬ್ರಲ್ ಪಾಲ್ಸಿ',
  'field.disability.MUSCULAR_DYSTROPHY': 'ಸ್ನಾಯು ಕ್ಷೀಣತೆ',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'ದೀರ್ಘಕಾಲಿಕ ನರವೈಜ್ಞಾನಿಕ ಸ್ಥಿತಿ',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'ನಿರ್ದಿಷ್ಟ ಕಲಿಕಾ ವಿಕಲಚೇತನ',
  'field.disability.MULTIPLE_SCLEROSIS': 'ಮಲ್ಟಿಪಲ್ ಸ್ಕ್ಲೆರೋಸಿಸ್',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'ಮಾತು ಮತ್ತು ಭಾಷಾ ವಿಕಲಚೇತನ',
  'field.disability.THALASSEMIA': 'ಥಲಸ್ಸೇಮಿಯಾ',
  'field.disability.HAEMOPHILIA': 'ಹಿಮೋಫಿಲಿಯಾ',
  'field.disability.SICKLE_CELL_DISEASE': 'ಸಿಕಲ್ ಸೆಲ್ ಕಾಯಿಲೆ',
  'field.disability.MULTIPLE_DISABILITIES': 'ಬಹು ವಿಕಲಚೇತನಗಳು, ಕಿವುಡು-ಕುರುಡುತನ ಸೇರಿದಂತೆ',
  'field.disability.ACID_ATTACK_VICTIM': 'ಆ್ಯಸಿಡ್ ದಾಳಿಯಿಂದ ಪಾರಾದವರು',
  'field.disability.PARKINSONS_DISEASE': 'ಪಾರ್ಕಿನ್ಸನ್ಸ್ ಕಾಯಿಲೆ',

  'field.state.AN': 'ಅಂಡಮಾನ್ ಮತ್ತು ನಿಕೋಬಾರ್ ದ್ವೀಪಗಳು',
  'field.state.AP': 'ಆಂಧ್ರಪ್ರದೇಶ',
  'field.state.AR': 'ಅರುಣಾಚಲ ಪ್ರದೇಶ',
  'field.state.AS': 'ಅಸ್ಸಾಂ',
  'field.state.BR': 'ಬಿಹಾರ',
  'field.state.CH': 'ಚಂಡೀಗಢ',
  'field.state.CT': 'ಛತ್ತೀಸ್‌ಗಢ',
  'field.state.DL': 'ದೆಹಲಿ',
  'field.state.DN': 'ದಾದ್ರಾ ಮತ್ತು ನಗರ ಹವೇಲಿ ಮತ್ತು ದಮನ್ ಮತ್ತು ದಿಯು',
  'field.state.GA': 'ಗೋವಾ',
  'field.state.GJ': 'ಗುಜರಾತ್',
  'field.state.HP': 'ಹಿಮಾಚಲ ಪ್ರದೇಶ',
  'field.state.HR': 'ಹರಿಯಾಣ',
  'field.state.JH': 'ಜಾರ್ಖಂಡ್',
  'field.state.JK': 'ಜಮ್ಮು ಮತ್ತು ಕಾಶ್ಮೀರ',
  'field.state.KA': 'ಕರ್ನಾಟಕ',
  'field.state.KL': 'ಕೇರಳ',
  'field.state.LA': 'ಲಡಾಖ್',
  'field.state.LD': 'ಲಕ್ಷದ್ವೀಪ',
  'field.state.MH': 'ಮಹಾರಾಷ್ಟ್ರ',
  'field.state.ML': 'ಮೇಘಾಲಯ',
  'field.state.MN': 'ಮಣಿಪುರ',
  'field.state.MP': 'ಮಧ್ಯಪ್ರದೇಶ',
  'field.state.MZ': 'ಮಿಜೋರಾಂ',
  'field.state.NL': 'ನಾಗಾಲ್ಯಾಂಡ್',
  'field.state.OR': 'ಒಡಿಶಾ',
  'field.state.PB': 'ಪಂಜಾಬ್',
  'field.state.PY': 'ಪುದುಚೇರಿ',
  'field.state.RJ': 'ರಾಜಸ್ಥಾನ',
  'field.state.SK': 'ಸಿಕ್ಕಿಂ',
  'field.state.TG': 'ತೆಲಂಗಾಣ',
  'field.state.TN': 'ತಮಿಳುನಾಡು',
  'field.state.TR': 'ತ್ರಿಪುರ',
  'field.state.UP': 'ಉತ್ತರ ಪ್ರದೇಶ',
  'field.state.UT': 'ಉತ್ತರಾಖಂಡ',
  'field.state.WB': 'ಪಶ್ಚಿಮ ಬಂಗಾಳ',

  'field.level.SCHOOL': 'ಶಾಲೆ',
  'field.level.SCHOOL.sub': '9, 10, 11, 12ನೇ ತರಗತಿ',
  'field.level.UNDERGRADUATE': 'ಪದವಿ',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech ಮುಂತಾದವು',
  'field.level.POSTGRADUATE': 'ಸ್ನಾತಕೋತ್ತರ',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech ಮುಂತಾದವು',
  'field.level.DOCTORAL': 'ಡಾಕ್ಟರೇಟ್',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'ಶಾಲೆ',
  'field.qual.SCHOOL.sub': '1ರಿಂದ 12ನೇ ತರಗತಿ',
  'field.qual.UNDERGRADUATE': 'ಪದವಿ',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — ಮತ್ತು ಡಿಪ್ಲೊಮಾ ಅಥವಾ ITI',
  'field.qual.POSTGRADUATE': 'ಸ್ನಾತಕೋತ್ತರ ಪದವಿ',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA ಮುಂತಾದವು',
  'field.qual.DOCTORAL': 'PhD / ಡಾಕ್ಟರೇಟ್',

  'field.subject.engineering': 'ಇಂಜಿನಿಯರಿಂಗ್',
  'field.subject.medical': 'ವೈದ್ಯಕೀಯ',
  'field.subject.management': 'ನಿರ್ವಹಣೆ',
  'field.subject.science': 'ವಿಜ್ಞಾನ',
  'field.subject.commerce': 'ವಾಣಿಜ್ಯ',
  'field.subject.arts': 'ಕಲೆ ಮತ್ತು ಮಾನವಿಕ',
  'field.subject.vocational': 'ವೃತ್ತಿಪರ',
  'field.subject.fellowship': 'ಫೆಲೋಶಿಪ್',
  'field.subject.talent': 'ಪ್ರತಿಭೆ',
  'field.subject.sports': 'ಕ್ರೀಡೆ',

  'field.gender.FEMALE': 'ಮಹಿಳೆ',
  'field.gender.MALE': 'ಪುರುಷ',
  'field.gender.TRANSGENDER': 'ತೃತೀಯಲಿಂಗಿ',
  'field.gender.UNDISCLOSED': 'ಹೇಳಲು ಇಷ್ಟವಿಲ್ಲ',
  'field.genderFilter.TRANSGENDER': 'ಮೂರನೇ ಲಿಂಗ / ತೃತೀಯಲಿಂಗಿ',

  'field.year.below9': '9ನೇ ತರಗತಿಗಿಂತ ಕೆಳಗೆ',
  'field.year.c9': '9ನೇ ತರಗತಿ',
  'field.year.c10': '10ನೇ ತರಗತಿ',
  'field.year.c11': '11ನೇ ತರಗತಿ',
  'field.year.c12': '12ನೇ ತರಗತಿ',
  'field.year.y1': 'ಮೊದಲ ವರ್ಷ',
  'field.year.y2': 'ಎರಡನೇ ವರ್ಷ',
  'field.year.y3': 'ಮೂರನೇ ವರ್ಷ',
  'field.year.y4': 'ನಾಲ್ಕನೇ ವರ್ಷ',
  'field.year.pg1': 'ಸ್ನಾತಕೋತ್ತರ ಮೊದಲ ವರ್ಷ',
  'field.year.pg2': 'ಸ್ನಾತಕೋತ್ತರ ಎರಡನೇ ವರ್ಷ',

  'q.full_name': 'ನಿಮ್ಮ ಹೆಸರೇನು?',
  'q.full_name.help': 'ನಿಮ್ಮ ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿ ಇರುವಂತೆಯೇ. ಪೂರೈಕೆದಾರರು ಎರಡೂ ಹೊಂದುತ್ತವೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.',
  'q.gender': 'ನಿಮ್ಮ ಲಿಂಗ ಯಾವುದು?',
  'q.gender.help': 'ಕೆಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಮಹಿಳೆಯರಿಗೆ ಮಾತ್ರ, ಅಥವಾ ತೃತೀಯಲಿಂಗಿ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ. ಹೇಳಲು ಇಷ್ಟವಿಲ್ಲದಿದ್ದರೆ ಬಿಟ್ಟುಬಿಡಿ.',
  'q.disability_type': 'ನಿಮ್ಮ ವಿಕಲಚೇತನ ಯಾವುದು?',
  'q.disability_type.help': 'ನಿಮ್ಮ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿ ಬರೆದಿರುವಂತೆ. ಹೆಚ್ಚಿನ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಇದರ ಮೇಲೆಯೇ ಶೋಧಿಸುತ್ತವೆ.',
  'q.disability_percent': 'ನಿಮ್ಮ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿ ಎಷ್ಟು ಶೇಕಡಾ ಇದೆ?',
  'q.disability_percent.help': '0 ಮತ್ತು 100ರ ನಡುವಿನ ಸಂಖ್ಯೆ. ಹಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ 40% ಅಥವಾ ಹೆಚ್ಚು ಬೇಕು.',
  'q.disability_percent.range': 'ಪ್ರಮಾಣಪತ್ರದ ಶೇಕಡಾವಾರು 0 ಮತ್ತು 100ರ ನಡುವೆ ಇರುತ್ತದೆ.',
  'q.udid_number': 'ನಿಮ್ಮ UDID ಸಂಖ್ಯೆ ಯಾವುದು?',
  'q.udid_number.help': 'ನಿಮ್ಮ UDID (ವಿಶಿಷ್ಟ ವಿಕಲಚೇತನ ಗುರುತು) ಕಾರ್ಡ್‌ನಲ್ಲಿರುವ ಸಂಖ್ಯೆ. ಇನ್ನೂ ನೀಡಲಾಗಿಲ್ಲವೆಂದರೆ ಬಿಟ್ಟುಬಿಡಿ — ನೀವು ಯಾವುದಕ್ಕೆ ಅರ್ಹರು ಎಂಬುದರಲ್ಲಿ ಇದು ಏನನ್ನೂ ಬದಲಿಸುವುದಿಲ್ಲ, ನಂತರ ಸೇರಿಸಬಹುದು.',
  'q.date_of_birth': 'ನೀವು ಯಾವಾಗ ಹುಟ್ಟಿದಿರಿ?',
  'q.date_of_birth.help': 'ಕೆಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ ವಯಸ್ಸಿನ ಮಿತಿ ಇರುತ್ತದೆ.',
  'q.course_name': 'ನೀವು ಏನು ಓದುತ್ತಿದ್ದೀರಿ?',
  'q.course_name.help': 'ನೋಂದಾಯಿಸುವಾಗ ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಕೋರ್ಸ್.',
  'q.institution_name': 'ನೀವು ಎಲ್ಲಿ ಓದುತ್ತಿದ್ದೀರಿ?',
  'q.institution_name.help': 'ನಿಮ್ಮ ಶಾಲೆ, ಕಾಲೇಜು ಅಥವಾ ವಿಶ್ವವಿದ್ಯಾಲಯದ ಹೆಸರು, ನಿಮ್ಮ ಬೋನಫೈಡ್ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿ ಬರೆದಿರುವಂತೆ. ಇನ್ನೂ ಆರಂಭಿಸಿಲ್ಲವೆಂದರೆ ಬಿಟ್ಟುಬಿಡಿ.',
  'q.institution_name.placeholder': 'ನಿಮ್ಮ ಶಾಲೆ ಅಥವಾ ಕಾಲೇಜಿನ ಹೆಸರು',
  'q.state_code': 'ನೀವು ಯಾವ ರಾಜ್ಯದಲ್ಲಿ ವಾಸಿಸುತ್ತೀರಿ?',
  'q.state_code.help': 'ಹಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಕೆಲವು ರಾಜ್ಯಗಳ ನಿವಾಸಿಗಳಿಗೆ ಮಾತ್ರ ಮುಕ್ತವಾಗಿವೆ.',
  'q.annual_family_income': 'ನಿಮ್ಮ ಕುಟುಂಬದ ವಾರ್ಷಿಕ ಆದಾಯ ಎಷ್ಟು?',
  'q.annual_family_income.help': 'ರೂಪಾಯಿಗಳಲ್ಲಿ, ನಿಮ್ಮ ಆದಾಯ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿ ಇರುವಂತೆ. ಹೆಚ್ಚಿನ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳಿಗೆ ಒಂದು ಗರಿಷ್ಠ ಮಿತಿ ಇರುತ್ತದೆ.',
  'q.annual_family_income.range': 'ಆದಾಯ ಶೂನ್ಯಕ್ಕಿಂತ ಕಡಿಮೆ ಇರಲಾಗದು.',
  'q.academic_percentage': 'ನಿಮ್ಮ ಕೊನೆಯ ಪರೀಕ್ಷೆಯ ಅಂಕಗಳು ಎಷ್ಟು?',
  'q.academic_percentage.help': 'ನಿಮ್ಮ ಅಂಕಪಟ್ಟಿ ಅವನ್ನು ಹೇಳುವ ರೀತಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ, ನಂತರ ಸಂಖ್ಯೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ. ಹಲವು ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಕನಿಷ್ಠ ಅಂಕ ಕೇಳುತ್ತವೆ.',
  'field.orgKind.NGO': 'ಸ್ವಯಂಸೇವಾ ಸಂಸ್ಥೆ',
  'field.orgKind.CORPORATE': 'ಕಾರ್ಪೊರೇಟ್',
  'field.orgKind.GOVERNMENT': 'ಸರ್ಕಾರಿ',
  'field.orgKind.PRIVATE': 'ಖಾಸಗಿ',

  'field.doc.DISABILITY_CERTIFICATE': 'ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರ',
  'field.doc.UDID_CARD': 'UDID ಕಾರ್ಡ್',
  'field.doc.INCOME_CERTIFICATE': 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ',
  'field.doc.DOMICILE_CERTIFICATE': 'ವಾಸಸ್ಥಳ ಪ್ರಮಾಣಪತ್ರ',
  'field.doc.CASTE_CERTIFICATE': 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ',
  'field.doc.MARKSHEET': 'ಅಂಕಪಟ್ಟಿ',
  'field.doc.ADMISSION_LETTER': 'ಪ್ರವೇಶ ಪತ್ರ',
  'field.doc.BONAFIDE_CERTIFICATE': 'ಬೋನಫೈಡ್ ಪ್ರಮಾಣಪತ್ರ',
  'field.doc.FEE_RECEIPT': 'ಶುಲ್ಕದ ರಸೀದಿ',
  'field.doc.BANK_PASSBOOK': 'ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್',
  'field.doc.IDENTITY_PROOF': 'ಗುರುತಿನ ಪುರಾವೆ',
  'field.doc.PHOTOGRAPH': 'ಭಾವಚಿತ್ರ',

  'appl.next.SUBMITTED': 'ಪೂರೈಕೆದಾರರ ಬಳಿ ನಿಮ್ಮ ಅರ್ಜಿ ಇದೆ. ಮುಂದೆ ಒಬ್ಬ ಪರಿಶೀಲಕರು ಅದನ್ನು ಓದುತ್ತಾರೆ.',
  'appl.next.UNDER_REVIEW': 'ಒಬ್ಬ ಪರಿಶೀಲಕರು ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಓದುತ್ತಿದ್ದಾರೆ. ಸಾಮಾನ್ಯವಾಗಿ ಇದೇ ಅತ್ಯಂತ ಸುದೀರ್ಘ ಹಂತ.',
  'appl.next.INFO_REQUESTED': 'ಅವರು ನಿಮ್ಮಿಂದ ಏನನ್ನೋ ಕೇಳಿದ್ದಾರೆ. ನೀವು ಉತ್ತರಿಸುವವರೆಗೆ ನಿಮ್ಮ ಅರ್ಜಿ ಕಾಯುತ್ತದೆ.',
  'appl.next.DOCUMENT_CHECK': 'ನಿಮ್ಮ ಅರ್ಜಿ ಪರಿಶೀಲಕರ ಬಳಿ ಇದೆ. ನಿಮ್ಮಿಂದ ಏನೂ ಬೇಕಿಲ್ಲ.',
  'appl.next.VERIFIED': 'ನಿಮ್ಮ ಅರ್ಜಿ ಪರಿಶೀಲಕರ ಬಳಿ ಇದೆ. ನಿಮ್ಮಿಂದ ಏನೂ ಬೇಕಿಲ್ಲ.',
  'appl.next.SHORTLISTED': 'ನಿಮ್ಮ ಅರ್ಜಿ ಪರಿಶೀಲಕರ ಬಳಿ ಇದೆ. ಮುಂದೆ ನಿರ್ಧಾರ.',
  'appl.next.APPROVED': 'ಅನುಮೋದಿತ. ಪೂರೈಕೆದಾರರು ಮಂಜೂರಾತಿಯನ್ನು ದಾಖಲಿಸಿ, ನಂತರ ಪಾವತಿಗೆ ವ್ಯವಸ್ಥೆ ಮಾಡುತ್ತಾರೆ.',
  'appl.next.SANCTIONED': 'ಹಣ ಮಂಜೂರಾಗಿದೆ. ಪಾವತಿ ಅವರ ಬ್ಯಾಂಕ್ ಮೂಲಕ ನಡೆಯುತ್ತದೆ.',
  'appl.next.DISBURSED': 'ಪಾವತಿ ದಾಖಲಾಗಿದೆ. ಕೆಲವು ಕೆಲಸದ ದಿನಗಳಲ್ಲಿ ನಿಮ್ಮ ಖಾತೆಗೆ ತಲುಪದಿದ್ದರೆ, ದೂರು ಸಲ್ಲಿಸಿ.',
  'appl.next.REJECTED': 'ಈ ಅರ್ಜಿ ಯಶಸ್ವಿಯಾಗಲಿಲ್ಲ. ಇದು ನಿಮ್ಮ ಇತರ ಅರ್ಜಿಗಳ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ.',
  'appl.next.CLOSED': 'ಈ ಅರ್ಜಿ ಪೂರ್ಣಗೊಂಡಿದೆ.',
  'appl.next.WITHDRAWN': 'ನೀವು ಈ ಅರ್ಜಿಯನ್ನು ಹಿಂಪಡೆದಿದ್ದೀರಿ.',
}

export default kn
