/* Kashmiri, in Perso-Arabic.
 *
 * ---------------------------------------------------------------------------
 * Read this before trusting a string in this file
 * ---------------------------------------------------------------------------
 *
 * This is the one table here that has not been checked by somebody who speaks
 * the language, and it is the one that most needs it. Kashmiri is a low-resource
 * language for every machine translator including the one that drafted this;
 * the administrative vocabulary is largely shared with Urdu and is likely
 * right, and the grammar around it — the چھُ / چھےٚ / چھِ copulas, the
 * ergative, the polite imperative — is where an error will be. Errors here are
 * not cosmetic: the strings in this file tell a student why an application was
 * refused and what a consent covers.
 *
 * Until a native speaker has read it, treat this as a first draft that ships
 * because the alternative — the language absent from the switcher — is worse for
 * a reader who has no other option, and because every string is individually
 * replaceable without touching code. A key deleted from this file falls back to
 * English on the next render.
 *
 * Right to left, like Urdu; see the note in ur.ts about {placeholders} and the
 * bidirectional algorithm, which applies here unchanged.
 */

import type { Dict } from '../i18n-strings'

const ks: Dict = {
  'app.name': 'وظیفہٕ پورٹل',
  'app.tagline': 'معذور طالِب عِلمَن خٲطرٕ',
  'app.yourApplication': 'توٚہُنٛز درخواست · {title}',

  'nav.find': 'وظیفہٕ',
  'nav.how': 'یہِ کِتھ پٲٹھؠ کٲم کران چھُ',
  'nav.matches': 'مےٚ ہُنٛد میٛل',
  'nav.applications': 'مےٚ ہٕنٛز درخواستہٕ',
  'nav.documents': 'مےٚ ہٕنٛز دستاویزہٕ',
  'nav.profile': 'مےٚ ہٕنٛز پروفائل',
  'nav.privacy': 'مےٚ ہُنٛد ڈیٹا',
  'nav.account': 'مےٚ ہُنٛد اکاؤنٹ',
  'nav.register': 'سائن اپ',
  'nav.language': 'زبان',
  'footer.social': 'انڈِک اے آی بیٚیِن جایَن پؠٹھ',
  'footer.sponsor': 'تعاون سٕتؠ',
  'footer.copyright': 'کاپی رائٹ © {year} انڈِک اے آی | تمام حُقوق محفوظ چھِ',
  'nav.signin': 'سائن اِن',
  'nav.signout': 'سائن آؤٹ',
  'nav.skip': 'بٔنِیادی مواد کُن گٔژھِو',

  'public.title': 'سُہ وظیفہٕ ژھٲنڈِو یَتھ خٲطرٕ توٚہہِ اہل چھِو',
  'public.lede': 'یَتہِ آسِتھ پرٛٮ۪تھ وظیفہٕ چھُ معذور طالِب عِلمَن خٲطرٕ کھولہٕ۔ وُچھنہٕ خٲطرٕ چھُنہٕ اکاؤنٹ ضَروری۔',
  'public.search': 'ناو یا لَفظ سٕتؠ ژھٲنڈِو',
  'public.filter.disability': 'معذوری ہُنٛد قِسم',
  'public.filter.qualification': 'اہلیت',
  'public.filter.state': 'توٚہُنٛز ریاست',
  'public.filter.provider': 'کُس چھُ دِوان',
  'public.filter.any': 'کانٛہہ تہِ',
  'public.filter.anyDisability': 'کانٛہہ تہِ معذوری',
  'public.filter.anyQualification': 'کانٛہہ تہِ اہلیت',
  'public.filter.allStates': 'تمام ریاستہٕ',
  'public.filter.gender': 'جِنس',
  'public.filter.anyGender': 'کانٛہہ تہِ جِنس',
  'public.filter.course': 'کورس',
  'public.filter.anyCourse': 'کانٛہہ تہِ کورس',
  'public.filter.where': 'توٚہہِ کَتہِ چھِو پَران',
  'public.filter.anyWhere': 'ہِنٛدوستان یا بٔرونہٕ مُلُک',
  'public.filter.inIndia': 'ہِنٛدوستانَس مَنٛز',
  'public.filter.abroad': 'بٔرونہٕ مُلُک تعلیم',
  'public.filters': 'فِلٹَر',
  'public.clear': 'ہٹٲیِو',
  'public.results': 'وظیفہٕ وۄنہِ کھولہٕ چھِ',
  'public.searching': 'ژھانڈان چھُ…',
  'public.none': 'تِمَن فِلٹَرَن سٕتؠ چھُنہٕ کانٛہہ وظیفہٕ میٛلان',
  'public.none.hint': 'اکھ فِلٹَر ہٹٲیِتھ وُچھِو۔ سٲری وۄہر نٔوۍ سکیٖمہٕ کھولان چھِ۔',
  'public.none.clear': 'تمام فِلٹَر ہٹٲیِو',
  'public.empty': 'یَتہِ چھُنہٕ وۄنہِ تام کانٛہہ وظیفہٕ درج',
  'public.empty.hint': 'دِوان وٲلؠ ادارٕ چھِ وۄنہِ شٲمِل کٔرِتھ یِوان۔ یَتہِ چھُنہٕ کِہین٘ٛہ اکاؤنٹَس پَتہٕ کُنہِ — سکیٖمہٕ درج گٔژھِتھ وُچھِو کھۄتہِ سائن اِن کٔرنہٕ ورٲے تہِ۔',
  'public.whoFor': 'یہِ چھُ کَمِ خٲطرٕ',
  'public.about': 'اَمہِ وظیفہٕ چہِ بارٕ',
  'public.atAGlance': 'اَکِس نَظرٕ مَنٛز',
  'public.closes': 'بَنٛد گٔژھان چھُ',
  'public.awardUnstated': 'رَقم چھِنہٕ ؤنمٕژ',
  'public.noClose': 'کانٛہہ آخری تٲریٖخ چھِنہٕ',
  'public.closesIn': '{n} دۄہَن مَنٛز بَنٛد',
  'public.closesToday': 'اَز بَنٛد گٔژھان چھُ',
  'public.closed': 'بَنٛد',
  'public.award': 'رَقم',
  'public.renewable': 'پرٛٮ۪تھ وۄہری تَجدیٖد گٔژھِتھ ہیٚکہِ',
  'public.offeredBy': 'دِوان وول ادارٕ',
  'public.eligibility': 'اہل بَنَنہٕ خٲطرٕ',
  'public.benefits': 'فٲیدٕ',
  'public.readMore': 'ژھٹھ پٔریِو',
  'public.viewDetails': 'تَفصیٖلہٕ وُچھِو',
  'public.applyNow': 'وۄنہِ درخواست دِیِو',
  'public.registerToApply': 'درخواست دِیِو',
  'public.registerToApplyHelp': 'درخواستہٕ چھِ توٚہُنٛدِ اکاؤنٹَس ذَریعہٕ دِنہٕ یِوان۔ رجسٹر کٔرِتھ ہیٚکِو توٚہہِ سُہ پرٛٮ۪تھ وظیفہٕ تہِ وُچھِتھ یَتھ خٲطرٕ توٚہہِ اہل چھِو۔',
  'public.closedNote': 'یہِ سکیٖم چھےٚ بَنٛد گٔیہِ',
  'sheet.close': 'بَنٛد کٔرِو',
  'sheet.loading': 'وظیفہٕ چہِ تَفصیٖلہٕ',
  'public.benefitComponent': 'مَد',
  'public.benefitAmount': 'طالِب عِلمَس کیٛاہ چھُ میٚلان',
  'public.whatYouGet': 'توٚہہِ کیٛاہ میٚلِ',
  'public.eligibilityDetail': 'اہلیت تَفصیٖل سٕتؠ',
  'public.documentsRequired': 'ضَروری دستاویزہٕ',
  'public.documentsHelp': 'دِوان وول ادارٕ چھُ یِم ژھانڈان۔ یِم چھِوٕنہٕ توٚہہِ یَتہِ اپ لوڈ کَران۔',
  'public.howToApply': 'درخواست کِتھ کَنؠ دِیِو',
  'public.importantNotes': 'زٲننہٕ لایِق',
  'public.academicYear': 'کَمہِ وۄہری خٲطرٕ',
  'public.awardBasis': 'کَمہِ بُنیادس پؠٹھ',
  'public.basis.MERIT': 'قٲبِلیت',
  'public.basis.NEED': 'مٲلی ضَرورت',
  'public.basis.MERIT_CUM_MEANS': 'قٲبِلیت تہٕ آمدنی',
  'public.basis.CATEGORY': 'زٲژ',
  'public.basis.OTHER': 'بیٛاکھ',
  'public.cta': 'پٔنٕنؠ خٲطرٕ وظیفہٕ ژھٲنڈِو',
  'public.applyExternal': 'تِمَن ہٕنٛدِس سائٹَس پؠٹھ درخواست دِیِو',
  'public.applyExternalHelp': 'أسؠ چھِ یہِ وظیفہٕ اَمہِ خٲطرٕ درج کَران زِ توٚہہِ ہیٚکِو یہِ ژھٲنڈِتھ۔ یہِ چھُ {org} چلاوان تہٕ درخواستہٕ چھُ پٲنؠ ہِنٛدِس ویب سائٹَس پؠٹھ ہیوان، اَمہِ کِنؠ چھُنہٕ یہِ یَتہِ توٚہُنٛدِ درخواستَن مَنٛز ہاوٕنہٕ یِوان۔',
  'public.applyExternalHelpPartner': '{org} چھُ یہِ درخواست پٲنؠ ہِنٛدِس ویب سائٹَس پؠٹھ ہیوان، اَمہِ کِنؠ چھِنہٕ یہِ یَتہِ توٚہُنٛدِ درخواستَن مَنٛز ہاوٕنہٕ یِوان۔',
  'common.newTab': 'نٔوِس ٹیبَس مَنٛز کھولان چھُ',
  'public.applyHelp': 'أسؠ چھِ گۄڈٕ توٚہُنٛز پروفائل تہٕ دستاویزہٕ اَمہِ وظیفہٕ سٕتؠ ژٲریتھ وُچھان تہٕ ونان زِ کِہین٘ٛہ چھُ راوان کِنہٕ نہٕ۔ توٚہُنٛدِ تَصدیٖقہٕ برونٛہہ چھُنہٕ کِہین٘ٛہ سوزنہٕ یِوان۔',
  'public.ctaHelp': 'پٔنٕنہِ بارٕ اکھ لٹہِ ونیِو تہٕ أسؠ ہاوَو توٚہہِ سُہ پرٛٮ۪تھ وظیفہٕ یَتھ خٲطرٕ توٚہہِ اہل چھِو۔',
  'public.back': 'تمام وظیفَن کُن واپس',
  'notFound.title': 'اَسہِ مێول نہٕ یہ صفہٕ',
  'notFound.body': 'پَتس منٛز ہیٚکہِ ٹایپنٕچ غلطی آسِتھ، یا ہیٚکہِ صفہٕ بَدلاونہٕ آمُت آسِتھ۔',
  'notFound.home': 'ہوم صفس پؠٹھ گژھِو',

  'nav.dashboard': 'ڈیش بورڈ',
  'dash.title': 'توٚہُنٛد ڈیش بورڈ',
  'dash.lede': 'توٚہُنٛدؠ وظیفہٕ، درخواستہٕ تہٕ دستاویزہٕ، سٲری اَکِس جایہِ۔',
  'dash.matches': 'یَمَن وظیفَن خٲطرٕ توٚہہِ ہیٚکِو درخواست دِتھ',
  'dash.matchesHint': 'توٚہہِ دِژمٕتؠن تَفصیٖلَن ہِنٛدِس بُنیادَس پؠٹھ۔',
  'dash.matchesBlocked': '{n} چھِ توٚہہِ نِشہٕ بیٛاکھ تَفصیٖل اِنتظار کَران۔',
  'dash.applications': 'چلان درخواستہٕ',
  'dash.applicationsHint': '{approved} منظور · {rejected} کامیاب نہٕ',
  'dash.applicationsNone': 'وۄنہِ تام چھُنہٕ کِہین٘ٛہ سوزنہٕ آمُت۔',
  'dash.documents': 'تَصدیٖق شُدٕ دستاویزہٕ',
  'dash.documentsHint': 'اکھ لٹہِ ژٲرِتھ وُچھمٕژ۔ پرٛٮ۪تھ درخواستہٕ مَنٛز کٲمہِ یِوان چھِ۔',
  'dash.funding': 'وۄنہِ تام میٚلۆو',
  'dash.fundingHint': 'مُجمُوعی {sanctioned} منظور۔',
  'dash.recent': 'تازٕ درخواستہٕ',
  'dash.noApplications': 'وۄنہِ تام کانٛہہ درخواست چھِنہٕ',
  'dash.noApplicationsHint': 'توٚہہِ یَمہِ خٲطرٕ تہِ درخواست دِیِو سُہ یَتہِ ہاوٕنہٕ یِیہِ۔',
  'dash.findScholarships': 'وظیفہٕ ژھٲنڈِو',
  'dash.profileTitle': 'توٚہُنٛز پروفائل',
  'dash.toGo': '{n}% باقی',
  'dash.allApplications': 'سٲری وُچھِو',
  'dash.matchesGo': 'پٔنٕنؠ میٛل وُچھِو',
  'dash.applicationsGo': 'پٔنٕنؠ درخواستہٕ وُچھِو',
  'dash.documentsGo': 'دستاویزہٕ سَنبٲلِو',
  'dash.draftsTitle': '{n} درخواست چھِنہٕ سوزنہٕ آمٕژ | {n} درخواستہٕ چھِنہٕ سوزنہٕ آمٕژہٕ',
  'dash.draftsBody': 'درخواست شُرۆع کٔرِتھ چھِنہٕ سوٚہ سوزنہٕ یِوان۔ وظیفہٕ بَنٛد گٔژھنہٕ برونٛہہ مُکمَل کٔرِو۔',
  'dash.draftsAction': 'وۄنہِ مُکمَل کٔرِو',
  'dash.expiringTitle': '{n} دستاویزٕچ میٛعاد چھےٚ جلدی ختم گٔژھان | {n} دستاویزَن ہٕنٛز میٛعاد چھےٚ جلدی ختم گٔژھان',
  'dash.expiringBody': 'پرٛٮ۪تھ درخواستہٕ مَنٛز کٲمہِ یِیہِ، اَمہِ خٲطرٕ یہِ وۄنہِ بَدلٲیِو۔ | پرٛٮ۪تھ درخواستہٕ مَنٛز کٲمہِ یِیَن، اَمہِ خٲطرٕ یِم وۄنہِ بَدلٲیِو۔',
  'dash.expiringAction': 'دستاویزہٕ وُچھِو',

  'auth.title': 'پنُن موبائل نَمبَر دِیِو',
  'auth.phone': 'موبائل نَمبَر',
  'auth.phoneHint': 'أسؠ سوزَو اَمہِ نَمبَرَس پؠٹھ ایس ایم ایس سٕتؠ 6 ہِنٛدسَن ہُنٛد کوڈ۔ پرٛٮ۪تھ لٹہِ چھُ یہِ ہِے نَمبَر توٚہہِ سائن اِن کَراوان۔',
  'auth.phoneMissing': 'بۆنہٕ گٔژھنہٕ خٲطرٕ پَنُن موبائل نَمبَر دِیِو۔',
  'auth.phoneInvalid': 'یہِ چھُنہٕ ٹھیٚکہٕ ہاوان۔ ہِنٛدوستٲنؠ موبائل نَمبَر چھِ 10 ہِنٛدسَن ہٕنٛدؠ تہٕ 6، 7، 8 یا 9 پٮ۪ٹھۍ شُرۆع گٔژھان چھِ۔',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'نٔوۍ آسِو یا واپس یِوان، سوٚے نَمبَر چھُ کٲم کَران۔ اگر توٚہُنٛد اکاؤنٹ چھُنہٕ تہٕ أسؠ بَناوَو۔',
  'auth.stepOf': 'مرحلہٕ {n} / 2 · {name}',
  'auth.stepPhone': 'توٚہُنٛد نَمبَر',
  'auth.stepCode': 'توٚہُنٛد OTP کوڈ',
  'auth.privacy': 'توٚہُنٛد نَمبَر چھُ صرف توٚہہِ سائن اِن کَراونہٕ خٲطرٕ اِستِعمال گٔژھان، بیٛاکِس کُنہِ کٲمہِ خٲطرٕ نہٕ۔ یاد تھاوٕنہٕ خٲطرٕ چھُنہٕ کانٛہہ پاس ورڈ۔',
  'auth.sendCode': 'کوڈ سوزِو',
  'auth.sending': 'سوزنہٕ یِوان چھُ…',
  'auth.checking': 'ژٲرِتھ وُچھان چھُ…',
  'auth.welcomeBack': 'دوبارٕ خوش آمدید۔ سائن اِن کَرنہٕ خٲطرٕ کوڈ دِیِو۔',
  'auth.newHere': 'کوڈ دِتھ ہِے بَناوَو أسؠ توٚہُنٛد اکاؤنٹ۔',
  'auth.codeTitle': 'أسؠ یُس کوڈ سوز سُہ دِیِو',
  'auth.code': '6 ہِنٛدسَن ہُنٛد کوڈ',
  'auth.codeHint': 'پٮ۪غام چھُ عٲم طور کینٛہہ سیکنٛڈَن مَنٛز یِوان۔',
  'auth.noCode': 'وۄنہِ تام پٮ۪غام چھُنہٕ آمُت؟ بیٛاکھ طریٖقہٕ آزمٲیِو:',
  'auth.verify': 'تَصدیٖق کٔرِو',
  'auth.viaSms': 'ایس ایم ایس سٕتؠ سوزِو',
  'auth.viaWhatsapp': 'واٹس ایپَس پؠٹھ سوزِو',
  'auth.viaVoice': 'کوڈ ونٕنہٕ خٲطرٕ مےٚ کٔرِو فون',
  'auth.resentVia.sms': 'ایس ایم ایس سٕتؠ سوزٕو۔ یِنہٕ مَنٛز ہیٚکہِ کینٛہہ وَقت لَگِتھ۔',
  'auth.resentVia.whatsapp': 'واٹس ایپَس پؠٹھ سوزٕو۔ پٮ۪غامہٕ خٲطرٕ واٹس ایپ وُچھِو۔',
  'auth.resentVia.voice': 'کوڈ ونٕنہٕ خٲطرٕ وۄنہِ فون کَران چھِ۔ بوزنہٕ خٲطرٕ فون ہٮ۪یِو۔',
  'auth.resendIn': '{n} سیکنٛڈَن مَنٛز دوبارٕ سوزِو',
  'auth.changeNumber': 'بیٛاکھ نَمبَر اِستِعمال کٔرِو',
  'auth.change': 'بَدلٲیِو',

  'profile.complete': '{n}% مُکمَل',
  'profile.viewLede': 'توٚہہِ أسہِ یُس کِہین٘ٛہ وۄن۔ کانٛہہ تہِ جَواب بَدلٲیِو تہٕ تَمہِ پَتہٕ چھُ پرٛٮ۪تھ وظیفہٕ خٲطرٕ سُہ ہِے اِستِعمال گٔژھان۔',
  'profile.notAnswered': 'وۄنہِ تام جَواب چھُنہٕ دِژمُت',
  'profile.verified': 'تَصدیٖق شُدٕ',
  'profile.continue': 'یَتہِ تروٚو توٚتہٕ پٮ۪ٹھۍ جاری تھٲیِو',
  'profile.start': 'پٔنٕنؠ پروفائل شُرۆع کٔرِو',
  'profile.saved': 'محفوظ گَو',

  'match.title': 'توٚہہِ خٲطرٕ وظیفہٕ',
  'match.lede': 'توٚہُنٛزِ پروفائلہٕ سٕتؠ ژٲرِتھ وُچھمٕتؠ۔ یَمَن خٲطرٕ درخواست دِتھ ہیٚکِو تِم گۄڈٕ۔',
  'match.eligible': 'توٚہہِ چھِو اہل',
  'match.likely': 'توٚہہِ چھِو شایَد اہل',
  'match.blocked': 'گۄڈٕ اکھ کٲم',
  'match.actionable': 'توٚہہِ خٲطرٕ کھولہٕ',
  'match.actionableHelp': 'کینٛہہَن خٲطرٕ ہیٚکہِ درخواستہٕ برونٛہہ اکھ دستاویز ضَروری آسِتھ۔',
  'match.ineligible': 'توٚہہِ خٲطرٕ کھولہٕ نہٕ',
  'match.eligibleHelp': 'أسہِ یُس کِہین٘ٛہ ژٲرِتھ وُچھ سُہ سٲری چھُ تَصدیٖق شُدٕ۔',
  'match.likelyHelp': 'توٚہہِ یُس وۄن تَمہِ بُنیادَس پؠٹھ۔ تَصدیٖق کَراوِتھ چھےٚ توٚہُنٛز درخواست مَضبوط گٔژھان۔',
  'match.blockedHelp': 'توٚہہِ چھِو نٔزدیٖک۔ یہِ کٔرِو تہٕ درخواست دِتھ ہیٚکِو۔',
  'match.ineligibleHelp': 'یہِ سکیٖم چھےٚ تِتھ کِہین٘ٛہ ژھانڈان یُس توٚہہِ بَدلٲوِتھ ہیٚکو نہٕ۔',
  'match.apply': 'درخواست دِیِو',
  'match.applied': 'توٚہہِ چھِو درخواست دِژمٕژ',
  'match.none': 'وۄنہِ تام کانٛہہ میٛل چھُنہٕ',
  'match.noneHint': 'پٔنٕنؠ پروفائل مُکمَل کٔرِو تہٕ أسؠ ژٲرِتھ وُچھَو توٚہہِ خٲطرٕ پرٛٮ۪تھ وظیفہٕ۔',
  'match.figQualify': 'توٚہہِ چھِو اہل',
  'match.figStep': 'اکھ قَدَم دوٗر',
  'match.figClosing': 'جلدی بَنٛد',
  'match.figNo': 'توٚہہِ خٲطرٕ کھولہٕ نہٕ',
  'match.filterLabel': 'کَم وظیفہٕ ہاوٕنہٕ یِیَن',
  'match.filterAll': 'سٲری',
  'match.filterQualify': 'توٚہہِ چھِو اہل',
  'match.filterStep': 'اکھ قَدَم دوٗر',
  'match.filterClosing': 'جلدی بَنٛد',
  'match.filterNo': 'توٚہہِ خٲطرٕ کھولہٕ نہٕ',
  'match.filterEmpty': 'اَمہِ گرۄپَس مَنٛز چھُنہٕ کِہین٘ٛہ۔ “سٲری” آزمٲیِو۔',
  'match.moreWithProfile': 'توٚہہِ کوتاہ بَریِو تِتؠ ژھٹھ وظیفہٕ ہاوٕنہٕ یِیَن۔',
  'match.youQualify': 'توٚہُنٛزِ پروفائلہٕ مُطٲبِق چھِو توٚہہِ شَرطہٕ پورٕ کَران۔',
  'match.yesTitle': 'توٚہہِ ہیٚکِو درخواست دِتھ',
  'match.blockedTitle': 'گۄڈٕ اکھ کٲم',
  'match.noTitle': 'اہل نہٕ',
  'match.appliedTitle': 'برونٛہہ پٮ۪ٹھۍ سوزمٕژ',
  'match.seeDetails': 'قٲیدٕ وُچھِو',
  'match.learnMore': 'ژھٹھ زٲنِو',
  'match.runBy': '{kind} چھُ چلاوان',
  'match.sortBy': 'ترتیٖب',
  'match.sortRecommended': 'تَجویٖز کَرِتھ',
  'match.sortClosing': 'سٲرِوؠ برونٛہہ بَنٛد گٔژھَن وٲلؠ',
  'match.sortAward': 'سٲرِوؠ بۆڈ رَقم',
  'match.applyAway': 'تِمَن ہٕنٛدِس سائٹَس پؠٹھ درخواست دِیِو',
  'match.applyHere': 'یَتہِ ہِے درخواست دِیِو',
  'match.notOpenToYou': 'وۄنکہِ حالَتہٕ مَنٛز چھُنہٕ توٚہہِ خٲطرٕ کھولہٕ۔',
  'match.working': 'وۄنہِ کھولہٕ کانٛہہ سکیٖم چھِنہٕ توٚہہِ دِژمٕتؠن تَفصیٖلَن سٕتؠ میٛلان۔ پروفائلہٕ مَنٛز ژھٹھ شٲمِل کٔرِتھ چھُ یہِ بَدلان۔',

  'doc.title': 'توٚہُنٛدؠ دستاویزہٕ',
  'doc.lede': 'اکھ دستاویز اکھ لٹہِ اپ لوڈ کٔرِو۔ توٚہہِ یَمہِ تہِ وظیفہٕ خٲطرٕ درخواست دِیِو سُہ ہیٚکہِ یہِ اِستِعمال کٔرِتھ — توٚہہِ نِشہٕ چھِنہٕ دوبارٕ ژھانڈنہٕ یِوان۔',
  'doc.upload': 'دستاویز شٲمِل کٔرِو',
  'doc.type': 'یہِ چھےٚ کُس دستاویز؟',
  'doc.file': 'فائل ژٲرِو',
  'doc.fileHint': 'پی ڈی ایف یا صاف تصویٖر۔ 10 ایم بی تام۔',
  'doc.verified': 'تَصدیٖق شُدٕ',
  'doc.verifiedBy': '{org} کٔر تَصدیٖق',
  'doc.pending': 'تَصدیٖقہٕ ہٕنٛدِس اِنتظارَس مَنٛز',
  'doc.expired': 'تَصدیٖقٕچ میٛعاد ختم',
  'doc.expiring': '{n} دۄہَن مَنٛز میٛعاد ختم',
  'doc.validUntil': '{date} تام کارآمَد',
  'doc.none': 'توٚہہِ چھُنہٕ وۄنہِ تام کانٛہہ دستاویز شٲمِل کٔرمُت',
  'doc.uploading': 'اپ لوڈ گٔژھان چھُ…',
  'doc.remove': 'ہٹٲیِو',
  'doc.removing': 'ہٹاونہٕ یِوان چھُ…',

  'apply.title': 'درخواست دِیِو',
  'apply.consent': 'مےٚ ہٕنٛز تَفصیٖلہٕ اَمہِ ادارَس سٕتؠ شٲرِک کٔرِو',
  'apply.consentBody': 'فٮ۪صلہٕ کَرنہٕ خٲطرٕ اَمہِ وظیفہٕ کیٛاہ ضَروری چھُ صرف سُہ ہِے وُچھَن تِم: {fields}. توٚہُنٛدؠ دستاویزہٕ کَمہِ وُچھِ یہِ ہیٚکِو توٚہہِ کٔنہہ تہِ وُچھِتھ۔',
  'apply.consentBodyNoDocs': 'فٮ۪صلہٕ کَرنہٕ خٲطرٕ اَمہِ وظیفہٕ کیٛاہ ضَروری چھُ صرف سُہ ہِے وُچھَن تِم، بیٛاکھ کِہین٘ٛہ نہٕ۔ توٚہُنٛدؠ تَفصیٖلہٕ کَمہِ وُچھِ یہِ ہیٚکِو توٚہہِ کٔنہہ تہِ وُچھِتھ۔',
  'apply.submit': 'مےٚ ہٕنٛز درخواست سوزِو',
  'apply.submitting': 'سوزنہٕ یِوان چھُ…',
  'apply.blocked': 'توٚہہِ ہیٚکو نہٕ وۄنہِ درخواست دِتھ',
  'apply.needProfile': 'گۄڈٕ توٚہُنٛز پروفائل',
  'apply.needProfileHint': 'درخواست چھےٚ توٚہُنٛزِ پروفائلہٕ پٮ۪ٹھۍ سوزنہٕ یِوان، اَمہِ کِنؠ چھےٚ درخواستہٕ برونٛہہ سوٚہ ضَروری۔ اَمہِ مَنٛز چھِ کینٛہہ ہِے منٹ لَگان، تہٕ توٚہہِ یُس برونٛہہ وۄن سُہ چھُ بٔرِتھ میٚلان۔',
  'apply.elsewhereTitle': 'اَمُک درخواست چھےٚ اسپانسَرَکِس ویب سائٹَس پؠٹھ گٔژھان',
  'apply.elsewhereBody': 'أسؠ چھِ یہِ وظیفہٕ اَمہِ خٲطرٕ درج کَران زِ توٚہہِ ہیٚکِو یہِ ژھٲنڈِتھ، تہٕ درخواستہٕ چھِ اسپانسَر پانہٕ ہیوان۔ توٚہہِ أسہِ یُس وۄن سُہ چھُ محفوظ رۄزان، تہٕ یِم وظیفہٕ أسؠ چلاوان چھِ تِمَن خٲطرٕ چھُ برونٛہہ پٮ۪ٹھۍ بٔرِتھ۔',
  'apply.elsewhereBodyPartner': 'یہِ وظیفہٕ چھُ یَتہِ ہِے چلان، مَگر اسپانسَر چھِ درخواستہٕ پٲنؠ ہِنٛدِس ویب سائٹَس پؠٹھ ہیوان۔ توٚہہِ أسہِ یُس وۄن سُہ چھُ محفوظ رۄزان، تہٕ یِم درخواستہٕ أسہِ سیٖدؠ میٚلان چھِ تِمَن خٲطرٕ چھُ برونٛہہ پٮ۪ٹھۍ بٔرِتھ۔',
  'apply.bundleTitle': 'پٔنٕنؠ دستاویزہٕ پانہٕ سٕتؠ نیِو',
  'apply.bundleBody': 'یہِ وظیفہٕ یِم دستاویزہٕ ژھانڈان چھُ تِم ہیٚکَو أسؠ اَکِس فائلہٕ مَنٛز تھٲوِتھ، تِمَن ہٕنٛدِس ویب سائٹَس پؠٹھ اپ لوڈ کَرنہٕ خٲطرٕ تیار۔ تِم یُس ژھانڈان چھِ تہٕ أسہِ نِش وۄنہِ تام چھُنہٕ، سُہ تہِ چھُ اَمہِ مَنٛز درج۔',
  'apply.bundleAction': 'مےٚ ہٕنٛز دستاویزہٕ ڈاؤن لوڈ کٔرِو',
  'apply.bundleWorking': 'تیار کَرنہٕ یِوان چھُ…',
  'apply.bundleDone': 'توٚہُنٛدؠ دستاویزہٕ ڈاؤن لوڈ گٔیہِ۔',
  'apply.docs': 'اَمہِ وظیفہٕ خٲطرٕ ضَروری دستاویزہٕ',

  'appl.title': 'توٚہُنٛدؠ درخواستہٕ',
  'appl.none': 'توٚہہِ چھُنہٕ وۄنہِ تام کَمہِ خٲطرٕ درخواست دِژمٕژ',
  'appl.noneHint': 'یَمَن وظیفَن خٲطرٕ توٚہہِ اہل چھِو تِم ژھانڈنہٕ خٲطرٕ پٔنٕنؠ میٛل وُچھِو۔',
  'appl.reference': 'حوالہٕ',
  'appl.whatNext': 'بۆنہٕ کیٛاہ گٔژھِ',
  'appl.history': 'تٲریٖخ',
  'appl.needsYou': 'تِمَن چھُ توٚہہِ نِشہٕ کِہین٘ٛہ ضَروری',
  'track.label': 'اَمہِ درخواستٕچ پیش رَفت',
  'track.sent': 'سوزمٕژ',
  'track.review': 'جایِزٕ',
  'track.decision': 'فٮ۪صلہٕ',
  'track.doneSr': 'مُکمَل',
  'track.currentSr': 'وۄنہِ جاری چھُ',
  'track.todoSr': 'شُرۆع چھُنہٕ گۄمُت',
  'appl.sentOn': '{when} سوزمٕژ',
  'appl.decidedOn': '{when} فٮ۪صلہٕ گَو',
  'appl.outcomeApproved': 'میٚلۆو',
  'appl.outcomeRejected': 'اَمہِ لٹہِ چھُنہٕ میٚلومُت',
  'appl.outcomeWithdrawn': 'توٚہہِ کٔر یہِ واپس',
  'appl.inProgress': 'ادارَس نِش',
  'appl.outcome': 'نَتیٖجہٕ',
  'appl.award': 'رَقم',
  'appl.applied': 'درخواست دِژمٕژ',
  'appl.decided': 'فٮ۪صلہٕ گَو',
  'appl.automatic': 'خۆدکار',
  'appl.noHistory': 'وۄنہِ تام چھُنہٕ کِہین٘ٛہ گۄمُت۔',

  'ref.heading': 'تِمَن ہٕنٛدِس ویب سائٹَس پؠٹھ سوزمٕژ',
  'ref.blurb': 'یَمَن ہٕنٛز درخواست چھےٚ دِوان وٲلِس ادارَس ہِنٛدِس پٲنٕنِس سائٹَس پؠٹھ گٔژھان، اَمہِ کِنؠ ہیٚکو نہٕ أسؠ وُچھِتھ زِ کیٛاہ گَو۔ أسہِ ونیِو تہٕ أسؠ تھاوَو یہِ باقیَن سٕتؠ۔',
  'ref.sentOn': 'توٚہہِ کھول یہِ {when}',
  'ref.again': 'مُجمُوعی {times} لٹہِ',
  'ref.open': 'تِمَن ہُنٛد سائٹ دوبارٕ کھولِو',
  'ref.what': 'کیٛاہ گَو؟',
  'ref.APPLIED': 'مےٚ دِژ درخواست',
  'ref.AWARDED': 'مےٚ میٚلۆو',
  'ref.NOT_AWARDED': 'مےٚ چھُنہٕ میٚلومُت',
  'ref.DID_NOT_APPLY': 'مےٚ چھِنہٕ درخواست دِژمٕژ',
  'ref.saidAPPLIED': 'توٚہہِ دِژ درخواست',
  'ref.saidAWARDED': 'توٚہہِ میٚلۆو',
  'ref.saidNOT_AWARDED': 'توٚہہِ چھُنہٕ میٚلومُت',
  'ref.saidDID_NOT_APPLY': 'توٚہہِ چھِنہٕ درخواست دِژمٕژ',
  'ref.youSaid': 'توٚہہِ أسہِ وۄن: {what}',
  'ref.change': 'بَدلٲیِو',

  'privacy.title': 'توٚہُنٛد ڈیٹا',
  'privacy.lede': 'أسہِ نِش کیٛاہ چھُ، کَمہِ وُچھ، تہٕ یہِ واپس کِتھ کَنؠ نیِو۔',
  'privacy.access': 'توٚہُنٛدؠ دستاویزہٕ کَمہِ وُچھہٕ',
  'privacy.accessNone': 'توٚہُنٛدِس پٲنٕنِس اکاؤنٹَس نیٚبَر چھُنہٕ کٔنہہ توٚہُنٛدؠ دستاویزہٕ کھولمٕژہٕ۔',
  'privacy.consents': 'توٚہہِ کیٛاہ شٲرِک کَرنُک رضامَنٛدی دِژ',
  'privacy.withdraw': 'واپس نیِو',
  'privacy.withdrawing': 'واپس نیٚنہٕ یِوان چھےٚ…',
  'privacy.export': 'أسہِ نِش یُس کِہین٘ٛہ چھُ سٲری ڈاؤن لوڈ کٔرِو',
  'privacy.exporting': 'توٚہُنٛز نَقل تیار کَرنہٕ یِوان چھےٚ…',
  'privacy.exportBody': 'توٚہُنٛدِس ڈیٹا ہٕنٛز مُکمَل، مَشیٖنہٕ سٕتؠ پَرنہٕ یِنہٕ وٲلہِ نَقل۔',
  'privacy.erase': 'مےٚ ہُنٛد ڈیٹا مٹٲیِو',
  'privacy.erasing': 'درخواست کَرنہٕ یِوان چھےٚ…',
  'privacy.eraseBody': 'توٚہہِ دِژمٕتِس کُنہِ تہِ وظیفہٕ ہُنٛد ریکارڈ چھُ أسہِ تھاوُن پَزان۔ باقی سٲری چھُ ہٹاونہٕ یِوان۔',
  'auth.closedTitle': 'توٚہُنٛد اکاؤنٹ چھُ وۄنہِ بَنٛد۔',
  'auth.closedHelp': 'مَدَد ضَروری چھےٚ؟ أسہِ ہٕنٛز سَپورٹ ٹیم ہیٚکہِ توٚہہِ سَمجھَنہٕ مَنٛز مَدَد کٔرِتھ ',
  'auth.closedSoon': 'مَدَد ژھٲنڈِو (جلدی)',
  'reg.district': 'ضِلعہٕ',
  'reg.districtHint': 'توٚہُنٛدِس علاقَس مَنٛز چلان سکیٖمَن سٕتؠ میٛلاوَنہٕ مَنٛز مَدَد کَران چھُ۔',
  'privacy.requested': 'درخواست کٔرمٕژ',
  'privacy.window': 'وۄنہِ تام چھُنہٕ کِہین٘ٛہ مٹاونہٕ آمُت',
  'privacy.windowBody': 'توٚہُنٛد ڈیٹا یِیہِ {date} مٹاونہٕ۔ تَمہِ تام ہیٚکِو توٚہہِ ',
  'privacy.cancel': 'یہِ درخواست منسوخ کٔرِو',
  'privacy.cancelling': 'منسوخ کَرنہٕ یِوان چھےٚ…',
  'privacy.cancelled': 'توٚہُنٛز درخواست چھےٚ منسوخ کٔرنہٕ آمٕژ۔ کِہین٘ٛہ چھُنہٕ مٹاونہٕ آمُت۔',

  'common.loading': 'لوڈ گٔژھان چھُ',
  'common.retry': 'دوبارٕ کوشِش کٔرِو',
  'common.required': 'لازِمی',
  'common.optional': 'اِختیٲری',
  'common.error': 'کِہین٘ٛہ غَلَط گَو',
  'common.offline': 'توٚہہِ چھِو آف لائن۔ توٚہُنٛد کٲم چھُ اَمہِ آلَس پؠٹھ محفوظ۔',

  'slides.lead.was': '',
  'slides.lead.able': 'صَلاحیتہٕ پٮ۪ٹھۍ',
  'slides.lead.dist': 'اِمتِیازَس کُن',
  'slides.lead.body': 'پرٛٮ۪تھ سُہ وظیفہٕ یَتھ خٲطرٕ توٚہہِ اہل چھِو — سرکٲری تہٕ نِجی — توٚہُنٛزِ پروفائلہٕ سٕتؠ میٛلٲوِتھ، توٚہُنٛزِ زبٲنہِ مَنٛز، اَکِس جایہِ۔',
  'slides.lead.free': 'بالکُل مُفت',
  'slides.lead.languages': '14 زبانہٕ',
  'slides.lead.support': 'پرٛٮ۪تھ قَدَمَس پؠٹھ ذٲتی مَدَد',
  'slides.label': 'اعلانہٕ',
  'slides.position': '{total} مَنٛزٕ {n}',
  'slides.goto': '{name} ہٲیِو',
  'slides.watch': 'ویڈیو وُچھِو',
  'slides.external': 'بیٛاکھ ویب سائٹ کھولان چھُ',

  'home.title': 'معذور طالِب عِلمَن خٲطرٕ وظیفہٕ، اَکِس جایہِ',
  'home.lede': 'پٔنٕنہِ بارٕ اکھ لٹہِ ونیِو۔ أسؠ چھِ یَتُک پرٛٮ۪تھ وظیفہٕ سٕتؠ توٚہہِ ژٲریتھ وُچھان تہٕ ونان زِ توٚہہِ کَمَن خٲطرٕ اہل چھِو — تہٕ باقیَن خٲطرٕ ٹھیٚکہٕ ٹھیٚکہٕ کیٛاہ چھُ کَم۔',
  'home.search': 'وظیفہٕ ژھٲنڈِو',
  'home.searchPlaceholder': 'مَثلن: انجینئرِنگ، دِلی، پوسٹ میٹرِک',
  'home.searchGo': 'ژھٲنڈِو',
  'home.browseAll': 'تمام وظیفہٕ وُچھِو',
  'home.openNow': 'وظیفہٕ وۄنہِ کھولہٕ چھِ',
  'home.noAccount': 'وُچھنہٕ خٲطرٕ چھُنہٕ اکاؤنٹ ضَروری۔',
  'home.openNone': 'یَتہِ چھُنہٕ وۄنہِ تام کانٛہہ وظیفہٕ درج۔',
  'home.openNoneBody': 'فہرست چھےٚ وۄنہِ بَرنہٕ یِوان۔ یَتہِ چھُنہٕ کِہین٘ٛہ اکاؤنٹَس پَتہٕ کُنہِ — سکیٖمہٕ درج گٔژھِتھ وُچھِو کھۄتہِ سائن اِن کٔرنہٕ ورٲے تہِ۔',
  'home.how': 'یہِ کِتھ پٲٹھؠ کٲم کران چھُ',
  'home.howLede': 'رجسٹر کَرنہٕ خٲطرٕ چھُ اکھ موبائل نَمبَر تہٕ تَمہِ پؠٹھ سوزمُت کوڈ ضَروری۔ کانٛہہ پاس ورڈ نہٕ، تہٕ گۄڈٕ بَرنہٕ خٲطرٕ کانٛہہ سائن اپ فارم تہِ نہٕ۔',
  'home.step1': 'رجسٹر ژٮ۪کِو',
  'home.step1Body': 'اَمہِ صفحس پؠٹھ۔ اگر برونٛہہ پٮ۪ٹھۍ آمٕتؠ چھِو تہٕ ساتہِ وول لاگ اِن اِستِعمال کٔرِو — دۄشَوٕن مَنٛز چھُ سوٚے نَمبَر کٲم کَران۔',
  'home.step2': 'پَنُن موبائل نَمبَر دِیِو',
  'home.step2Body': 'دَہ ہِنٛدسہٕ، +91 برونٛہہ پٮ۪ٹھۍ بٔرِتھ۔ تَمہِ نَمبَرَس پؠٹھ چھُ 6 ہِنٛدسَن ہُنٛد کوڈ گٔژھان۔',
  'home.step3': 'کوڈ دِیِو',
  'home.step3Body': 'شیہہ ہِنٛدسہٕ ٹائپ کٔرِو تہٕ توٚہہِ چھِو اَنٛدَر۔ اگر کانٛہہ پٮ۪غام نہٕ یِیہِ تہٕ کوڈ واٹس ایپَس پؠٹھ ژھٲنڈِو، یا أسہِ فون کٔرِتھ پٔرِتھ بوزناوَنہٕ خٲطرٕ ونیِو۔',
  'home.step4': 'پٔنٕنؠ تَفصیٖلہٕ بَریِو',
  'home.step4Body': 'توٚہُنٛد ناو، توٚہُنٛد سَرٹیفِکیٹ تہٕ توٚہہِ کَتہِ چھِو پَران — اَکِس لٹہِ اکھ سَوال، تہٕ پرٛٮ۪تھ جَواب دِتھ ہِے چھُ محفوظ گٔژھان۔',
  'home.step5': 'پٔنٕنؠ دستاویزہٕ اپ لوڈ کٔرِو',
  'home.step5Body': 'معذوری سَرٹیفِکیٹ، یو ڈی آی ڈی کارڈ، آمدنی ہُنٛد سَرٹیفِکیٹ تہٕ باقی۔ پرٛٮ۪تھ اکھ صرف اکھ لٹہِ، پرٛٮ۪تھ وظیفہٕ خٲطرٕ عَلحدٕ نہٕ۔',
  'home.step6': 'پٔنٕنؠ میٛل وُچھِو',
  'home.step6Body': 'مےٚ ہُنٛد میٛل چھُ تِم وظیفہٕ ہاوان یَمَن خٲطرٕ توٚہہِ اہل چھِو — تہٕ یَتہِ کانٛہہ توٚہہِ خٲطرٕ بَنٛد چھُ، توٚتہِ چھُ سَبَب ونان۔',
  'home.step7': 'درخواست دِیِو',
  'home.step7Body': 'یِم ژھانڈِو تِم ژٲرِو۔ توٚہُنٛدؠ تَفصیٖلہٕ تہٕ دستاویزہٕ چھِ درخواستہٕ سٕتؠ گٔژھان۔',
  'home.assure': 'زٲننہٕ لایِق',
  'home.assure1': 'یاد تھاوٕنہٕ خٲطرٕ کانٛہہ پاس ورڈ نہٕ',
  'home.assure2': 'عَلحدٕ کانٛہہ رجسٹریشَن فارم نہٕ',
  'home.assure3': 'توٚہہِ ہیٚکِو رٔٹِتھ پَتہٕ مُکمَل کٔرِتھ',
  'home.help': 'کُنہِ مرحلس پؠٹھ رٔٹِو؟',
  'home.helpBody': 'فون کٔرِو، کانٛہہ توٚہہِ پار کَرَنٲوِ۔',
  'home.helpCall': '{number} پؠٹھ فون کٔرِو',
  'home.closing': 'جلدی بَنٛد',
  'home.closingLede': 'گۄڈٕ یَمَن خٲطرٕ درخواست دِیِو۔',
  'home.closingNext': 'بۆنہٕ کٕنؠ آخری تٲریٖخہٕ',
  'home.closingNextLede': 'سٲرِوؠ برونٛہہ بَنٛد گٔژھَن وٲلؠ ترٛےٚ۔',
  'home.allDeadlines': 'تمام وظیفہٕ وُچھِو',
  'home.browse': 'اَمہِ مُطٲبِق وُچھِو',
  'home.browseWho': 'کُس چھُ دِوان',
  'home.browseLevel': 'توٚہُنٛدِ تعلیمُک درجہٕ',
  'home.cta': 'پٔنٕنؠ میٛل وُچھنہٕ خٲطرٕ تیار چھِو؟',
  'home.ctaBody': 'اکاؤنٹ بَناونہٕ خٲطرٕ چھُ اکھ موبائل نَمبَر یا ای میل پَتہٕ ضَروری۔ بیٛاکھ کِہین٘ٛہ نہٕ۔',
  'home.ctaButton': 'اکاؤنٹ بَنٲیِو',
  'home.signedInCta': 'وُچھِو توٚہہِ کَمہِ خٲطرٕ اہل چھِو',

  'reg.title': 'وظیفہٕ ژھانڈنہٕ خٲطرٕ رجسٹر کٔرِو',
  'reg.editTitle': 'پٔنٕنؠ تَفصیٖلہٕ تازٕ کٔرِو',
  'reg.requiredNote': '* وٲلؠ سٲری خانہٕ چھِ لازِمی۔',
  'reg.personal': 'ذٲتی تَفصیٖلہٕ',
  'reg.disability': 'معذوری ہٕنٛز تَفصیٖلہٕ',
  'reg.education': 'تعلیمٕچ تَفصیٖلہٕ',
  'reg.name': 'پورٕ ناو',
  'reg.namePlaceholder': 'پَنُن پورٕ ناو لیٚکھِو',
  'reg.phoneHint': 'أسؠ چھِ اَمہِ نَمبَرَس پؠٹھ 6 ہِنٛدسَن ہُنٛد کوڈ سوزان۔ پرٛٮ۪تھ لٹہِ چھُ یہِ ہِے نَمبَر توٚہہِ سائن اِن کَراوان۔',
  'reg.sendOtp': 'او ٹی پی سوزِو',
  'reg.otpPlaceholder': '6 ہِنٛدسَن ہُنٛد او ٹی پی لیٚکھِو',
  'reg.verified': 'فون نَمبَر تَصدیٖق شُدٕ',
  'reg.verifyFirst': 'رجسٹریشَن مُکمَل کَرنہٕ خٲطرٕ پَنُن فون نَمبَر تَصدیٖق کٔرِو۔',
  'reg.email': 'ای میل',
  'reg.emailHint': 'تاکہٕ أسؠ ہیٚکَو آخری تٲریٖخ یاد کَرٲوِتھ۔ أسؠ چھِوٕنہٕ یہِ کٔنہہ تہِ شٲرِک کَران۔',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'جِنس',
  'reg.genderHint': '(کینٛہہ وظیفہٕ چھِ صرف زنانَن یا ٹرانس جینڈَر طالِب عِلمَن خٲطرٕ)',
  'reg.udid': 'یو ڈی آی ڈی نَمبَر',
  'reg.udidHint': 'توٚہُنٛدِس یو ڈی آی ڈی (مُنفَرِد معذوری شِناخت) کارڈَس پؠٹھ لیٚکھمُت نَمبَر۔',
  'reg.udidPlaceholder': 'پَنُن یو ڈی آی ڈی نَمبَر لیٚکھِو',
  'reg.certificate': 'یو ڈی آی ڈی سَرٹیفِکیٹ اپ لوڈ کٔرِو',
  'reg.certificateHint': 'پی ڈی ایف یا تصویٖر، 5 ایم بی یا تَمہِ کھۄتہٕ کَم۔',
  'reg.fileType': 'سوٚہ فائل گٔژھہِ پی ڈی ایف، جے پی ای جی یا پی این جی آسُن۔',
  'reg.fileSize': 'سوٚہ فائل چھےٚ 5 ایم بی کھۄتہٕ بۆڈ۔ فونہٕ سٕتؠ ہیٚژمٕژ تصویٖر چھےٚ عٲم طور لۆکٕٹ گٔژھان اگر توٚہہِ سوٚہ ہیٚنہٕ بَجایہِ اسکین کٔرِو۔',
  'reg.fileLater': 'توٚہُنٛز رجسٹریشَن گٔیہِ تہٕ تَفصیٖلہٕ چھِ محفوظ۔ سَرٹیفِکیٹ چھُنہٕ اپ لوڈ گۄمُت — سُہ مےٚ ہٕنٛدؠن دستاویزَن پٮ۪ٹھۍ شٲمِل کٔرِو، بیٛاکھ کِہین٘ٛہ چھُنہٕ دوبارٕ کَرُن۔',
  'reg.disabilityType': 'معذوری ہُنٛد قِسم',
  'reg.percent': 'معذوری ہُنٛد فیٖصد',
  'reg.percentHint': 'توٚہُنٛدِس سَرٹیفِکیٹَس پؠٹھ لیٚکھمُت عَدَد۔ واریاہَن وظیفَن خٲطرٕ چھُ 40% یا تَمہِ کھۄتہٕ ژھٹھ ضَروری۔',
  'reg.percentPlaceholder': 'مَثلن 40',
  'reg.percentRange': 'سَرٹیفِکیٹُک فیٖصد چھُ 0 تہٕ 100 دَرمِیان مُکمَل عَدَد۔',
  'reg.state': 'ریاست',
  'reg.statePlaceholder': 'پٔنٕنؠ ریاست ژھانڈنہٕ خٲطرٕ ٹائپ کٔرِو…',
  'reg.program': 'پَنُن کورس ژٲرِو',
  'reg.graduation': 'گریجویشَن',
  'reg.postgraduation': 'پوسٹ گریجویشَن / ماسٹَرز',
  'reg.year': 'وۄہر ژٲرِو',
  'reg.yearAfterProgram': 'گۄڈٕ پَنُن کورس ژٲرِو',
  'reg.institution': 'اسکول / کالِجُک ناو',
  'reg.institutionPlaceholder': 'پٔنٕنِس ادارَس ہُنٛد ناو لیٚکھِو',
  'reg.required': 'یہِ چھُ ضَروری۔',
  'reg.fix': 'کینٛہہ جَوابَن پؠٹھ چھےٚ توَجہٕ ضَروری۔ گۄڈنیُک چھُ بۆنہٕ ژارمُت۔',
  'reg.cta': 'رجسٹر کٔرِو تہٕ وظیفہٕ ژھٲنڈِو',
  'reg.saveChanges': 'تَبدیٖلی محفوظ کٔرِو',
  'reg.saving': 'محفوظ کَرنہٕ یِوان چھُ…',
  'reg.done': 'رجسٹریشَن گٔیہِ۔ توٚہُنٛدؠ وظیفہٕ ژھانڈنہٕ یِوان چھِ۔',
  'reg.doneTitle': 'توٚہُنٛز رجسٹریشَن گٔیہِ',
  'reg.already': 'برونٛہہ پٮ۪ٹھۍ رجسٹرڈ چھِو؟',
  'reg.login': 'او ٹی پی سٕتؠ لاگ اِن',
  'nav.registerCta': 'رجسٹر',
  'nav.loginCta': 'لاگ اِن',
  'profile.edit': 'پٔنٕنؠ تَفصیٖلہٕ تازٕ کٔرِو',
  /* The medical and legal terms below are the Urdu ones, and that is a
     judgement rather than a shortcut: the RPwD Act's twenty-one conditions have
     no settled Kashmiri rendering, the certificates a student is reading these
     against are issued in Urdu or English, and inventing Kashmiri coinages for
     them would leave a reader matching this list against a document that uses
     none of them. The sentences around them are Kashmiri. */
  'field.disability.BLINDNESS': 'نابیناپن',
  'field.disability.LOW_VISION': 'کم بیٖنٲیی',
  'field.disability.LEPROSY_CURED': 'جذام (ٹھیٚک گۄمُت)',
  'field.disability.HEARING_IMPAIRMENT': 'بوزنٕچ کمزوٗری',
  'field.disability.LOCOMOTOR_DISABILITY': 'پکنٕچ معذوری',
  'field.disability.DWARFISM': 'ژھۄٹ قٲمی',
  'field.disability.INTELLECTUAL_DISABILITY': 'ذہنی معذوری',
  'field.disability.MENTAL_ILLNESS': 'نفسیاتی بیٖمٲری',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'آٹزم سپیکٹرم ڈس آرڈر',
  'field.disability.CEREBRAL_PALSY': 'دماغی فالج',
  'field.disability.MUSCULAR_DYSTROPHY': 'پٹھَن ہٕنٛز کمزوٗری',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'دیریٖنہٕ اعصابی حالت',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'مخصوص تعلیمی معذوری',
  'field.disability.MULTIPLE_SCLEROSIS': 'ملٹیپل سکلیروسس',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'گویٲیی تہٕ زبٲنؠ معذوری',
  'field.disability.THALASSEMIA': 'تھیلیسیمیا',
  'field.disability.HAEMOPHILIA': 'ہیموفیلیا',
  'field.disability.SICKLE_CELL_DISEASE': 'سکل سیل بیٖمٲری',
  'field.disability.MULTIPLE_DISABILITIES': 'واریاہ معذوریہٕ، بوزنہٕ تہٕ وُچھنٕچ معذوری سمیت',
  'field.disability.ACID_ATTACK_VICTIM': 'تیزاب حملہٕ پٮ۪ٹھۍ بٔچمُت',
  'field.disability.PARKINSONS_DISEASE': 'پارکنسنز بیٖمٲری',

  'field.state.AN': 'انڈمان تہٕ نکوبار جزٲیِر',
  'field.state.AP': 'آندھرا پردیش',
  'field.state.AR': 'اروناچل پردیش',
  'field.state.AS': 'آسام',
  'field.state.BR': 'بہار',
  'field.state.CH': 'چندی گڑھ',
  'field.state.CT': 'چھتیس گڑھ',
  'field.state.DL': 'دِلی',
  'field.state.DN': 'دادرا تہٕ نگر حویلی تہٕ دمن تہٕ دیو',
  'field.state.GA': 'گوا',
  'field.state.GJ': 'گجرات',
  'field.state.HP': 'ہماچل پردیش',
  'field.state.HR': 'ہریانہ',
  'field.state.JH': 'جھارکھنڈ',
  'field.state.JK': 'جموں تہٕ کشمیٖر',
  'field.state.KA': 'کرناٹک',
  'field.state.KL': 'کیرالہ',
  'field.state.LA': 'لداخ',
  'field.state.LD': 'لکشدیپ',
  'field.state.MH': 'مہاراشٹر',
  'field.state.ML': 'میگھالیہ',
  'field.state.MN': 'منی پور',
  'field.state.MP': 'مدھیہ پردیش',
  'field.state.MZ': 'میزورم',
  'field.state.NL': 'ناگالینڈ',
  'field.state.OR': 'اوڈیشہ',
  'field.state.PB': 'پنجاب',
  'field.state.PY': 'پڈوچیری',
  'field.state.RJ': 'راجستھان',
  'field.state.SK': 'سکم',
  'field.state.TG': 'تلنگانہ',
  'field.state.TN': 'تمل ناڈو',
  'field.state.TR': 'تریپورہ',
  'field.state.UP': 'اتر پردیش',
  'field.state.UT': 'اتراکھنڈ',
  'field.state.WB': 'مغربی بنگال',

  'field.level.SCHOOL': 'اسکول',
  'field.level.SCHOOL.sub': 'جماعت 9، 10، 11، 12',
  'field.level.UNDERGRADUATE': 'گریجویشن',
  'field.level.UNDERGRADUATE.sub': 'BA، BSc، BTech تہٕ تِتھؠ',
  'field.level.POSTGRADUATE': 'پوسٹ گریجویشن',
  'field.level.POSTGRADUATE.sub': 'MA، MSc، MTech تہٕ تِتھؠ',
  'field.level.DOCTORAL': 'ڈاکٹریٹ',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'اسکول',
  'field.qual.SCHOOL.sub': 'جماعت 1 پٮ۪ٹھۍ 12 تام',
  'field.qual.UNDERGRADUATE': 'گریجویشن',
  'field.qual.UNDERGRADUATE.sub': 'BA، BSc، BCom، BE / BTech، MBBS — تہٕ ڈپلوما یا ITI',
  'field.qual.POSTGRADUATE': 'پوسٹ گریجویشن',
  'field.qual.POSTGRADUATE.sub': 'MA، MSc، MTech، MBA تہٕ تِتھؠ',
  'field.qual.DOCTORAL': 'PhD / ڈاکٹریٹ',

  'field.subject.engineering': 'انجینئرنگ',
  'field.subject.medical': 'طب',
  'field.subject.management': 'انتظامیہ',
  'field.subject.science': 'سائنس',
  'field.subject.commerce': 'تجارت',
  'field.subject.arts': 'فنون تہٕ علومِ انسٲنی',
  'field.subject.vocational': 'پیشہ ورانہ',
  'field.subject.fellowship': 'فیلوشپ',
  'field.subject.talent': 'صلاحیت',
  'field.subject.sports': 'کھیل',

  'field.gender.FEMALE': 'زنانہ',
  'field.gender.MALE': 'مرد',
  'field.gender.TRANSGENDER': 'ٹرانس جینڈر',
  'field.gender.UNDISCLOSED': 'ونُن چھُنہٕ چاہان',
  'field.genderFilter.TRANSGENDER': 'ترٛیِیِم جِنس / ٹرانس جینڈر',

  'field.year.below9': 'جماعت 9 بۄنہٕ',
  'field.year.c9': 'جماعت 9',
  'field.year.c10': 'جماعت 10',
  'field.year.c11': 'جماعت 11',
  'field.year.c12': 'جماعت 12',
  'field.year.y1': 'گۄڈنیُک ؤری',
  'field.year.y2': 'دۆیِم ؤری',
  'field.year.y3': 'ترٛیِیِم ؤری',
  'field.year.y4': 'ژوٗرِم ؤری',
  'field.year.pg1': 'پوسٹ گریجویٹ ؤری 1',
  'field.year.pg2': 'پوسٹ گریجویٹ ؤری 2',

  'q.full_name': 'توٚہُنٛد ناو کیٛاہ چھُ؟',
  'q.full_name.help': 'بالکل یِتھ پٲٹھؠ توٚہُنٛدِس معذوری سَرٹیفِکیٹَس پؠٹھ لیٚکھمُت چھُ۔ دِوان وٲلؠ ادارٕ چھِ دۄشوَے ژٲرِتھ وُچھان۔',
  'q.gender': 'توٚہُنٛز جِنس کیٛاہ چھےٚ؟',
  'q.gender.help': 'کینٛہہ وظیفہٕ چھِ صرف زنانَن خٲطرٕ، یا ٹرانس جینڈر طالِب عِلمَن خٲطرٕ۔ ونُن نہٕ چاہِو تہٕ ترٲیِو۔',
  'q.disability_type': 'توٚہُنٛز معذوری کیٛاہ چھےٚ؟',
  'q.disability_type.help': 'یِتھ پٲٹھؠ توٚہُنٛدِس سَرٹیفِکیٹَس پؠٹھ لیٚکھمُت چھُ۔ زیادٕ تر وظیفہٕ چھِ اَمہِ پؠٹھ ہِے ژھانان۔',
  'q.disability_percent': 'توٚہُنٛدِس سَرٹیفِکیٹَس پؠٹھ کوتاہ فیٖصد چھِ؟',
  'q.disability_percent.help': '0 تہٕ 100 دَرمِیان اکھ عَدَد۔ واریاہَن وظیفَن خٲطرٕ چھُ 40% یا ژھٹھ ضَروری۔',
  'q.disability_percent.range': 'سَرٹیفِکیٹُک فیٖصد چھُ 0 تہٕ 100 دَرمِیان گٔژھان۔',
  'q.udid_number': 'توٚہُنٛد UDID نَمبَر کیٛاہ چھُ؟',
  'q.udid_number.help': 'توٚہُنٛدِس UDID (مُنفَرِد معذوری شِناخت) کارڈَس پؠٹھ لیٚکھمُت نَمبَر۔ اگر وۄنہِ تام چھُنہٕ میٚلومُت تہٕ ترٲیِو — توٚہہِ کَمہِ خٲطرٕ اہل چھِو تَمہِ مَنٛز چھُنہٕ اَمہِ سٕتؠ کانٛہہ فرق پیٚوان، تہٕ پَتہٕ شٲمِل کٔرِتھ ہیٚکِو۔',
  'q.date_of_birth': 'توٚہہِ کٔر کٔنہہ جنم؟',
  'q.date_of_birth.help': 'کینٛہہ وظیفَن مَنٛز چھےٚ عُمرٕ ہٕنٛز حَد۔',
  'q.course_name': 'توٚہہِ کیٛاہ چھِو پَران؟',
  'q.course_name.help': 'رجسٹر کَرنہٕ وَقتہِ توٚہہِ یُس کورس ژور۔',
  'q.institution_name': 'توٚہہِ کَتہِ چھِو پَران؟',
  'q.institution_name.help': 'توٚہُنٛدِس اسکول، کالِج یا یونیورسٹی ہُنٛد ناو، یِتھ پٲٹھؠ توٚہُنٛدِس بونافائیڈ سَرٹیفِکیٹَس پؠٹھ لیٚکھمُت چھُ۔ اگر وۄنہِ تام شُرۆع چھُنہٕ کٔرمُت تہٕ ترٲیِو۔',
  'q.institution_name.placeholder': 'توٚہُنٛدِس اسکول یا کالِجُک ناو',
  'q.state_code': 'توٚہہِ کَمہِ ریاستَس مَنٛز چھِو رۄزان؟',
  'q.state_code.help': 'واریاہ وظیفہٕ چھِ صرف کینٛہہ ریاستَن ہٕنٛدؠن رۄزَن وٲلؠن خٲطرٕ کھولہٕ۔',
  'q.annual_family_income': 'توٚہُنٛدِس گھَرَکؠ سالانہ آمدنی کوتاہ چھےٚ؟',
  'q.annual_family_income.help': 'رۄپَیَن مَنٛز، یِتھ پٲٹھؠ توٚہُنٛدِس آمدنی سَرٹیفِکیٹَس پؠٹھ چھُ۔ زیادٕ تر وظیفَن مَنٛز چھےٚ اکھ حَد۔',
  'q.annual_family_income.range': 'آمدنی ہیٚکہِ نہٕ صفرٕ کھۄتہٕ کم آسِتھ۔',
  'q.academic_percentage': 'توٚہُنٛدِس پَتِمِس امتحانَس مَنٛز کوتاہ نَمبَر آیہِ؟',
  'q.academic_percentage.help': 'توٚہُنٛز مارک شیٹ یِتھ پٲٹھؠ تِم چھےٚ ونان سُہ ژٲرِو، تہٕ پَتہٕ عَدَد لیٚکھِو۔ واریاہ وظیفہٕ چھِ کم از کم نَمبَر ژھانڈان۔',
  'field.orgKind.NGO': 'این جی او',
  'field.orgKind.CORPORATE': 'کارپوریٹ',
  'field.orgKind.GOVERNMENT': 'سرکٲری',
  'field.orgKind.PRIVATE': 'نِجی',

  'field.doc.DISABILITY_CERTIFICATE': 'معذوری سَرٹیفِکیٹ',
  'field.doc.UDID_CARD': 'UDID کارڈ',
  'field.doc.INCOME_CERTIFICATE': 'آمدنی سَرٹیفِکیٹ',
  'field.doc.DOMICILE_CERTIFICATE': 'رِہٲیش سَرٹیفِکیٹ',
  'field.doc.CASTE_CERTIFICATE': 'ذات سَرٹیفِکیٹ',
  'field.doc.MARKSHEET': 'مارک شیٹ',
  'field.doc.ADMISSION_LETTER': 'داخلہٕ خط',
  'field.doc.BONAFIDE_CERTIFICATE': 'بونافائیڈ سَرٹیفِکیٹ',
  'field.doc.FEE_RECEIPT': 'فیٖسٕچ رسیٖد',
  'field.doc.BANK_PASSBOOK': 'بینک پاس بُک',
  'field.doc.IDENTITY_PROOF': 'شِناختُک ثبوت',
  'field.doc.PHOTOGRAPH': 'تصویٖر',

  'appl.next.SUBMITTED': 'دِوان وٲلِس ادارَس نِش چھےٚ توٚہُنٛز درخواست۔ بۆنہٕ پَرِ یہِ اکھ جٲیزٕ کار۔',
  'appl.next.UNDER_REVIEW': 'اکھ جٲیزٕ کار چھُ توٚہُنٛز درخواست پَران۔ عٲم طور چھُ یہِ ہِے سٲرِوؠ بۆڈ مرحلہٕ۔',
  'appl.next.INFO_REQUESTED': 'تِمَو چھُ توٚہہِ نِشہٕ کِہین٘ٛہ ژھۄنڈمُت۔ ییٚلہِ تام توٚہہِ جَواب چھِوٕنہٕ دِوان، درخواست چھےٚ رٔٹِتھ رۄزان۔',
  'appl.next.DOCUMENT_CHECK': 'توٚہُنٛز درخواست چھےٚ جٲیزٕ کارَس نِش۔ توٚہہِ نِشہٕ چھُنہٕ کِہین٘ٛہ ضَروری۔',
  'appl.next.VERIFIED': 'توٚہُنٛز درخواست چھےٚ جٲیزٕ کارَس نِش۔ توٚہہِ نِشہٕ چھُنہٕ کِہین٘ٛہ ضَروری۔',
  'appl.next.SHORTLISTED': 'توٚہُنٛز درخواست چھےٚ جٲیزٕ کارَس نِش۔ بۆنہٕ یِیہِ فٮ۪صلہٕ۔',
  'appl.next.APPROVED': 'منظور۔ دِوان وول ادارٕ کَرِ منظوری درج، تہٕ پَتہٕ اَدایِگی ہُنٛد بَندوبست۔',
  'appl.next.SANCTIONED': 'رَقم چھےٚ منظور گٔیہِ۔ اَدایِگی چھےٚ تِمَن ہٕنٛدِس بینکہٕ ذَریعہٕ گٔژھان۔',
  'appl.next.DISBURSED': 'اَدایِگی چھےٚ درج گٔیہِ۔ اگر کینٛہہ کاروباری دۄہَن مَنٛز توٚہُنٛدِس کھاتَس مَنٛز نہٕ واتہِ تہٕ شِکایت کٔرِو۔',
  'appl.next.REJECTED': 'یہِ درخواست چھِنہٕ کامیاب گٔیہِ۔ اَمہِ سٕتؠ چھُنہٕ توٚہُنٛدؠن بیٛاکِن درخواستَن پؠٹھ کانٛہہ اثر پیٚوان۔',
  'appl.next.CLOSED': 'یہِ درخواست چھےٚ مُکمَل گٔیہِ۔',
  'appl.next.WITHDRAWN': 'توٚہہِ اۄس یہِ درخواست واپس نیٛومُت۔',
}

export default ks
