/* Maithili, in Devanagari.
 *
 * Not Hindi in a different hat. The pronoun is अहाँ rather than आप, the
 * copula अछि rather than है, and the polite imperative ends -ू (करू, देखू,
 * भरू) rather than -ें. A Hindi table copied across would be read as Hindi by
 * the people this row exists for, which is the one outcome that makes a
 * fourteenth language pointless.
 *
 * One word per term: scholarship छात्रवृत्ति, application आवेदन,
 * document कागजात, disability दिव्यांगता, verified प्रमाणित, eligible योग्य,
 * certificate प्रमाणपत्र.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const mai: Dict = {
  'app.name': 'इंडिक एआइ छात्रवृत्ति',
  'app.tagline': 'दिव्यांग विद्यार्थी सभक लेल',
  'app.yourApplication': 'अहाँक आवेदन · {title}',

  'nav.find': 'छात्रवृत्ति',
  'nav.how': 'ई कोना काज करैत अछि',
  'nav.matches': 'हमर मेल',
  'nav.applications': 'हमर आवेदन',
  'nav.documents': 'हमर कागजात',
  'nav.profile': 'हमर प्रोफाइल',
  'nav.privacy': 'हमर डेटा',
  'nav.account': 'हमर खाता',
  'nav.register': 'साइन अप',
  'nav.language': 'भाषा',
  'footer.social': 'इंडिक एआइ आन ठाम',
  'footer.sponsor': 'सहयोगसँ',
  'footer.copyright': 'कॉपीराइट © {year} इंडिक एआइ | सभ अधिकार सुरक्षित',
  'nav.signin': 'साइन इन',
  'nav.signout': 'साइन आउट',
  'nav.skip': 'मुख्य सामग्री दिस जाउ',

  'public.title': 'ओ छात्रवृत्ति ताकू जकरा लेल अहाँ योग्य छी',
  'public.lede': 'एतऽ हर छात्रवृत्ति दिव्यांग विद्यार्थी सभक लेल खुजल अछि। देखबा लेल खाताक जरूरत नहि।',
  'public.search': 'नाम वा शब्दसँ ताकू',
  'public.filter.disability': 'दिव्यांगताक प्रकार',
  'public.filter.qualification': 'योग्यता',
  'public.filter.state': 'अहाँक राज्य',
  'public.filter.provider': 'के दऽ रहल अछि',
  'public.filter.any': 'कोनो',
  'public.filter.anyDisability': 'कोनो दिव्यांगता',
  'public.filter.anyQualification': 'कोनो योग्यता',
  'public.filter.allStates': 'सभ राज्य',
  'public.filter.gender': 'लिंग',
  'public.filter.anyGender': 'कोनो लिंग',
  'public.filter.course': 'पाठ्यक्रम',
  'public.filter.anyCourse': 'कोनो पाठ्यक्रम',
  'public.filter.where': 'अहाँ कतऽ पढ़ैत छी',
  'public.filter.anyWhere': 'भारत वा विदेश',
  'public.filter.inIndia': 'भारतमे',
  'public.filter.abroad': 'विदेशमे अध्ययन',
  'public.filters': 'फिल्टर',
  'public.clear': 'हटाउ',
  'public.results': 'छात्रवृत्ति आब खुजल अछि',
  'public.searching': 'ताकि रहल छी…',
  'public.none': 'एहि फिल्टर सभसँ कोनो छात्रवृत्ति मेल नहि खाइत अछि',
  'public.none.hint': 'एकटा फिल्टर हटा कऽ देखू। सालभरि नव योजना खुजैत रहैत अछि।',
  'public.none.clear': 'सभ फिल्टर हटाउ',
  'public.empty': 'एतऽ आइ धरि कोनो छात्रवृत्ति सूचीबद्ध नहि अछि',
  'public.empty.hint': 'देनिहार संस्था सभ आब जोड़ल जा रहल अछि। एतऽ किछु खाताक पाछाँ नहि अछि — योजना सूचीबद्ध होयबा पर अहाँ साइन इन केने बिना देख सकब।',
  'public.whoFor': 'ई ककरा लेल अछि',
  'public.about': 'एहि छात्रवृत्तिक बारेमे',
  'public.atAGlance': 'एक नजरिमे',
  'public.closes': 'बन्न होइत अछि',
  'public.awardUnstated': 'राशि नहि कहल गेल',
  'public.noClose': 'कोनो अन्तिम तिथि नहि',
  'public.closesIn': '{n} दिनमे बन्न',
  'public.closesToday': 'आइ बन्न भऽ रहल अछि',
  'public.closed': 'बन्न',
  'public.award': 'राशि',
  'public.renewable': 'हर साल नवीकरण कयल जा सकैत अछि',
  'public.offeredBy': 'देनिहार',
  'public.eligibility': 'योग्य होयबा लेल',
  'public.benefits': 'लाभ',
  'public.readMore': 'आओर पढ़ू',
  'public.viewDetails': 'विवरण देखू',
  'public.applyNow': 'आबे आवेदन करू',
  'public.registerToApply': 'आवेदन करू',
  'public.registerToApplyHelp': 'आवेदन अहाँक खाता द्वारा कयल जाइत अछि। पंजीकरण केलासँ अहाँकेँ ओ हर छात्रवृत्ति सेहो देखाओत जकरा लेल अहाँ योग्य छी।',
  'public.closedNote': 'ई योजना बन्न भऽ गेल अछि',
  'sheet.close': 'बन्न करू',
  'sheet.loading': 'छात्रवृत्तिक विवरण',
  'public.benefitComponent': 'मद',
  'public.benefitAmount': 'विद्यार्थीकेँ की भेटैत अछि',
  'public.whatYouGet': 'अहाँकेँ की भेटत',
  'public.eligibilityDetail': 'योग्यता विस्तारसँ',
  'public.documentsRequired': 'आवश्यक कागजात',
  'public.documentsHelp': 'देनिहार संस्था ई सभ मंगैत अछि। ई सभ अहाँ एतऽ अपलोड नहि करैत छी।',
  'public.howToApply': 'आवेदन कोना करी',
  'public.importantNotes': 'जनबा योग्य',
  'public.academicYear': 'कोन सालक लेल',
  'public.awardBasis': 'कोन आधार पर',
  'public.basis.MERIT': 'मेधा',
  'public.basis.NEED': 'आर्थिक आवश्यकता',
  'public.basis.MERIT_CUM_MEANS': 'मेधा आ आय',
  'public.basis.CATEGORY': 'श्रेणी',
  'public.basis.OTHER': 'आन',
  'public.cta': 'अपना लेल छात्रवृत्ति ताकू',
  'public.applyExternal': 'हुनकर साइट पर आवेदन करू',
  'public.applyExternalHelp': 'अहाँ ताकि सकी तेँ हम ई छात्रवृत्तिकेँ सूचीबद्ध करैत छी। एकरा {org} चलबैत अछि आ आवेदन अपन वेबसाइट पर लैत अछि, तेँ ई एतऽ अहाँक आवेदनमे नहि देखाओत।',
  'public.applyExternalHelpPartner': '{org} ई आवेदन अपन वेबसाइट पर लैत अछि, तेँ ई एतऽ अहाँक आवेदनमे नहि देखाओत।',
  'common.newTab': 'नव टैबमे खुजैत अछि',
  'public.applyHelp': 'हम पहिने अहाँक प्रोफाइल आ कागजातकेँ एहि छात्रवृत्तिसँ जाँचैत छी आ कहैत छी जे किछु छूटि रहल अछि की नहि। अहाँक पुष्टि भेला बिना किछु नहि पठाओल जाइत अछि।',
  'public.ctaHelp': 'अपना बारेमे एक बेर कहू आ हम अहाँकेँ ओ हर छात्रवृत्ति देखाएब जकरा लेल अहाँ योग्य छी।',
  'public.back': 'सभ छात्रवृत्ति दिस घुरू',
  'notFound.title': 'हमरा ई पेज नहि भेटल',
  'notFound.body': 'पता मे टाइपिंग के गलती भ सकैत अछि, वा पेज कतहु आन ठाम चलि गेल हो।',
  'notFound.home': 'होम पेज पर जाउ',

  'nav.dashboard': 'डैशबोर्ड',
  'dash.title': 'अहाँक डैशबोर्ड',
  'dash.lede': 'अहाँक छात्रवृत्ति, आवेदन आ कागजात, सभ एक ठाम।',
  'dash.matches': 'जाहि छात्रवृत्ति लेल अहाँ आवेदन कऽ सकैत छी',
  'dash.matchesHint': 'अहाँक देल विवरणक आधार पर।',
  'dash.matchesBlocked': '{n} अहाँसँ आओर एकटा जानकारीक बाट देखि रहल अछि।',
  'dash.applications': 'चलैत आवेदन',
  'dash.applicationsHint': '{approved} स्वीकृत · {rejected} सफल नहि',
  'dash.applicationsNone': 'आइ धरि किछु नहि पठाओल गेल।',
  'dash.documents': 'प्रमाणित कागजात',
  'dash.documentsHint': 'एक बेर जाँचल। हर आवेदनमे काज अबैत अछि।',
  'dash.funding': 'आइ धरि भेटल',
  'dash.fundingHint': 'कुल {sanctioned} स्वीकृत।',
  'dash.recent': 'हालक आवेदन',
  'dash.noApplications': 'आइ धरि कोनो आवेदन नहि',
  'dash.noApplicationsHint': 'अहाँ जकरो लेल आवेदन करब से एतऽ देखाओत।',
  'dash.findScholarships': 'छात्रवृत्ति ताकू',
  'dash.profileTitle': 'अहाँक प्रोफाइल',
  'dash.toGo': '{n}% बाकी',
  'dash.allApplications': 'सभ देखू',
  'dash.matchesGo': 'अपन मेल देखू',
  'dash.applicationsGo': 'अपन आवेदन देखू',
  'dash.documentsGo': 'कागजात सम्हारू',
  'dash.draftsTitle': '{n} आवेदन नहि पठाओल गेल | {n} आवेदन नहि पठाओल गेल',
  'dash.draftsBody': 'आवेदन शुरू केलासँ ओ पठाओल नहि जाइत अछि। छात्रवृत्ति बन्न होयबासँ पहिने पूरा करू।',
  'dash.draftsAction': 'आबे पूरा करू',
  'dash.expiringTitle': '{n} कागजातक अवधि जल्दी समाप्त भऽ रहल अछि | {n} कागजातक अवधि जल्दी समाप्त भऽ रहल अछि',
  'dash.expiringBody': 'हर आवेदनमे काज आबय तेँ एकरा आबे बदलि दिअ। | हर आवेदनमे काज आबय तेँ एकरा सभकेँ आबे बदलि दिअ।',
  'dash.expiringAction': 'कागजात जाँचू',

  'auth.title': 'अपन मोबाइल नम्बर भरू',
  'auth.phone': 'मोबाइल नम्बर',
  'auth.phoneHint': 'हम एहि नम्बर पर एसएमएससँ 6 अंकक कोड पठाएब। हर बेर इएह नम्बर अहाँकेँ साइन इन करबैत अछि।',
  'auth.phoneMissing': 'आगाँ बढ़बा लेल अपन मोबाइल नम्बर दिअ।',
  'auth.phoneInvalid': 'ई ठीक नहि लागि रहल अछि। भारतीय मोबाइल नम्बर 10 अंकक होइत अछि आ 6, 7, 8 वा 9सँ शुरू होइत अछि।',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'नव होइ वा घुरि कऽ आबि रहल होइ, ओही नम्बर काज करैत अछि। अहाँक खाता नहि होइ तँ हम बना दैत छी।',
  'auth.stepOf': 'चरण {n} / 2 · {name}',
  'auth.stepPhone': 'अहाँक नम्बर',
  'auth.stepCode': 'अहाँक OTP कोड',
  'auth.privacy': 'अहाँक नम्बर मात्र अहाँकेँ साइन इन करबा लेल प्रयोग होइत अछि, आन कोनो काज लेल नहि। मोन राखबा लेल कोनो पासवर्ड नहि अछि।',
  'auth.sendCode': 'कोड पठाउ',
  'auth.sending': 'पठाओल जा रहल अछि…',
  'auth.checking': 'जाँचल जा रहल अछि…',
  'auth.welcomeBack': 'फेर स्वागत अछि। साइन इन करबा लेल कोड भरू।',
  'auth.newHere': 'कोड भरितहि हम अहाँक खाता बना देब।',
  'auth.codeTitle': 'हम जे कोड पठौलहुँ से भरू',
  'auth.code': '6 अंकक कोड',
  'auth.codeHint': 'सन्देश साधारणतः किछुए सेकेण्डमे आबि जाइत अछि।',
  'auth.noCode': 'आइ धरि सन्देश नहि आयल? आन उपाय आजमाउ:',
  'auth.verify': 'प्रमाणित करू',
  'auth.viaSms': 'एसएमएससँ पठाउ',
  'auth.viaWhatsapp': 'व्हाट्सऐप पर पठाउ',
  'auth.viaVoice': 'कोड कहबा लेल हमरा फोन करू',
  'auth.resentVia.sms': 'एसएमएससँ पठा देल। आबयमे किछु समय लागि सकैत अछि।',
  'auth.resentVia.whatsapp': 'व्हाट्सऐप पर पठा देल। सन्देश लेल व्हाट्सऐप देखू।',
  'auth.resentVia.voice': 'कोड कहबा लेल आबे फोन कऽ रहल छी। सुनबा लेल फोन उठाउ।',
  'auth.resendIn': '{n} सेकेण्डमे फेर पठाउ',
  'auth.changeNumber': 'दोसर नम्बर प्रयोग करू',
  'auth.change': 'बदलू',

  'profile.complete': '{n}% पूरा',
  'profile.viewLede': 'अहाँ हमरा जे किछु कहने छी। कोनो उत्तर बदलू आ ओकर बाद हर छात्रवृत्ति लेल इएह प्रयोग होयत।',
  'profile.notAnswered': 'आइ धरि उत्तर नहि देल',
  'profile.verified': 'प्रमाणित',
  'profile.continue': 'जतऽ छोड़ने रही ओतहिसँ आगाँ बढ़ू',
  'profile.start': 'अपन प्रोफाइल शुरू करू',
  'profile.saved': 'सुरक्षित भेल',

  'match.title': 'अहाँक लेल छात्रवृत्ति',
  'match.lede': 'अहाँक प्रोफाइलसँ जाँचल। जकरा लेल आवेदन कऽ सकैत छी से पहिने।',
  'match.eligible': 'अहाँ योग्य छी',
  'match.likely': 'अहाँ सम्भवतः योग्य छी',
  'match.blocked': 'पहिने एकटा काज',
  'match.actionable': 'अहाँक लेल खुजल',
  'match.actionableHelp': 'किछुक लेल आवेदनसँ पहिने एकटा कागजातक जरूरत भऽ सकैत अछि।',
  'match.ineligible': 'अहाँक लेल खुजल नहि',
  'match.eligibleHelp': 'हम जे किछु जाँचलहुँ से सभ प्रमाणित अछि।',
  'match.likelyHelp': 'अहाँ जे कहलहुँ ताहिक आधार पर। प्रमाणित करा लेलासँ अहाँक आवेदन मजबूत होइत अछि।',
  'match.blockedHelp': 'अहाँ लगीच छी। ई कऽ लिअ आ आवेदन कऽ सकब।',
  'match.ineligibleHelp': 'ई योजना एहन किछु मंगैत अछि जकरा अहाँ बदलि नहि सकैत छी।',
  'match.apply': 'आवेदन करू',
  'match.applied': 'अहाँ आवेदन कऽ देने छी',
  'match.none': 'आइ धरि कोनो मेल नहि',
  'match.noneHint': 'अपन प्रोफाइल पूरा करू आ हम अहाँक लेल हर छात्रवृत्ति जाँचब।',
  'match.figQualify': 'अहाँ योग्य छी',
  'match.figStep': 'एक डेग दूर',
  'match.figClosing': 'जल्दी बन्न',
  'match.figNo': 'अहाँक लेल खुजल नहि',
  'match.filterLabel': 'कोन छात्रवृत्ति देखाओल जाय',
  'match.filterAll': 'सभ',
  'match.filterQualify': 'अहाँ योग्य छी',
  'match.filterStep': 'एक डेग दूर',
  'match.filterClosing': 'जल्दी बन्न',
  'match.filterNo': 'अहाँक लेल खुजल नहि',
  'match.filterEmpty': 'एहि समूहमे किछु नहि। “सभ” आजमाउ।',
  'match.moreWithProfile': 'अहाँ जतेक भरब ततेक आओर छात्रवृत्ति देखाओत।',
  'match.youQualify': 'अहाँक प्रोफाइलक अनुसार अहाँ शर्त पूरा करैत छी।',
  'match.yesTitle': 'अहाँ आवेदन कऽ सकैत छी',
  'match.blockedTitle': 'पहिने एकटा काज',
  'match.noTitle': 'योग्य नहि',
  'match.appliedTitle': 'पहिनहिसँ पठाओल',
  'match.seeDetails': 'नियम देखू',
  'match.learnMore': 'आओर जानू',
  'match.runBy': '{kind} द्वारा संचालित',
  'match.sortBy': 'क्रम',
  'match.sortRecommended': 'सुझाओल गेल',
  'match.sortClosing': 'सभसँ पहिने बन्न होबय वला',
  'match.sortAward': 'सभसँ पैघ राशि',
  'match.applyAway': 'हुनकर साइट पर आवेदन करू',
  'match.applyHere': 'एतहि आवेदन करू',
  'match.notOpenToYou': 'वर्तमान स्थितिमे अहाँक लेल खुजल नहि।',
  'match.working': 'आब खुजल कोनो योजना अहाँक देल विवरणसँ मेल नहि खाइत अछि। प्रोफाइलमे आओर जोड़लासँ ई बदलैत अछि।',

  'doc.title': 'अहाँक कागजात',
  'doc.lede': 'एकटा कागजात एक बेर अपलोड करू। अहाँ जाहि छात्रवृत्ति लेल आवेदन करब ओ एकरा प्रयोग कऽ सकैत अछि — अहाँसँ फेर नहि मांगल जायत।',
  'doc.upload': 'कागजात जोड़ू',
  'doc.type': 'ई कोन कागजात अछि?',
  'doc.file': 'फाइल चुनू',
  'doc.fileHint': 'पीडीएफ वा साफ फोटो। 10 एमबी धरि।',
  'doc.verified': 'प्रमाणित',
  'doc.verifiedBy': '{org} द्वारा प्रमाणित',
  'doc.pending': 'प्रमाणीकरणक बाटमे',
  'doc.expired': 'प्रमाणीकरणक अवधि समाप्त',
  'doc.expiring': '{n} दिनमे अवधि समाप्त',
  'doc.validUntil': '{date} धरि मान्य',
  'doc.none': 'अहाँ आइ धरि कोनो कागजात नहि जोड़ने छी',
  'doc.uploading': 'अपलोड भऽ रहल अछि…',
  'doc.remove': 'हटाउ',
  'doc.removing': 'हटाओल जा रहल अछि…',

  'apply.title': 'आवेदन करू',
  'apply.consent': 'हमर विवरण एहि संस्थाक संग साझा करू',
  'apply.consentBody': 'निर्णय लेबा लेल एहि छात्रवृत्तिकेँ जे चाही मात्र सएह ओ देखताह: {fields}. अहाँक कागजात के देखलक से अहाँ कहियो देख सकैत छी।',
  'apply.consentBodyNoDocs': 'निर्णय लेबा लेल एहि छात्रवृत्तिकेँ जे चाही मात्र सएह ओ देखताह, आओर किछु नहि। अहाँक विवरण के देखलक से अहाँ कहियो देख सकैत छी।',
  'apply.submit': 'हमर आवेदन पठाउ',
  'apply.submitting': 'पठाओल जा रहल अछि…',
  'apply.blocked': 'अहाँ आइ धरि आवेदन नहि कऽ सकैत छी',
  'apply.needProfile': 'पहिने अहाँक प्रोफाइल',
  'apply.needProfileHint': 'आवेदन अहाँक प्रोफाइलसँ पठाओल जाइत अछि, तेँ आवेदनसँ पहिने ओ चाही। एहिमे किछुए मिनट लगैत अछि, आ अहाँ पहिने जे कहने छी से भरल भेटत।',
  'apply.elsewhereTitle': 'एकर आवेदन प्रायोजकक वेबसाइट पर होइत अछि',
  'apply.elsewhereBody': 'अहाँ ताकि सकी तेँ हम ई छात्रवृत्तिकेँ सूचीबद्ध करैत छी, आ आवेदन प्रायोजक अपने लैत छथि। अहाँ हमरा जे कहने छी से सुरक्षित रहैत अछि, आ जे छात्रवृत्ति हम चलबैत छी ताहि लेल पहिनहिसँ भरल रहैत अछि।',
  'apply.elsewhereBodyPartner': 'ई छात्रवृत्ति एतहि चलैत अछि, मुदा प्रायोजक आवेदन अपन वेबसाइट पर लैत छथि। अहाँ हमरा जे कहने छी से सुरक्षित रहैत अछि, आ जे आवेदन हमरा सोझे भेटैत अछि ताहि लेल पहिनहिसँ भरल रहैत अछि।',
  'apply.bundleTitle': 'अपन कागजात संगे लऽ जाउ',
  'apply.bundleBody': 'ई छात्रवृत्ति जे कागजात मंगैत अछि तकरा हम एकटा फाइलमे राखि सकैत छी, हुनकर वेबसाइट पर अपलोड करबा लेल तैयार। ओ जे चाहैत छथि आ हमरा लग आइ धरि नहि अछि, से सेहो एहिमे लिखल रहैत अछि।',
  'apply.bundleAction': 'हमर कागजात डाउनलोड करू',
  'apply.bundleWorking': 'तैयार कयल जा रहल अछि…',
  'apply.bundleDone': 'अहाँक कागजात डाउनलोड भऽ गेल अछि।',
  'apply.docs': 'एहि छात्रवृत्ति लेल आवश्यक कागजात',

  'appl.title': 'अहाँक आवेदन',
  'appl.none': 'अहाँ आइ धरि कोनो आवेदन नहि केने छी',
  'appl.noneHint': 'अहाँ जकरा लेल योग्य छी से छात्रवृत्ति ताकबा लेल अपन मेल देखू।',
  'appl.reference': 'सन्दर्भ',
  'appl.whatNext': 'आगाँ की होयत',
  'appl.history': 'इतिहास',
  'appl.needsYou': 'हुनका अहाँसँ किछु चाही',
  'track.label': 'एहि आवेदनक प्रगति',
  'track.sent': 'पठाओल',
  'track.review': 'समीक्षा',
  'track.decision': 'निर्णय',
  'track.doneSr': 'पूरा',
  'track.currentSr': 'आबे चलि रहल अछि',
  'track.todoSr': 'शुरू नहि भेल',
  'appl.sentOn': '{when} पठाओल',
  'appl.decidedOn': '{when} निर्णय भेल',
  'appl.outcomeApproved': 'भेटि गेल',
  'appl.outcomeRejected': 'एहि बेर नहि भेटल',
  'appl.outcomeWithdrawn': 'अहाँ एकरा वापस लऽ लेलहुँ',
  'appl.inProgress': 'संस्थाक लग',
  'appl.outcome': 'परिणाम',
  'appl.award': 'राशि',
  'appl.applied': 'आवेदन कयल',
  'appl.decided': 'निर्णय भेल',
  'appl.automatic': 'स्वचालित',
  'appl.noHistory': 'आइ धरि किछु नहि भेल।',

  'ref.heading': 'हुनकर वेबसाइट पर पठाओल',
  'ref.blurb': 'एकर आवेदन देनिहार संस्थाक अपन साइट पर होइत अछि, तेँ की भेल से हम नहि देख सकैत छी। हमरा कहू आ हम एकरा बाकीक संग राखि लेब।',
  'ref.sentOn': 'अहाँ एकरा {when} खोलने रही',
  'ref.again': 'कुल {times} बेर',
  'ref.open': 'हुनकर साइट फेर खोलू',
  'ref.what': 'की भेल?',
  'ref.APPLIED': 'हम आवेदन केलहुँ',
  'ref.AWARDED': 'हमरा भेटल',
  'ref.NOT_AWARDED': 'हमरा नहि भेटल',
  'ref.DID_NOT_APPLY': 'हम आवेदन नहि केलहुँ',
  'ref.saidAPPLIED': 'अहाँ आवेदन केलहुँ',
  'ref.saidAWARDED': 'अहाँकेँ भेटल',
  'ref.saidNOT_AWARDED': 'अहाँकेँ नहि भेटल',
  'ref.saidDID_NOT_APPLY': 'अहाँ आवेदन नहि केलहुँ',
  'ref.youSaid': 'अहाँ हमरा कहलहुँ: {what}',
  'ref.change': 'बदलू',

  'privacy.title': 'अहाँक डेटा',
  'privacy.lede': 'हमरा लग की अछि, के देखलक अछि, आ एकरा वापस कोना ली।',
  'privacy.access': 'अहाँक कागजात के देखने अछि',
  'privacy.accessNone': 'अहाँक अपन खाताक बाहर ककरो अहाँक कागजात नहि खोलने अछि।',
  'privacy.consents': 'अहाँ की साझा करबाक सहमति देने छी',
  'privacy.withdraw': 'वापस लिअ',
  'privacy.withdrawing': 'वापस लेल जा रहल अछि…',
  'privacy.export': 'हमरा लग जे किछु अछि से सभ डाउनलोड करू',
  'privacy.exporting': 'अहाँक प्रति तैयार कयल जा रहल अछि…',
  'privacy.exportBody': 'अहाँक डेटाक पूर्ण, मशीन-पठनीय प्रति।',
  'privacy.erase': 'हमर डेटा मेटाउ',
  'privacy.erasing': 'अनुरोध कयल जा रहल अछि…',
  'privacy.eraseBody': 'अहाँकेँ देल गेल कोनो छात्रवृत्तिक अभिलेख हमरा राखय पड़ैत अछि। बाकी सभ हटा देल जाइत अछि।',
  'auth.closedTitle': 'अहाँक खाता एहि समय बन्न अछि।',
  'auth.closedHelp': 'मदद चाही? हमर सहायता टीम अहाँकेँ बुझबामे मदद कऽ सकैत अछि ',
  'auth.closedSoon': 'सहायता मांगू (जल्दी)',
  'reg.district': 'जिला',
  'reg.districtHint': 'अहाँक क्षेत्रमे चलैत योजनासँ मेल करबामे मदद करैत अछि।',
  'privacy.requested': 'अनुरोध कयल',
  'privacy.window': 'आइ धरि किछु नहि मेटाओल गेल',
  'privacy.windowBody': 'अहाँक डेटा {date} केँ मेटा देल जायत। ताहि धरि अहाँ ',
  'privacy.cancel': 'ई अनुरोध रद्द करू',
  'privacy.cancelling': 'रद्द कयल जा रहल अछि…',
  'privacy.cancelled': 'अहाँक अनुरोध रद्द कऽ देल गेल अछि। किछु नहि मेटाओल गेल।',

  'common.loading': 'लोड भऽ रहल अछि',
  'common.retry': 'फेर प्रयास करू',
  'common.required': 'आवश्यक',
  'common.optional': 'वैकल्पिक',
  'common.error': 'किछु गड़बड़ भऽ गेल',
  'common.offline': 'अहाँ ऑफलाइन छी। अहाँक काज एहि डिवाइस पर सुरक्षित अछि।',

  'slides.lead.was': '',
  'slides.lead.able': 'क्षमतासँ',
  'slides.lead.dist': 'विशिष्टता धरि',
  'slides.lead.body': 'अहाँ जकरा लेल योग्य छी ओ हर छात्रवृत्ति — सरकारी आ निजी — अहाँक प्रोफाइलसँ मेल कऽ कऽ, अहाँक भाषामे, एक ठाम।',
  'slides.lead.free': 'पूर्णतः निःशुल्क',
  'slides.lead.languages': '14 भाषा',
  'slides.lead.support': 'हर डेग पर व्यक्तिगत सहायता',
  'slides.label': 'घोषणा',
  'slides.position': '{total}मे सँ {n}',
  'slides.goto': '{name} देखाउ',
  'slides.watch': 'वीडियो देखू',
  'slides.external': 'दोसर वेबसाइट खोलैत अछि',

  'home.title': 'दिव्यांग विद्यार्थी सभक लेल छात्रवृत्ति, एक ठाम',
  'home.lede': 'अपना बारेमे एक बेर कहू। हम एतऽक हर छात्रवृत्तिसँ अहाँकेँ जाँचैत छी आ कहैत छी जे अहाँ कोन लेल योग्य छी — आ बाकीक लेल ठीक-ठीक की छूटि रहल अछि।',
  'home.search': 'छात्रवृत्ति ताकू',
  'home.searchPlaceholder': 'जेना: इंजीनियरिंग, दिल्ली, पोस्ट-मैट्रिक',
  'home.searchGo': 'ताकू',
  'home.browseAll': 'सभ छात्रवृत्ति देखू',
  'home.openNow': 'छात्रवृत्ति आब खुजल अछि',
  'home.noAccount': 'देखबा लेल खाताक जरूरत नहि।',
  'home.openNone': 'एतऽ आइ धरि कोनो छात्रवृत्ति सूचीबद्ध नहि अछि।',
  'home.openNoneBody': 'सूची आब भरल जा रहल अछि। एतऽ किछु खाताक पाछाँ नहि अछि — योजना सूचीबद्ध होयबा पर अहाँ साइन इन केने बिना देख सकब।',
  'home.how': 'ई कोना काज करैत अछि',
  'home.howLede': 'पंजीकरण लेल एकटा मोबाइल नम्बर आ ओहि पर पठाओल कोड चाही। कोनो पासवर्ड नहि, आ पहिने भरबा लेल कोनो साइन-अप फॉर्म सेहो नहि।',
  'home.step1': 'पंजीकरण दबाउ',
  'home.step1Body': 'एहि पन्नाक ऊपर। पहिने आबि चुकल छी तँ बगलमे लॉगिन प्रयोग करू — दूनूमे ओही नम्बर काज करैत अछि।',
  'home.step2': 'अपन मोबाइल नम्बर भरू',
  'home.step2Body': 'दस अंक, +91 पहिनहिसँ भरल। ओहि नम्बर पर 6 अंकक कोड जाइत अछि।',
  'home.step3': 'कोड भरू',
  'home.step3Body': 'छह अंक टाइप करू आ अहाँ भीतर छी। जँ कोनो सन्देश नहि आबय, तँ कोड व्हाट्सऐप पर मांगू, वा हमरा फोन कऽ कऽ पढ़ि सुनबय लेल कहू।',
  'home.step4': 'अपन विवरण भरू',
  'home.step4Body': 'अहाँक नाम, अहाँक प्रमाणपत्र आ अहाँ कतऽ पढ़ैत छी — एक बेरमे एकटा प्रश्न, आ हर उत्तर दितहि सुरक्षित भऽ जाइत अछि।',
  'home.step5': 'अपन कागजात अपलोड करू',
  'home.step5Body': 'दिव्यांगता प्रमाणपत्र, यूडीआइडी कार्ड, आय प्रमाणपत्र आ बाकी। हर एकटा मात्र एक बेर, हर छात्रवृत्ति लेल अलगसँ नहि।',
  'home.step6': 'अपन मेल देखू',
  'home.step6Body': 'हमर मेल ओ छात्रवृत्ति सभ देखबैत अछि जकरा लेल अहाँ योग्य छी — आ जतऽ कोनो अहाँक लेल बन्न अछि, ओतऽ कारण कहैत अछि।',
  'home.step7': 'आवेदन करू',
  'home.step7Body': 'जे चाही से चुनू। अहाँक विवरण आ कागजात आवेदनक संग जाइत अछि।',
  'home.assure': 'जनबा योग्य',
  'home.assure1': 'मोन राखबा लेल कोनो पासवर्ड नहि',
  'home.assure2': 'अलग कोनो पंजीकरण फॉर्म नहि',
  'home.assure3': 'अहाँ रुकि कऽ बादमे पूरा कऽ सकैत छी',
  'home.help': 'कोनो चरण पर अटकि गेलहुँ?',
  'home.helpBody': 'फोन करू आ कियो अहाँकेँ पार करा देताह।',
  'home.helpCall': '{number} पर फोन करू',
  'home.closing': 'जल्दी बन्न',
  'home.closingLede': 'पहिने एकर लेल आवेदन करू।',
  'home.closingNext': 'अगिला अन्तिम तिथि',
  'home.closingNextLede': 'सभसँ पहिने बन्न होबय वला तीन।',
  'home.allDeadlines': 'सभ छात्रवृत्ति देखू',
  'home.browse': 'एकर अनुसार देखू',
  'home.browseWho': 'के दऽ रहल अछि',
  'home.browseLevel': 'अहाँक अध्ययनक स्तर',
  'home.cta': 'अपन मेल देखबा लेल तैयार छी?',
  'home.ctaBody': 'खाता बनबा लेल एकटा मोबाइल नम्बर वा एकटा ईमेल पता चाही। आओर किछु नहि।',
  'home.ctaButton': 'खाता बनाउ',
  'home.signedInCta': 'देखू अहाँ कोन लेल योग्य छी',

  'reg.title': 'छात्रवृत्ति ताकबा लेल पंजीकरण करू',
  'reg.editTitle': 'अपन विवरण अद्यतन करू',
  'reg.requiredNote': '* चिन्हित सभ खाना आवश्यक अछि।',
  'reg.personal': 'व्यक्तिगत विवरण',
  'reg.disability': 'दिव्यांगताक विवरण',
  'reg.education': 'शिक्षाक विवरण',
  'reg.name': 'पूरा नाम',
  'reg.namePlaceholder': 'अपन पूरा नाम लिखू',
  'reg.phoneHint': 'हम एहि नम्बर पर 6 अंकक कोड पठबैत छी। हर बेर इएह नम्बर अहाँकेँ साइन इन करबैत अछि।',
  'reg.sendOtp': 'ओटीपी पठाउ',
  'reg.otpPlaceholder': '6 अंकक ओटीपी लिखू',
  'reg.verified': 'फोन नम्बर प्रमाणित',
  'reg.verifyFirst': 'पंजीकरण पूरा करबा लेल अपन फोन नम्बर प्रमाणित करू।',
  'reg.email': 'ईमेल',
  'reg.emailHint': 'जाहिसँ हम अन्तिम तिथि मोन पाड़ि सकी। हम एकरा कहियो साझा नहि करैत छी।',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'लिंग',
  'reg.genderHint': '(किछु छात्रवृत्ति मात्र महिला वा ट्रांसजेंडर विद्यार्थी सभक लेल अछि)',
  'reg.udid': 'यूडीआइडी संख्या',
  'reg.udidHint': 'अहाँक यूडीआइडी (विशिष्ट दिव्यांगता पहचान) कार्ड पर लिखल संख्या।',
  'reg.udidPlaceholder': 'अपन यूडीआइडी संख्या लिखू',
  'reg.certificate': 'यूडीआइडी प्रमाणपत्र अपलोड करू',
  'reg.certificateHint': 'पीडीएफ वा चित्र, 5 एमबी वा ताहिसँ कम।',
  'reg.fileType': 'ओ फाइल पीडीएफ, जेपीईजी वा पीएनजी होयबाक चाही।',
  'reg.fileSize': 'ओ फाइल 5 एमबीसँ पैघ अछि। फोनसँ लेल फोटो साधारणतः छोट होइत अछि जँ अहाँ ओकरा खींचबाक बदला स्कैन करी।',
  'reg.fileLater': 'अहाँक पंजीकरण भऽ गेल आ विवरण सुरक्षित अछि। प्रमाणपत्र अपलोड नहि भेल — ओकरा हमर कागजातसँ जोड़ि दिअ, आओर किछु फेरसँ नहि करबाक अछि।',
  'reg.disabilityType': 'दिव्यांगताक प्रकार',
  'reg.percent': 'दिव्यांगताक प्रतिशत',
  'reg.percentHint': 'अहाँक प्रमाणपत्र पर लिखल आँकड़ा। बहुत छात्रवृत्ति लेल 40% वा ताहिसँ बेसी चाही।',
  'reg.percentPlaceholder': 'जेना 40',
  'reg.percentRange': 'प्रमाणपत्रक प्रतिशत 0 आ 100 बीचक पूर्ण संख्या होइत अछि।',
  'reg.state': 'राज्य',
  'reg.statePlaceholder': 'अपन राज्य ताकबा लेल टाइप करू…',
  'reg.program': 'अपन पाठ्यक्रम चुनू',
  'reg.graduation': 'स्नातक',
  'reg.postgraduation': 'स्नातकोत्तर / मास्टर्स',
  'reg.year': 'साल चुनू',
  'reg.yearAfterProgram': 'पहिने अपन पाठ्यक्रम चुनू',
  'reg.institution': 'विद्यालय / महाविद्यालयक नाम',
  'reg.institutionPlaceholder': 'अपन संस्थानक नाम लिखू',
  'reg.required': 'ई जरूरी अछि।',
  'reg.fix': 'किछु उत्तर पर ध्यान चाही। पहिल नीचाँ चुनल अछि।',
  'reg.cta': 'पंजीकरण करू आ छात्रवृत्ति ताकू',
  'reg.saveChanges': 'बदलाव सुरक्षित करू',
  'reg.saving': 'सुरक्षित कयल जा रहल अछि…',
  'reg.done': 'पंजीकरण भऽ गेल। अहाँक छात्रवृत्ति ताकल जा रहल अछि।',
  'reg.doneTitle': 'अहाँक पंजीकरण भऽ गेल अछि',
  'reg.already': 'पहिनहिसँ पंजीकृत छी?',
  'reg.login': 'ओटीपीसँ लॉगिन',
  'nav.registerCta': 'पंजीकरण',
  'nav.loginCta': 'लॉगिन',
  'profile.edit': 'अपन विवरण अद्यतन करू',
  'field.disability.BLINDNESS': 'दृष्टिहीनता',
  'field.disability.LOW_VISION': 'कम दृष्टि',
  'field.disability.LEPROSY_CURED': 'कुष्ठ रोग (नीक भेल)',
  'field.disability.HEARING_IMPAIRMENT': 'श्रवण बाधा',
  'field.disability.LOCOMOTOR_DISABILITY': 'चलन दिव्यांगता',
  'field.disability.DWARFISM': 'बौनापन',
  'field.disability.INTELLECTUAL_DISABILITY': 'बौद्धिक दिव्यांगता',
  'field.disability.MENTAL_ILLNESS': 'मानसिक बेमारी',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ऑटिज़्म स्पेक्ट्रम विकार',
  'field.disability.CEREBRAL_PALSY': 'प्रमस्तिष्क घात',
  'field.disability.MUSCULAR_DYSTROPHY': 'मांसपेशीय क्षय',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'दीर्घकालिक स्नायु सम्बन्धी स्थिति',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'विशिष्ट अधिगम दिव्यांगता',
  'field.disability.MULTIPLE_SCLEROSIS': 'मल्टिपल स्क्लेरोसिस',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'वाणी आ भाषा दिव्यांगता',
  'field.disability.THALASSEMIA': 'थैलेसीमिया',
  'field.disability.HAEMOPHILIA': 'हीमोफीलिया',
  'field.disability.SICKLE_CELL_DISEASE': 'सिकल सेल रोग',
  'field.disability.MULTIPLE_DISABILITIES': 'बहु दिव्यांगता, जाहिमे दृष्टि-श्रवण बाधा सेहो',
  'field.disability.ACID_ATTACK_VICTIM': 'तेजाब हमलासँ बाँचल',
  'field.disability.PARKINSONS_DISEASE': 'पार्किंसंस रोग',

  'field.state.AN': 'अंडमान आ निकोबार द्वीपसमूह',
  'field.state.AP': 'आंध्र प्रदेश',
  'field.state.AR': 'अरुणाचल प्रदेश',
  'field.state.AS': 'असम',
  'field.state.BR': 'बिहार',
  'field.state.CH': 'चंडीगढ़',
  'field.state.CT': 'छत्तीसगढ़',
  'field.state.DL': 'दिल्ली',
  'field.state.DN': 'दादरा आ नगर हवेली आ दमन आ दीव',
  'field.state.GA': 'गोवा',
  'field.state.GJ': 'गुजरात',
  'field.state.HP': 'हिमाचल प्रदेश',
  'field.state.HR': 'हरियाणा',
  'field.state.JH': 'झारखंड',
  'field.state.JK': 'जम्मू आ कश्मीर',
  'field.state.KA': 'कर्नाटक',
  'field.state.KL': 'केरल',
  'field.state.LA': 'लद्दाख',
  'field.state.LD': 'लक्षद्वीप',
  'field.state.MH': 'महाराष्ट्र',
  'field.state.ML': 'मेघालय',
  'field.state.MN': 'मणिपुर',
  'field.state.MP': 'मध्य प्रदेश',
  'field.state.MZ': 'मिज़ोरम',
  'field.state.NL': 'नागालैंड',
  'field.state.OR': 'ओडिशा',
  'field.state.PB': 'पंजाब',
  'field.state.PY': 'पुदुचेरी',
  'field.state.RJ': 'राजस्थान',
  'field.state.SK': 'सिक्किम',
  'field.state.TG': 'तेलंगाना',
  'field.state.TN': 'तमिलनाडु',
  'field.state.TR': 'त्रिपुरा',
  'field.state.UP': 'उत्तर प्रदेश',
  'field.state.UT': 'उत्तराखंड',
  'field.state.WB': 'पश्चिम बंगाल',

  'field.level.SCHOOL': 'विद्यालय',
  'field.level.SCHOOL.sub': 'वर्ग 9, 10, 11, 12',
  'field.level.UNDERGRADUATE': 'स्नातक',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech आ एहने',
  'field.level.POSTGRADUATE': 'स्नातकोत्तर',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech आ एहने',
  'field.level.DOCTORAL': 'डॉक्टरेट',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'विद्यालय',
  'field.qual.SCHOOL.sub': 'वर्ग 1 सँ 12',
  'field.qual.UNDERGRADUATE': 'स्नातक',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — आ डिप्लोमा वा ITI',
  'field.qual.POSTGRADUATE': 'स्नातकोत्तर',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA आ एहने',
  'field.qual.DOCTORAL': 'PhD / डॉक्टरेट',

  'field.subject.engineering': 'इंजीनियरिंग',
  'field.subject.medical': 'चिकित्सा',
  'field.subject.management': 'प्रबंधन',
  'field.subject.science': 'विज्ञान',
  'field.subject.commerce': 'वाणिज्य',
  'field.subject.arts': 'कला आ मानविकी',
  'field.subject.vocational': 'व्यावसायिक',
  'field.subject.fellowship': 'फेलोशिप',
  'field.subject.talent': 'प्रतिभा',
  'field.subject.sports': 'खेल',

  'field.gender.FEMALE': 'महिला',
  'field.gender.MALE': 'पुरुष',
  'field.gender.TRANSGENDER': 'ट्रांसजेंडर',
  'field.gender.UNDISCLOSED': 'कहय नहि चाहैत छी',
  'field.genderFilter.TRANSGENDER': 'तृतीय लिंग / ट्रांसजेंडर',

  'field.year.below9': 'वर्ग 9 सँ नीचाँ',
  'field.year.c9': 'वर्ग 9',
  'field.year.c10': 'वर्ग 10',
  'field.year.c11': 'वर्ग 11',
  'field.year.c12': 'वर्ग 12',
  'field.year.y1': 'पहिल वर्ष',
  'field.year.y2': 'दोसर वर्ष',
  'field.year.y3': 'तेसर वर्ष',
  'field.year.y4': 'चारिम वर्ष',
  'field.year.pg1': 'स्नातकोत्तर वर्ष 1',
  'field.year.pg2': 'स्नातकोत्तर वर्ष 2',

  'q.full_name': 'अहाँक नाम की अछि?',
  'q.full_name.help': 'ठीक जेना अहाँक दिव्यांगता प्रमाणपत्र पर लिखल अछि। देनिहार संस्था दूनूकेँ मिलाय कऽ देखैत अछि।',
  'q.gender': 'अहाँक लिंग की अछि?',
  'q.gender.help': 'किछु छात्रवृत्ति मात्र महिला लेल अछि, वा ट्रांसजेंडर विद्यार्थी लेल। कहय नहि चाही तँ छोड़ि दिअ।',
  'q.disability_type': 'अहाँक दिव्यांगता की अछि?',
  'q.disability_type.help': 'जेना अहाँक प्रमाणपत्र पर लिखल अछि। बेसी छात्रवृत्ति एहि परे छानैत अछि।',
  'q.disability_percent': 'अहाँक प्रमाणपत्र पर कतेक प्रतिशत अछि?',
  'q.disability_percent.help': '0 आ 100 बीचक एकटा संख्या। बहुत छात्रवृत्ति लेल 40% वा ताहिसँ बेसी चाही।',
  'q.disability_percent.range': 'प्रमाणपत्रक प्रतिशत 0 आ 100 बीचमे होइत अछि।',
  'q.udid_number': 'अहाँक UDID संख्या की अछि?',
  'q.udid_number.help': 'अहाँक UDID (विशिष्ट दिव्यांगता पहचान) कार्ड पर लिखल संख्या। जँ आइ धरि नहि भेटल अछि तँ छोड़ि दिअ — अहाँ कोन लेल योग्य छी ताहिमे एहिसँ कोनो अंतर नहि पड़ैत अछि, आ बादमे जोड़ि सकैत छी।',
  'q.date_of_birth': 'अहाँक जन्म कहिया भेल?',
  'q.date_of_birth.help': 'किछु छात्रवृत्तिमे आयु सीमा होइत अछि।',
  'q.course_name': 'अहाँ की पढ़ि रहल छी?',
  'q.course_name.help': 'पंजीकरणक समय अहाँ जे पाठ्यक्रम चुनने रही।',
  'q.institution_name': 'अहाँ कतऽ पढ़ैत छी?',
  'q.institution_name.help': 'अहाँक विद्यालय, महाविद्यालय वा विश्वविद्यालयक नाम, जेना अहाँक बोनाफाइड प्रमाणपत्र पर लिखल अछि। जँ आइ धरि शुरू नहि केने छी तँ छोड़ि दिअ।',
  'q.institution_name.placeholder': 'अहाँक विद्यालय वा महाविद्यालयक नाम',
  'q.state_code': 'अहाँ कोन राज्यमे रहैत छी?',
  'q.state_code.help': 'बहुत छात्रवृत्ति मात्र किछु राज्यक निवासी लेल खुजल अछि।',
  'q.annual_family_income': 'अहाँक परिवारक वार्षिक आय कतेक अछि?',
  'q.annual_family_income.help': 'टाकामे, जेना अहाँक आय प्रमाणपत्र पर अछि। बेसी छात्रवृत्तिमे एकटा सीमा होइत अछि।',
  'q.annual_family_income.range': 'आय शून्यसँ कम नहि भऽ सकैत अछि।',
  'q.academic_percentage': 'अहाँक पछिला परीक्षाक अंक कतेक छल?',
  'q.academic_percentage.help': 'अहाँक अंकपत्र जाहि तरहेँ ओकरा कहैत अछि से चुनू, तखन संख्या लिखू। बहुत छात्रवृत्ति न्यूनतम अंक मंगैत अछि।',
  'field.orgKind.NGO': 'एनजीओ',
  'field.orgKind.CORPORATE': 'कॉर्पोरेट',
  'field.orgKind.GOVERNMENT': 'सरकारी',
  'field.orgKind.PRIVATE': 'निजी',

  'field.doc.DISABILITY_CERTIFICATE': 'दिव्यांगता प्रमाणपत्र',
  'field.doc.UDID_CARD': 'यूडीआइडी कार्ड',
  'field.doc.INCOME_CERTIFICATE': 'आय प्रमाणपत्र',
  'field.doc.DOMICILE_CERTIFICATE': 'निवास प्रमाणपत्र',
  'field.doc.CASTE_CERTIFICATE': 'श्रेणी प्रमाणपत्र',
  'field.doc.MARKSHEET': 'अंकपत्र',
  'field.doc.ADMISSION_LETTER': 'नामांकन पत्र',
  'field.doc.BONAFIDE_CERTIFICATE': 'बोनाफाइड प्रमाणपत्र',
  'field.doc.FEE_RECEIPT': 'शुल्क रसीद',
  'field.doc.BANK_PASSBOOK': 'बैंक पासबुक',
  'field.doc.IDENTITY_PROOF': 'पहचानक प्रमाण',
  'field.doc.PHOTOGRAPH': 'फोटो',

  'appl.next.SUBMITTED': 'देनिहार संस्थाक लग अहाँक आवेदन अछि। आगाँ कियो समीक्षक एकरा पढ़ताह।',
  'appl.next.UNDER_REVIEW': 'एकटा समीक्षक अहाँक आवेदन पढ़ि रहल छथि। साधारणतः इएह सभसँ नमगर चरण होइत अछि।',
  'appl.next.INFO_REQUESTED': 'ओ अहाँसँ किछु मंगने छथि। जा धरि अहाँ उत्तर नहि दैत छी, आवेदन रुकल रहत।',
  'appl.next.DOCUMENT_CHECK': 'अहाँक आवेदन समीक्षकक लग अछि। अहाँसँ किछु नहि चाही।',
  'appl.next.VERIFIED': 'अहाँक आवेदन समीक्षकक लग अछि। अहाँसँ किछु नहि चाही।',
  'appl.next.SHORTLISTED': 'अहाँक आवेदन समीक्षकक लग अछि। आगाँ निर्णय अछि।',
  'appl.next.APPROVED': 'स्वीकृत। देनिहार संस्था स्वीकृति दर्ज करत, तखन भुगतानक व्यवस्था करत।',
  'appl.next.SANCTIONED': 'राशि स्वीकृत भऽ गेल। भुगतान हुनकर बैंक द्वारा होइत अछि।',
  'appl.next.DISBURSED': 'भुगतान दर्ज भऽ गेल। जँ किछु कार्यदिवसमे अहाँक खातामे नहि पहुँचय, तँ शिकायत करू।',
  'appl.next.REJECTED': 'ई आवेदन सफल नहि भेल। एकरासँ अहाँक आन आवेदन पर कोनो असर नहि पड़ैत अछि।',
  'appl.next.CLOSED': 'ई आवेदन पूरा भऽ गेल अछि।',
  'appl.next.WITHDRAWN': 'अहाँ ई आवेदन वापस लऽ लेने रही।',
}

export default mai
