/* Malayalam.
 *
 * One word per term: scholarship സ്കോളർഷിപ്പ്, application അപേക്ഷ,
 * document രേഖ, disability ഭിന്നശേഷി (Kerala's own term, in preference to
 * വൈകല്യം), verified സ്ഥിരീകരിച്ചു, eligible അർഹത,
 * certificate സർട്ടിഫിക്കറ്റ്, profile പ്രൊഫൈൽ.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const ml: Dict = {
  'app.name': 'സ്കോളർഷിപ്പ് പോർട്ടൽ',
  'app.tagline': 'ഭിന്നശേഷി വിദ്യാർഥികൾക്കായി',
  'app.yourApplication': 'നിങ്ങളുടെ അപേക്ഷ · {title}',

  'nav.find': 'സ്കോളർഷിപ്പുകൾ',
  'nav.how': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
  'nav.matches': 'എന്റെ പൊരുത്തങ്ങൾ',
  'nav.applications': 'എന്റെ അപേക്ഷകൾ',
  'nav.documents': 'എന്റെ രേഖകൾ',
  'nav.profile': 'എന്റെ പ്രൊഫൈൽ',
  'nav.privacy': 'എന്റെ വിവരങ്ങൾ',
  'nav.account': 'എന്റെ അക്കൗണ്ട്',
  'nav.register': 'സൈൻ അപ്പ്',
  'nav.language': 'ഭാഷ',
  'footer.social': 'ഇൻഡിക് എഐ മറ്റിടങ്ങളിൽ',
  'footer.sponsor': 'പിന്തുണയോടെ',
  'footer.copyright': 'പകർപ്പവകാശം © {year} ഇൻഡിക് എഐ | എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം',
  'nav.signin': 'സൈൻ ഇൻ',
  'nav.signout': 'സൈൻ ഔട്ട്',
  'nav.skip': 'പ്രധാന ഉള്ളടക്കത്തിലേക്ക് പോകുക',

  'public.title': 'നിങ്ങൾക്ക് അർഹതയുള്ള സ്കോളർഷിപ്പ് കണ്ടെത്തൂ',
  'public.lede': 'ഇവിടെയുള്ള എല്ലാ സ്കോളർഷിപ്പും ഭിന്നശേഷി വിദ്യാർഥികൾക്ക് തുറന്നതാണ്. കാണാൻ അക്കൗണ്ട് വേണ്ട.',
  'public.search': 'പേരോ വാക്കോ ഉപയോഗിച്ച് തിരയുക',
  'public.filter.disability': 'ഭിന്നശേഷിയുടെ തരം',
  'public.filter.qualification': 'യോഗ്യത',
  'public.filter.state': 'നിങ്ങളുടെ സംസ്ഥാനം',
  'public.filter.provider': 'ആരാണ് നൽകുന്നത്',
  'public.filter.any': 'ഏതെങ്കിലും',
  'public.filter.anyDisability': 'ഏത് ഭിന്നശേഷിയും',
  'public.filter.anyQualification': 'ഏത് യോഗ്യതയും',
  'public.filter.allStates': 'എല്ലാ സംസ്ഥാനങ്ങളും',
  'public.filter.gender': 'ലിംഗം',
  'public.filter.anyGender': 'ഏത് ലിംഗവും',
  'public.filter.course': 'കോഴ്സ്',
  'public.filter.anyCourse': 'ഏത് കോഴ്സും',
  'public.filter.where': 'നിങ്ങൾ എവിടെ പഠിക്കുന്നു',
  'public.filter.anyWhere': 'ഇന്ത്യയോ വിദേശമോ',
  'public.filter.inIndia': 'ഇന്ത്യയിൽ',
  'public.filter.abroad': 'വിദേശ പഠനം',
  'public.filters': 'ഫിൽട്ടറുകൾ',
  'public.clear': 'നീക്കുക',
  'public.results': 'സ്കോളർഷിപ്പുകൾ ഇപ്പോൾ തുറന്നിരിക്കുന്നു',
  'public.searching': 'തിരയുന്നു…',
  'public.none': 'ഈ ഫിൽട്ടറുകൾക്ക് ഒരു സ്കോളർഷിപ്പും ചേർന്നില്ല',
  'public.none.hint': 'ഒരു ഫിൽട്ടർ നീക്കി നോക്കൂ. വർഷം മുഴുവൻ പുതിയ പദ്ധതികൾ തുറക്കുന്നു.',
  'public.none.clear': 'എല്ലാ ഫിൽട്ടറുകളും നീക്കുക',
  'public.empty': 'ഇവിടെ ഇതുവരെ ഒരു സ്കോളർഷിപ്പും പട്ടികപ്പെടുത്തിയിട്ടില്ല',
  'public.empty.hint': 'ദാതാക്കളെ ഇപ്പോൾ ചേർക്കുന്നുണ്ട്. ഇവിടെ ഒന്നും അക്കൗണ്ടിനു പിന്നിലല്ല — പദ്ധതികൾ പട്ടികപ്പെടുത്തിയാൽ സൈൻ ഇൻ ചെയ്യാതെ തന്നെ കാണാം.',
  'public.whoFor': 'ഇത് ആർക്കുവേണ്ടി',
  'public.about': 'ഈ സ്കോളർഷിപ്പിനെക്കുറിച്ച്',
  'public.atAGlance': 'ഒറ്റനോട്ടത്തിൽ',
  'public.closes': 'അവസാനിക്കുന്നു',
  'public.awardUnstated': 'തുക പറഞ്ഞിട്ടില്ല',
  'public.noClose': 'അവസാന തീയതിയില്ല',
  'public.closesIn': '{n} ദിവസത്തിനുള്ളിൽ അവസാനിക്കും',
  'public.closesToday': 'ഇന്ന് അവസാനിക്കും',
  'public.closed': 'അവസാനിച്ചു',
  'public.award': 'തുക',
  'public.renewable': 'എല്ലാ വർഷവും പുതുക്കാം',
  'public.offeredBy': 'നൽകുന്നത്',
  'public.eligibility': 'അർഹത നേടാൻ',
  'public.benefits': 'ആനുകൂല്യങ്ങൾ',
  'public.readMore': 'കൂടുതൽ വായിക്കുക',
  'public.viewDetails': 'വിശദാംശങ്ങൾ കാണുക',
  'public.applyNow': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
  'public.registerToApply': 'അപേക്ഷിക്കുക',
  'public.registerToApplyHelp': 'അപേക്ഷകൾ നിങ്ങളുടെ അക്കൗണ്ട് വഴിയാണ് നൽകുന്നത്. രജിസ്റ്റർ ചെയ്താൽ നിങ്ങൾക്ക് അർഹതയുള്ള എല്ലാ സ്കോളർഷിപ്പും കാണാം.',
  'public.closedNote': 'ഈ പദ്ധതി അവസാനിച്ചു',
  'sheet.close': 'അടയ്ക്കുക',
  'sheet.loading': 'സ്കോളർഷിപ്പ് വിശദാംശങ്ങൾ',
  'public.benefitComponent': 'ഇനം',
  'public.benefitAmount': 'വിദ്യാർഥിക്ക് എന്ത് ലഭിക്കും',
  'public.whatYouGet': 'നിങ്ങൾക്ക് എന്ത് ലഭിക്കും',
  'public.eligibilityDetail': 'അർഹത വിശദമായി',
  'public.documentsRequired': 'ആവശ്യമായ രേഖകൾ',
  'public.documentsHelp': 'ദാതാവ് ഇവ ആവശ്യപ്പെടുന്നു. ഇവ നിങ്ങൾ ഇവിടെ അപ്‌ലോഡ് ചെയ്യുന്നില്ല.',
  'public.howToApply': 'എങ്ങനെ അപേക്ഷിക്കാം',
  'public.importantNotes': 'അറിഞ്ഞിരിക്കേണ്ടത്',
  'public.academicYear': 'ഏത് വർഷത്തേക്ക്',
  'public.awardBasis': 'എന്തിന്റെ അടിസ്ഥാനത്തിൽ',
  'public.basis.MERIT': 'മെറിറ്റ്',
  'public.basis.NEED': 'സാമ്പത്തിക ആവശ്യം',
  'public.basis.MERIT_CUM_MEANS': 'മെറിറ്റും വരുമാനവും',
  'public.basis.CATEGORY': 'വിഭാഗം',
  'public.basis.OTHER': 'മറ്റുള്ളവ',
  'public.cta': 'നിങ്ങൾക്കുള്ള സ്കോളർഷിപ്പുകൾ കണ്ടെത്തൂ',
  'public.applyExternal': 'അവരുടെ സൈറ്റിൽ അപേക്ഷിക്കുക',
  'public.applyExternalHelp': 'നിങ്ങൾക്ക് കണ്ടെത്താനാവാൻ വേണ്ടിയാണ് ഞങ്ങൾ ഈ സ്കോളർഷിപ്പ് പട്ടികപ്പെടുത്തുന്നത്. {org} ആണ് ഇത് നടത്തുന്നത്, അപേക്ഷകൾ സ്വന്തം വെബ്സൈറ്റിലാണ് സ്വീകരിക്കുന്നത്, അതിനാൽ ഇത് ഇവിടെ നിങ്ങളുടെ അപേക്ഷകളിൽ കാണില്ല.',
  'public.applyExternalHelpPartner': '{org} ഈ അപേക്ഷ സ്വന്തം വെബ്സൈറ്റിലാണ് സ്വീകരിക്കുന്നത്, അതിനാൽ ഇത് ഇവിടെ നിങ്ങളുടെ അപേക്ഷകളിൽ കാണില്ല.',
  'common.newTab': 'പുതിയ ടാബിൽ തുറക്കുന്നു',
  'public.applyHelp': 'ഞങ്ങൾ ആദ്യം നിങ്ങളുടെ പ്രൊഫൈലും രേഖകളും ഈ സ്കോളർഷിപ്പുമായി പരിശോധിച്ച്, എന്തെങ്കിലും കുറവുണ്ടെങ്കിൽ പറയും. നിങ്ങൾ സ്ഥിരീകരിക്കുന്നതുവരെ ഒന്നും അയയ്ക്കില്ല.',
  'public.ctaHelp': 'നിങ്ങളെക്കുറിച്ച് ഒരിക്കൽ പറയൂ, നിങ്ങൾക്ക് അർഹതയുള്ള എല്ലാ സ്കോളർഷിപ്പും കാണിച്ചുതരാം.',
  'public.back': 'എല്ലാ സ്കോളർഷിപ്പുകളിലേക്കും മടങ്ങുക',
  'notFound.title': 'ഈ പേജ് ഞങ്ങൾക്ക് കണ്ടെത്താനായില്ല',
  'notFound.body': 'വിലാസത്തിൽ ടൈപ്പിംഗ് പിശക് ഉണ്ടാകാം, അല്ലെങ്കിൽ പേജ് മാറ്റിയിരിക്കാം.',
  'notFound.home': 'ഹോം പേജിലേക്ക് പോകുക',

  'nav.dashboard': 'ഡാഷ്ബോർഡ്',
  'dash.title': 'നിങ്ങളുടെ ഡാഷ്ബോർഡ്',
  'dash.lede': 'നിങ്ങളുടെ സ്കോളർഷിപ്പുകൾ, അപേക്ഷകൾ, രേഖകൾ — എല്ലാം ഒരിടത്ത്.',
  'dash.matches': 'നിങ്ങൾക്ക് അപേക്ഷിക്കാവുന്ന സ്കോളർഷിപ്പുകൾ',
  'dash.matchesHint': 'നിങ്ങൾ നൽകിയ വിവരങ്ങളുടെ അടിസ്ഥാനത്തിൽ.',
  'dash.matchesBlocked': '{n} എണ്ണം നിങ്ങളിൽനിന്ന് ഒരു വിവരംകൂടി കാത്തിരിക്കുന്നു.',
  'dash.applications': 'നടന്നുകൊണ്ടിരിക്കുന്ന അപേക്ഷകൾ',
  'dash.applicationsHint': '{approved} അംഗീകരിച്ചു · {rejected} വിജയിച്ചില്ല',
  'dash.applicationsNone': 'ഇതുവരെ ഒന്നും അയച്ചിട്ടില്ല.',
  'dash.documents': 'സ്ഥിരീകരിച്ച രേഖകൾ',
  'dash.documentsHint': 'ഒരിക്കൽ പരിശോധിച്ചവ. എല്ലാ അപേക്ഷയ്ക്കും ഉപയോഗിക്കും.',
  'dash.funding': 'ഇതുവരെ ലഭിച്ചത്',
  'dash.fundingHint': 'ആകെ {sanctioned} അനുവദിച്ചു.',
  'dash.recent': 'സമീപകാല അപേക്ഷകൾ',
  'dash.noApplications': 'ഇതുവരെ അപേക്ഷകളില്ല',
  'dash.noApplicationsHint': 'നിങ്ങൾ എന്തിന് അപേക്ഷിച്ചാലും അത് ഇവിടെ കാണാം.',
  'dash.findScholarships': 'സ്കോളർഷിപ്പുകൾ കണ്ടെത്തൂ',
  'dash.profileTitle': 'നിങ്ങളുടെ പ്രൊഫൈൽ',
  'dash.toGo': '{n}% ബാക്കി',
  'dash.allApplications': 'എല്ലാം കാണുക',
  'dash.matchesGo': 'നിങ്ങളുടെ പൊരുത്തങ്ങൾ കാണുക',
  'dash.applicationsGo': 'നിങ്ങളുടെ അപേക്ഷകൾ നിരീക്ഷിക്കുക',
  'dash.documentsGo': 'രേഖകൾ കൈകാര്യം ചെയ്യുക',
  'dash.draftsTitle': '{n} അപേക്ഷ അയച്ചിട്ടില്ല | {n} അപേക്ഷകൾ അയച്ചിട്ടില്ല',
  'dash.draftsBody': 'അപേക്ഷ തുടങ്ങിയാൽ അത് അയച്ചെന്നല്ല. സ്കോളർഷിപ്പ് അവസാനിക്കുംമുമ്പ് പൂർത്തിയാക്കൂ.',
  'dash.draftsAction': 'ഇപ്പോൾ പൂർത്തിയാക്കുക',
  'dash.expiringTitle': '{n} രേഖയുടെ കാലാവധി ഉടൻ തീരും | {n} രേഖകളുടെ കാലാവധി ഉടൻ തീരും',
  'dash.expiringBody': 'എല്ലാ അപേക്ഷയ്ക്കും ഉപയോഗിക്കാൻ ഇത് ഇപ്പോൾതന്നെ മാറ്റൂ. | എല്ലാ അപേക്ഷയ്ക്കും ഉപയോഗിക്കാൻ ഇവ ഇപ്പോൾതന്നെ മാറ്റൂ.',
  'dash.expiringAction': 'രേഖകൾ പരിശോധിക്കുക',

  'auth.title': 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകൂ',
  'auth.phone': 'മൊബൈൽ നമ്പർ',
  'auth.phoneHint': 'ഈ നമ്പറിലേക്ക് 6 അക്ക കോഡ് SMS ആയി അയയ്ക്കും. എല്ലാ തവണയും ഈ നമ്പർതന്നെ നിങ്ങളെ സൈൻ ഇൻ ചെയ്യിക്കും.',
  'auth.phoneMissing': 'തുടരാൻ നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകൂ.',
  'auth.phoneInvalid': 'ഇത് ശരിയായി തോന്നുന്നില്ല. ഇന്ത്യൻ മൊബൈൽ നമ്പറുകൾ 10 അക്കങ്ങളാണ്, 6, 7, 8 അല്ലെങ്കിൽ 9 കൊണ്ട് തുടങ്ങും.',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'പുതിയ ആളായാലും മടങ്ങിവരുന്ന ആളായാലും അതേ നമ്പർ പ്രവർത്തിക്കും. അക്കൗണ്ട് ഇല്ലെങ്കിൽ ഞങ്ങൾ ഉണ്ടാക്കിത്തരും.',
  'auth.stepOf': 'ഘട്ടം {n} / 2 · {name}',
  'auth.stepPhone': 'നിങ്ങളുടെ നമ്പർ',
  'auth.stepCode': 'നിങ്ങളുടെ OTP കോഡ്',
  'auth.privacy': 'നിങ്ങളുടെ നമ്പർ സൈൻ ഇൻ ചെയ്യിക്കാൻ മാത്രമാണ് ഉപയോഗിക്കുന്നത്, മറ്റൊന്നിനുമല്ല. ഓർത്തിരിക്കാൻ പാസ്‌വേഡ് ഒന്നുമില്ല.',
  'auth.sendCode': 'കോഡ് അയയ്ക്കുക',
  'auth.sending': 'അയയ്ക്കുന്നു…',
  'auth.checking': 'പരിശോധിക്കുന്നു…',
  'auth.welcomeBack': 'വീണ്ടും സ്വാഗതം. സൈൻ ഇൻ ചെയ്യാൻ കോഡ് നൽകൂ.',
  'auth.newHere': 'കോഡ് നൽകിയാലുടൻ നിങ്ങളുടെ അക്കൗണ്ട് ഉണ്ടാക്കും.',
  'auth.codeTitle': 'ഞങ്ങൾ അയച്ച കോഡ് നൽകൂ',
  'auth.code': '6 അക്ക കോഡ്',
  'auth.codeHint': 'സന്ദേശം സാധാരണ ഏതാനും സെക്കൻഡിനുള്ളിൽ എത്തും.',
  'auth.noCode': 'ഇതുവരെ സന്ദേശം വന്നില്ലേ? മറ്റൊരു വഴി നോക്കൂ:',
  'auth.verify': 'പരിശോധിക്കുക',
  'auth.viaSms': 'SMS ആയി അയയ്ക്കുക',
  'auth.viaWhatsapp': 'വാട്സ്ആപ്പിൽ അയയ്ക്കുക',
  'auth.viaVoice': 'കോഡ് പറയാൻ എന്നെ വിളിക്കൂ',
  'auth.resentVia.sms': 'SMS ആയി അയച്ചു. എത്താൻ അൽപ്പസമയം എടുത്തേക്കാം.',
  'auth.resentVia.whatsapp': 'വാട്സ്ആപ്പിൽ അയച്ചു. സന്ദേശത്തിനായി വാട്സ്ആപ്പ് നോക്കൂ.',
  'auth.resentVia.voice': 'കോഡ് പറയാൻ ഇപ്പോൾ വിളിക്കുന്നു. കേൾക്കാൻ ഫോൺ എടുക്കൂ.',
  'auth.resendIn': '{n} സെക്കൻഡിൽ വീണ്ടും അയയ്ക്കുക',
  'auth.changeNumber': 'മറ്റൊരു നമ്പർ ഉപയോഗിക്കുക',
  'auth.change': 'മാറ്റുക',

  'profile.complete': '{n}% പൂർത്തിയായി',
  'profile.viewLede': 'നിങ്ങൾ ഞങ്ങളോട് പറഞ്ഞതെല്ലാം. ഏത് ഉത്തരവും മാറ്റൂ, അതിനുശേഷം എല്ലാ സ്കോളർഷിപ്പിനും അതുതന്നെ ഉപയോഗിക്കും.',
  'profile.notAnswered': 'ഇതുവരെ ഉത്തരം നൽകിയിട്ടില്ല',
  'profile.verified': 'സ്ഥിരീകരിച്ചു',
  'profile.continue': 'നിർത്തിയിടത്തുനിന്ന് തുടരൂ',
  'profile.start': 'നിങ്ങളുടെ പ്രൊഫൈൽ തുടങ്ങൂ',
  'profile.saved': 'സംരക്ഷിച്ചു',

  'match.title': 'നിങ്ങൾക്കുള്ള സ്കോളർഷിപ്പുകൾ',
  'match.lede': 'നിങ്ങളുടെ പ്രൊഫൈലുമായി ഒത്തുനോക്കിയത്. അപേക്ഷിക്കാവുന്നവ ആദ്യം.',
  'match.eligible': 'നിങ്ങൾക്ക് അർഹതയുണ്ട്',
  'match.likely': 'നിങ്ങൾക്ക് ഒരുപക്ഷേ അർഹതയുണ്ട്',
  'match.blocked': 'ആദ്യം ഒരു കാര്യം',
  'match.actionable': 'നിങ്ങൾക്ക് തുറന്നത്',
  'match.actionableHelp': 'ചിലതിന് അപേക്ഷിക്കുംമുമ്പ് ഒരു രേഖ വേണ്ടിവന്നേക്കാം.',
  'match.ineligible': 'നിങ്ങൾക്ക് തുറന്നിട്ടില്ല',
  'match.eligibleHelp': 'ഞങ്ങൾ പരിശോധിച്ചതെല്ലാം സ്ഥിരീകരിച്ചതാണ്.',
  'match.likelyHelp': 'നിങ്ങൾ പറഞ്ഞതിന്റെ അടിസ്ഥാനത്തിൽ. സ്ഥിരീകരിച്ചാൽ നിങ്ങളുടെ അപേക്ഷ കൂടുതൽ ശക്തമാകും.',
  'match.blockedHelp': 'നിങ്ങൾ അടുത്തെത്തി. ഇത് ചെയ്താൽ അപേക്ഷിക്കാം.',
  'match.ineligibleHelp': 'നിങ്ങൾക്ക് മാറ്റാനാവാത്ത ഒന്നാണ് ഈ പദ്ധതി ചോദിക്കുന്നത്.',
  'match.apply': 'അപേക്ഷിക്കുക',
  'match.applied': 'നിങ്ങൾ അപേക്ഷിച്ചിട്ടുണ്ട്',
  'match.none': 'ഇതുവരെ പൊരുത്തങ്ങളില്ല',
  'match.noneHint': 'നിങ്ങളുടെ പ്രൊഫൈൽ പൂർത്തിയാക്കൂ, എല്ലാ സ്കോളർഷിപ്പും നിങ്ങൾക്കായി പരിശോധിക്കാം.',
  'match.figQualify': 'നിങ്ങൾക്ക് അർഹതയുണ്ട്',
  'match.figStep': 'ഒരു ചുവട് അകലെ',
  'match.figClosing': 'ഉടൻ അവസാനിക്കും',
  'match.figNo': 'നിങ്ങൾക്ക് തുറന്നിട്ടില്ല',
  'match.filterLabel': 'ഏത് സ്കോളർഷിപ്പുകൾ കാണിക്കണം',
  'match.filterAll': 'എല്ലാം',
  'match.filterQualify': 'നിങ്ങൾക്ക് അർഹതയുണ്ട്',
  'match.filterStep': 'ഒരു ചുവട് അകലെ',
  'match.filterClosing': 'ഉടൻ അവസാനിക്കും',
  'match.filterNo': 'നിങ്ങൾക്ക് തുറന്നിട്ടില്ല',
  'match.filterEmpty': 'ഈ കൂട്ടത്തിൽ ഒന്നുമില്ല. “എല്ലാം” നോക്കൂ.',
  'match.moreWithProfile': 'നിങ്ങൾ പൂരിപ്പിക്കുന്തോറും കൂടുതൽ സ്കോളർഷിപ്പുകൾ കാണാം.',
  'match.youQualify': 'നിങ്ങളുടെ പ്രൊഫൈൽ പ്രകാരം നിങ്ങൾ നിബന്ധനകൾ പാലിക്കുന്നു.',
  'match.yesTitle': 'നിങ്ങൾക്ക് അപേക്ഷിക്കാം',
  'match.blockedTitle': 'ആദ്യം ഒരു കാര്യം',
  'match.noTitle': 'അർഹതയില്ല',
  'match.appliedTitle': 'ഇതിനകം അയച്ചു',
  'match.seeDetails': 'നിബന്ധനകൾ കാണുക',
  'match.learnMore': 'കൂടുതൽ അറിയുക',
  'match.runBy': '{kind} നടത്തുന്നു',
  'match.sortBy': 'ക്രമീകരിക്കുക',
  'match.sortRecommended': 'ശുപാർശ ചെയ്തവ',
  'match.sortClosing': 'ആദ്യം അവസാനിക്കുന്നവ',
  'match.sortAward': 'ഏറ്റവും വലിയ തുക',
  'match.applyAway': 'അവരുടെ സൈറ്റിൽ അപേക്ഷിക്കുക',
  'match.applyHere': 'ഇവിടെത്തന്നെ അപേക്ഷിക്കുക',
  'match.notOpenToYou': 'ഇപ്പോഴത്തെ അവസ്ഥയിൽ നിങ്ങൾക്ക് തുറന്നിട്ടില്ല.',
  'match.working': 'ഇപ്പോൾ തുറന്ന ഒരു പദ്ധതിയും നിങ്ങൾ നൽകിയ വിവരങ്ങളുമായി ചേരുന്നില്ല. പ്രൊഫൈലിൽ കൂടുതൽ ചേർക്കുന്നതാണ് ഇത് മാറ്റുന്നത്.',

  'doc.title': 'നിങ്ങളുടെ രേഖകൾ',
  'doc.lede': 'ഒരു രേഖ ഒരിക്കൽ അപ്‌ലോഡ് ചെയ്യൂ. നിങ്ങൾ അപേക്ഷിക്കുന്ന എല്ലാ സ്കോളർഷിപ്പിനും അത് ഉപയോഗിക്കാം — വീണ്ടും ചോദിക്കില്ല.',
  'doc.upload': 'രേഖ ചേർക്കുക',
  'doc.type': 'ഇത് ഏത് രേഖയാണ്?',
  'doc.file': 'ഫയൽ തിരഞ്ഞെടുക്കുക',
  'doc.fileHint': 'PDF അല്ലെങ്കിൽ വ്യക്തമായ ഫോട്ടോ. 10 MB വരെ.',
  'doc.verified': 'സ്ഥിരീകരിച്ചു',
  'doc.verifiedBy': '{org} സ്ഥിരീകരിച്ചു',
  'doc.pending': 'സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു',
  'doc.expired': 'സ്ഥിരീകരണത്തിന്റെ കാലാവധി തീർന്നു',
  'doc.expiring': '{n} ദിവസത്തിനുള്ളിൽ കാലാവധി തീരും',
  'doc.validUntil': '{date} വരെ സാധുവാണ്',
  'doc.none': 'നിങ്ങൾ ഇതുവരെ ഒരു രേഖയും ചേർത്തിട്ടില്ല',
  'doc.uploading': 'അപ്‌ലോഡ് ചെയ്യുന്നു…',
  'doc.remove': 'നീക്കുക',
  'doc.removing': 'നീക്കുന്നു…',

  'apply.title': 'അപേക്ഷിക്കുക',
  'apply.consent': 'എന്റെ വിവരങ്ങൾ ഈ ദാതാവുമായി പങ്കുവെക്കുക',
  'apply.consentBody': 'തീരുമാനമെടുക്കാൻ ഈ സ്കോളർഷിപ്പിന് വേണ്ടത് മാത്രമേ അവർ കാണൂ: {fields}. നിങ്ങളുടെ രേഖകൾ ആര് കണ്ടുവെന്ന് എപ്പോൾ വേണമെങ്കിലും കാണാം.',
  'apply.consentBodyNoDocs': 'തീരുമാനമെടുക്കാൻ ഈ സ്കോളർഷിപ്പിന് വേണ്ടത് മാത്രമേ അവർ കാണൂ, മറ്റൊന്നുമില്ല. നിങ്ങളുടെ വിവരങ്ങൾ ആര് കണ്ടുവെന്ന് എപ്പോൾ വേണമെങ്കിലും കാണാം.',
  'apply.submit': 'എന്റെ അപേക്ഷ അയയ്ക്കുക',
  'apply.submitting': 'അയയ്ക്കുന്നു…',
  'apply.blocked': 'നിങ്ങൾക്ക് ഇതുവരെ അപേക്ഷിക്കാനാവില്ല',
  'apply.needProfile': 'ആദ്യം നിങ്ങളുടെ പ്രൊഫൈൽ',
  'apply.needProfileHint': 'അപേക്ഷ നിങ്ങളുടെ പ്രൊഫൈലിൽനിന്നാണ് അയയ്ക്കുന്നത്, അതിനാൽ അപേക്ഷിക്കുംമുമ്പ് അത് വേണം. ഏതാനും മിനിറ്റേ എടുക്കൂ, നിങ്ങൾ നേരത്തേ പറഞ്ഞതെല്ലാം പൂരിപ്പിച്ചിരിക്കും.',
  'apply.elsewhereTitle': 'ഇതിന് സ്പോൺസറുടെ വെബ്സൈറ്റിലാണ് അപേക്ഷിക്കേണ്ടത്',
  'apply.elsewhereBody': 'നിങ്ങൾക്ക് കണ്ടെത്താനാവാൻ വേണ്ടിയാണ് ഞങ്ങൾ ഈ സ്കോളർഷിപ്പ് പട്ടികപ്പെടുത്തുന്നത്, അപേക്ഷകൾ സ്പോൺസർ തന്നെ സ്വീകരിക്കുന്നു. നിങ്ങൾ ഞങ്ങളോട് പറഞ്ഞതെല്ലാം സംരക്ഷിക്കപ്പെടുന്നു, ഞങ്ങൾ നടത്തുന്ന സ്കോളർഷിപ്പുകൾക്ക് അത് നേരത്തേ പൂരിപ്പിച്ചിരിക്കും.',
  'apply.elsewhereBodyPartner': 'ഈ സ്കോളർഷിപ്പ് ഇവിടെത്തന്നെയാണ് നടത്തുന്നത്, പക്ഷേ സ്പോൺസർ അപേക്ഷകൾ സ്വന്തം വെബ്സൈറ്റിലാണ് സ്വീകരിക്കുന്നത്. നിങ്ങൾ ഞങ്ങളോട് പറഞ്ഞതെല്ലാം സംരക്ഷിക്കപ്പെടുന്നു, ഞങ്ങൾക്ക് നേരിട്ട് കിട്ടുന്ന സ്കോളർഷിപ്പുകൾക്ക് അത് നേരത്തേ പൂരിപ്പിച്ചിരിക്കും.',
  'apply.bundleTitle': 'നിങ്ങളുടെ രേഖകൾ കൂടെ കൊണ്ടുപോകൂ',
  'apply.bundleBody': 'ഈ സ്കോളർഷിപ്പ് ചോദിക്കുന്ന രേഖകൾ ഞങ്ങൾക്ക് ഒരൊറ്റ ഫയലാക്കി നൽകാം, അവരുടെ വെബ്സൈറ്റിൽ അപ്‌ലോഡ് ചെയ്യാൻ തയ്യാറായി. അവർ ചോദിക്കുന്നതും ഞങ്ങളുടെ പക്കൽ ഇതുവരെ ഇല്ലാത്തതും അതിൽ പട്ടികപ്പെടുത്തും.',
  'apply.bundleAction': 'എന്റെ രേഖകൾ ഡൗൺലോഡ് ചെയ്യുക',
  'apply.bundleWorking': 'തയ്യാറാക്കുന്നു…',
  'apply.bundleDone': 'നിങ്ങളുടെ രേഖകൾ ഡൗൺലോഡ് ചെയ്തു.',
  'apply.docs': 'ഈ സ്കോളർഷിപ്പിന് വേണ്ട രേഖകൾ',

  'appl.title': 'നിങ്ങളുടെ അപേക്ഷകൾ',
  'appl.none': 'നിങ്ങൾ ഇതുവരെ ഒന്നിനും അപേക്ഷിച്ചിട്ടില്ല',
  'appl.noneHint': 'നിങ്ങൾക്ക് അർഹതയുള്ള സ്കോളർഷിപ്പുകൾ കണ്ടെത്താൻ നിങ്ങളുടെ പൊരുത്തങ്ങൾ നോക്കൂ.',
  'appl.reference': 'റഫറൻസ്',
  'appl.whatNext': 'അടുത്തത് എന്ത് സംഭവിക്കും',
  'appl.history': 'ചരിത്രം',
  'appl.needsYou': 'അവർക്ക് നിങ്ങളിൽനിന്ന് എന്തോ വേണം',
  'track.label': 'ഈ അപേക്ഷയുടെ പുരോഗതി',
  'track.sent': 'അയച്ചു',
  'track.review': 'പരിശോധന',
  'track.decision': 'തീരുമാനം',
  'track.doneSr': 'പൂർത്തിയായി',
  'track.currentSr': 'ഇപ്പോൾ നടക്കുന്നു',
  'track.todoSr': 'തുടങ്ങിയിട്ടില്ല',
  'appl.sentOn': '{when} അയച്ചു',
  'appl.decidedOn': '{when} തീരുമാനിച്ചു',
  'appl.outcomeApproved': 'ലഭിച്ചു',
  'appl.outcomeRejected': 'ഇത്തവണ ലഭിച്ചില്ല',
  'appl.outcomeWithdrawn': 'നിങ്ങൾ ഇത് പിൻവലിച്ചു',
  'appl.inProgress': 'ദാതാവിന്റെ പക്കൽ',
  'appl.outcome': 'ഫലം',
  'appl.award': 'തുക',
  'appl.applied': 'അപേക്ഷിച്ചു',
  'appl.decided': 'തീരുമാനിച്ചു',
  'appl.automatic': 'സ്വയമേവ',
  'appl.noHistory': 'ഇതുവരെ ഒന്നും സംഭവിച്ചിട്ടില്ല.',

  'ref.heading': 'അവരുടെ വെബ്സൈറ്റിലേക്ക് അയച്ചു',
  'ref.blurb': 'ഇവയ്ക്ക് ദാതാവിന്റെ സ്വന്തം സൈറ്റിലാണ് അപേക്ഷിക്കേണ്ടത്, അതിനാൽ എന്ത് സംഭവിച്ചെന്ന് ഞങ്ങൾക്ക് കാണാനാവില്ല. ഞങ്ങളോട് പറയൂ, ബാക്കിയുള്ളവയോടൊപ്പം സൂക്ഷിക്കാം.',
  'ref.sentOn': 'നിങ്ങൾ ഇത് {when} തുറന്നു',
  'ref.again': 'ആകെ {times} തവണ',
  'ref.open': 'അവരുടെ സൈറ്റ് വീണ്ടും തുറക്കുക',
  'ref.what': 'എന്ത് സംഭവിച്ചു?',
  'ref.APPLIED': 'ഞാൻ അപേക്ഷിച്ചു',
  'ref.AWARDED': 'എനിക്ക് ലഭിച്ചു',
  'ref.NOT_AWARDED': 'എനിക്ക് ലഭിച്ചില്ല',
  'ref.DID_NOT_APPLY': 'ഞാൻ അപേക്ഷിച്ചില്ല',
  'ref.saidAPPLIED': 'നിങ്ങൾ അപേക്ഷിച്ചു',
  'ref.saidAWARDED': 'നിങ്ങൾക്ക് ലഭിച്ചു',
  'ref.saidNOT_AWARDED': 'നിങ്ങൾക്ക് ലഭിച്ചില്ല',
  'ref.saidDID_NOT_APPLY': 'നിങ്ങൾ അപേക്ഷിച്ചില്ല',
  'ref.youSaid': 'നിങ്ങൾ ഞങ്ങളോട് പറഞ്ഞത്: {what}',
  'ref.change': 'മാറ്റുക',

  'privacy.title': 'നിങ്ങളുടെ വിവരങ്ങൾ',
  'privacy.lede': 'ഞങ്ങളുടെ പക്കൽ എന്തുണ്ട്, ആര് കണ്ടു, അത് തിരിച്ചെടുക്കുന്നതെങ്ങനെ.',
  'privacy.access': 'നിങ്ങളുടെ രേഖകൾ ആര് കണ്ടു',
  'privacy.accessNone': 'നിങ്ങളുടെ സ്വന്തം അക്കൗണ്ടിന് പുറത്ത് ആരും നിങ്ങളുടെ രേഖകൾ തുറന്നിട്ടില്ല.',
  'privacy.consents': 'പങ്കുവെക്കാൻ നിങ്ങൾ സമ്മതിച്ചത്',
  'privacy.withdraw': 'പിൻവലിക്കുക',
  'privacy.withdrawing': 'പിൻവലിക്കുന്നു…',
  'privacy.export': 'ഞങ്ങളുടെ പക്കലുള്ളതെല്ലാം ഡൗൺലോഡ് ചെയ്യുക',
  'privacy.exporting': 'നിങ്ങളുടെ പകർപ്പ് തയ്യാറാക്കുന്നു…',
  'privacy.exportBody': 'നിങ്ങളുടെ വിവരങ്ങളുടെ പൂർണമായ, യന്ത്രം വായിക്കാവുന്ന പകർപ്പ്.',
  'privacy.erase': 'എന്റെ വിവരങ്ങൾ മായ്ക്കുക',
  'privacy.erasing': 'അഭ്യർഥിക്കുന്നു…',
  'privacy.eraseBody': 'നിങ്ങൾക്ക് നൽകിയ ഏതൊരു സ്കോളർഷിപ്പിന്റെയും രേഖകൾ ഞങ്ങൾ സൂക്ഷിക്കേണ്ടതുണ്ട്. ബാക്കിയെല്ലാം നീക്കം ചെയ്യും.',
  'auth.closedTitle': 'നിങ്ങളുടെ അക്കൗണ്ട് ഇപ്പോൾ അടച്ചിരിക്കുന്നു.',
  'auth.closedHelp': 'സഹായം വേണോ? ഞങ്ങളുടെ പിന്തുണാ സംഘത്തിന് നിങ്ങളെ മനസ്സിലാക്കാൻ സഹായിക്കാം ',
  'auth.closedSoon': 'പിന്തുണ അഭ്യർഥിക്കുക (ഉടൻ)',
  'reg.district': 'ജില്ല',
  'reg.districtHint': 'നിങ്ങളുടെ പ്രദേശത്ത് നടക്കുന്ന പദ്ധതികളുമായി ചേർക്കാൻ സഹായിക്കുന്നു.',
  'privacy.requested': 'അഭ്യർഥിച്ചു',
  'privacy.window': 'ഇതുവരെ ഒന്നും മായ്ച്ചിട്ടില്ല',
  'privacy.windowBody': 'നിങ്ങളുടെ വിവരങ്ങൾ {date}ന് മായ്ക്കും. അതുവരെ നിങ്ങൾക്ക് ',
  'privacy.cancel': 'ഈ അഭ്യർഥന റദ്ദാക്കുക',
  'privacy.cancelling': 'റദ്ദാക്കുന്നു…',
  'privacy.cancelled': 'നിങ്ങളുടെ അഭ്യർഥന റദ്ദാക്കി. ഒന്നും മായ്ച്ചിട്ടില്ല.',

  'common.loading': 'ലോഡ് ചെയ്യുന്നു',
  'common.retry': 'വീണ്ടും ശ്രമിക്കുക',
  'common.required': 'ആവശ്യം',
  'common.optional': 'ഐച്ഛികം',
  'common.error': 'എന്തോ പിഴച്ചു',
  'common.offline': 'നിങ്ങൾ ഓഫ്‌ലൈനാണ്. നിങ്ങളുടെ ജോലി ഈ ഉപകരണത്തിൽ സംരക്ഷിച്ചിട്ടുണ്ട്.',

  'slides.lead.was': '',
  'slides.lead.able': 'കഴിവിൽനിന്ന്',
  'slides.lead.dist': 'വിശിഷ്ടതയിലേക്ക്',
  'slides.lead.body': 'നിങ്ങൾക്ക് അർഹതയുള്ള എല്ലാ സ്കോളർഷിപ്പും — സർക്കാർ, സ്വകാര്യ — നിങ്ങളുടെ പ്രൊഫൈലുമായി ചേർത്ത്, നിങ്ങളുടെ ഭാഷയിൽ, ഒരിടത്ത്.',
  'slides.lead.free': 'പൂർണമായും സൗജന്യം',
  'slides.lead.languages': '14 ഭാഷകൾ',
  'slides.lead.support': 'ഓരോ ചുവടിലും വ്യക്തിഗത സഹായം',
  'slides.label': 'അറിയിപ്പുകൾ',
  'slides.position': '{total}-ൽ {n}',
  'slides.goto': '{name} കാണിക്കുക',
  'slides.watch': 'വീഡിയോ കാണുക',
  'slides.external': 'മറ്റൊരു വെബ്സൈറ്റ് തുറക്കുന്നു',

  'home.title': 'ഭിന്നശേഷി വിദ്യാർഥികൾക്കുള്ള സ്കോളർഷിപ്പുകൾ, ഒരിടത്ത്',
  'home.lede': 'നിങ്ങളെക്കുറിച്ച് ഒരിക്കൽ പറയൂ. ഇവിടത്തെ എല്ലാ സ്കോളർഷിപ്പുമായും നിങ്ങളെ ഒത്തുനോക്കി, ഏതിനൊക്കെ അർഹതയുണ്ടെന്ന് പറയാം — ബാക്കിയുള്ളവയ്ക്ക് എന്താണ് കുറവെന്നും കൃത്യമായി.',
  'home.search': 'സ്കോളർഷിപ്പുകൾ തിരയുക',
  'home.searchPlaceholder': 'ഉദാ: എൻജിനീയറിങ്, ഡൽഹി, പോസ്റ്റ്-മെട്രിക്',
  'home.searchGo': 'തിരയുക',
  'home.browseAll': 'എല്ലാ സ്കോളർഷിപ്പുകളും കാണുക',
  'home.openNow': 'സ്കോളർഷിപ്പുകൾ ഇപ്പോൾ തുറന്നിരിക്കുന്നു',
  'home.noAccount': 'കാണാൻ അക്കൗണ്ട് വേണ്ട.',
  'home.openNone': 'ഇവിടെ ഇതുവരെ ഒരു സ്കോളർഷിപ്പും പട്ടികപ്പെടുത്തിയിട്ടില്ല.',
  'home.openNoneBody': 'പട്ടിക ഇപ്പോൾ നിറയ്ക്കുന്നുണ്ട്. ഇവിടെ ഒന്നും അക്കൗണ്ടിനു പിന്നിലല്ല — പദ്ധതികൾ പട്ടികപ്പെടുത്തിയാൽ സൈൻ ഇൻ ചെയ്യാതെ തന്നെ കാണാം.',
  'home.how': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
  'home.howLede': 'രജിസ്റ്റർ ചെയ്യാൻ ഒരു മൊബൈൽ നമ്പറും അതിലേക്ക് ഞങ്ങൾ അയയ്ക്കുന്ന കോഡും മതി. പാസ്‌വേഡില്ല, ആദ്യം പൂരിപ്പിക്കാൻ സൈൻ-അപ്പ് ഫോമുമില്ല.',
  'home.step1': 'രജിസ്റ്റർ അമർത്തൂ',
  'home.step1Body': 'ഈ പേജിന്റെ മുകളിൽ. മുമ്പ് വന്നിട്ടുണ്ടെങ്കിൽ അടുത്തുള്ള ലോഗിൻ ഉപയോഗിക്കൂ — രണ്ടിലും അതേ നമ്പർ പ്രവർത്തിക്കും.',
  'home.step2': 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകൂ',
  'home.step2Body': 'പത്ത് അക്കങ്ങൾ, +91 നേരത്തേ പൂരിപ്പിച്ചിരിക്കും. ആ നമ്പറിലേക്ക് 6 അക്ക കോഡ് പോകും.',
  'home.step3': 'കോഡ് നൽകൂ',
  'home.step3Body': 'ആറ് അക്കം ടൈപ്പ് ചെയ്താൽ അകത്തെത്തും. സന്ദേശം വന്നില്ലെങ്കിൽ കോഡ് വാട്സ്ആപ്പിൽ ചോദിക്കൂ, അല്ലെങ്കിൽ ഞങ്ങൾ വിളിച്ച് വായിച്ചുതരാൻ പറയൂ.',
  'home.step4': 'നിങ്ങളുടെ വിവരങ്ങൾ പൂരിപ്പിക്കൂ',
  'home.step4Body': 'നിങ്ങളുടെ പേര്, സർട്ടിഫിക്കറ്റ്, എവിടെ പഠിക്കുന്നു — ഒരു സമയം ഒരു ചോദ്യം, ഓരോ ഉത്തരവും നൽകുമ്പോൾതന്നെ സംരക്ഷിക്കുന്നു.',
  'home.step5': 'നിങ്ങളുടെ രേഖകൾ അപ്‌ലോഡ് ചെയ്യൂ',
  'home.step5Body': 'ഭിന്നശേഷി സർട്ടിഫിക്കറ്റ്, UDID കാർഡ്, വരുമാന സർട്ടിഫിക്കറ്റ്, ബാക്കിയുള്ളവ. ഓരോന്നും ഒരിക്കൽ മാത്രം, ഓരോ സ്കോളർഷിപ്പിനും വെവ്വേറെയല്ല.',
  'home.step6': 'നിങ്ങളുടെ പൊരുത്തങ്ങൾ കാണൂ',
  'home.step6Body': 'എന്റെ പൊരുത്തങ്ങൾ നിങ്ങൾക്ക് അർഹതയുള്ള സ്കോളർഷിപ്പുകൾ പട്ടികപ്പെടുത്തുന്നു — ഒന്ന് നിങ്ങൾക്ക് അടഞ്ഞതാണെങ്കിൽ എന്തുകൊണ്ടെന്നും പറയുന്നു.',
  'home.step7': 'അപേക്ഷിക്കൂ',
  'home.step7Body': 'വേണ്ടവ തിരഞ്ഞെടുക്കൂ. നിങ്ങളുടെ വിവരങ്ങളും രേഖകളും അപേക്ഷയോടൊപ്പം പോകും.',
  'home.assure': 'അറിഞ്ഞിരിക്കാൻ',
  'home.assure1': 'ഓർത്തിരിക്കാൻ പാസ്‌വേഡില്ല',
  'home.assure2': 'വേറെ രജിസ്ട്രേഷൻ ഫോമില്ല',
  'home.assure3': 'നിർത്തി പിന്നീട് പൂർത്തിയാക്കാം',
  'home.help': 'ഏതെങ്കിലും ഘട്ടത്തിൽ കുടുങ്ങിയോ?',
  'home.helpBody': 'വിളിക്കൂ, ആരെങ്കിലും നിങ്ങളെ കൂട്ടിക്കൊണ്ടുപോകും.',
  'home.helpCall': '{number} എന്ന നമ്പറിൽ വിളിക്കൂ',
  'home.closing': 'ഉടൻ അവസാനിക്കും',
  'home.closingLede': 'ആദ്യം ഇവയ്ക്ക് അപേക്ഷിക്കൂ.',
  'home.closingNext': 'അടുത്ത അവസാന തീയതികൾ',
  'home.closingNextLede': 'ആദ്യം അവസാനിക്കുന്ന മൂന്ന്.',
  'home.allDeadlines': 'എല്ലാ സ്കോളർഷിപ്പുകളും കാണുക',
  'home.browse': 'ഇതനുസരിച്ച് കാണുക',
  'home.browseWho': 'ആരാണ് നൽകുന്നത്',
  'home.browseLevel': 'നിങ്ങളുടെ പഠന നിലവാരം',
  'home.cta': 'നിങ്ങളുടെ പൊരുത്തങ്ങൾ കാണാൻ തയ്യാറാണോ?',
  'home.ctaBody': 'അക്കൗണ്ട് ഉണ്ടാക്കാൻ ഒരു മൊബൈൽ നമ്പറോ ഇമെയിൽ വിലാസമോ മതി. മറ്റൊന്നും വേണ്ട.',
  'home.ctaButton': 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
  'home.signedInCta': 'നിങ്ങൾക്ക് എന്തിന് അർഹതയുണ്ടെന്ന് കാണൂ',

  'reg.title': 'സ്കോളർഷിപ്പുകൾ കണ്ടെത്താൻ രജിസ്റ്റർ ചെയ്യൂ',
  'reg.editTitle': 'നിങ്ങളുടെ വിവരങ്ങൾ പുതുക്കൂ',
  'reg.requiredNote': '* അടയാളമുള്ള എല്ലാ കള്ളികളും നിർബന്ധമാണ്.',
  'reg.personal': 'വ്യക്തിഗത വിവരങ്ങൾ',
  'reg.disability': 'ഭിന്നശേഷി വിവരങ്ങൾ',
  'reg.education': 'വിദ്യാഭ്യാസ വിവരങ്ങൾ',
  'reg.name': 'പൂർണ നാമം',
  'reg.namePlaceholder': 'നിങ്ങളുടെ പൂർണ നാമം നൽകൂ',
  'reg.phoneHint': 'ഈ നമ്പറിലേക്ക് 6 അക്ക കോഡ് അയയ്ക്കും. എല്ലാ തവണയും ഈ നമ്പർതന്നെ നിങ്ങളെ സൈൻ ഇൻ ചെയ്യിക്കും.',
  'reg.sendOtp': 'OTP അയയ്ക്കുക',
  'reg.otpPlaceholder': '6 അക്ക OTP നൽകൂ',
  'reg.verified': 'ഫോൺ നമ്പർ സ്ഥിരീകരിച്ചു',
  'reg.verifyFirst': 'രജിസ്ട്രേഷൻ പൂർത്തിയാക്കാൻ നിങ്ങളുടെ ഫോൺ നമ്പർ സ്ഥിരീകരിക്കൂ.',
  'reg.email': 'ഇമെയിൽ',
  'reg.emailHint': 'അവസാന തീയതി ഓർമിപ്പിക്കാൻ. ഇത് ഞങ്ങൾ ഒരിക്കലും പങ്കുവെക്കില്ല.',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'ലിംഗം',
  'reg.genderHint': '(ചില സ്കോളർഷിപ്പുകൾ സ്ത്രീകൾക്കോ ട്രാൻസ്ജെൻഡർ വിദ്യാർഥികൾക്കോ മാത്രമാണ്)',
  'reg.udid': 'UDID നമ്പർ',
  'reg.udidHint': 'നിങ്ങളുടെ UDID (വിശിഷ്ട ഭിന്നശേഷി തിരിച്ചറിയൽ) കാർഡിലെ നമ്പർ.',
  'reg.udidPlaceholder': 'നിങ്ങളുടെ UDID നമ്പർ നൽകൂ',
  'reg.certificate': 'UDID സർട്ടിഫിക്കറ്റ് അപ്‌ലോഡ് ചെയ്യൂ',
  'reg.certificateHint': 'PDF അല്ലെങ്കിൽ ചിത്രം, 5 MB അല്ലെങ്കിൽ കുറവ്.',
  'reg.fileType': 'ആ ഫയൽ PDF, JPEG അല്ലെങ്കിൽ PNG ആയിരിക്കണം.',
  'reg.fileSize': 'ആ ഫയൽ 5 MB-യിൽ വലുതാണ്. ഫോണിൽ എടുത്ത ചിത്രം ഫോട്ടോ എടുക്കുന്നതിനുപകരം സ്കാൻ ചെയ്താൽ സാധാരണ ചെറുതായിരിക്കും.',
  'reg.fileLater': 'നിങ്ങൾ രജിസ്റ്റർ ചെയ്തു, വിവരങ്ങൾ സംരക്ഷിച്ചു. സർട്ടിഫിക്കറ്റ് അപ്‌ലോഡ് ആയില്ല — എന്റെ രേഖകളിൽനിന്ന് ചേർക്കൂ, മറ്റൊന്നും വീണ്ടും ചെയ്യേണ്ടതില്ല.',
  'reg.disabilityType': 'ഭിന്നശേഷിയുടെ തരം',
  'reg.percent': 'ഭിന്നശേഷി ശതമാനം',
  'reg.percentHint': 'നിങ്ങളുടെ സർട്ടിഫിക്കറ്റിലെ സംഖ്യ. പല സ്കോളർഷിപ്പുകൾക്കും 40% അല്ലെങ്കിൽ കൂടുതൽ വേണം.',
  'reg.percentPlaceholder': 'ഉദാ. 40',
  'reg.percentRange': 'സർട്ടിഫിക്കറ്റ് ശതമാനം 0-നും 100-നും ഇടയിലുള്ള പൂർണസംഖ്യയാണ്.',
  'reg.state': 'സംസ്ഥാനം',
  'reg.statePlaceholder': 'നിങ്ങളുടെ സംസ്ഥാനം തിരയാൻ ടൈപ്പ് ചെയ്യൂ…',
  'reg.program': 'നിങ്ങളുടെ കോഴ്സ് തിരഞ്ഞെടുക്കൂ',
  'reg.graduation': 'ബിരുദം',
  'reg.postgraduation': 'ബിരുദാനന്തര ബിരുദം / മാസ്റ്റേഴ്സ്',
  'reg.year': 'വർഷം തിരഞ്ഞെടുക്കൂ',
  'reg.yearAfterProgram': 'ആദ്യം നിങ്ങളുടെ കോഴ്സ് തിരഞ്ഞെടുക്കൂ',
  'reg.institution': 'സ്കൂൾ / കോളേജിന്റെ പേര്',
  'reg.institutionPlaceholder': 'നിങ്ങളുടെ സ്ഥാപനത്തിന്റെ പേര് നൽകൂ',
  'reg.required': 'ഇത് വേണം.',
  'reg.fix': 'ചില ഉത്തരങ്ങൾക്ക് ശ്രദ്ധ വേണം. ആദ്യത്തേത് താഴെ തിരഞ്ഞെടുത്തിട്ടുണ്ട്.',
  'reg.cta': 'രജിസ്റ്റർ ചെയ്ത് സ്കോളർഷിപ്പുകൾ കണ്ടെത്തൂ',
  'reg.saveChanges': 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
  'reg.saving': 'സംരക്ഷിക്കുന്നു…',
  'reg.done': 'രജിസ്റ്റർ ചെയ്തു. നിങ്ങളുടെ സ്കോളർഷിപ്പുകൾ കണ്ടെത്തുന്നു.',
  'reg.doneTitle': 'നിങ്ങൾ രജിസ്റ്റർ ചെയ്തിരിക്കുന്നു',
  'reg.already': 'ഇതിനകം രജിസ്റ്റർ ചെയ്തോ?',
  'reg.login': 'OTP ഉപയോഗിച്ച് ലോഗിൻ',
  'nav.registerCta': 'രജിസ്റ്റർ',
  'nav.loginCta': 'ലോഗിൻ',
  'profile.edit': 'നിങ്ങളുടെ വിവരങ്ങൾ പുതുക്കൂ',
  'field.disability.BLINDNESS': 'അന്ധത',
  'field.disability.LOW_VISION': 'കാഴ്ചക്കുറവ്',
  'field.disability.LEPROSY_CURED': 'കുഷ്ഠം (ഭേദമായത്)',
  'field.disability.HEARING_IMPAIRMENT': 'കേൾവിക്കുറവ്',
  'field.disability.LOCOMOTOR_DISABILITY': 'ചലന ഭിന്നശേഷി',
  'field.disability.DWARFISM': 'വാമനത്വം',
  'field.disability.INTELLECTUAL_DISABILITY': 'ബൗദ്ധിക ഭിന്നശേഷി',
  'field.disability.MENTAL_ILLNESS': 'മാനസികരോഗം',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ഓട്ടിസം സ്പെക്ട്രം ഡിസോർഡർ',
  'field.disability.CEREBRAL_PALSY': 'സെറിബ്രൽ പാൾസി',
  'field.disability.MUSCULAR_DYSTROPHY': 'പേശീ ക്ഷയരോഗം',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'ദീർഘകാല നാഡീസംബന്ധമായ അവസ്ഥ',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'നിർദിഷ്ട പഠന ഭിന്നശേഷി',
  'field.disability.MULTIPLE_SCLEROSIS': 'മൾട്ടിപ്പിൾ സ്ക്ലിറോസിസ്',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'സംസാര, ഭാഷാ ഭിന്നശേഷി',
  'field.disability.THALASSEMIA': 'തലസീമിയ',
  'field.disability.HAEMOPHILIA': 'ഹീമോഫീലിയ',
  'field.disability.SICKLE_CELL_DISEASE': 'സിക്കിൾ സെൽ രോഗം',
  'field.disability.MULTIPLE_DISABILITIES': 'ഒന്നിലധികം ഭിന്നശേഷികൾ, ബധിരാന്ധത ഉൾപ്പെടെ',
  'field.disability.ACID_ATTACK_VICTIM': 'ആസിഡ് ആക്രമണത്തെ അതിജീവിച്ചവർ',
  'field.disability.PARKINSONS_DISEASE': 'പാർക്കിൻസൺസ് രോഗം',

  'field.state.AN': 'ആൻഡമാൻ നിക്കോബാർ ദ്വീപുകൾ',
  'field.state.AP': 'ആന്ധ്രാപ്രദേശ്',
  'field.state.AR': 'അരുണാചൽ പ്രദേശ്',
  'field.state.AS': 'അസം',
  'field.state.BR': 'ബിഹാർ',
  'field.state.CH': 'ചണ്ഡീഗഢ്',
  'field.state.CT': 'ഛത്തീസ്ഗഢ്',
  'field.state.DL': 'ഡൽഹി',
  'field.state.DN': 'ദാദ്ര നഗർ ഹവേലിയും ദാമനും ദിയുവും',
  'field.state.GA': 'ഗോവ',
  'field.state.GJ': 'ഗുജറാത്ത്',
  'field.state.HP': 'ഹിമാചൽ പ്രദേശ്',
  'field.state.HR': 'ഹരിയാന',
  'field.state.JH': 'ഝാർഖണ്ഡ്',
  'field.state.JK': 'ജമ്മു കശ്മീർ',
  'field.state.KA': 'കർണാടക',
  'field.state.KL': 'കേരളം',
  'field.state.LA': 'ലഡാക്ക്',
  'field.state.LD': 'ലക്ഷദ്വീപ്',
  'field.state.MH': 'മഹാരാഷ്ട്ര',
  'field.state.ML': 'മേഘാലയ',
  'field.state.MN': 'മണിപ്പൂർ',
  'field.state.MP': 'മധ്യപ്രദേശ്',
  'field.state.MZ': 'മിസോറം',
  'field.state.NL': 'നാഗാലാൻഡ്',
  'field.state.OR': 'ഒഡീഷ',
  'field.state.PB': 'പഞ്ചാബ്',
  'field.state.PY': 'പുതുച്ചേരി',
  'field.state.RJ': 'രാജസ്ഥാൻ',
  'field.state.SK': 'സിക്കിം',
  'field.state.TG': 'തെലങ്കാന',
  'field.state.TN': 'തമിഴ്‌നാട്',
  'field.state.TR': 'ത്രിപുര',
  'field.state.UP': 'ഉത്തർപ്രദേശ്',
  'field.state.UT': 'ഉത്തരാഖണ്ഡ്',
  'field.state.WB': 'പശ്ചിമ ബംഗാൾ',

  'field.level.SCHOOL': 'സ്കൂൾ',
  'field.level.SCHOOL.sub': '9, 10, 11, 12 ക്ലാസുകൾ',
  'field.level.UNDERGRADUATE': 'ബിരുദം',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech തുടങ്ങിയവ',
  'field.level.POSTGRADUATE': 'ബിരുദാനന്തര ബിരുദം',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech തുടങ്ങിയവ',
  'field.level.DOCTORAL': 'ഡോക്ടറേറ്റ്',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'സ്കൂൾ',
  'field.qual.SCHOOL.sub': '1 മുതൽ 12 വരെ ക്ലാസുകൾ',
  'field.qual.UNDERGRADUATE': 'ബിരുദം',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — കൂടാതെ ഡിപ്ലോമ അല്ലെങ്കിൽ ITI',
  'field.qual.POSTGRADUATE': 'ബിരുദാനന്തര ബിരുദം',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA തുടങ്ങിയവ',
  'field.qual.DOCTORAL': 'PhD / ഡോക്ടറേറ്റ്',

  'field.subject.engineering': 'എൻജിനീയറിങ്',
  'field.subject.medical': 'വൈദ്യശാസ്ത്രം',
  'field.subject.management': 'മാനേജ്മെന്റ്',
  'field.subject.science': 'ശാസ്ത്രം',
  'field.subject.commerce': 'വാണിജ്യം',
  'field.subject.arts': 'കലയും മാനവികവിഷയങ്ങളും',
  'field.subject.vocational': 'തൊഴിലധിഷ്ഠിതം',
  'field.subject.fellowship': 'ഫെലോഷിപ്പ്',
  'field.subject.talent': 'പ്രതിഭ',
  'field.subject.sports': 'കായികം',

  'field.gender.FEMALE': 'സ്ത്രീ',
  'field.gender.MALE': 'പുരുഷൻ',
  'field.gender.TRANSGENDER': 'ട്രാൻസ്ജെൻഡർ',
  'field.gender.UNDISCLOSED': 'പറയാൻ ആഗ്രഹിക്കുന്നില്ല',
  'field.genderFilter.TRANSGENDER': 'മൂന്നാം ലിംഗം / ട്രാൻസ്ജെൻഡർ',

  'field.year.below9': 'ഒൻപതാം ക്ലാസിന് താഴെ',
  'field.year.c9': 'ഒൻപതാം ക്ലാസ്',
  'field.year.c10': 'പത്താം ക്ലാസ്',
  'field.year.c11': 'പതിനൊന്നാം ക്ലാസ്',
  'field.year.c12': 'പന്ത്രണ്ടാം ക്ലാസ്',
  'field.year.y1': 'ഒന്നാം വർഷം',
  'field.year.y2': 'രണ്ടാം വർഷം',
  'field.year.y3': 'മൂന്നാം വർഷം',
  'field.year.y4': 'നാലാം വർഷം',
  'field.year.pg1': 'ബിരുദാനന്തര ഒന്നാം വർഷം',
  'field.year.pg2': 'ബിരുദാനന്തര രണ്ടാം വർഷം',

  'q.full_name': 'നിങ്ങളുടെ പേര് എന്താണ്?',
  'q.full_name.help': 'നിങ്ങളുടെ ഭിന്നശേഷി സർട്ടിഫിക്കറ്റിൽ ഉള്ളതുപോലെ തന്നെ. ദാതാക്കൾ രണ്ടും ഒത്തുപോകുന്നുണ്ടോ എന്ന് പരിശോധിക്കും.',
  'q.gender': 'നിങ്ങളുടെ ലിംഗം എന്താണ്?',
  'q.gender.help': 'ചില സ്കോളർഷിപ്പുകൾ സ്ത്രീകൾക്ക് മാത്രമാണ്, അല്ലെങ്കിൽ ട്രാൻസ്ജെൻഡർ വിദ്യാർഥികൾക്ക്. പറയാൻ ആഗ്രഹിക്കുന്നില്ലെങ്കിൽ വിട്ടേക്കൂ.',
  'q.disability_type': 'നിങ്ങളുടെ ഭിന്നശേഷി എന്താണ്?',
  'q.disability_type.help': 'നിങ്ങളുടെ സർട്ടിഫിക്കറ്റിൽ എഴുതിയിരിക്കുന്നതുപോലെ. മിക്ക സ്കോളർഷിപ്പുകളും ഇതിന്റെ അടിസ്ഥാനത്തിലാണ് അരിച്ചെടുക്കുന്നത്.',
  'q.disability_percent': 'നിങ്ങളുടെ സർട്ടിഫിക്കറ്റിൽ എത്ര ശതമാനമുണ്ട്?',
  'q.disability_percent.help': '0-നും 100-നും ഇടയിലുള്ള ഒരു സംഖ്യ. പല സ്കോളർഷിപ്പുകൾക്കും 40% അല്ലെങ്കിൽ അതിലധികം വേണം.',
  'q.disability_percent.range': 'സർട്ടിഫിക്കറ്റ് ശതമാനം 0-നും 100-നും ഇടയിലാണ്.',
  'q.udid_number': 'നിങ്ങളുടെ UDID നമ്പർ എന്താണ്?',
  'q.udid_number.help': 'നിങ്ങളുടെ UDID (വിശിഷ്ട ഭിന്നശേഷി തിരിച്ചറിയൽ) കാർഡിലെ നമ്പർ. ഇതുവരെ ലഭിച്ചിട്ടില്ലെങ്കിൽ വിട്ടേക്കൂ — നിങ്ങൾ എന്തിന് അർഹരാണ് എന്നതിൽ ഇത് ഒരു മാറ്റവും വരുത്തുന്നില്ല, പിന്നീട് ചേർക്കാം.',
  'q.date_of_birth': 'നിങ്ങൾ എപ്പോഴാണ് ജനിച്ചത്?',
  'q.date_of_birth.help': 'ചില സ്കോളർഷിപ്പുകൾക്ക് പ്രായപരിധിയുണ്ട്.',
  'q.course_name': 'നിങ്ങൾ എന്താണ് പഠിക്കുന്നത്?',
  'q.course_name.help': 'രജിസ്റ്റർ ചെയ്തപ്പോൾ നിങ്ങൾ തിരഞ്ഞെടുത്ത കോഴ്സ്.',
  'q.institution_name': 'നിങ്ങൾ എവിടെയാണ് പഠിക്കുന്നത്?',
  'q.institution_name.help': 'നിങ്ങളുടെ സ്കൂൾ, കോളേജ് അല്ലെങ്കിൽ സർവകലാശാലയുടെ പേര്, നിങ്ങളുടെ ബോണഫൈഡ് സർട്ടിഫിക്കറ്റിൽ എഴുതിയിരിക്കുന്നതുപോലെ. ഇതുവരെ തുടങ്ങിയിട്ടില്ലെങ്കിൽ വിട്ടേക്കൂ.',
  'q.institution_name.placeholder': 'നിങ്ങളുടെ സ്കൂളിന്റെയോ കോളേജിന്റെയോ പേര്',
  'q.state_code': 'നിങ്ങൾ ഏത് സംസ്ഥാനത്താണ് താമസിക്കുന്നത്?',
  'q.state_code.help': 'പല സ്കോളർഷിപ്പുകളും ചില സംസ്ഥാനങ്ങളിലെ താമസക്കാർക്ക് മാത്രമാണ് തുറന്നിരിക്കുന്നത്.',
  'q.annual_family_income': 'നിങ്ങളുടെ കുടുംബത്തിന്റെ വാർഷിക വരുമാനം എത്രയാണ്?',
  'q.annual_family_income.help': 'രൂപയിൽ, നിങ്ങളുടെ വരുമാന സർട്ടിഫിക്കറ്റിൽ ഉള്ളതുപോലെ. മിക്ക സ്കോളർഷിപ്പുകൾക്കും ഒരു പരിധിയുണ്ട്.',
  'q.annual_family_income.range': 'വരുമാനം പൂജ്യത്തിൽ കുറവാകാൻ കഴിയില്ല.',
  'q.academic_percentage': 'നിങ്ങളുടെ അവസാന പരീക്ഷയുടെ മാർക്ക് എത്രയായിരുന്നു?',
  'q.academic_percentage.help': 'നിങ്ങളുടെ മാർക്ക് ലിസ്റ്റ് അവ പറയുന്ന രീതി തിരഞ്ഞെടുത്ത്, പിന്നെ സംഖ്യ ടൈപ്പ് ചെയ്യൂ. പല സ്കോളർഷിപ്പുകളും ഒരു കുറഞ്ഞ മാർക്ക് ചോദിക്കുന്നു.',
  'field.orgKind.NGO': 'സന്നദ്ധ സംഘടന',
  'field.orgKind.CORPORATE': 'കോർപ്പറേറ്റ്',
  'field.orgKind.GOVERNMENT': 'സർക്കാർ',
  'field.orgKind.PRIVATE': 'സ്വകാര്യം',

  'field.doc.DISABILITY_CERTIFICATE': 'ഭിന്നശേഷി സർട്ടിഫിക്കറ്റ്',
  'field.doc.UDID_CARD': 'UDID കാർഡ്',
  'field.doc.INCOME_CERTIFICATE': 'വരുമാന സർട്ടിഫിക്കറ്റ്',
  'field.doc.DOMICILE_CERTIFICATE': 'സ്ഥിരതാമസ സർട്ടിഫിക്കറ്റ്',
  'field.doc.CASTE_CERTIFICATE': 'ജാതി സർട്ടിഫിക്കറ്റ്',
  'field.doc.MARKSHEET': 'മാർക്ക് ലിസ്റ്റ്',
  'field.doc.ADMISSION_LETTER': 'പ്രവേശന കത്ത്',
  'field.doc.BONAFIDE_CERTIFICATE': 'ബോണഫൈഡ് സർട്ടിഫിക്കറ്റ്',
  'field.doc.FEE_RECEIPT': 'ഫീസ് രസീത്',
  'field.doc.BANK_PASSBOOK': 'ബാങ്ക് പാസ്ബുക്ക്',
  'field.doc.IDENTITY_PROOF': 'തിരിച്ചറിയൽ രേഖ',
  'field.doc.PHOTOGRAPH': 'ഫോട്ടോ',

  'appl.next.SUBMITTED': 'ദാതാവിന്റെ പക്കൽ നിങ്ങളുടെ അപേക്ഷയുണ്ട്. അടുത്തതായി ഒരു പരിശോധകൻ അത് വായിക്കും.',
  'appl.next.UNDER_REVIEW': 'ഒരു പരിശോധകൻ നിങ്ങളുടെ അപേക്ഷ വായിക്കുന്നു. സാധാരണ ഇതാണ് ഏറ്റവും നീണ്ട ഘട്ടം.',
  'appl.next.INFO_REQUESTED': 'അവർ നിങ്ങളോട് എന്തോ ചോദിച്ചിട്ടുണ്ട്. നിങ്ങൾ മറുപടി നൽകുന്നതുവരെ അപേക്ഷ കാത്തിരിക്കും.',
  'appl.next.DOCUMENT_CHECK': 'നിങ്ങളുടെ അപേക്ഷ ഒരു പരിശോധകന്റെ പക്കലാണ്. നിങ്ങളിൽനിന്ന് ഒന്നും വേണ്ട.',
  'appl.next.VERIFIED': 'നിങ്ങളുടെ അപേക്ഷ ഒരു പരിശോധകന്റെ പക്കലാണ്. നിങ്ങളിൽനിന്ന് ഒന്നും വേണ്ട.',
  'appl.next.SHORTLISTED': 'നിങ്ങളുടെ അപേക്ഷ ഒരു പരിശോധകന്റെ പക്കലാണ്. അടുത്തത് തീരുമാനം.',
  'appl.next.APPROVED': 'അംഗീകരിച്ചു. ദാതാവ് അനുമതി രേഖപ്പെടുത്തി, പിന്നെ പണം നൽകാൻ ക്രമീകരിക്കും.',
  'appl.next.SANCTIONED': 'പണം അനുവദിച്ചു. പണം അവരുടെ ബാങ്ക് വഴിയാണ് നൽകുന്നത്.',
  'appl.next.DISBURSED': 'പണം നൽകിയത് രേഖപ്പെടുത്തി. ഏതാനും പ്രവൃത്തിദിവസങ്ങൾക്കുള്ളിൽ നിങ്ങളുടെ അക്കൗണ്ടിൽ എത്തിയില്ലെങ്കിൽ പരാതി നൽകൂ.',
  'appl.next.REJECTED': 'ഈ അപേക്ഷ വിജയിച്ചില്ല. ഇത് നിങ്ങളുടെ മറ്റ് അപേക്ഷകളെ ബാധിക്കില്ല.',
  'appl.next.CLOSED': 'ഈ അപേക്ഷ പൂർത്തിയായി.',
  'appl.next.WITHDRAWN': 'നിങ്ങൾ ഈ അപേക്ഷ പിൻവലിച്ചു.',
}

export default ml
