/* Odia.
 *
 * One word per term: scholarship ଛାତ୍ରବୃତ୍ତି, application ଆବେଦନ,
 * document ନଥି, disability ଦିବ୍ୟାଙ୍ଗତା, verified ସତ୍ୟାପିତ, eligible ଯୋଗ୍ୟ,
 * certificate ପ୍ରମାଣପତ୍ର, profile ପ୍ରୋଫାଇଲ୍.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const or: Dict = {
  'app.name': 'ଛାତ୍ରବୃତ୍ତି ପୋର୍ଟାଲ',
  'app.tagline': 'ଦିବ୍ୟାଙ୍ଗ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ',
  'app.yourApplication': 'ଆପଣଙ୍କ ଆବେଦନ · {title}',

  'nav.find': 'ଛାତ୍ରବୃତ୍ତି',
  'nav.how': 'ଏହା କିପରି କାମ କରେ',
  'nav.matches': 'ମୋର ମେଳ',
  'nav.applications': 'ମୋର ଆବେଦନ',
  'nav.documents': 'ମୋର ନଥି',
  'nav.profile': 'ମୋର ପ୍ରୋଫାଇଲ୍',
  'nav.privacy': 'ମୋର ତଥ୍ୟ',
  'nav.account': 'ମୋର ଖାତା',
  'nav.register': 'ସାଇନ୍ ଅପ୍',
  'nav.language': 'ଭାଷା',
  'footer.social': 'ଇଣ୍ଡିକ୍ ଏଆଇ ଅନ୍ୟତ୍ର',
  'footer.sponsor': 'ସହଯୋଗରେ',
  'footer.copyright': 'କପିରାଇଟ୍ © {year} ଇଣ୍ଡିକ୍ ଏଆଇ | ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ',
  'nav.signin': 'ସାଇନ୍ ଇନ୍',
  'nav.signout': 'ସାଇନ୍ ଆଉଟ୍',
  'nav.skip': 'ମୁଖ୍ୟ ବିଷୟବସ୍ତୁକୁ ଯାଆନ୍ତୁ',

  'public.title': 'ଆପଣ ଯୋଗ୍ୟ ଥିବା ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ',
  'public.lede': 'ଏଠାରେ ଥିବା ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ଦିବ୍ୟାଙ୍ଗ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ଖୋଲା। ଦେଖିବାକୁ ଖାତା ଦରକାର ନାହିଁ।',
  'public.search': 'ନାମ କିମ୍ବା ଶବ୍ଦରେ ଖୋଜନ୍ତୁ',
  'public.filter.disability': 'ଦିବ୍ୟାଙ୍ଗତାର ପ୍ରକାର',
  'public.filter.qualification': 'ଯୋଗ୍ୟତା',
  'public.filter.state': 'ଆପଣଙ୍କ ରାଜ୍ୟ',
  'public.filter.provider': 'କିଏ ଦେଉଛି',
  'public.filter.any': 'ଯେକୌଣସି',
  'public.filter.anyDisability': 'ଯେକୌଣସି ଦିବ୍ୟାଙ୍ଗତା',
  'public.filter.anyQualification': 'ଯେକୌଣସି ଯୋଗ୍ୟତା',
  'public.filter.allStates': 'ସମସ୍ତ ରାଜ୍ୟ',
  'public.filter.gender': 'ଲିଙ୍ଗ',
  'public.filter.anyGender': 'ଯେକୌଣସି ଲିଙ୍ଗ',
  'public.filter.course': 'ପାଠ୍ୟକ୍ରମ',
  'public.filter.anyCourse': 'ଯେକୌଣସି ପାଠ୍ୟକ୍ରମ',
  'public.filter.where': 'ଆପଣ କେଉଁଠି ପଢ଼ୁଛନ୍ତି',
  'public.filter.anyWhere': 'ଭାରତ କିମ୍ବା ବିଦେଶ',
  'public.filter.inIndia': 'ଭାରତରେ',
  'public.filter.abroad': 'ବିଦେଶରେ ଅଧ୍ୟୟନ',
  'public.filters': 'ଫିଲ୍ଟର୍',
  'public.clear': 'ହଟାନ୍ତୁ',
  'public.results': 'ଛାତ୍ରବୃତ୍ତି ବର୍ତ୍ତମାନ ଖୋଲା ଅଛି',
  'public.searching': 'ଖୋଜୁଛି…',
  'public.none': 'ଏହି ଫିଲ୍ଟରଗୁଡ଼ିକ ସହିତ କୌଣସି ଛାତ୍ରବୃତ୍ତି ମେଳ ଖାଉ ନାହିଁ',
  'public.none.hint': 'ଗୋଟିଏ ଫିଲ୍ଟର ହଟାଇ ଦେଖନ୍ତୁ। ବର୍ଷସାରା ନୂଆ ଯୋଜନା ଖୋଲେ।',
  'public.none.clear': 'ସମସ୍ତ ଫିଲ୍ଟର ହଟାନ୍ତୁ',
  'public.empty': 'ଏଠାରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଛାତ୍ରବୃତ୍ତି ତାଲିକାଭୁକ୍ତ ହୋଇନାହିଁ',
  'public.empty.hint': 'ପ୍ରଦାନକାରୀମାନଙ୍କୁ ବର୍ତ୍ତମାନ ଯୋଡ଼ାଯାଉଛି। ଏଠାରେ କିଛି ବି ଖାତା ପଛରେ ନାହିଁ — ଯୋଜନାଗୁଡ଼ିକ ତାଲିକାଭୁକ୍ତ ହେଲେ ସାଇନ୍ ଇନ୍ ନକରି ମଧ୍ୟ ଦେଖିପାରିବେ।',
  'public.whoFor': 'ଏହା କାହା ପାଇଁ',
  'public.about': 'ଏହି ଛାତ୍ରବୃତ୍ତି ବିଷୟରେ',
  'public.atAGlance': 'ଏକ ନଜରରେ',
  'public.closes': 'ବନ୍ଦ ହୁଏ',
  'public.awardUnstated': 'ରାଶି କୁହାଯାଇ ନାହିଁ',
  'public.noClose': 'ଶେଷ ତାରିଖ ନାହିଁ',
  'public.closesIn': '{n} ଦିନରେ ବନ୍ଦ',
  'public.closesToday': 'ଆଜି ବନ୍ଦ ହେଉଛି',
  'public.closed': 'ବନ୍ଦ',
  'public.award': 'ରାଶି',
  'public.renewable': 'ପ୍ରତିବର୍ଷ ନବୀକରଣ କରାଯାଇପାରେ',
  'public.offeredBy': 'ପ୍ରଦାନ କରୁଛନ୍ତି',
  'public.eligibility': 'ଯୋଗ୍ୟ ହେବାକୁ',
  'public.benefits': 'ସୁବିଧା',
  'public.readMore': 'ଅଧିକ ପଢ଼ନ୍ତୁ',
  'public.viewDetails': 'ବିବରଣୀ ଦେଖନ୍ତୁ',
  'public.applyNow': 'ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ',
  'public.registerToApply': 'ଆବେଦନ କରନ୍ତୁ',
  'public.registerToApplyHelp': 'ଆବେଦନ ଆପଣଙ୍କ ଖାତା ମାଧ୍ୟମରେ କରାଯାଏ। ପଞ୍ଜୀକରଣ କଲେ ଆପଣ ଯୋଗ୍ୟ ଥିବା ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ମଧ୍ୟ ଦେଖିବେ।',
  'public.closedNote': 'ଏହି ଯୋଜନା ବନ୍ଦ ହୋଇଯାଇଛି',
  'sheet.close': 'ବନ୍ଦ କରନ୍ତୁ',
  'sheet.loading': 'ଛାତ୍ରବୃତ୍ତିର ବିବରଣୀ',
  'public.benefitComponent': 'ଅଂଶ',
  'public.benefitAmount': 'ଛାତ୍ରଛାତ୍ରୀ କ’ଣ ପାଆନ୍ତି',
  'public.whatYouGet': 'ଆପଣ କ’ଣ ପାଇବେ',
  'public.eligibilityDetail': 'ଯୋଗ୍ୟତା ବିସ୍ତୃତ ଭାବେ',
  'public.documentsRequired': 'ଆବଶ୍ୟକ ନଥି',
  'public.documentsHelp': 'ପ୍ରଦାନକାରୀ ଏଗୁଡ଼ିକ ମାଗନ୍ତି। ଏଗୁଡ଼ିକ ଆପଣ ଏଠାରେ ଅପଲୋଡ୍ କରନ୍ତି ନାହିଁ।',
  'public.howToApply': 'କିପରି ଆବେଦନ କରିବେ',
  'public.importantNotes': 'ଜାଣିବା ଯୋଗ୍ୟ',
  'public.academicYear': 'କେଉଁ ବର୍ଷ ପାଇଁ',
  'public.awardBasis': 'କେଉଁ ଆଧାରରେ',
  'public.basis.MERIT': 'ମେଧା',
  'public.basis.NEED': 'ଆର୍ଥିକ ଆବଶ୍ୟକତା',
  'public.basis.MERIT_CUM_MEANS': 'ମେଧା ଓ ଆୟ',
  'public.basis.CATEGORY': 'ବର୍ଗ',
  'public.basis.OTHER': 'ଅନ୍ୟାନ୍ୟ',
  'public.cta': 'ଆପଣଙ୍କ ପାଇଁ ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ',
  'public.applyExternal': 'ସେମାନଙ୍କ ସାଇଟ୍‌ରେ ଆବେଦନ କରନ୍ତୁ',
  'public.applyExternalHelp': 'ଆପଣ ଖୋଜିପାରିବେ ବୋଲି ଆମେ ଏହି ଛାତ୍ରବୃତ୍ତିକୁ ତାଲିକାଭୁକ୍ତ କରୁ। {org} ଏହାକୁ ଚଳାଏ ଏବଂ ନିଜ ୱେବସାଇଟ୍‌ରେ ହିଁ ଆବେଦନ ନିଏ, ତେଣୁ ଏହା ଏଠାରେ ଆପଣଙ୍କ ଆବେଦନ ତାଲିକାରେ ଦେଖାଯିବ ନାହିଁ।',
  'public.applyExternalHelpPartner': '{org} ଏହି ଆବେଦନ ନିଜ ୱେବସାଇଟ୍‌ରେ ହିଁ ନିଏ, ତେଣୁ ଏହା ଏଠାରେ ଆପଣଙ୍କ ଆବେଦନ ତାଲିକାରେ ଦେଖାଯିବ ନାହିଁ।',
  'common.newTab': 'ନୂଆ ଟାବ୍‌ରେ ଖୋଲେ',
  'public.applyHelp': 'ଆମେ ପ୍ରଥମେ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଓ ନଥି ଏହି ଛାତ୍ରବୃତ୍ତି ସହିତ ଯାଞ୍ଚ କରୁ ଏବଂ କିଛି ଛାଡ଼ି ଯାଇଥିଲେ କହୁ। ଆପଣ ନିଶ୍ଚିତ ନକଲା ପର୍ଯ୍ୟନ୍ତ କିଛି ପଠାଯାଏ ନାହିଁ।',
  'public.ctaHelp': 'ନିଜ ବିଷୟରେ ଥରେ କୁହନ୍ତୁ ଏବଂ ଆମେ ଆପଣଙ୍କୁ ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ଦେଖାଇବୁ ଯେଉଁଥିପାଇଁ ଆପଣ ଯୋଗ୍ୟ।',
  'public.back': 'ସମସ୍ତ ଛାତ୍ରବୃତ୍ତିକୁ ଫେରନ୍ତୁ',
  'notFound.title': 'ଆମେ ଏହି ପୃଷ୍ଠା ଖୋଜି ପାଇଲୁ ନାହିଁ',
  'notFound.body': 'ଠିକଣାରେ ଟାଇପିଂ ଭୁଲ ଥାଇପାରେ, କିମ୍ବା ପୃଷ୍ଠାଟି ଅନ୍ୟତ୍ର ଯାଇଛି।',
  'notFound.home': 'ହୋମ ପୃଷ୍ଠାକୁ ଯାଆନ୍ତୁ',

  'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
  'dash.title': 'ଆପଣଙ୍କ ଡ୍ୟାସବୋର୍ଡ',
  'dash.lede': 'ଆପଣଙ୍କ ଛାତ୍ରବୃତ୍ତି, ଆବେଦନ ଓ ନଥି, ସବୁ ଏକ ସ୍ଥାନରେ।',
  'dash.matches': 'ଯେଉଁ ଛାତ୍ରବୃତ୍ତି ପାଇଁ ଆପଣ ଆବେଦନ କରିପାରିବେ',
  'dash.matchesHint': 'ଆପଣ ଦେଇଥିବା ବିବରଣୀ ଆଧାରରେ।',
  'dash.matchesBlocked': '{n}ଟି ଆପଣଙ୍କଠାରୁ ଆଉ ଏକ ବିବରଣୀର ଅପେକ୍ଷାରେ।',
  'dash.applications': 'ଚାଲୁଥିବା ଆବେଦନ',
  'dash.applicationsHint': '{approved} ମଞ୍ଜୁର · {rejected} ସଫଳ ହୋଇନାହିଁ',
  'dash.applicationsNone': 'ଏପର୍ଯ୍ୟନ୍ତ କିଛି ପଠାଯାଇନାହିଁ।',
  'dash.documents': 'ସତ୍ୟାପିତ ନଥି',
  'dash.documentsHint': 'ଥରେ ଯାଞ୍ଚ ହୋଇଛି। ପ୍ରତ୍ୟେକ ଆବେଦନରେ କାମରେ ଆସେ।',
  'dash.funding': 'ଏପର୍ଯ୍ୟନ୍ତ ମିଳିଛି',
  'dash.fundingHint': 'ମୋଟ {sanctioned} ମଞ୍ଜୁର।',
  'dash.recent': 'ସମ୍ପ୍ରତିର ଆବେଦନ',
  'dash.noApplications': 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆବେଦନ ନାହିଁ',
  'dash.noApplicationsHint': 'ଆପଣ ଯେଉଁଥିପାଇଁ ବି ଆବେଦନ କରିବେ ତାହା ଏଠାରେ ଦେଖାଯିବ।',
  'dash.findScholarships': 'ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ',
  'dash.profileTitle': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍',
  'dash.toGo': '{n}% ବାକି',
  'dash.allApplications': 'ସବୁ ଦେଖନ୍ତୁ',
  'dash.matchesGo': 'ଆପଣଙ୍କ ମେଳ ଦେଖନ୍ତୁ',
  'dash.applicationsGo': 'ଆପଣଙ୍କ ଆବେଦନ ଦେଖନ୍ତୁ',
  'dash.documentsGo': 'ନଥି ପରିଚାଳନା କରନ୍ତୁ',
  'dash.draftsTitle': '{n}ଟି ଆବେଦନ ପଠାଯାଇନାହିଁ | {n}ଟି ଆବେଦନ ପଠାଯାଇନାହିଁ',
  'dash.draftsBody': 'ଆବେଦନ ଆରମ୍ଭ କଲେ ତାହା ପଠାଯାଏ ନାହିଁ। ଛାତ୍ରବୃତ୍ତି ବନ୍ଦ ହେବା ପୂର୍ବରୁ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ।',
  'dash.draftsAction': 'ବର୍ତ୍ତମାନ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
  'dash.expiringTitle': '{n}ଟି ନଥିର ମିଆଦ ଶୀଘ୍ର ଶେଷ ହେଉଛି | {n}ଟି ନଥିର ମିଆଦ ଶୀଘ୍ର ଶେଷ ହେଉଛି',
  'dash.expiringBody': 'ପ୍ରତ୍ୟେକ ଆବେଦନରେ କାମରେ ଆସିବା ପାଇଁ ଏହାକୁ ବର୍ତ୍ତମାନ ବଦଳାନ୍ତୁ। | ପ୍ରତ୍ୟେକ ଆବେଦନରେ କାମରେ ଆସିବା ପାଇଁ ଏଗୁଡ଼ିକୁ ବର୍ତ୍ତମାନ ବଦଳାନ୍ତୁ।',
  'dash.expiringAction': 'ନଥି ଯାଞ୍ଚ କରନ୍ତୁ',

  'auth.title': 'ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
  'auth.phone': 'ମୋବାଇଲ୍ ନମ୍ବର',
  'auth.phoneHint': 'ଆମେ ଏହି ନମ୍ବରକୁ SMS ମାଧ୍ୟମରେ 6 ଅଙ୍କର କୋଡ୍ ପଠାଇବୁ। ପ୍ରତିଥର ଏହି ନମ୍ବର ହିଁ ଆପଣଙ୍କୁ ସାଇନ୍ ଇନ୍ କରାଏ।',
  'auth.phoneMissing': 'ଆଗକୁ ବଢ଼ିବା ପାଇଁ ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ।',
  'auth.phoneInvalid': 'ଏହା ଠିକ୍ ଲାଗୁନାହିଁ। ଭାରତୀୟ ମୋବାଇଲ୍ ନମ୍ବର 10 ଅଙ୍କର ହୋଇଥାଏ ଏବଂ 6, 7, 8 କିମ୍ବା 9ରୁ ଆରମ୍ଭ ହୁଏ।',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'ନୂଆ ହୁଅନ୍ତୁ କି ଫେରି ଆସୁଥାଆନ୍ତୁ, ସେହି ନମ୍ବର ହିଁ କାମ କରେ। ଆପଣଙ୍କର ଖାତା ନଥିଲେ ଆମେ ତିଆରି କରିଦେଉ।',
  'auth.stepOf': 'ପଦକ୍ଷେପ {n} / 2 · {name}',
  'auth.stepPhone': 'ଆପଣଙ୍କ ନମ୍ବର',
  'auth.stepCode': 'ଆପଣଙ୍କ OTP କୋଡ୍',
  'auth.privacy': 'ଆପଣଙ୍କ ନମ୍ବର କେବଳ ଆପଣଙ୍କୁ ସାଇନ୍ ଇନ୍ କରାଇବା ପାଇଁ ବ୍ୟବହାର ହୁଏ, ଆଉ କୌଣସି କାମ ପାଇଁ ନୁହେଁ। ମନେ ରଖିବା ପାଇଁ କୌଣସି ପାସୱାର୍ଡ ନାହିଁ।',
  'auth.sendCode': 'କୋଡ୍ ପଠାନ୍ତୁ',
  'auth.sending': 'ପଠାଯାଉଛି…',
  'auth.checking': 'ଯାଞ୍ଚ କରାଯାଉଛି…',
  'auth.welcomeBack': 'ପୁଣି ସ୍ୱାଗତ। ସାଇନ୍ ଇନ୍ କରିବାକୁ କୋଡ୍ ଦିଅନ୍ତୁ।',
  'auth.newHere': 'କୋଡ୍ ଦେଲାକ୍ଷଣି ଆମେ ଆପଣଙ୍କ ଖାତା ତିଆରି କରିଦେବୁ।',
  'auth.codeTitle': 'ଆମେ ପଠାଇଥିବା କୋଡ୍ ଦିଅନ୍ତୁ',
  'auth.code': '6 ଅଙ୍କର କୋଡ୍',
  'auth.codeHint': 'ସନ୍ଦେଶ ସାଧାରଣତଃ କିଛି ସେକେଣ୍ଡ ଭିତରେ ଆସିଯାଏ।',
  'auth.noCode': 'ଏପର୍ଯ୍ୟନ୍ତ ସନ୍ଦେଶ ଆସିନାହିଁ? ଅନ୍ୟ ଉପାୟ ଦେଖନ୍ତୁ:',
  'auth.verify': 'ସତ୍ୟାପିତ କରନ୍ତୁ',
  'auth.viaSms': 'SMS ମାଧ୍ୟମରେ ପଠାନ୍ତୁ',
  'auth.viaWhatsapp': 'ହ୍ୱାଟ୍ସଆପ୍‌ରେ ପଠାନ୍ତୁ',
  'auth.viaVoice': 'କୋଡ୍ କହିବା ପାଇଁ ମୋତେ ଫୋନ୍ କରନ୍ତୁ',
  'auth.resentVia.sms': 'SMS ମାଧ୍ୟମରେ ପଠାଯାଇଛି। ଆସିବାକୁ ଟିକେ ସମୟ ଲାଗିପାରେ।',
  'auth.resentVia.whatsapp': 'ହ୍ୱାଟ୍ସଆପ୍‌ରେ ପଠାଯାଇଛି। ସନ୍ଦେଶ ପାଇଁ ହ୍ୱାଟ୍ସଆପ୍ ଦେଖନ୍ତୁ।',
  'auth.resentVia.voice': 'କୋଡ୍ କହିବା ପାଇଁ ବର୍ତ୍ତମାନ ଫୋନ୍ କରୁଛୁ। ଶୁଣିବାକୁ ଫୋନ୍ ଧରନ୍ତୁ।',
  'auth.resendIn': '{n} ସେକେଣ୍ଡରେ ପୁଣି ପଠାନ୍ତୁ',
  'auth.changeNumber': 'ଅନ୍ୟ ନମ୍ବର ବ୍ୟବହାର କରନ୍ତୁ',
  'auth.change': 'ବଦଳାନ୍ତୁ',

  'profile.complete': '{n}% ସମ୍ପୂର୍ଣ୍ଣ',
  'profile.viewLede': 'ଆପଣ ଆମକୁ ଯାହା ସବୁ କହିଛନ୍ତି। ଯେକୌଣସି ଉତ୍ତର ବଦଳାନ୍ତୁ ଏବଂ ତା’ପରେ ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ପାଇଁ ସେହିଟି ହିଁ ବ୍ୟବହାର ହେବ।',
  'profile.notAnswered': 'ଏପର୍ଯ୍ୟନ୍ତ ଉତ୍ତର ଦିଆଯାଇନାହିଁ',
  'profile.verified': 'ସତ୍ୟାପିତ',
  'profile.continue': 'ଯେଉଁଠି ଛାଡ଼ିଥିଲେ ସେଠାରୁ ଜାରି ରଖନ୍ତୁ',
  'profile.start': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଆରମ୍ଭ କରନ୍ତୁ',
  'profile.saved': 'ସଞ୍ଚୟ ହେଲା',

  'match.title': 'ଆପଣଙ୍କ ପାଇଁ ଛାତ୍ରବୃତ୍ତି',
  'match.lede': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସହିତ ଯାଞ୍ଚ ହୋଇଛି। ଯେଉଁଥିପାଇଁ ଆବେଦନ କରିପାରିବେ ସେଗୁଡ଼ିକ ପ୍ରଥମେ।',
  'match.eligible': 'ଆପଣ ଯୋଗ୍ୟ',
  'match.likely': 'ଆପଣ ସମ୍ଭବତଃ ଯୋଗ୍ୟ',
  'match.blocked': 'ପ୍ରଥମେ ଗୋଟିଏ କାମ',
  'match.actionable': 'ଆପଣଙ୍କ ପାଇଁ ଖୋଲା',
  'match.actionableHelp': 'କେତେକ ପାଇଁ ଆବେଦନ ପୂର୍ବରୁ ଗୋଟିଏ ନଥି ଦରକାର ହୋଇପାରେ।',
  'match.ineligible': 'ଆପଣଙ୍କ ପାଇଁ ଖୋଲା ନୁହେଁ',
  'match.eligibleHelp': 'ଆମେ ଯାହା ସବୁ ଯାଞ୍ଚ କଲୁ ତାହା ସବୁ ସତ୍ୟାପିତ।',
  'match.likelyHelp': 'ଆପଣ ଯାହା କହିଛନ୍ତି ତାହା ଆଧାରରେ। ସତ୍ୟାପିତ କରାଇଲେ ଆପଣଙ୍କ ଆବେଦନ ଅଧିକ ଶକ୍ତିଶାଳୀ ହୁଏ।',
  'match.blockedHelp': 'ଆପଣ ପାଖାପାଖି ଅଛନ୍ତି। ଏହା କରିଦେଲେ ଆବେଦନ କରିପାରିବେ।',
  'match.ineligibleHelp': 'ଏହି ଯୋଜନା ଏମିତି କିଛି ମାଗେ ଯାହା ଆପଣ ବଦଳାଇ ପାରିବେ ନାହିଁ।',
  'match.apply': 'ଆବେଦନ କରନ୍ତୁ',
  'match.applied': 'ଆପଣ ଆବେଦନ କରିଛନ୍ତି',
  'match.none': 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମେଳ ନାହିଁ',
  'match.noneHint': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ ଏବଂ ଆମେ ଆପଣଙ୍କ ପାଇଁ ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ଯାଞ୍ଚ କରିବୁ।',
  'match.figQualify': 'ଆପଣ ଯୋଗ୍ୟ',
  'match.figStep': 'ଏକ ପାଦ ଦୂରରେ',
  'match.figClosing': 'ଶୀଘ୍ର ବନ୍ଦ',
  'match.figNo': 'ଆପଣଙ୍କ ପାଇଁ ଖୋଲା ନୁହେଁ',
  'match.filterLabel': 'କେଉଁ ଛାତ୍ରବୃତ୍ତି ଦେଖାଇବେ',
  'match.filterAll': 'ସବୁ',
  'match.filterQualify': 'ଆପଣ ଯୋଗ୍ୟ',
  'match.filterStep': 'ଏକ ପାଦ ଦୂରରେ',
  'match.filterClosing': 'ଶୀଘ୍ର ବନ୍ଦ',
  'match.filterNo': 'ଆପଣଙ୍କ ପାଇଁ ଖୋଲା ନୁହେଁ',
  'match.filterEmpty': 'ଏହି ଗୋଷ୍ଠୀରେ କିଛି ନାହିଁ। “ସବୁ” ଦେଖନ୍ତୁ।',
  'match.moreWithProfile': 'ଆପଣ ଯେତେ ଭରିବେ ସେତେ ଅଧିକ ଛାତ୍ରବୃତ୍ତି ଦେଖାଯିବ।',
  'match.youQualify': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଅନୁସାରେ ଆପଣ ସର୍ତ୍ତ ପୂରଣ କରୁଛନ୍ତି।',
  'match.yesTitle': 'ଆପଣ ଆବେଦନ କରିପାରିବେ',
  'match.blockedTitle': 'ପ୍ରଥମେ ଗୋଟିଏ କାମ',
  'match.noTitle': 'ଯୋଗ୍ୟ ନୁହନ୍ତି',
  'match.appliedTitle': 'ପୂର୍ବରୁ ପଠାଯାଇଛି',
  'match.seeDetails': 'ନିୟମ ଦେଖନ୍ତୁ',
  'match.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
  'match.runBy': '{kind} ଦ୍ୱାରା ପରିଚାଳିତ',
  'match.sortBy': 'କ୍ରମ',
  'match.sortRecommended': 'ସୁପାରିଶ କରାଯାଇଥିବା',
  'match.sortClosing': 'ସବୁଠାରୁ ଆଗ ବନ୍ଦ ହେଉଥିବା',
  'match.sortAward': 'ସବୁଠାରୁ ବଡ଼ ରାଶି',
  'match.applyAway': 'ସେମାନଙ୍କ ସାଇଟ୍‌ରେ ଆବେଦନ କରନ୍ତୁ',
  'match.applyHere': 'ଏଠାରେ ହିଁ ଆବେଦନ କରନ୍ତୁ',
  'match.notOpenToYou': 'ବର୍ତ୍ତମାନର ସ୍ଥିତିରେ ଆପଣଙ୍କ ପାଇଁ ଖୋଲା ନୁହେଁ।',
  'match.working': 'ବର୍ତ୍ତମାନ ଖୋଲା ଥିବା କୌଣସି ଯୋଜନା ଆପଣ ଦେଇଥିବା ବିବରଣୀ ସହିତ ମେଳ ଖାଉନାହିଁ। ପ୍ରୋଫାଇଲରେ ଅଧିକ ଯୋଡ଼ିଲେ ଏହା ବଦଳେ।',

  'doc.title': 'ଆପଣଙ୍କ ନଥି',
  'doc.lede': 'ଗୋଟିଏ ନଥି ଥରେ ଅପଲୋଡ୍ କରନ୍ତୁ। ଆପଣ ଯେଉଁ ଛାତ୍ରବୃତ୍ତି ପାଇଁ ବି ଆବେଦନ କରନ୍ତୁ ତାହା ଏହାକୁ ବ୍ୟବହାର କରିପାରିବ — ଆପଣଙ୍କୁ ପୁଣି ମଗାଯିବ ନାହିଁ।',
  'doc.upload': 'ନଥି ଯୋଡ଼ନ୍ତୁ',
  'doc.type': 'ଏହା କେଉଁ ନଥି?',
  'doc.file': 'ଫାଇଲ୍ ବାଛନ୍ତୁ',
  'doc.fileHint': 'PDF କିମ୍ବା ସ୍ପଷ୍ଟ ଫଟୋ। 10 MB ପର୍ଯ୍ୟନ୍ତ।',
  'doc.verified': 'ସତ୍ୟାପିତ',
  'doc.verifiedBy': '{org} ଦ୍ୱାରା ସତ୍ୟାପିତ',
  'doc.pending': 'ସତ୍ୟାପନର ଅପେକ୍ଷାରେ',
  'doc.expired': 'ସତ୍ୟାପନର ମିଆଦ ଶେଷ',
  'doc.expiring': '{n} ଦିନରେ ମିଆଦ ଶେଷ',
  'doc.validUntil': '{date} ପର୍ଯ୍ୟନ୍ତ ବୈଧ',
  'doc.none': 'ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ନଥି ଯୋଡ଼ିନାହାନ୍ତି',
  'doc.uploading': 'ଅପଲୋଡ୍ ହେଉଛି…',
  'doc.remove': 'ହଟାନ୍ତୁ',
  'doc.removing': 'ହଟାଯାଉଛି…',

  'apply.title': 'ଆବେଦନ କରନ୍ତୁ',
  'apply.consent': 'ମୋର ବିବରଣୀ ଏହି ପ୍ରଦାନକାରୀଙ୍କ ସହିତ ସେୟାର୍ କରନ୍ତୁ',
  'apply.consentBody': 'ନିଷ୍ପତ୍ତି ନେବା ପାଇଁ ଏହି ଛାତ୍ରବୃତ୍ତିକୁ ଯାହା ଦରକାର କେବଳ ତାହା ହିଁ ସେମାନେ ଦେଖିବେ: {fields}. ଆପଣଙ୍କ ନଥି କିଏ ଦେଖିଲା ତାହା ଆପଣ ଯେକୌଣସି ସମୟରେ ଦେଖିପାରିବେ।',
  'apply.consentBodyNoDocs': 'ନିଷ୍ପତ୍ତି ନେବା ପାଇଁ ଏହି ଛାତ୍ରବୃତ୍ତିକୁ ଯାହା ଦରକାର କେବଳ ତାହା ହିଁ ସେମାନେ ଦେଖିବେ, ଆଉ କିଛି ନୁହେଁ। ଆପଣଙ୍କ ବିବରଣୀ କିଏ ଦେଖିଲା ତାହା ଆପଣ ଯେକୌଣସି ସମୟରେ ଦେଖିପାରିବେ।',
  'apply.submit': 'ମୋ ଆବେଦନ ପଠାନ୍ତୁ',
  'apply.submitting': 'ପଠାଯାଉଛି…',
  'apply.blocked': 'ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ ଆବେଦନ କରିପାରିବେ ନାହିଁ',
  'apply.needProfile': 'ପ୍ରଥମେ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍',
  'apply.needProfileHint': 'ଆବେଦନ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲରୁ ହିଁ ପଠାଯାଏ, ତେଣୁ ଆବେଦନ ପୂର୍ବରୁ ତାହା ଦରକାର। ଏଥିରେ କିଛି ମିନିଟ୍ ଲାଗେ, ଏବଂ ଆପଣ ପୂର୍ବରୁ ଯାହା କହିଛନ୍ତି ତାହା ଭରାଯାଇଥିବ।',
  'apply.elsewhereTitle': 'ଏହା ପାଇଁ ଆବେଦନ ପୃଷ୍ଠପୋଷକଙ୍କ ୱେବସାଇଟ୍‌ରେ ହୁଏ',
  'apply.elsewhereBody': 'ଆପଣ ଖୋଜିପାରିବେ ବୋଲି ଆମେ ଏହି ଛାତ୍ରବୃତ୍ତିକୁ ତାଲିକାଭୁକ୍ତ କରୁ, ଏବଂ ଆବେଦନ ପୃଷ୍ଠପୋଷକ ନିଜେ ନିଅନ୍ତି। ଆପଣ ଆମକୁ ଯାହା କହିଛନ୍ତି ତାହା ସଞ୍ଚିତ ରହେ, ଏବଂ ଆମେ ଚଳାଉଥିବା ଛାତ୍ରବୃତ୍ତି ପାଇଁ ତାହା ପୂର୍ବରୁ ଭରାଯାଇଥାଏ।',
  'apply.elsewhereBodyPartner': 'ଏହି ଛାତ୍ରବୃତ୍ତି ଏଠାରେ ହିଁ ଚାଲେ, କିନ୍ତୁ ପୃଷ୍ଠପୋଷକ ଆବେଦନ ନିଜ ୱେବସାଇଟ୍‌ରେ ନିଅନ୍ତି। ଆପଣ ଆମକୁ ଯାହା କହିଛନ୍ତି ତାହା ସଞ୍ଚିତ ରହେ, ଏବଂ ଆମକୁ ସିଧାସଳଖ ମିଳୁଥିବା ଆବେଦନ ପାଇଁ ତାହା ପୂର୍ବରୁ ଭରାଯାଇଥାଏ।',
  'apply.bundleTitle': 'ଆପଣଙ୍କ ନଥି ସାଙ୍ଗରେ ନିଅନ୍ତୁ',
  'apply.bundleBody': 'ଏହି ଛାତ୍ରବୃତ୍ତି ଯେଉଁ ନଥି ମାଗେ ସେଗୁଡ଼ିକୁ ଆମେ ଗୋଟିଏ ଫାଇଲରେ ରଖିପାରିବୁ, ସେମାନଙ୍କ ୱେବସାଇଟ୍‌ରେ ଅପଲୋଡ୍ କରିବା ପାଇଁ ପ୍ରସ୍ତୁତ। ସେମାନେ ଯାହା ଚାହାନ୍ତି ଏବଂ ଆମ ପାଖରେ ଏପର୍ଯ୍ୟନ୍ତ ନାହିଁ, ତାହା ମଧ୍ୟ ଏଥିରେ ଲେଖାଥାଏ।',
  'apply.bundleAction': 'ମୋ ନଥି ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  'apply.bundleWorking': 'ପ୍ରସ୍ତୁତ କରାଯାଉଛି…',
  'apply.bundleDone': 'ଆପଣଙ୍କ ନଥି ଡାଉନଲୋଡ୍ ହୋଇଯାଇଛି।',
  'apply.docs': 'ଏହି ଛାତ୍ରବୃତ୍ତି ପାଇଁ ଆବଶ୍ୟକ ନଥି',

  'appl.title': 'ଆପଣଙ୍କ ଆବେଦନ',
  'appl.none': 'ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆବେଦନ କରିନାହାନ୍ତି',
  'appl.noneHint': 'ଆପଣ ଯୋଗ୍ୟ ଥିବା ଛାତ୍ରବୃତ୍ତି ଖୋଜିବା ପାଇଁ ଆପଣଙ୍କ ମେଳ ଦେଖନ୍ତୁ।',
  'appl.reference': 'ସନ୍ଦର୍ଭ',
  'appl.whatNext': 'ଏହା ପରେ କ’ଣ ହେବ',
  'appl.history': 'ଇତିହାସ',
  'appl.needsYou': 'ସେମାନଙ୍କୁ ଆପଣଙ୍କଠାରୁ କିଛି ଦରକାର',
  'track.label': 'ଏହି ଆବେଦନର ପ୍ରଗତି',
  'track.sent': 'ପଠାଯାଇଛି',
  'track.review': 'ସମୀକ୍ଷା',
  'track.decision': 'ନିଷ୍ପତ୍ତି',
  'track.doneSr': 'ସମ୍ପୂର୍ଣ୍ଣ',
  'track.currentSr': 'ବର୍ତ୍ତମାନ ଚାଲିଛି',
  'track.todoSr': 'ଆରମ୍ଭ ହୋଇନାହିଁ',
  'appl.sentOn': '{when} ପଠାଯାଇଛି',
  'appl.decidedOn': '{when} ନିଷ୍ପତ୍ତି ହୋଇଛି',
  'appl.outcomeApproved': 'ମିଳିଛି',
  'appl.outcomeRejected': 'ଏଥର ମିଳିନାହିଁ',
  'appl.outcomeWithdrawn': 'ଆପଣ ଏହାକୁ ପ୍ରତ୍ୟାହାର କରିଛନ୍ତି',
  'appl.inProgress': 'ପ୍ରଦାନକାରୀଙ୍କ ପାଖରେ',
  'appl.outcome': 'ଫଳାଫଳ',
  'appl.award': 'ରାଶି',
  'appl.applied': 'ଆବେଦନ କରାଯାଇଛି',
  'appl.decided': 'ନିଷ୍ପତ୍ତି ହୋଇଛି',
  'appl.automatic': 'ସ୍ୱୟଂଚାଳିତ',
  'appl.noHistory': 'ଏପର୍ଯ୍ୟନ୍ତ କିଛି ହୋଇନାହିଁ।',

  'ref.heading': 'ସେମାନଙ୍କ ୱେବସାଇଟ୍‌କୁ ପଠାଯାଇଛି',
  'ref.blurb': 'ଏଗୁଡ଼ିକ ପାଇଁ ଆବେଦନ ପ୍ରଦାନକାରୀଙ୍କ ନିଜ ସାଇଟ୍‌ରେ ହୁଏ, ତେଣୁ କ’ଣ ହେଲା ତାହା ଆମେ ଦେଖିପାରିବୁ ନାହିଁ। ଆମକୁ କୁହନ୍ତୁ ଏବଂ ଆମେ ଏହାକୁ ବାକିଗୁଡ଼ିକ ସହିତ ରଖିବୁ।',
  'ref.sentOn': 'ଆପଣ ଏହାକୁ {when} ଖୋଲିଥିଲେ',
  'ref.again': 'ମୋଟ {times} ଥର',
  'ref.open': 'ସେମାନଙ୍କ ସାଇଟ୍ ପୁଣି ଖୋଲନ୍ତୁ',
  'ref.what': 'କ’ଣ ହେଲା?',
  'ref.APPLIED': 'ମୁଁ ଆବେଦନ କଲି',
  'ref.AWARDED': 'ମୋତେ ମିଳିଲା',
  'ref.NOT_AWARDED': 'ମୋତେ ମିଳିଲା ନାହିଁ',
  'ref.DID_NOT_APPLY': 'ମୁଁ ଆବେଦନ କରିନାହିଁ',
  'ref.saidAPPLIED': 'ଆପଣ ଆବେଦନ କଲେ',
  'ref.saidAWARDED': 'ଆପଣଙ୍କୁ ମିଳିଲା',
  'ref.saidNOT_AWARDED': 'ଆପଣଙ୍କୁ ମିଳିଲା ନାହିଁ',
  'ref.saidDID_NOT_APPLY': 'ଆପଣ ଆବେଦନ କରିନାହାନ୍ତି',
  'ref.youSaid': 'ଆପଣ ଆମକୁ କହିଲେ: {what}',
  'ref.change': 'ବଦଳାନ୍ତୁ',

  'privacy.title': 'ଆପଣଙ୍କ ତଥ୍ୟ',
  'privacy.lede': 'ଆମ ପାଖରେ କ’ଣ ଅଛି, କିଏ ଦେଖିଛି, ଏବଂ ଏହାକୁ ଫେରାଇ ନେବା କିପରି।',
  'privacy.access': 'ଆପଣଙ୍କ ନଥି କିଏ ଦେଖିଛି',
  'privacy.accessNone': 'ଆପଣଙ୍କ ନିଜ ଖାତା ବାହାରେ କେହି ଆପଣଙ୍କ ନଥି ଖୋଲିନାହାନ୍ତି।',
  'privacy.consents': 'ଆପଣ କ’ଣ ସେୟାର୍ କରିବାକୁ ସମ୍ମତି ଦେଇଛନ୍ତି',
  'privacy.withdraw': 'ପ୍ରତ୍ୟାହାର କରନ୍ତୁ',
  'privacy.withdrawing': 'ପ୍ରତ୍ୟାହାର କରାଯାଉଛି…',
  'privacy.export': 'ଆମ ପାଖରେ ଯାହା ଅଛି ସବୁ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  'privacy.exporting': 'ଆପଣଙ୍କ ନକଲ ପ୍ରସ୍ତୁତ କରାଯାଉଛି…',
  'privacy.exportBody': 'ଆପଣଙ୍କ ତଥ୍ୟର ସମ୍ପୂର୍ଣ୍ଣ, ଯନ୍ତ୍ର-ପଠନୀୟ ନକଲ।',
  'privacy.erase': 'ମୋ ତଥ୍ୟ ଲିଭାନ୍ତୁ',
  'privacy.erasing': 'ଅନୁରୋଧ କରାଯାଉଛି…',
  'privacy.eraseBody': 'ଆପଣଙ୍କୁ ଦିଆଯାଇଥିବା ଯେକୌଣସି ଛାତ୍ରବୃତ୍ତିର ରେକର୍ଡ ଆମକୁ ରଖିବାକୁ ପଡ଼େ। ବାକି ସବୁ ହଟାଇ ଦିଆଯାଏ।',
  'auth.closedTitle': 'ଆପଣଙ୍କ ଖାତା ବର୍ତ୍ତମାନ ବନ୍ଦ ଅଛି।',
  'auth.closedHelp': 'ସାହାଯ୍ୟ ଦରକାର? ଆମ ସହାୟତା ଦଳ ଆପଣଙ୍କୁ ବୁଝିବାରେ ସାହାଯ୍ୟ କରିପାରିବେ ',
  'auth.closedSoon': 'ସହାୟତା ମାଗନ୍ତୁ (ଶୀଘ୍ର)',
  'reg.district': 'ଜିଲ୍ଲା',
  'reg.districtHint': 'ଆପଣଙ୍କ ଅଞ୍ଚଳରେ ଚାଲୁଥିବା ଯୋଜନା ସହିତ ମେଳ କରିବାରେ ସାହାଯ୍ୟ କରେ।',
  'privacy.requested': 'ଅନୁରୋଧ କରାଯାଇଛି',
  'privacy.window': 'ଏପର୍ଯ୍ୟନ୍ତ କିଛି ଲିଭାଯାଇନାହିଁ',
  'privacy.windowBody': 'ଆପଣଙ୍କ ତଥ୍ୟ {date}ରେ ଲିଭାଯିବ। ସେ ପର୍ଯ୍ୟନ୍ତ ଆପଣ ',
  'privacy.cancel': 'ଏହି ଅନୁରୋଧ ବାତିଲ୍ କରନ୍ତୁ',
  'privacy.cancelling': 'ବାତିଲ୍ କରାଯାଉଛି…',
  'privacy.cancelled': 'ଆପଣଙ୍କ ଅନୁରୋଧ ବାତିଲ୍ କରାଯାଇଛି। କିଛି ଲିଭାଯାଇନାହିଁ।',

  'common.loading': 'ଲୋଡ୍ ହେଉଛି',
  'common.retry': 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
  'common.required': 'ଆବଶ୍ୟକ',
  'common.optional': 'ଐଚ୍ଛିକ',
  'common.error': 'କିଛି ଭୁଲ୍ ହେଲା',
  'common.offline': 'ଆପଣ ଅଫଲାଇନ୍ ଅଛନ୍ତି। ଆପଣଙ୍କ କାମ ଏହି ଡିଭାଇସରେ ସଞ୍ଚିତ ଅଛି।',

  'slides.lead.was': '',
  'slides.lead.able': 'ସାମର୍ଥ୍ୟରୁ',
  'slides.lead.dist': 'ବିଶିଷ୍ଟତା ପର୍ଯ୍ୟନ୍ତ',
  'slides.lead.body': 'ଆପଣ ଯୋଗ୍ୟ ଥିବା ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି — ସରକାରୀ ଓ ବେସରକାରୀ — ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସହିତ ମେଳ କରି, ଆପଣଙ୍କ ଭାଷାରେ, ଏକ ସ୍ଥାନରେ।',
  'slides.lead.free': 'ସମ୍ପୂର୍ଣ୍ଣ ମାଗଣା',
  'slides.lead.languages': '14ଟି ଭାଷା',
  'slides.lead.support': 'ପ୍ରତ୍ୟେକ ପାଦରେ ବ୍ୟକ୍ତିଗତ ସହାୟତା',
  'slides.label': 'ଘୋଷଣା',
  'slides.position': '{total}ରୁ {n}',
  'slides.goto': '{name} ଦେଖାନ୍ତୁ',
  'slides.watch': 'ଭିଡିଓ ଦେଖନ୍ତୁ',
  'slides.external': 'ଅନ୍ୟ ୱେବସାଇଟ୍ ଖୋଲେ',

  'home.title': 'ଦିବ୍ୟାଙ୍ଗ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ଛାତ୍ରବୃତ୍ତି, ଏକ ସ୍ଥାନରେ',
  'home.lede': 'ନିଜ ବିଷୟରେ ଥରେ କୁହନ୍ତୁ। ଆମେ ଏଠାର ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ସହିତ ଆପଣଙ୍କୁ ଯାଞ୍ଚ କରୁ ଏବଂ କହୁ ଯେ ଆପଣ କେଉଁଥିପାଇଁ ଯୋଗ୍ୟ — ଏବଂ ବାକିଗୁଡ଼ିକ ପାଇଁ ଠିକ୍ କ’ଣ ଛାଡ଼ି ଯାଉଛି।',
  'home.search': 'ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ',
  'home.searchPlaceholder': 'ଯେମିତି: ଇଞ୍ଜିନିୟରିଂ, ଦିଲ୍ଲୀ, ପୋଷ୍ଟ-ମାଟ୍ରିକ୍',
  'home.searchGo': 'ଖୋଜନ୍ତୁ',
  'home.browseAll': 'ସମସ୍ତ ଛାତ୍ରବୃତ୍ତି ଦେଖନ୍ତୁ',
  'home.openNow': 'ଛାତ୍ରବୃତ୍ତି ବର୍ତ୍ତମାନ ଖୋଲା ଅଛି',
  'home.noAccount': 'ଦେଖିବାକୁ ଖାତା ଦରକାର ନାହିଁ।',
  'home.openNone': 'ଏଠାରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଛାତ୍ରବୃତ୍ତି ତାଲିକାଭୁକ୍ତ ହୋଇନାହିଁ।',
  'home.openNoneBody': 'ତାଲିକା ବର୍ତ୍ତମାନ ଭରାଯାଉଛି। ଏଠାରେ କିଛି ବି ଖାତା ପଛରେ ନାହିଁ — ଯୋଜନାଗୁଡ଼ିକ ତାଲିକାଭୁକ୍ତ ହେଲେ ସାଇନ୍ ଇନ୍ ନକରି ମଧ୍ୟ ଦେଖିପାରିବେ।',
  'home.how': 'ଏହା କିପରି କାମ କରେ',
  'home.howLede': 'ପଞ୍ଜୀକରଣ ପାଇଁ ଗୋଟିଏ ମୋବାଇଲ୍ ନମ୍ବର ଏବଂ ସେଥିକୁ ପଠାଯାଇଥିବା କୋଡ୍ ଦରକାର। କୌଣସି ପାସୱାର୍ଡ ନାହିଁ, ଏବଂ ପ୍ରଥମେ ଭରିବାକୁ କୌଣସି ସାଇନ୍-ଅପ୍ ଫର୍ମ ମଧ୍ୟ ନାହିଁ।',
  'home.step1': 'ପଞ୍ଜୀକରଣ ଦବାନ୍ତୁ',
  'home.step1Body': 'ଏହି ପୃଷ୍ଠାର ଉପରେ। ପୂର୍ବରୁ ଆସିଥିଲେ ପାଖରେ ଥିବା ଲଗଇନ୍ ବ୍ୟବହାର କରନ୍ତୁ — ଦୁହିଁଙ୍କରେ ସେହି ନମ୍ବର ହିଁ କାମ କରେ।',
  'home.step2': 'ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
  'home.step2Body': 'ଦଶ ଅଙ୍କ, +91 ପୂର୍ବରୁ ଭରାଯାଇଥାଏ। ସେହି ନମ୍ବରକୁ 6 ଅଙ୍କର କୋଡ୍ ଯାଏ।',
  'home.step3': 'କୋଡ୍ ଦିଅନ୍ତୁ',
  'home.step3Body': 'ଛଅ ଅଙ୍କ ଟାଇପ୍ କରନ୍ତୁ ଏବଂ ଆପଣ ଭିତରେ। ସନ୍ଦେଶ ନଆସିଲେ କୋଡ୍ ହ୍ୱାଟ୍ସଆପ୍‌ରେ ମାଗନ୍ତୁ, କିମ୍ବା ଆମକୁ ଫୋନ୍ କରି ପଢ଼ି ଶୁଣାଇବାକୁ କୁହନ୍ତୁ।',
  'home.step4': 'ଆପଣଙ୍କ ବିବରଣୀ ଭରନ୍ତୁ',
  'home.step4Body': 'ଆପଣଙ୍କ ନାମ, ଆପଣଙ୍କ ପ୍ରମାଣପତ୍ର ଏବଂ ଆପଣ କେଉଁଠି ପଢ଼ୁଛନ୍ତି — ଥରକେ ଗୋଟିଏ ପ୍ରଶ୍ନ, ଏବଂ ପ୍ରତ୍ୟେକ ଉତ୍ତର ଦେଲାକ୍ଷଣି ସଞ୍ଚୟ ହୋଇଯାଏ।',
  'home.step5': 'ଆପଣଙ୍କ ନଥି ଅପଲୋଡ୍ କରନ୍ତୁ',
  'home.step5Body': 'ଦିବ୍ୟାଙ୍ଗତା ପ୍ରମାଣପତ୍ର, UDID କାର୍ଡ, ଆୟ ପ୍ରମାଣପତ୍ର ଓ ବାକିଗୁଡ଼ିକ। ପ୍ରତ୍ୟେକଟି ଥରେ ମାତ୍ର, ପ୍ରତ୍ୟେକ ଛାତ୍ରବୃତ୍ତି ପାଇଁ ଅଲଗା ନୁହେଁ।',
  'home.step6': 'ଆପଣଙ୍କ ମେଳ ଦେଖନ୍ତୁ',
  'home.step6Body': 'ମୋର ମେଳ ସେହି ଛାତ୍ରବୃତ୍ତି ତାଲିକା ଦେଖାଏ ଯେଉଁଥିପାଇଁ ଆପଣ ଯୋଗ୍ୟ — ଏବଂ କୌଣସିଟି ଆପଣଙ୍କ ପାଇଁ ବନ୍ଦ ଥିଲେ କାରଣ ମଧ୍ୟ କହେ।',
  'home.step7': 'ଆବେଦନ କରନ୍ତୁ',
  'home.step7Body': 'ଯାହା ଚାହାନ୍ତି ବାଛନ୍ତୁ। ଆପଣଙ୍କ ବିବରଣୀ ଓ ନଥି ଆବେଦନ ସହିତ ଯାଏ।',
  'home.assure': 'ଜାଣିବା ଭଲ',
  'home.assure1': 'ମନେ ରଖିବା ପାଇଁ କୌଣସି ପାସୱାର୍ଡ ନାହିଁ',
  'home.assure2': 'ଅଲଗା କୌଣସି ପଞ୍ଜୀକରଣ ଫର୍ମ ନାହିଁ',
  'home.assure3': 'ଅଟକି ପରେ ସମ୍ପୂର୍ଣ୍ଣ କରିପାରିବେ',
  'home.help': 'କୌଣସି ପଦକ୍ଷେପରେ ଅଟକି ଯାଇଛନ୍ତି?',
  'home.helpBody': 'ଫୋନ୍ କରନ୍ତୁ, କେହି ଜଣେ ଆପଣଙ୍କୁ ପାର କରାଇଦେବେ।',
  'home.helpCall': '{number}କୁ ଫୋନ୍ କରନ୍ତୁ',
  'home.closing': 'ଶୀଘ୍ର ବନ୍ଦ',
  'home.closingLede': 'ପ୍ରଥମେ ଏଗୁଡ଼ିକ ପାଇଁ ଆବେଦନ କରନ୍ତୁ।',
  'home.closingNext': 'ପରବର୍ତ୍ତୀ ଶେଷ ତାରିଖ',
  'home.closingNextLede': 'ସବୁଠାରୁ ଆଗ ବନ୍ଦ ହେବାକୁ ଥିବା ତିନିଟି।',
  'home.allDeadlines': 'ସମସ୍ତ ଛାତ୍ରବୃତ୍ତି ଦେଖନ୍ତୁ',
  'home.browse': 'ଏହା ଅନୁସାରେ ଦେଖନ୍ତୁ',
  'home.browseWho': 'କିଏ ଦେଉଛି',
  'home.browseLevel': 'ଆପଣଙ୍କ ଅଧ୍ୟୟନର ସ୍ତର',
  'home.cta': 'ଆପଣଙ୍କ ମେଳ ଦେଖିବାକୁ ପ୍ରସ୍ତୁତ?',
  'home.ctaBody': 'ଖାତା ତିଆରି କରିବାକୁ ଗୋଟିଏ ମୋବାଇଲ୍ ନମ୍ବର କିମ୍ବା ଇମେଲ୍ ଠିକଣା ଦରକାର। ଆଉ କିଛି ନୁହେଁ।',
  'home.ctaButton': 'ଖାତା ତିଆରି କରନ୍ତୁ',
  'home.signedInCta': 'ଦେଖନ୍ତୁ ଆପଣ କେଉଁଥିପାଇଁ ଯୋଗ୍ୟ',

  'reg.title': 'ଛାତ୍ରବୃତ୍ତି ଖୋଜିବାକୁ ପଞ୍ଜୀକରଣ କରନ୍ତୁ',
  'reg.editTitle': 'ଆପଣଙ୍କ ବିବରଣୀ ଅଦ୍ୟତନ କରନ୍ତୁ',
  'reg.requiredNote': '* ଚିହ୍ନିତ ସମସ୍ତ ଘର ଆବଶ୍ୟକ।',
  'reg.personal': 'ବ୍ୟକ୍ତିଗତ ବିବରଣୀ',
  'reg.disability': 'ଦିବ୍ୟାଙ୍ଗତାର ବିବରଣୀ',
  'reg.education': 'ଶିକ୍ଷାର ବିବରଣୀ',
  'reg.name': 'ପୂରା ନାମ',
  'reg.namePlaceholder': 'ଆପଣଙ୍କ ପୂରା ନାମ ଲେଖନ୍ତୁ',
  'reg.phoneHint': 'ଆମେ ଏହି ନମ୍ବରକୁ 6 ଅଙ୍କର କୋଡ୍ ପଠାଉ। ପ୍ରତିଥର ଏହି ନମ୍ବର ହିଁ ଆପଣଙ୍କୁ ସାଇନ୍ ଇନ୍ କରାଏ।',
  'reg.sendOtp': 'OTP ପଠାନ୍ତୁ',
  'reg.otpPlaceholder': '6 ଅଙ୍କର OTP ଲେଖନ୍ତୁ',
  'reg.verified': 'ଫୋନ୍ ନମ୍ବର ସତ୍ୟାପିତ',
  'reg.verifyFirst': 'ପଞ୍ଜୀକରଣ ସମ୍ପୂର୍ଣ୍ଣ କରିବାକୁ ଆପଣଙ୍କ ଫୋନ୍ ନମ୍ବର ସତ୍ୟାପିତ କରନ୍ତୁ।',
  'reg.email': 'ଇମେଲ୍',
  'reg.emailHint': 'ଯାହାଫଳରେ ଆମେ ଶେଷ ତାରିଖ ମନେ ପକାଇ ପାରିବୁ। ଆମେ ଏହାକୁ କେବେ ବି ସେୟାର୍ କରୁନାହୁଁ।',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'ଲିଙ୍ଗ',
  'reg.genderHint': '(କିଛି ଛାତ୍ରବୃତ୍ତି କେବଳ ମହିଳା କିମ୍ବା ଟ୍ରାନ୍ସଜେଣ୍ଡର ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ)',
  'reg.udid': 'UDID ନମ୍ବର',
  'reg.udidHint': 'ଆପଣଙ୍କ UDID (ଅନନ୍ୟ ଦିବ୍ୟାଙ୍ଗତା ପରିଚୟ) କାର୍ଡରେ ଲେଖାଥିବା ନମ୍ବର।',
  'reg.udidPlaceholder': 'ଆପଣଙ୍କ UDID ନମ୍ବର ଲେଖନ୍ତୁ',
  'reg.certificate': 'UDID ପ୍ରମାଣପତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ',
  'reg.certificateHint': 'PDF କିମ୍ବା ଛବି, 5 MB କିମ୍ବା ତାହାଠାରୁ କମ୍।',
  'reg.fileType': 'ସେହି ଫାଇଲ୍ PDF, JPEG କିମ୍ବା PNG ହେବା ଆବଶ୍ୟକ।',
  'reg.fileSize': 'ସେହି ଫାଇଲ୍ 5 MBରୁ ବଡ଼। ଫୋନରେ ନିଆଯାଇଥିବା ଛବି ସାଧାରଣତଃ ଛୋଟ ହୁଏ ଯଦି ଆପଣ ଫଟୋ ନେବା ବଦଳରେ ସ୍କାନ୍ କରନ୍ତି।',
  'reg.fileLater': 'ଆପଣଙ୍କ ପଞ୍ଜୀକରଣ ହୋଇଯାଇଛି ଏବଂ ବିବରଣୀ ସଞ୍ଚୟ ହୋଇଛି। ପ୍ରମାଣପତ୍ର ଅପଲୋଡ୍ ହୋଇନାହିଁ — ତାହାକୁ ମୋର ନଥିରୁ ଯୋଡ଼ିଦିଅନ୍ତୁ, ଆଉ କିଛି ପୁଣି କରିବାକୁ ପଡ଼ିବ ନାହିଁ।',
  'reg.disabilityType': 'ଦିବ୍ୟାଙ୍ଗତାର ପ୍ରକାର',
  'reg.percent': 'ଦିବ୍ୟାଙ୍ଗତାର ପ୍ରତିଶତ',
  'reg.percentHint': 'ଆପଣଙ୍କ ପ୍ରମାଣପତ୍ରରେ ଲେଖାଥିବା ସଂଖ୍ୟା। ଅନେକ ଛାତ୍ରବୃତ୍ତି ପାଇଁ 40% କିମ୍ବା ଅଧିକ ଦରକାର।',
  'reg.percentPlaceholder': 'ଯେମିତି 40',
  'reg.percentRange': 'ପ୍ରମାଣପତ୍ରର ପ୍ରତିଶତ 0 ଓ 100 ମଧ୍ୟରେ ଏକ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା।',
  'reg.state': 'ରାଜ୍ୟ',
  'reg.statePlaceholder': 'ଆପଣଙ୍କ ରାଜ୍ୟ ଖୋଜିବାକୁ ଟାଇପ୍ କରନ୍ତୁ…',
  'reg.program': 'ଆପଣଙ୍କ ପାଠ୍ୟକ୍ରମ ବାଛନ୍ତୁ',
  'reg.graduation': 'ସ୍ନାତକ',
  'reg.postgraduation': 'ସ୍ନାତକୋତ୍ତର / ମାଷ୍ଟର୍ସ',
  'reg.year': 'ବର୍ଷ ବାଛନ୍ତୁ',
  'reg.yearAfterProgram': 'ପ୍ରଥମେ ଆପଣଙ୍କ ପାଠ୍ୟକ୍ରମ ବାଛନ୍ତୁ',
  'reg.institution': 'ବିଦ୍ୟାଳୟ / ମହାବିଦ୍ୟାଳୟର ନାମ',
  'reg.institutionPlaceholder': 'ଆପଣଙ୍କ ଅନୁଷ୍ଠାନର ନାମ ଲେଖନ୍ତୁ',
  'reg.required': 'ଏହା ଦରକାର।',
  'reg.fix': 'କିଛି ଉତ୍ତରକୁ ଧ୍ୟାନ ଦରକାର। ପ୍ରଥମଟି ତଳେ ବଛାଯାଇଛି।',
  'reg.cta': 'ପଞ୍ଜୀକରଣ କରନ୍ତୁ ଏବଂ ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ',
  'reg.saveChanges': 'ପରିବର୍ତ୍ତନ ସଞ୍ଚୟ କରନ୍ତୁ',
  'reg.saving': 'ସଞ୍ଚୟ କରାଯାଉଛି…',
  'reg.done': 'ପଞ୍ଜୀକରଣ ହୋଇଗଲା। ଆପଣଙ୍କ ଛାତ୍ରବୃତ୍ତି ଖୋଜାଯାଉଛି।',
  'reg.doneTitle': 'ଆପଣଙ୍କ ପଞ୍ଜୀକରଣ ହୋଇଯାଇଛି',
  'reg.already': 'ପୂର୍ବରୁ ପଞ୍ଜୀକୃତ?',
  'reg.login': 'OTP ସହିତ ଲଗଇନ୍',
  'nav.registerCta': 'ପଞ୍ଜୀକରଣ',
  'nav.loginCta': 'ଲଗଇନ୍',
  'profile.edit': 'ଆପଣଙ୍କ ବିବରଣୀ ଅଦ୍ୟତନ କରନ୍ତୁ',
  'field.disability.BLINDNESS': 'ଅନ୍ଧତ୍ୱ',
  'field.disability.LOW_VISION': 'କ୍ଷୀଣ ଦୃଷ୍ଟି',
  'field.disability.LEPROSY_CURED': 'କୁଷ୍ଠ (ଆରୋଗ୍ୟ ହୋଇଥିବା)',
  'field.disability.HEARING_IMPAIRMENT': 'ଶ୍ରବଣ ବାଧା',
  'field.disability.LOCOMOTOR_DISABILITY': 'ଚଳପ୍ରଚଳ ଦିବ୍ୟାଙ୍ଗତା',
  'field.disability.DWARFISM': 'ବାମନତା',
  'field.disability.INTELLECTUAL_DISABILITY': 'ବୌଦ୍ଧିକ ଦିବ୍ୟାଙ୍ଗତା',
  'field.disability.MENTAL_ILLNESS': 'ମାନସିକ ଅସୁସ୍ଥତା',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ଅଟିଜିମ୍ ସ୍ପେକ୍ଟ୍ରମ୍ ଡିସଅର୍ଡର',
  'field.disability.CEREBRAL_PALSY': 'ସେରିବ୍ରାଲ୍ ପାଲ୍ସି',
  'field.disability.MUSCULAR_DYSTROPHY': 'ମାଂସପେଶୀ କ୍ଷୟ',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'ଦୀର୍ଘସ୍ଥାୟୀ ସ୍ନାୟୁଗତ ଅବସ୍ଥା',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'ନିର୍ଦ୍ଦିଷ୍ଟ ଶିକ୍ଷଣ ଦିବ୍ୟାଙ୍ଗତା',
  'field.disability.MULTIPLE_SCLEROSIS': 'ମଲ୍ଟିପଲ୍ ସ୍କ୍ଲେରୋସିସ୍',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'ବାକ୍ ଓ ଭାଷା ଦିବ୍ୟାଙ୍ଗତା',
  'field.disability.THALASSEMIA': 'ଥାଲାସେମିଆ',
  'field.disability.HAEMOPHILIA': 'ହିମୋଫିଲିଆ',
  'field.disability.SICKLE_CELL_DISEASE': 'ସିକଲ୍ ସେଲ୍ ରୋଗ',
  'field.disability.MULTIPLE_DISABILITIES': 'ବହୁବିଧ ଦିବ୍ୟାଙ୍ଗତା, ଦୃଷ୍ଟି-ଶ୍ରବଣ ବାଧା ସମେତ',
  'field.disability.ACID_ATTACK_VICTIM': 'ଏସିଡ୍ ଆକ୍ରମଣରୁ ବଞ୍ଚିଥିବା ବ୍ୟକ୍ତି',
  'field.disability.PARKINSONS_DISEASE': 'ପାର୍କିନସନ୍ସ ରୋଗ',

  'field.state.AN': 'ଆଣ୍ଡାମାନ ଓ ନିକୋବର ଦ୍ୱୀପପୁଞ୍ଜ',
  'field.state.AP': 'ଆନ୍ଧ୍ରପ୍ରଦେଶ',
  'field.state.AR': 'ଅରୁଣାଚଳ ପ୍ରଦେଶ',
  'field.state.AS': 'ଆସାମ',
  'field.state.BR': 'ବିହାର',
  'field.state.CH': 'ଚଣ୍ଡୀଗଡ଼',
  'field.state.CT': 'ଛତିଶଗଡ଼',
  'field.state.DL': 'ଦିଲ୍ଲୀ',
  'field.state.DN': 'ଦାଦ୍ରା ଓ ନଗର ହାୱେଲୀ ଏବଂ ଦମନ ଓ ଦିଉ',
  'field.state.GA': 'ଗୋଆ',
  'field.state.GJ': 'ଗୁଜରାଟ',
  'field.state.HP': 'ହିମାଚଳ ପ୍ରଦେଶ',
  'field.state.HR': 'ହରିୟାଣା',
  'field.state.JH': 'ଝାଡ଼ଖଣ୍ଡ',
  'field.state.JK': 'ଜମ୍ମୁ ଓ କାଶ୍ମୀର',
  'field.state.KA': 'କର୍ଣ୍ଣାଟକ',
  'field.state.KL': 'କେରଳ',
  'field.state.LA': 'ଲଦାଖ',
  'field.state.LD': 'ଲକ୍ଷଦ୍ୱୀପ',
  'field.state.MH': 'ମହାରାଷ୍ଟ୍ର',
  'field.state.ML': 'ମେଘାଳୟ',
  'field.state.MN': 'ମଣିପୁର',
  'field.state.MP': 'ମଧ୍ୟପ୍ରଦେଶ',
  'field.state.MZ': 'ମିଜୋରାମ',
  'field.state.NL': 'ନାଗାଲାଣ୍ଡ',
  'field.state.OR': 'ଓଡ଼ିଶା',
  'field.state.PB': 'ପଞ୍ଜାବ',
  'field.state.PY': 'ପୁଦୁଚେରୀ',
  'field.state.RJ': 'ରାଜସ୍ଥାନ',
  'field.state.SK': 'ସିକ୍କିମ',
  'field.state.TG': 'ତେଲଙ୍ଗାନା',
  'field.state.TN': 'ତାମିଲନାଡୁ',
  'field.state.TR': 'ତ୍ରିପୁରା',
  'field.state.UP': 'ଉତ୍ତରପ୍ରଦେଶ',
  'field.state.UT': 'ଉତ୍ତରାଖଣ୍ଡ',
  'field.state.WB': 'ପଶ୍ଚିମବଙ୍ଗ',

  'field.level.SCHOOL': 'ବିଦ୍ୟାଳୟ',
  'field.level.SCHOOL.sub': 'ନବମ, ଦଶମ, ଏକାଦଶ, ଦ୍ୱାଦଶ ଶ୍ରେଣୀ',
  'field.level.UNDERGRADUATE': 'ସ୍ନାତକ',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech ଏବଂ ସେହିପରି',
  'field.level.POSTGRADUATE': 'ସ୍ନାତକୋତ୍ତର',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech ଏବଂ ସେହିପରି',
  'field.level.DOCTORAL': 'ଡକ୍ଟରେଟ୍',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'ବିଦ୍ୟାଳୟ',
  'field.qual.SCHOOL.sub': 'ପ୍ରଥମରୁ ଦ୍ୱାଦଶ ଶ୍ରେଣୀ',
  'field.qual.UNDERGRADUATE': 'ସ୍ନାତକ',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — ଏବଂ ଡିପ୍ଲୋମା କିମ୍ବା ITI',
  'field.qual.POSTGRADUATE': 'ସ୍ନାତକୋତ୍ତର',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA ଏବଂ ସେହିପରି',
  'field.qual.DOCTORAL': 'PhD / ଡକ୍ଟରେଟ୍',

  'field.subject.engineering': 'ଇଞ୍ଜିନିୟରିଂ',
  'field.subject.medical': 'ଚିକିତ୍ସା',
  'field.subject.management': 'ପରିଚାଳନା',
  'field.subject.science': 'ବିଜ୍ଞାନ',
  'field.subject.commerce': 'ବାଣିଜ୍ୟ',
  'field.subject.arts': 'କଳା ଓ ମାନବିକୀ',
  'field.subject.vocational': 'ବୃତ୍ତିମୂଳକ',
  'field.subject.fellowship': 'ଫେଲୋସିପ୍',
  'field.subject.talent': 'ପ୍ରତିଭା',
  'field.subject.sports': 'କ୍ରୀଡ଼ା',

  'field.gender.FEMALE': 'ମହିଳା',
  'field.gender.MALE': 'ପୁରୁଷ',
  'field.gender.TRANSGENDER': 'ଟ୍ରାନ୍ସଜେଣ୍ଡର',
  'field.gender.UNDISCLOSED': 'କହିବାକୁ ଚାହୁଁନାହିଁ',
  'field.genderFilter.TRANSGENDER': 'ତୃତୀୟ ଲିଙ୍ଗ / ଟ୍ରାନ୍ସଜେଣ୍ଡର',

  'field.year.below9': 'ନବମ ଶ୍ରେଣୀ ତଳେ',
  'field.year.c9': 'ନବମ ଶ୍ରେଣୀ',
  'field.year.c10': 'ଦଶମ ଶ୍ରେଣୀ',
  'field.year.c11': 'ଏକାଦଶ ଶ୍ରେଣୀ',
  'field.year.c12': 'ଦ୍ୱାଦଶ ଶ୍ରେଣୀ',
  'field.year.y1': 'ପ୍ରଥମ ବର୍ଷ',
  'field.year.y2': 'ଦ୍ୱିତୀୟ ବର୍ଷ',
  'field.year.y3': 'ତୃତୀୟ ବର୍ଷ',
  'field.year.y4': 'ଚତୁର୍ଥ ବର୍ଷ',
  'field.year.pg1': 'ସ୍ନାତକୋତ୍ତର ପ୍ରଥମ ବର୍ଷ',
  'field.year.pg2': 'ସ୍ନାତକୋତ୍ତର ଦ୍ୱିତୀୟ ବର୍ଷ',

  'q.full_name': 'ଆପଣଙ୍କ ନାମ କ’ଣ?',
  'q.full_name.help': 'ଠିକ୍ ଯେପରି ଆପଣଙ୍କ ଦିବ୍ୟାଙ୍ଗତା ପ୍ରମାଣପତ୍ରରେ ଲେଖାଅଛି। ପ୍ରଦାନକାରୀମାନେ ଦୁଇଟି ମେଳ ଖାଉଛି କି ନାହିଁ ଯାଞ୍ଚ କରନ୍ତି।',
  'q.gender': 'ଆପଣଙ୍କ ଲିଙ୍ଗ କ’ଣ?',
  'q.gender.help': 'କିଛି ଛାତ୍ରବୃତ୍ତି କେବଳ ମହିଳାଙ୍କ ପାଇଁ, କିମ୍ବା ଟ୍ରାନ୍ସଜେଣ୍ଡର ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ। କହିବାକୁ ନଚାହିଁଲେ ଛାଡ଼ିଦିଅନ୍ତୁ।',
  'q.disability_type': 'ଆପଣଙ୍କ ଦିବ୍ୟାଙ୍ଗତା କ’ଣ?',
  'q.disability_type.help': 'ଯେପରି ଆପଣଙ୍କ ପ୍ରମାଣପତ୍ରରେ ଲେଖାଅଛି। ଅଧିକାଂଶ ଛାତ୍ରବୃତ୍ତି ଏହା ଉପରେ ହିଁ ଛାଣନ୍ତି।',
  'q.disability_percent': 'ଆପଣଙ୍କ ପ୍ରମାଣପତ୍ରରେ କେତେ ପ୍ରତିଶତ ଅଛି?',
  'q.disability_percent.help': '0 ଓ 100 ମଧ୍ୟରେ ଏକ ସଂଖ୍ୟା। ଅନେକ ଛାତ୍ରବୃତ୍ତି ପାଇଁ 40% କିମ୍ବା ଅଧିକ ଦରକାର।',
  'q.disability_percent.range': 'ପ୍ରମାଣପତ୍ରର ପ୍ରତିଶତ 0 ଓ 100 ମଧ୍ୟରେ ହୋଇଥାଏ।',
  'q.udid_number': 'ଆପଣଙ୍କ UDID ନମ୍ବର କ’ଣ?',
  'q.udid_number.help': 'ଆପଣଙ୍କ UDID (ଅନନ୍ୟ ଦିବ୍ୟାଙ୍ଗତା ପରିଚୟ) କାର୍ଡରେ ଲେଖାଥିବା ନମ୍ବର। ଏପର୍ଯ୍ୟନ୍ତ ମିଳିନାହିଁ ତେବେ ଛାଡ଼ିଦିଅନ୍ତୁ — ଆପଣ କେଉଁଥିପାଇଁ ଯୋଗ୍ୟ ସେଥିରେ ଏହା କିଛି ବଦଳାଏ ନାହିଁ, ଏବଂ ପରେ ଯୋଡ଼ିପାରିବେ।',
  'q.date_of_birth': 'ଆପଣ କେବେ ଜନ୍ମ ହୋଇଥିଲେ?',
  'q.date_of_birth.help': 'କିଛି ଛାତ୍ରବୃତ୍ତିରେ ବୟସ ସୀମା ଥାଏ।',
  'q.course_name': 'ଆପଣ କ’ଣ ପଢ଼ୁଛନ୍ତି?',
  'q.course_name.help': 'ପଞ୍ଜୀକରଣ ସମୟରେ ଆପଣ ବାଛିଥିବା ପାଠ୍ୟକ୍ରମ।',
  'q.institution_name': 'ଆପଣ କେଉଁଠି ପଢ଼ନ୍ତି?',
  'q.institution_name.help': 'ଆପଣଙ୍କ ବିଦ୍ୟାଳୟ, ମହାବିଦ୍ୟାଳୟ କିମ୍ବା ବିଶ୍ୱବିଦ୍ୟାଳୟର ନାମ, ଯେପରି ଆପଣଙ୍କ ବୋନାଫାଇଡ୍ ପ୍ରମାଣପତ୍ରରେ ଲେଖାଅଛି। ଏପର୍ଯ୍ୟନ୍ତ ଆରମ୍ଭ କରିନାହାନ୍ତି ତେବେ ଛାଡ଼ିଦିଅନ୍ତୁ।',
  'q.institution_name.placeholder': 'ଆପଣଙ୍କ ବିଦ୍ୟାଳୟ କିମ୍ବା ମହାବିଦ୍ୟାଳୟର ନାମ',
  'q.state_code': 'ଆପଣ କେଉଁ ରାଜ୍ୟରେ ରହନ୍ତି?',
  'q.state_code.help': 'ଅନେକ ଛାତ୍ରବୃତ୍ତି କେବଳ କିଛି ରାଜ୍ୟର ବାସିନ୍ଦାଙ୍କ ପାଇଁ ଖୋଲା।',
  'q.annual_family_income': 'ଆପଣଙ୍କ ପରିବାରର ବାର୍ଷିକ ଆୟ କେତେ?',
  'q.annual_family_income.help': 'ଟଙ୍କାରେ, ଯେପରି ଆପଣଙ୍କ ଆୟ ପ୍ରମାଣପତ୍ରରେ ଅଛି। ଅଧିକାଂଶ ଛାତ୍ରବୃତ୍ତିରେ ଏକ ସୀମା ଥାଏ।',
  'q.annual_family_income.range': 'ଆୟ ଶୂନ୍ୟଠାରୁ କମ୍ ହୋଇପାରିବ ନାହିଁ।',
  'q.academic_percentage': 'ଆପଣଙ୍କ ଶେଷ ପରୀକ୍ଷାର ନମ୍ବର କେତେ ଥିଲା?',
  'q.academic_percentage.help': 'ଆପଣଙ୍କ ମାର୍କସିଟ୍ ଯେଉଁ ଢଙ୍ଗରେ ତାହା କହେ ସେହିଟି ବାଛନ୍ତୁ, ତାପରେ ସଂଖ୍ୟା ଲେଖନ୍ତୁ। ଅନେକ ଛାତ୍ରବୃତ୍ତି ଏକ ନ୍ୟୂନତମ ମାଗନ୍ତି।',
  'field.orgKind.NGO': 'ଏନଜିଓ',
  'field.orgKind.CORPORATE': 'କର୍ପୋରେଟ୍',
  'field.orgKind.GOVERNMENT': 'ସରକାରୀ',
  'field.orgKind.PRIVATE': 'ବେସରକାରୀ',

  'field.doc.DISABILITY_CERTIFICATE': 'ଦିବ୍ୟାଙ୍ଗତା ପ୍ରମାଣପତ୍ର',
  'field.doc.UDID_CARD': 'UDID କାର୍ଡ',
  'field.doc.INCOME_CERTIFICATE': 'ଆୟ ପ୍ରମାଣପତ୍ର',
  'field.doc.DOMICILE_CERTIFICATE': 'ବସବାସ ପ୍ରମାଣପତ୍ର',
  'field.doc.CASTE_CERTIFICATE': 'ଜାତି ପ୍ରମାଣପତ୍ର',
  'field.doc.MARKSHEET': 'ମାର୍କସିଟ୍',
  'field.doc.ADMISSION_LETTER': 'ନାମଲେଖା ପତ୍ର',
  'field.doc.BONAFIDE_CERTIFICATE': 'ବୋନାଫାଇଡ୍ ପ୍ରମାଣପତ୍ର',
  'field.doc.FEE_RECEIPT': 'ଫି ରସିଦ',
  'field.doc.BANK_PASSBOOK': 'ବ୍ୟାଙ୍କ ପାସବୁକ୍',
  'field.doc.IDENTITY_PROOF': 'ପରିଚୟ ପ୍ରମାଣ',
  'field.doc.PHOTOGRAPH': 'ଫଟୋ',

  'appl.next.SUBMITTED': 'ପ୍ରଦାନକାରୀଙ୍କ ପାଖରେ ଆପଣଙ୍କ ଆବେଦନ ଅଛି। ଏହା ପରେ ଜଣେ ସମୀକ୍ଷକ ଏହାକୁ ପଢ଼ିବେ।',
  'appl.next.UNDER_REVIEW': 'ଜଣେ ସମୀକ୍ଷକ ଆପଣଙ୍କ ଆବେଦନ ପଢ଼ୁଛନ୍ତି। ସାଧାରଣତଃ ଏହା ହିଁ ସବୁଠାରୁ ଦୀର୍ଘ ପଦକ୍ଷେପ।',
  'appl.next.INFO_REQUESTED': 'ସେମାନେ ଆପଣଙ୍କଠାରୁ କିଛି ମାଗିଛନ୍ତି। ଆପଣ ଉତ୍ତର ନଦେବା ପର୍ଯ୍ୟନ୍ତ ଆବେଦନ ଅପେକ୍ଷା କରିବ।',
  'appl.next.DOCUMENT_CHECK': 'ଆପଣଙ୍କ ଆବେଦନ ସମୀକ୍ଷକଙ୍କ ପାଖରେ ଅଛି। ଆପଣଙ୍କଠାରୁ କିଛି ଦରକାର ନାହିଁ।',
  'appl.next.VERIFIED': 'ଆପଣଙ୍କ ଆବେଦନ ସମୀକ୍ଷକଙ୍କ ପାଖରେ ଅଛି। ଆପଣଙ୍କଠାରୁ କିଛି ଦରକାର ନାହିଁ।',
  'appl.next.SHORTLISTED': 'ଆପଣଙ୍କ ଆବେଦନ ସମୀକ୍ଷକଙ୍କ ପାଖରେ ଅଛି। ଏହା ପରେ ନିଷ୍ପତ୍ତି।',
  'appl.next.APPROVED': 'ଅନୁମୋଦିତ। ପ୍ରଦାନକାରୀ ମଞ୍ଜୁରୀ ଲିପିବଦ୍ଧ କରିବେ, ତାପରେ ଦେୟର ବ୍ୟବସ୍ଥା କରିବେ।',
  'appl.next.SANCTIONED': 'ଟଙ୍କା ମଞ୍ଜୁର ହୋଇଛି। ଦେୟ ସେମାନଙ୍କ ବ୍ୟାଙ୍କ ମାଧ୍ୟମରେ କରାଯାଏ।',
  'appl.next.DISBURSED': 'ଦେୟ ଲିପିବଦ୍ଧ ହୋଇଛି। କିଛି କାର୍ଯ୍ୟଦିବସ ମଧ୍ୟରେ ଆପଣଙ୍କ ଖାତାକୁ ନପହଞ୍ଚିଲେ ଅଭିଯୋଗ କରନ୍ତୁ।',
  'appl.next.REJECTED': 'ଏହି ଆବେଦନ ସଫଳ ହୋଇନାହିଁ। ଏଥିରେ ଆପଣଙ୍କ ଅନ୍ୟ ଆବେଦନ ଉପରେ କୌଣସି ପ୍ରଭାବ ପଡ଼େ ନାହିଁ।',
  'appl.next.CLOSED': 'ଏହି ଆବେଦନ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି।',
  'appl.next.WITHDRAWN': 'ଆପଣ ଏହି ଆବେଦନ ପ୍ରତ୍ୟାହାର କରିଥିଲେ।',
}

export default or
