/* Punjabi, in Gurmukhi.
 *
 * One word per term: scholarship ਵਜ਼ੀਫ਼ਾ, application ਅਰਜ਼ੀ,
 * document ਦਸਤਾਵੇਜ਼, disability ਦਿਵਿਆਂਗਤਾ (the RPwD Act's word; ਅਪਾਹਜ is
 * not used anywhere in this file), verified ਤਸਦੀਕਸ਼ੁਦਾ, eligible ਯੋਗ,
 * certificate ਸਰਟੀਫਿਕੇਟ, profile ਪ੍ਰੋਫਾਈਲ.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const pa: Dict = {
  'app.name': 'ਇੰਡਿਕ ਏਆਈ ਵਜ਼ੀਫ਼ਾ',
  'app.tagline': 'ਦਿਵਿਆਂਗ ਵਿਦਿਆਰਥੀਆਂ ਲਈ',
  'app.yourApplication': 'ਤੁਹਾਡੀ ਅਰਜ਼ੀ · {title}',

  'nav.find': 'ਵਜ਼ੀਫ਼ੇ',
  'nav.how': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
  'nav.matches': 'ਮੇਰੇ ਮੇਲ',
  'nav.applications': 'ਮੇਰੀਆਂ ਅਰਜ਼ੀਆਂ',
  'nav.documents': 'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',
  'nav.profile': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
  'nav.privacy': 'ਮੇਰਾ ਡਾਟਾ',
  'nav.account': 'ਮੇਰਾ ਖਾਤਾ',
  'nav.register': 'ਸਾਈਨ ਅੱਪ',
  'nav.language': 'ਭਾਸ਼ਾ',
  'footer.social': 'ਇੰਡਿਕ ਏਆਈ ਹੋਰ ਥਾਵਾਂ ਉੱਤੇ',
  'footer.sponsor': 'ਸਹਿਯੋਗ ਨਾਲ',
  'footer.copyright': 'ਕਾਪੀਰਾਈਟ © {year} ਇੰਡਿਕ ਏਆਈ | ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ',
  'nav.signin': 'ਸਾਈਨ ਇਨ',
  'nav.signout': 'ਸਾਈਨ ਆਊਟ',
  'nav.skip': 'ਮੁੱਖ ਸਮੱਗਰੀ ਉੱਤੇ ਜਾਓ',

  'public.title': 'ਉਹ ਵਜ਼ੀਫ਼ਾ ਲੱਭੋ ਜਿਸ ਦੇ ਤੁਸੀਂ ਯੋਗ ਹੋ',
  'public.lede': 'ਇੱਥੇ ਹਰ ਵਜ਼ੀਫ਼ਾ ਦਿਵਿਆਂਗ ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਖੁੱਲ੍ਹਾ ਹੈ। ਵੇਖਣ ਲਈ ਖਾਤੇ ਦੀ ਲੋੜ ਨਹੀਂ।',
  'public.search': 'ਨਾਂ ਜਾਂ ਸ਼ਬਦ ਨਾਲ ਲੱਭੋ',
  'public.filter.disability': 'ਦਿਵਿਆਂਗਤਾ ਦੀ ਕਿਸਮ',
  'public.filter.qualification': 'ਯੋਗਤਾ',
  'public.filter.state': 'ਤੁਹਾਡਾ ਰਾਜ',
  'public.filter.provider': 'ਕੌਣ ਦੇ ਰਿਹਾ ਹੈ',
  'public.filter.any': 'ਕੋਈ ਵੀ',
  'public.filter.anyDisability': 'ਕੋਈ ਵੀ ਦਿਵਿਆਂਗਤਾ',
  'public.filter.anyQualification': 'ਕੋਈ ਵੀ ਯੋਗਤਾ',
  'public.filter.allStates': 'ਸਾਰੇ ਰਾਜ',
  'public.filter.gender': 'ਲਿੰਗ',
  'public.filter.anyGender': 'ਕੋਈ ਵੀ ਲਿੰਗ',
  'public.filter.course': 'ਕੋਰਸ',
  'public.filter.anyCourse': 'ਕੋਈ ਵੀ ਕੋਰਸ',
  'public.filter.where': 'ਤੁਸੀਂ ਕਿੱਥੇ ਪੜ੍ਹਦੇ ਹੋ',
  'public.filter.anyWhere': 'ਭਾਰਤ ਜਾਂ ਵਿਦੇਸ਼',
  'public.filter.inIndia': 'ਭਾਰਤ ਵਿੱਚ',
  'public.filter.abroad': 'ਵਿਦੇਸ਼ ਵਿੱਚ ਪੜ੍ਹਾਈ',
  'public.filters': 'ਫ਼ਿਲਟਰ',
  'public.clear': 'ਹਟਾਓ',
  'public.results': 'ਵਜ਼ੀਫ਼ੇ ਹੁਣ ਖੁੱਲ੍ਹੇ ਹਨ',
  'public.searching': 'ਲੱਭ ਰਹੇ ਹਾਂ…',
  'public.none': 'ਇਨ੍ਹਾਂ ਫ਼ਿਲਟਰਾਂ ਨਾਲ ਕੋਈ ਵਜ਼ੀਫ਼ਾ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ',
  'public.none.hint': 'ਇੱਕ ਫ਼ਿਲਟਰ ਹਟਾ ਕੇ ਵੇਖੋ। ਸਾਰਾ ਸਾਲ ਨਵੀਆਂ ਸਕੀਮਾਂ ਖੁੱਲ੍ਹਦੀਆਂ ਰਹਿੰਦੀਆਂ ਹਨ।',
  'public.none.clear': 'ਸਾਰੇ ਫ਼ਿਲਟਰ ਹਟਾਓ',
  'public.empty': 'ਇੱਥੇ ਹਾਲੇ ਕੋਈ ਵਜ਼ੀਫ਼ਾ ਸੂਚੀਬੱਧ ਨਹੀਂ ਹੈ',
  'public.empty.hint': 'ਦੇਣ ਵਾਲੀਆਂ ਸੰਸਥਾਵਾਂ ਹੁਣ ਜੋੜੀਆਂ ਜਾ ਰਹੀਆਂ ਹਨ। ਇੱਥੇ ਕੁਝ ਵੀ ਖਾਤੇ ਪਿੱਛੇ ਨਹੀਂ — ਸਕੀਮਾਂ ਸੂਚੀਬੱਧ ਹੋਣ ਉੱਤੇ ਤੁਸੀਂ ਸਾਈਨ ਇਨ ਕੀਤੇ ਬਿਨਾਂ ਹੀ ਵੇਖ ਸਕੋਗੇ।',
  'public.whoFor': 'ਇਹ ਕਿਸ ਲਈ ਹੈ',
  'public.about': 'ਇਸ ਵਜ਼ੀਫ਼ੇ ਬਾਰੇ',
  'public.atAGlance': 'ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ',
  'public.closes': 'ਬੰਦ ਹੁੰਦਾ ਹੈ',
  'public.awardUnstated': 'ਰਕਮ ਨਹੀਂ ਦੱਸੀ ਗਈ',
  'public.noClose': 'ਕੋਈ ਆਖ਼ਰੀ ਤਾਰੀਖ਼ ਨਹੀਂ',
  'public.closesIn': '{n} ਦਿਨਾਂ ਵਿੱਚ ਬੰਦ',
  'public.closesToday': 'ਅੱਜ ਬੰਦ ਹੋ ਰਿਹਾ ਹੈ',
  'public.closed': 'ਬੰਦ',
  'public.award': 'ਰਕਮ',
  'public.renewable': 'ਹਰ ਸਾਲ ਨਵਿਆਇਆ ਜਾ ਸਕਦਾ ਹੈ',
  'public.offeredBy': 'ਦੇਣ ਵਾਲੀ ਸੰਸਥਾ',
  'public.eligibility': 'ਯੋਗ ਹੋਣ ਲਈ',
  'public.benefits': 'ਲਾਭ',
  'public.readMore': 'ਹੋਰ ਪੜ੍ਹੋ',
  'public.viewDetails': 'ਵੇਰਵੇ ਵੇਖੋ',
  'public.applyNow': 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
  'public.registerToApply': 'ਅਰਜ਼ੀ ਦਿਓ',
  'public.registerToApplyHelp': 'ਅਰਜ਼ੀਆਂ ਤੁਹਾਡੇ ਖਾਤੇ ਰਾਹੀਂ ਦਿੱਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ। ਰਜਿਸਟਰ ਕਰਨ ਨਾਲ ਤੁਹਾਨੂੰ ਹਰ ਉਹ ਵਜ਼ੀਫ਼ਾ ਵੀ ਦਿਸੇਗਾ ਜਿਸ ਦੇ ਤੁਸੀਂ ਯੋਗ ਹੋ।',
  'public.closedNote': 'ਇਹ ਸਕੀਮ ਬੰਦ ਹੋ ਚੁੱਕੀ ਹੈ',
  'sheet.close': 'ਬੰਦ ਕਰੋ',
  'sheet.loading': 'ਵਜ਼ੀਫ਼ੇ ਦੇ ਵੇਰਵੇ',
  'public.benefitComponent': 'ਮਦ',
  'public.benefitAmount': 'ਵਿਦਿਆਰਥੀ ਨੂੰ ਕੀ ਮਿਲਦਾ ਹੈ',
  'public.whatYouGet': 'ਤੁਹਾਨੂੰ ਕੀ ਮਿਲੇਗਾ',
  'public.eligibilityDetail': 'ਯੋਗਤਾ ਵਿਸਤਾਰ ਨਾਲ',
  'public.documentsRequired': 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
  'public.documentsHelp': 'ਦੇਣ ਵਾਲੀ ਸੰਸਥਾ ਇਹ ਮੰਗਦੀ ਹੈ। ਇਹ ਤੁਸੀਂ ਇੱਥੇ ਅੱਪਲੋਡ ਨਹੀਂ ਕਰਦੇ।',
  'public.howToApply': 'ਅਰਜ਼ੀ ਕਿਵੇਂ ਦੇਣੀ ਹੈ',
  'public.importantNotes': 'ਜਾਣਨ ਯੋਗ ਗੱਲਾਂ',
  'public.academicYear': 'ਕਿਸ ਸਾਲ ਲਈ',
  'public.awardBasis': 'ਕਿਸ ਆਧਾਰ ਉੱਤੇ',
  'public.basis.MERIT': 'ਮੈਰਿਟ',
  'public.basis.NEED': 'ਆਰਥਿਕ ਲੋੜ',
  'public.basis.MERIT_CUM_MEANS': 'ਮੈਰਿਟ ਅਤੇ ਆਮਦਨ',
  'public.basis.CATEGORY': 'ਸ਼੍ਰੇਣੀ',
  'public.basis.OTHER': 'ਹੋਰ',
  'public.cta': 'ਆਪਣੇ ਲਈ ਵਜ਼ੀਫ਼ੇ ਲੱਭੋ',
  'public.applyExternal': 'ਉਨ੍ਹਾਂ ਦੀ ਸਾਈਟ ਉੱਤੇ ਅਰਜ਼ੀ ਦਿਓ',
  'public.applyExternalHelp': 'ਅਸੀਂ ਇਹ ਵਜ਼ੀਫ਼ਾ ਇਸੇ ਲਈ ਸੂਚੀਬੱਧ ਕਰਦੇ ਹਾਂ ਤਾਂ ਜੋ ਤੁਸੀਂ ਇਸ ਨੂੰ ਲੱਭ ਸਕੋ। ਇਸ ਨੂੰ {org} ਚਲਾਉਂਦੀ ਹੈ ਅਤੇ ਅਰਜ਼ੀਆਂ ਆਪਣੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਹੀ ਲੈਂਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਇੱਥੇ ਤੁਹਾਡੀਆਂ ਅਰਜ਼ੀਆਂ ਵਿੱਚ ਨਹੀਂ ਦਿਸੇਗਾ।',
  'public.applyExternalHelpPartner': '{org} ਇਹ ਅਰਜ਼ੀ ਆਪਣੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਹੀ ਲੈਂਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਇੱਥੇ ਤੁਹਾਡੀਆਂ ਅਰਜ਼ੀਆਂ ਵਿੱਚ ਨਹੀਂ ਦਿਸੇਗੀ।',
  'common.newTab': 'ਨਵੀਂ ਟੈਬ ਵਿੱਚ ਖੁੱਲ੍ਹਦਾ ਹੈ',
  'public.applyHelp': 'ਅਸੀਂ ਪਹਿਲਾਂ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਦਸਤਾਵੇਜ਼ ਇਸ ਵਜ਼ੀਫ਼ੇ ਨਾਲ ਪਰਖਦੇ ਹਾਂ ਅਤੇ ਜੇ ਕੁਝ ਘਟਦਾ ਹੋਵੇ ਤਾਂ ਦੱਸਦੇ ਹਾਂ। ਤੁਹਾਡੀ ਪੁਸ਼ਟੀ ਤੋਂ ਪਹਿਲਾਂ ਕੁਝ ਨਹੀਂ ਭੇਜਿਆ ਜਾਂਦਾ।',
  'public.ctaHelp': 'ਆਪਣੇ ਬਾਰੇ ਇੱਕ ਵਾਰ ਦੱਸੋ ਅਤੇ ਅਸੀਂ ਤੁਹਾਨੂੰ ਹਰ ਉਹ ਵਜ਼ੀਫ਼ਾ ਵਿਖਾਵਾਂਗੇ ਜਿਸ ਦੇ ਤੁਸੀਂ ਯੋਗ ਹੋ।',
  'public.back': 'ਸਾਰੇ ਵਜ਼ੀਫ਼ਿਆਂ ਉੱਤੇ ਵਾਪਸ',
  'notFound.title': 'ਸਾਨੂੰ ਇਹ ਪੰਨਾ ਨਹੀਂ ਮਿਲਿਆ',
  'notFound.body': 'ਪਤੇ ਵਿੱਚ ਟਾਈਪਿੰਗ ਦੀ ਗਲਤੀ ਹੋ ਸਕਦੀ ਹੈ, ਜਾਂ ਪੰਨਾ ਕਿਤੇ ਹੋਰ ਚਲਾ ਗਿਆ ਹੋ ਸਕਦਾ ਹੈ।',
  'notFound.home': 'ਹੋਮ ਪੰਨੇ ’ਤੇ ਜਾਓ',

  'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
  'dash.title': 'ਤੁਹਾਡਾ ਡੈਸ਼ਬੋਰਡ',
  'dash.lede': 'ਤੁਹਾਡੇ ਵਜ਼ੀਫ਼ੇ, ਅਰਜ਼ੀਆਂ ਅਤੇ ਦਸਤਾਵੇਜ਼, ਸਭ ਇੱਕੋ ਥਾਂ।',
  'dash.matches': 'ਜਿਨ੍ਹਾਂ ਵਜ਼ੀਫ਼ਿਆਂ ਲਈ ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਸਕਦੇ ਹੋ',
  'dash.matchesHint': 'ਤੁਹਾਡੇ ਦਿੱਤੇ ਵੇਰਵਿਆਂ ਦੇ ਆਧਾਰ ਉੱਤੇ।',
  'dash.matchesBlocked': '{n} ਤੁਹਾਥੋਂ ਇੱਕ ਹੋਰ ਵੇਰਵੇ ਦੀ ਉਡੀਕ ਵਿੱਚ।',
  'dash.applications': 'ਚੱਲਦੀਆਂ ਅਰਜ਼ੀਆਂ',
  'dash.applicationsHint': '{approved} ਮਨਜ਼ੂਰ · {rejected} ਸਫ਼ਲ ਨਹੀਂ',
  'dash.applicationsNone': 'ਹਾਲੇ ਕੁਝ ਨਹੀਂ ਭੇਜਿਆ।',
  'dash.documents': 'ਤਸਦੀਕਸ਼ੁਦਾ ਦਸਤਾਵੇਜ਼',
  'dash.documentsHint': 'ਇੱਕ ਵਾਰ ਪਰਖੇ ਗਏ। ਹਰ ਅਰਜ਼ੀ ਵਿੱਚ ਕੰਮ ਆਉਂਦੇ ਹਨ।',
  'dash.funding': 'ਹੁਣ ਤੱਕ ਮਿਲਿਆ',
  'dash.fundingHint': 'ਕੁੱਲ {sanctioned} ਮਨਜ਼ੂਰ।',
  'dash.recent': 'ਹਾਲੀਆ ਅਰਜ਼ੀਆਂ',
  'dash.noApplications': 'ਹਾਲੇ ਕੋਈ ਅਰਜ਼ੀ ਨਹੀਂ',
  'dash.noApplicationsHint': 'ਤੁਸੀਂ ਜਿਸ ਲਈ ਵੀ ਅਰਜ਼ੀ ਦਿਓਗੇ ਉਹ ਇੱਥੇ ਦਿਸੇਗੀ।',
  'dash.findScholarships': 'ਵਜ਼ੀਫ਼ੇ ਲੱਭੋ',
  'dash.profileTitle': 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ',
  'dash.toGo': '{n}% ਬਾਕੀ',
  'dash.allApplications': 'ਸਭ ਵੇਖੋ',
  'dash.matchesGo': 'ਆਪਣੇ ਮੇਲ ਵੇਖੋ',
  'dash.applicationsGo': 'ਆਪਣੀਆਂ ਅਰਜ਼ੀਆਂ ਵੇਖੋ',
  'dash.documentsGo': 'ਦਸਤਾਵੇਜ਼ ਸੰਭਾਲੋ',
  'dash.draftsTitle': '{n} ਅਰਜ਼ੀ ਨਹੀਂ ਭੇਜੀ ਗਈ | {n} ਅਰਜ਼ੀਆਂ ਨਹੀਂ ਭੇਜੀਆਂ ਗਈਆਂ',
  'dash.draftsBody': 'ਅਰਜ਼ੀ ਸ਼ੁਰੂ ਕਰਨ ਨਾਲ ਉਹ ਭੇਜੀ ਨਹੀਂ ਜਾਂਦੀ। ਵਜ਼ੀਫ਼ਾ ਬੰਦ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਪੂਰੀ ਕਰੋ।',
  'dash.draftsAction': 'ਹੁਣੇ ਪੂਰੀ ਕਰੋ',
  'dash.expiringTitle': '{n} ਦਸਤਾਵੇਜ਼ ਦੀ ਮਿਆਦ ਜਲਦੀ ਮੁੱਕ ਰਹੀ ਹੈ | {n} ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਮਿਆਦ ਜਲਦੀ ਮੁੱਕ ਰਹੀ ਹੈ',
  'dash.expiringBody': 'ਹਰ ਅਰਜ਼ੀ ਵਿੱਚ ਕੰਮ ਆਵੇ, ਇਸ ਲਈ ਇਸ ਨੂੰ ਹੁਣੇ ਬਦਲੋ। | ਹਰ ਅਰਜ਼ੀ ਵਿੱਚ ਕੰਮ ਆਉਣ, ਇਸ ਲਈ ਇਨ੍ਹਾਂ ਨੂੰ ਹੁਣੇ ਬਦਲੋ।',
  'dash.expiringAction': 'ਦਸਤਾਵੇਜ਼ ਵੇਖੋ',

  'auth.title': 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ',
  'auth.phone': 'ਮੋਬਾਈਲ ਨੰਬਰ',
  'auth.phoneHint': 'ਅਸੀਂ ਇਸ ਨੰਬਰ ਉੱਤੇ SMS ਰਾਹੀਂ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਭੇਜਾਂਗੇ। ਹਰ ਵਾਰ ਇਹੀ ਨੰਬਰ ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਕਰਾਉਂਦਾ ਹੈ।',
  'auth.phoneMissing': 'ਅੱਗੇ ਵਧਣ ਲਈ ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ।',
  'auth.phoneInvalid': 'ਇਹ ਠੀਕ ਨਹੀਂ ਲੱਗਦਾ। ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ 10 ਅੰਕਾਂ ਦੇ ਹੁੰਦੇ ਹਨ ਅਤੇ 6, 7, 8 ਜਾਂ 9 ਤੋਂ ਸ਼ੁਰੂ ਹੁੰਦੇ ਹਨ।',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'ਨਵੇਂ ਹੋਵੋ ਜਾਂ ਵਾਪਸ ਆ ਰਹੇ ਹੋਵੋ, ਉਹੀ ਨੰਬਰ ਕੰਮ ਕਰਦਾ ਹੈ। ਜੇ ਤੁਹਾਡਾ ਖਾਤਾ ਨਹੀਂ ਤਾਂ ਅਸੀਂ ਬਣਾ ਦਿੰਦੇ ਹਾਂ।',
  'auth.stepOf': 'ਕਦਮ {n} / 2 · {name}',
  'auth.stepPhone': 'ਤੁਹਾਡਾ ਨੰਬਰ',
  'auth.stepCode': 'ਤੁਹਾਡਾ OTP ਕੋਡ',
  'auth.privacy': 'ਤੁਹਾਡਾ ਨੰਬਰ ਸਿਰਫ਼ ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਕਰਾਉਣ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ, ਹੋਰ ਕਿਸੇ ਕੰਮ ਲਈ ਨਹੀਂ। ਯਾਦ ਰੱਖਣ ਲਈ ਕੋਈ ਪਾਸਵਰਡ ਨਹੀਂ ਹੈ।',
  'auth.sendCode': 'ਕੋਡ ਭੇਜੋ',
  'auth.sending': 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
  'auth.checking': 'ਪਰਖਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
  'auth.welcomeBack': 'ਫਿਰ ਜੀ ਆਇਆਂ ਨੂੰ। ਸਾਈਨ ਇਨ ਕਰਨ ਲਈ ਕੋਡ ਭਰੋ।',
  'auth.newHere': 'ਕੋਡ ਭਰਦੇ ਹੀ ਅਸੀਂ ਤੁਹਾਡਾ ਖਾਤਾ ਬਣਾ ਦੇਵਾਂਗੇ।',
  'auth.codeTitle': 'ਅਸੀਂ ਜੋ ਕੋਡ ਭੇਜਿਆ ਹੈ ਉਹ ਭਰੋ',
  'auth.code': '6 ਅੰਕਾਂ ਦਾ ਕੋਡ',
  'auth.codeHint': 'ਸੁਨੇਹਾ ਆਮ ਤੌਰ ਉੱਤੇ ਕੁਝ ਹੀ ਸਕਿੰਟਾਂ ਵਿੱਚ ਆ ਜਾਂਦਾ ਹੈ।',
  'auth.noCode': 'ਹਾਲੇ ਤੱਕ ਸੁਨੇਹਾ ਨਹੀਂ ਆਇਆ? ਕੋਈ ਹੋਰ ਤਰੀਕਾ ਅਜ਼ਮਾਓ:',
  'auth.verify': 'ਤਸਦੀਕ ਕਰੋ',
  'auth.viaSms': 'SMS ਰਾਹੀਂ ਭੇਜੋ',
  'auth.viaWhatsapp': 'ਵਟਸਐਪ ਉੱਤੇ ਭੇਜੋ',
  'auth.viaVoice': 'ਕੋਡ ਦੱਸਣ ਲਈ ਮੈਨੂੰ ਫ਼ੋਨ ਕਰੋ',
  'auth.resentVia.sms': 'SMS ਰਾਹੀਂ ਭੇਜ ਦਿੱਤਾ। ਆਉਣ ਵਿੱਚ ਥੋੜ੍ਹਾ ਸਮਾਂ ਲੱਗ ਸਕਦਾ ਹੈ।',
  'auth.resentVia.whatsapp': 'ਵਟਸਐਪ ਉੱਤੇ ਭੇਜ ਦਿੱਤਾ। ਸੁਨੇਹੇ ਲਈ ਵਟਸਐਪ ਵੇਖੋ।',
  'auth.resentVia.voice': 'ਕੋਡ ਦੱਸਣ ਲਈ ਹੁਣੇ ਫ਼ੋਨ ਕਰ ਰਹੇ ਹਾਂ। ਸੁਣਨ ਲਈ ਫ਼ੋਨ ਚੁੱਕੋ।',
  'auth.resendIn': '{n} ਸਕਿੰਟਾਂ ਵਿੱਚ ਫਿਰ ਭੇਜੋ',
  'auth.changeNumber': 'ਹੋਰ ਨੰਬਰ ਵਰਤੋ',
  'auth.change': 'ਬਦਲੋ',

  'profile.complete': '{n}% ਪੂਰੀ',
  'profile.viewLede': 'ਤੁਸੀਂ ਸਾਨੂੰ ਜੋ ਕੁਝ ਦੱਸਿਆ ਹੈ। ਕੋਈ ਵੀ ਜਵਾਬ ਬਦਲੋ ਅਤੇ ਉਸ ਤੋਂ ਬਾਅਦ ਹਰ ਵਜ਼ੀਫ਼ੇ ਲਈ ਉਹੀ ਵਰਤਿਆ ਜਾਵੇਗਾ।',
  'profile.notAnswered': 'ਹਾਲੇ ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ',
  'profile.verified': 'ਤਸਦੀਕਸ਼ੁਦਾ',
  'profile.continue': 'ਜਿੱਥੇ ਛੱਡਿਆ ਸੀ ਉੱਥੋਂ ਜਾਰੀ ਰੱਖੋ',
  'profile.start': 'ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਸ਼ੁਰੂ ਕਰੋ',
  'profile.saved': 'ਸੰਭਾਲ ਲਿਆ',

  'match.title': 'ਤੁਹਾਡੇ ਲਈ ਵਜ਼ੀਫ਼ੇ',
  'match.lede': 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਨਾਲ ਪਰਖੇ ਗਏ। ਜਿਨ੍ਹਾਂ ਲਈ ਅਰਜ਼ੀ ਦੇ ਸਕਦੇ ਹੋ ਉਹ ਪਹਿਲਾਂ।',
  'match.eligible': 'ਤੁਸੀਂ ਯੋਗ ਹੋ',
  'match.likely': 'ਤੁਸੀਂ ਸ਼ਾਇਦ ਯੋਗ ਹੋ',
  'match.blocked': 'ਪਹਿਲਾਂ ਇੱਕ ਕੰਮ',
  'match.actionable': 'ਤੁਹਾਡੇ ਲਈ ਖੁੱਲ੍ਹੇ',
  'match.actionableHelp': 'ਕੁਝ ਲਈ ਅਰਜ਼ੀ ਤੋਂ ਪਹਿਲਾਂ ਇੱਕ ਦਸਤਾਵੇਜ਼ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ।',
  'match.ineligible': 'ਤੁਹਾਡੇ ਲਈ ਖੁੱਲ੍ਹੇ ਨਹੀਂ',
  'match.eligibleHelp': 'ਅਸੀਂ ਜੋ ਕੁਝ ਪਰਖਿਆ ਉਹ ਸਭ ਤਸਦੀਕਸ਼ੁਦਾ ਹੈ।',
  'match.likelyHelp': 'ਤੁਸੀਂ ਜੋ ਦੱਸਿਆ ਉਸ ਦੇ ਆਧਾਰ ਉੱਤੇ। ਤਸਦੀਕ ਕਰਵਾਉਣ ਨਾਲ ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਮਜ਼ਬੂਤ ਹੁੰਦੀ ਹੈ।',
  'match.blockedHelp': 'ਤੁਸੀਂ ਨੇੜੇ ਹੋ। ਇਹ ਕਰ ਲਓ ਅਤੇ ਅਰਜ਼ੀ ਦੇ ਸਕੋਗੇ।',
  'match.ineligibleHelp': 'ਇਹ ਸਕੀਮ ਅਜਿਹੀ ਚੀਜ਼ ਮੰਗਦੀ ਹੈ ਜੋ ਤੁਸੀਂ ਬਦਲ ਨਹੀਂ ਸਕਦੇ।',
  'match.apply': 'ਅਰਜ਼ੀ ਦਿਓ',
  'match.applied': 'ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਦਿੱਤੀ ਹੈ',
  'match.none': 'ਹਾਲੇ ਕੋਈ ਮੇਲ ਨਹੀਂ',
  'match.noneHint': 'ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਪੂਰੀ ਕਰੋ ਅਤੇ ਅਸੀਂ ਤੁਹਾਡੇ ਲਈ ਹਰ ਵਜ਼ੀਫ਼ਾ ਪਰਖਾਂਗੇ।',
  'match.figQualify': 'ਤੁਸੀਂ ਯੋਗ ਹੋ',
  'match.figStep': 'ਇੱਕ ਕਦਮ ਦੂਰ',
  'match.figClosing': 'ਜਲਦੀ ਬੰਦ',
  'match.figNo': 'ਤੁਹਾਡੇ ਲਈ ਖੁੱਲ੍ਹੇ ਨਹੀਂ',
  'match.filterLabel': 'ਕਿਹੜੇ ਵਜ਼ੀਫ਼ੇ ਵਿਖਾਉਣੇ ਹਨ',
  'match.filterAll': 'ਸਾਰੇ',
  'match.filterQualify': 'ਤੁਸੀਂ ਯੋਗ ਹੋ',
  'match.filterStep': 'ਇੱਕ ਕਦਮ ਦੂਰ',
  'match.filterClosing': 'ਜਲਦੀ ਬੰਦ',
  'match.filterNo': 'ਤੁਹਾਡੇ ਲਈ ਖੁੱਲ੍ਹੇ ਨਹੀਂ',
  'match.filterEmpty': 'ਇਸ ਸਮੂਹ ਵਿੱਚ ਕੁਝ ਨਹੀਂ। “ਸਾਰੇ” ਅਜ਼ਮਾਓ।',
  'match.moreWithProfile': 'ਜਿਵੇਂ-ਜਿਵੇਂ ਤੁਸੀਂ ਇਸ ਨੂੰ ਭਰੋਗੇ, ਹੋਰ ਵਜ਼ੀਫ਼ੇ ਦਿਸਣਗੇ।',
  'match.youQualify': 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਮੁਤਾਬਕ ਤੁਸੀਂ ਸ਼ਰਤਾਂ ਪੂਰੀਆਂ ਕਰਦੇ ਹੋ।',
  'match.yesTitle': 'ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਸਕਦੇ ਹੋ',
  'match.blockedTitle': 'ਪਹਿਲਾਂ ਇੱਕ ਕੰਮ',
  'match.noTitle': 'ਯੋਗ ਨਹੀਂ',
  'match.appliedTitle': 'ਪਹਿਲਾਂ ਹੀ ਭੇਜੀ ਗਈ',
  'match.seeDetails': 'ਨਿਯਮ ਵੇਖੋ',
  'match.learnMore': 'ਹੋਰ ਜਾਣੋ',
  'match.runBy': '{kind} ਵੱਲੋਂ ਚਲਾਇਆ ਜਾਂਦਾ ਹੈ',
  'match.sortBy': 'ਤਰਤੀਬ',
  'match.sortRecommended': 'ਸਿਫ਼ਾਰਸ਼ ਕੀਤੇ',
  'match.sortClosing': 'ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਬੰਦ ਹੋਣ ਵਾਲੇ',
  'match.sortAward': 'ਸਭ ਤੋਂ ਵੱਡੀ ਰਕਮ',
  'match.applyAway': 'ਉਨ੍ਹਾਂ ਦੀ ਸਾਈਟ ਉੱਤੇ ਅਰਜ਼ੀ ਦਿਓ',
  'match.applyHere': 'ਇੱਥੇ ਹੀ ਅਰਜ਼ੀ ਦਿਓ',
  'match.notOpenToYou': 'ਮੌਜੂਦਾ ਹਾਲਤ ਵਿੱਚ ਤੁਹਾਡੇ ਲਈ ਖੁੱਲ੍ਹਾ ਨਹੀਂ।',
  'match.working': 'ਹੁਣ ਖੁੱਲ੍ਹੀ ਕੋਈ ਵੀ ਸਕੀਮ ਤੁਹਾਡੇ ਦਿੱਤੇ ਵੇਰਵਿਆਂ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦੀ। ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਹੋਰ ਜੋੜਨ ਨਾਲ ਇਹ ਬਦਲਦਾ ਹੈ।',

  'doc.title': 'ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼',
  'doc.lede': 'ਦਸਤਾਵੇਜ਼ ਇੱਕ ਵਾਰ ਅੱਪਲੋਡ ਕਰੋ। ਤੁਸੀਂ ਜਿਸ ਵੀ ਵਜ਼ੀਫ਼ੇ ਲਈ ਅਰਜ਼ੀ ਦਿਓ ਉਹ ਇਸ ਨੂੰ ਵਰਤ ਸਕਦਾ ਹੈ — ਤੁਹਾਥੋਂ ਦੁਬਾਰਾ ਨਹੀਂ ਮੰਗਿਆ ਜਾਵੇਗਾ।',
  'doc.upload': 'ਦਸਤਾਵੇਜ਼ ਜੋੜੋ',
  'doc.type': 'ਇਹ ਕਿਹੜਾ ਦਸਤਾਵੇਜ਼ ਹੈ?',
  'doc.file': 'ਫ਼ਾਈਲ ਚੁਣੋ',
  'doc.fileHint': 'PDF ਜਾਂ ਸਾਫ਼ ਫ਼ੋਟੋ। 10 MB ਤੱਕ।',
  'doc.verified': 'ਤਸਦੀਕਸ਼ੁਦਾ',
  'doc.verifiedBy': '{org} ਵੱਲੋਂ ਤਸਦੀਕਸ਼ੁਦਾ',
  'doc.pending': 'ਤਸਦੀਕ ਦੀ ਉਡੀਕ ਵਿੱਚ',
  'doc.expired': 'ਤਸਦੀਕ ਦੀ ਮਿਆਦ ਮੁੱਕ ਗਈ',
  'doc.expiring': '{n} ਦਿਨਾਂ ਵਿੱਚ ਮਿਆਦ ਮੁੱਕਦੀ ਹੈ',
  'doc.validUntil': '{date} ਤੱਕ ਜਾਇਜ਼',
  'doc.none': 'ਤੁਸੀਂ ਹਾਲੇ ਕੋਈ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ ਜੋੜਿਆ',
  'doc.uploading': 'ਅੱਪਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
  'doc.remove': 'ਹਟਾਓ',
  'doc.removing': 'ਹਟਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…',

  'apply.title': 'ਅਰਜ਼ੀ ਦਿਓ',
  'apply.consent': 'ਮੇਰੇ ਵੇਰਵੇ ਇਸ ਸੰਸਥਾ ਨਾਲ ਸਾਂਝੇ ਕਰੋ',
  'apply.consentBody': 'ਫ਼ੈਸਲਾ ਲੈਣ ਲਈ ਇਸ ਵਜ਼ੀਫ਼ੇ ਨੂੰ ਜੋ ਚਾਹੀਦਾ ਹੈ ਸਿਰਫ਼ ਉਹੀ ਉਹ ਵੇਖਣਗੇ: {fields}. ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼ ਕਿਸ ਨੇ ਵੇਖੇ, ਇਹ ਤੁਸੀਂ ਕਦੇ ਵੀ ਵੇਖ ਸਕਦੇ ਹੋ।',
  'apply.consentBodyNoDocs': 'ਫ਼ੈਸਲਾ ਲੈਣ ਲਈ ਇਸ ਵਜ਼ੀਫ਼ੇ ਨੂੰ ਜੋ ਚਾਹੀਦਾ ਹੈ ਸਿਰਫ਼ ਉਹੀ ਉਹ ਵੇਖਣਗੇ, ਹੋਰ ਕੁਝ ਨਹੀਂ। ਤੁਹਾਡੇ ਵੇਰਵੇ ਕਿਸ ਨੇ ਵੇਖੇ, ਇਹ ਤੁਸੀਂ ਕਦੇ ਵੀ ਵੇਖ ਸਕਦੇ ਹੋ।',
  'apply.submit': 'ਮੇਰੀ ਅਰਜ਼ੀ ਭੇਜੋ',
  'apply.submitting': 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
  'apply.blocked': 'ਤੁਸੀਂ ਹਾਲੇ ਅਰਜ਼ੀ ਨਹੀਂ ਦੇ ਸਕਦੇ',
  'apply.needProfile': 'ਪਹਿਲਾਂ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ',
  'apply.needProfileHint': 'ਅਰਜ਼ੀ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਤੋਂ ਭੇਜੀ ਜਾਂਦੀ ਹੈ, ਇਸ ਲਈ ਅਰਜ਼ੀ ਤੋਂ ਪਹਿਲਾਂ ਉਹ ਚਾਹੀਦੀ ਹੈ। ਇਸ ਵਿੱਚ ਕੁਝ ਹੀ ਮਿੰਟ ਲੱਗਦੇ ਹਨ, ਅਤੇ ਤੁਸੀਂ ਪਹਿਲਾਂ ਜੋ ਦੱਸਿਆ ਹੈ ਉਹ ਭਰਿਆ ਹੋਇਆ ਮਿਲੇਗਾ।',
  'apply.elsewhereTitle': 'ਇਸ ਲਈ ਅਰਜ਼ੀ ਸਪਾਂਸਰ ਦੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ',
  'apply.elsewhereBody': 'ਅਸੀਂ ਇਹ ਵਜ਼ੀਫ਼ਾ ਇਸੇ ਲਈ ਸੂਚੀਬੱਧ ਕਰਦੇ ਹਾਂ ਤਾਂ ਜੋ ਤੁਸੀਂ ਇਸ ਨੂੰ ਲੱਭ ਸਕੋ, ਅਤੇ ਅਰਜ਼ੀਆਂ ਸਪਾਂਸਰ ਆਪ ਲੈਂਦੇ ਹਨ। ਤੁਸੀਂ ਸਾਨੂੰ ਜੋ ਦੱਸਿਆ ਹੈ ਉਹ ਸੰਭਾਲਿਆ ਰਹਿੰਦਾ ਹੈ, ਅਤੇ ਜੋ ਵਜ਼ੀਫ਼ੇ ਅਸੀਂ ਚਲਾਉਂਦੇ ਹਾਂ ਉਨ੍ਹਾਂ ਲਈ ਪਹਿਲਾਂ ਤੋਂ ਭਰਿਆ ਹੁੰਦਾ ਹੈ।',
  'apply.elsewhereBodyPartner': 'ਇਹ ਵਜ਼ੀਫ਼ਾ ਇੱਥੇ ਹੀ ਚੱਲਦਾ ਹੈ, ਪਰ ਸਪਾਂਸਰ ਅਰਜ਼ੀਆਂ ਆਪਣੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਲੈਂਦੇ ਹਨ। ਤੁਸੀਂ ਸਾਨੂੰ ਜੋ ਦੱਸਿਆ ਹੈ ਉਹ ਸੰਭਾਲਿਆ ਰਹਿੰਦਾ ਹੈ, ਅਤੇ ਜੋ ਅਰਜ਼ੀਆਂ ਸਾਨੂੰ ਸਿੱਧੀਆਂ ਮਿਲਦੀਆਂ ਹਨ ਉਨ੍ਹਾਂ ਲਈ ਪਹਿਲਾਂ ਤੋਂ ਭਰਿਆ ਹੁੰਦਾ ਹੈ।',
  'apply.bundleTitle': 'ਆਪਣੇ ਦਸਤਾਵੇਜ਼ ਨਾਲ ਲੈ ਜਾਓ',
  'apply.bundleBody': 'ਇਹ ਵਜ਼ੀਫ਼ਾ ਜੋ ਦਸਤਾਵੇਜ਼ ਮੰਗਦਾ ਹੈ ਉਨ੍ਹਾਂ ਨੂੰ ਅਸੀਂ ਇੱਕ ਫ਼ਾਈਲ ਵਿੱਚ ਪਾ ਸਕਦੇ ਹਾਂ, ਉਨ੍ਹਾਂ ਦੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਤਿਆਰ। ਜੋ ਉਹ ਚਾਹੁੰਦੇ ਹਨ ਅਤੇ ਸਾਡੇ ਕੋਲ ਹਾਲੇ ਨਹੀਂ, ਉਹ ਵੀ ਇਸ ਵਿੱਚ ਲਿਖਿਆ ਹੁੰਦਾ ਹੈ।',
  'apply.bundleAction': 'ਮੇਰੇ ਦਸਤਾਵੇਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ',
  'apply.bundleWorking': 'ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ…',
  'apply.bundleDone': 'ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼ ਡਾਊਨਲੋਡ ਹੋ ਗਏ ਹਨ।',
  'apply.docs': 'ਇਸ ਵਜ਼ੀਫ਼ੇ ਲਈ ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',

  'appl.title': 'ਤੁਹਾਡੀਆਂ ਅਰਜ਼ੀਆਂ',
  'appl.none': 'ਤੁਸੀਂ ਹਾਲੇ ਕਿਸੇ ਲਈ ਅਰਜ਼ੀ ਨਹੀਂ ਦਿੱਤੀ',
  'appl.noneHint': 'ਜਿਨ੍ਹਾਂ ਵਜ਼ੀਫ਼ਿਆਂ ਦੇ ਤੁਸੀਂ ਯੋਗ ਹੋ ਉਹ ਲੱਭਣ ਲਈ ਆਪਣੇ ਮੇਲ ਵੇਖੋ।',
  'appl.reference': 'ਹਵਾਲਾ',
  'appl.whatNext': 'ਅੱਗੇ ਕੀ ਹੋਵੇਗਾ',
  'appl.history': 'ਇਤਿਹਾਸ',
  'appl.needsYou': 'ਉਨ੍ਹਾਂ ਨੂੰ ਤੁਹਾਥੋਂ ਕੁਝ ਚਾਹੀਦਾ ਹੈ',
  'track.label': 'ਇਸ ਅਰਜ਼ੀ ਦੀ ਪ੍ਰਗਤੀ',
  'track.sent': 'ਭੇਜੀ ਗਈ',
  'track.review': 'ਸਮੀਖਿਆ',
  'track.decision': 'ਫ਼ੈਸਲਾ',
  'track.doneSr': 'ਪੂਰਾ',
  'track.currentSr': 'ਹੁਣ ਚੱਲ ਰਿਹਾ ਹੈ',
  'track.todoSr': 'ਸ਼ੁਰੂ ਨਹੀਂ ਹੋਇਆ',
  'appl.sentOn': '{when} ਭੇਜੀ ਗਈ',
  'appl.decidedOn': '{when} ਫ਼ੈਸਲਾ ਹੋਇਆ',
  'appl.outcomeApproved': 'ਮਿਲ ਗਿਆ',
  'appl.outcomeRejected': 'ਇਸ ਵਾਰ ਨਹੀਂ ਮਿਲਿਆ',
  'appl.outcomeWithdrawn': 'ਤੁਸੀਂ ਇਹ ਵਾਪਸ ਲੈ ਲਈ',
  'appl.inProgress': 'ਸੰਸਥਾ ਕੋਲ',
  'appl.outcome': 'ਨਤੀਜਾ',
  'appl.award': 'ਰਕਮ',
  'appl.applied': 'ਅਰਜ਼ੀ ਦਿੱਤੀ',
  'appl.decided': 'ਫ਼ੈਸਲਾ ਹੋਇਆ',
  'appl.automatic': 'ਆਪਣੇ ਆਪ',
  'appl.noHistory': 'ਹਾਲੇ ਕੁਝ ਨਹੀਂ ਹੋਇਆ।',

  'ref.heading': 'ਉਨ੍ਹਾਂ ਦੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਭੇਜੀ ਗਈ',
  'ref.blurb': 'ਇਨ੍ਹਾਂ ਲਈ ਅਰਜ਼ੀ ਸੰਸਥਾ ਦੀ ਆਪਣੀ ਸਾਈਟ ਉੱਤੇ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ, ਇਸ ਲਈ ਕੀ ਹੋਇਆ ਇਹ ਅਸੀਂ ਵੇਖ ਨਹੀਂ ਸਕਦੇ। ਸਾਨੂੰ ਦੱਸੋ ਅਤੇ ਅਸੀਂ ਇਸ ਨੂੰ ਬਾਕੀਆਂ ਨਾਲ ਰੱਖ ਲਵਾਂਗੇ।',
  'ref.sentOn': 'ਤੁਸੀਂ ਇਹ {when} ਖੋਲ੍ਹੀ ਸੀ',
  'ref.again': 'ਕੁੱਲ {times} ਵਾਰ',
  'ref.open': 'ਉਨ੍ਹਾਂ ਦੀ ਸਾਈਟ ਫਿਰ ਖੋਲ੍ਹੋ',
  'ref.what': 'ਕੀ ਹੋਇਆ?',
  'ref.APPLIED': 'ਮੈਂ ਅਰਜ਼ੀ ਦਿੱਤੀ',
  'ref.AWARDED': 'ਮੈਨੂੰ ਮਿਲ ਗਿਆ',
  'ref.NOT_AWARDED': 'ਮੈਨੂੰ ਨਹੀਂ ਮਿਲਿਆ',
  'ref.DID_NOT_APPLY': 'ਮੈਂ ਅਰਜ਼ੀ ਨਹੀਂ ਦਿੱਤੀ',
  'ref.saidAPPLIED': 'ਤੁਸੀਂ ਅਰਜ਼ੀ ਦਿੱਤੀ',
  'ref.saidAWARDED': 'ਤੁਹਾਨੂੰ ਮਿਲ ਗਿਆ',
  'ref.saidNOT_AWARDED': 'ਤੁਹਾਨੂੰ ਨਹੀਂ ਮਿਲਿਆ',
  'ref.saidDID_NOT_APPLY': 'ਤੁਸੀਂ ਅਰਜ਼ੀ ਨਹੀਂ ਦਿੱਤੀ',
  'ref.youSaid': 'ਤੁਸੀਂ ਸਾਨੂੰ ਦੱਸਿਆ: {what}',
  'ref.change': 'ਬਦਲੋ',

  'privacy.title': 'ਤੁਹਾਡਾ ਡਾਟਾ',
  'privacy.lede': 'ਸਾਡੇ ਕੋਲ ਕੀ ਹੈ, ਕਿਸ ਨੇ ਵੇਖਿਆ ਹੈ, ਅਤੇ ਇਸ ਨੂੰ ਵਾਪਸ ਕਿਵੇਂ ਲੈਣਾ ਹੈ।',
  'privacy.access': 'ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼ ਕਿਸ ਨੇ ਵੇਖੇ ਹਨ',
  'privacy.accessNone': 'ਤੁਹਾਡੇ ਆਪਣੇ ਖਾਤੇ ਤੋਂ ਬਾਹਰ ਕਿਸੇ ਨੇ ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ ਖੋਲ੍ਹੇ।',
  'privacy.consents': 'ਤੁਸੀਂ ਕੀ ਸਾਂਝਾ ਕਰਨ ਲਈ ਸਹਿਮਤੀ ਦਿੱਤੀ ਹੈ',
  'privacy.withdraw': 'ਵਾਪਸ ਲਓ',
  'privacy.withdrawing': 'ਵਾਪਸ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
  'privacy.export': 'ਸਾਡੇ ਕੋਲ ਜੋ ਕੁਝ ਹੈ ਉਹ ਸਭ ਡਾਊਨਲੋਡ ਕਰੋ',
  'privacy.exporting': 'ਤੁਹਾਡੀ ਨਕਲ ਤਿਆਰ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ…',
  'privacy.exportBody': 'ਤੁਹਾਡੇ ਡਾਟੇ ਦੀ ਪੂਰੀ, ਮਸ਼ੀਨ-ਪੜ੍ਹਨਯੋਗ ਨਕਲ।',
  'privacy.erase': 'ਮੇਰਾ ਡਾਟਾ ਮਿਟਾਓ',
  'privacy.erasing': 'ਬੇਨਤੀ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ…',
  'privacy.eraseBody': 'ਤੁਹਾਨੂੰ ਦਿੱਤੇ ਕਿਸੇ ਵੀ ਵਜ਼ੀਫ਼ੇ ਦਾ ਰਿਕਾਰਡ ਸਾਨੂੰ ਰੱਖਣਾ ਪੈਂਦਾ ਹੈ। ਬਾਕੀ ਸਭ ਹਟਾ ਦਿੱਤਾ ਜਾਂਦਾ ਹੈ।',
  'auth.closedTitle': 'ਤੁਹਾਡਾ ਖਾਤਾ ਇਸ ਵੇਲੇ ਬੰਦ ਹੈ।',
  'auth.closedHelp': 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ? ਸਾਡੀ ਸਹਾਇਤਾ ਟੀਮ ਤੁਹਾਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦੀ ਹੈ ',
  'auth.closedSoon': 'ਸਹਾਇਤਾ ਮੰਗੋ (ਜਲਦੀ)',
  'reg.district': 'ਜ਼ਿਲ੍ਹਾ',
  'reg.districtHint': 'ਤੁਹਾਡੇ ਇਲਾਕੇ ਵਿੱਚ ਚੱਲਦੀਆਂ ਸਕੀਮਾਂ ਨਾਲ ਮੇਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
  'privacy.requested': 'ਬੇਨਤੀ ਕੀਤੀ',
  'privacy.window': 'ਹਾਲੇ ਕੁਝ ਵੀ ਮਿਟਾਇਆ ਨਹੀਂ ਗਿਆ',
  'privacy.windowBody': 'ਤੁਹਾਡਾ ਡਾਟਾ {date} ਨੂੰ ਮਿਟਾ ਦਿੱਤਾ ਜਾਵੇਗਾ। ਉਦੋਂ ਤੱਕ ਤੁਸੀਂ ',
  'privacy.cancel': 'ਇਹ ਬੇਨਤੀ ਰੱਦ ਕਰੋ',
  'privacy.cancelling': 'ਰੱਦ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ…',
  'privacy.cancelled': 'ਤੁਹਾਡੀ ਬੇਨਤੀ ਰੱਦ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ। ਕੁਝ ਵੀ ਨਹੀਂ ਮਿਟਾਇਆ ਗਿਆ।',

  'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ',
  'common.retry': 'ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  'common.required': 'ਲਾਜ਼ਮੀ',
  'common.optional': 'ਮਰਜ਼ੀ ਨਾਲ',
  'common.error': 'ਕੁਝ ਗ਼ਲਤ ਹੋ ਗਿਆ',
  'common.offline': 'ਤੁਸੀਂ ਔਫ਼ਲਾਈਨ ਹੋ। ਤੁਹਾਡਾ ਕੰਮ ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਸੰਭਾਲਿਆ ਗਿਆ ਹੈ।',

  'slides.lead.was': '',
  'slides.lead.able': 'ਸਮਰੱਥਾ ਤੋਂ',
  'slides.lead.dist': 'ਵਿਸ਼ੇਸ਼ਤਾ ਤੱਕ',
  'slides.lead.body': 'ਹਰ ਉਹ ਵਜ਼ੀਫ਼ਾ ਜਿਸ ਦੇ ਤੁਸੀਂ ਯੋਗ ਹੋ — ਸਰਕਾਰੀ ਅਤੇ ਨਿੱਜੀ — ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਨਾਲ ਮੇਲ ਕਰਕੇ, ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ, ਇੱਕੋ ਥਾਂ।',
  'slides.lead.free': 'ਬਿਲਕੁਲ ਮੁਫ਼ਤ',
  'slides.lead.languages': '14 ਭਾਸ਼ਾਵਾਂ',
  'slides.lead.support': 'ਹਰ ਕਦਮ ਉੱਤੇ ਨਿੱਜੀ ਸਹਾਇਤਾ',
  'slides.label': 'ਐਲਾਨ',
  'slides.position': '{total} ਵਿੱਚੋਂ {n}',
  'slides.goto': '{name} ਵਿਖਾਓ',
  'slides.watch': 'ਵੀਡੀਓ ਵੇਖੋ',
  'slides.external': 'ਹੋਰ ਵੈੱਬਸਾਈਟ ਖੋਲ੍ਹਦਾ ਹੈ',

  'home.title': 'ਦਿਵਿਆਂਗ ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਵਜ਼ੀਫ਼ੇ, ਇੱਕੋ ਥਾਂ',
  'home.lede': 'ਆਪਣੇ ਬਾਰੇ ਇੱਕ ਵਾਰ ਦੱਸੋ। ਅਸੀਂ ਇੱਥੇ ਦੇ ਹਰ ਵਜ਼ੀਫ਼ੇ ਨਾਲ ਤੁਹਾਨੂੰ ਪਰਖਦੇ ਹਾਂ ਅਤੇ ਦੱਸਦੇ ਹਾਂ ਕਿ ਤੁਸੀਂ ਕਿਨ੍ਹਾਂ ਦੇ ਯੋਗ ਹੋ — ਅਤੇ ਬਾਕੀਆਂ ਲਈ ਠੀਕ-ਠੀਕ ਕੀ ਘਟਦਾ ਹੈ।',
  'home.search': 'ਵਜ਼ੀਫ਼ੇ ਲੱਭੋ',
  'home.searchPlaceholder': 'ਜਿਵੇਂ: ਇੰਜੀਨੀਅਰਿੰਗ, ਦਿੱਲੀ, ਪੋਸਟ-ਮੈਟ੍ਰਿਕ',
  'home.searchGo': 'ਲੱਭੋ',
  'home.browseAll': 'ਸਾਰੇ ਵਜ਼ੀਫ਼ੇ ਵੇਖੋ',
  'home.openNow': 'ਵਜ਼ੀਫ਼ੇ ਹੁਣ ਖੁੱਲ੍ਹੇ ਹਨ',
  'home.noAccount': 'ਵੇਖਣ ਲਈ ਖਾਤੇ ਦੀ ਲੋੜ ਨਹੀਂ।',
  'home.openNone': 'ਇੱਥੇ ਹਾਲੇ ਕੋਈ ਵਜ਼ੀਫ਼ਾ ਸੂਚੀਬੱਧ ਨਹੀਂ ਹੈ।',
  'home.openNoneBody': 'ਸੂਚੀ ਹੁਣ ਭਰੀ ਜਾ ਰਹੀ ਹੈ। ਇੱਥੇ ਕੁਝ ਵੀ ਖਾਤੇ ਪਿੱਛੇ ਨਹੀਂ — ਸਕੀਮਾਂ ਸੂਚੀਬੱਧ ਹੋਣ ਉੱਤੇ ਤੁਸੀਂ ਸਾਈਨ ਇਨ ਕੀਤੇ ਬਿਨਾਂ ਹੀ ਵੇਖ ਸਕੋਗੇ।',
  'home.how': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
  'home.howLede': 'ਰਜਿਸਟਰ ਕਰਨ ਲਈ ਇੱਕ ਮੋਬਾਈਲ ਨੰਬਰ ਅਤੇ ਉਸ ਉੱਤੇ ਭੇਜਿਆ ਕੋਡ ਚਾਹੀਦਾ ਹੈ। ਕੋਈ ਪਾਸਵਰਡ ਨਹੀਂ, ਅਤੇ ਪਹਿਲਾਂ ਭਰਨ ਵਾਲਾ ਕੋਈ ਸਾਈਨ-ਅੱਪ ਫ਼ਾਰਮ ਵੀ ਨਹੀਂ।',
  'home.step1': 'ਰਜਿਸਟਰ ਦਬਾਓ',
  'home.step1Body': 'ਇਸ ਪੰਨੇ ਦੇ ਉੱਤੇ। ਜੇ ਪਹਿਲਾਂ ਆ ਚੁੱਕੇ ਹੋ ਤਾਂ ਨਾਲ ਵਾਲਾ ਲੌਗਇਨ ਵਰਤੋ — ਦੋਹਾਂ ਵਿੱਚ ਉਹੀ ਨੰਬਰ ਕੰਮ ਕਰਦਾ ਹੈ।',
  'home.step2': 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ',
  'home.step2Body': 'ਦਸ ਅੰਕ, +91 ਪਹਿਲਾਂ ਤੋਂ ਭਰਿਆ ਹੋਇਆ। ਉਸ ਨੰਬਰ ਉੱਤੇ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਜਾਂਦਾ ਹੈ।',
  'home.step3': 'ਕੋਡ ਭਰੋ',
  'home.step3Body': 'ਛੇ ਅੰਕ ਲਿਖੋ ਅਤੇ ਤੁਸੀਂ ਅੰਦਰ। ਜੇ ਕੋਈ ਸੁਨੇਹਾ ਨਾ ਆਵੇ ਤਾਂ ਕੋਡ ਵਟਸਐਪ ਉੱਤੇ ਮੰਗੋ, ਜਾਂ ਸਾਨੂੰ ਫ਼ੋਨ ਕਰਕੇ ਪੜ੍ਹ ਕੇ ਸੁਣਾਉਣ ਲਈ ਕਹੋ।',
  'home.step4': 'ਆਪਣੇ ਵੇਰਵੇ ਭਰੋ',
  'home.step4Body': 'ਤੁਹਾਡਾ ਨਾਂ, ਤੁਹਾਡਾ ਸਰਟੀਫਿਕੇਟ ਅਤੇ ਤੁਸੀਂ ਕਿੱਥੇ ਪੜ੍ਹਦੇ ਹੋ — ਇੱਕ ਵਾਰ ਵਿੱਚ ਇੱਕ ਸਵਾਲ, ਅਤੇ ਹਰ ਜਵਾਬ ਦਿੰਦੇ ਸਾਰ ਸੰਭਾਲ ਲਿਆ ਜਾਂਦਾ ਹੈ।',
  'home.step5': 'ਆਪਣੇ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
  'home.step5Body': 'ਦਿਵਿਆਂਗਤਾ ਸਰਟੀਫਿਕੇਟ, UDID ਕਾਰਡ, ਆਮਦਨ ਸਰਟੀਫਿਕੇਟ ਅਤੇ ਬਾਕੀ। ਹਰ ਇੱਕ ਸਿਰਫ਼ ਇੱਕ ਵਾਰ, ਹਰ ਵਜ਼ੀਫ਼ੇ ਲਈ ਵੱਖਰਾ ਨਹੀਂ।',
  'home.step6': 'ਆਪਣੇ ਮੇਲ ਵੇਖੋ',
  'home.step6Body': 'ਮੇਰੇ ਮੇਲ ਉਹ ਵਜ਼ੀਫ਼ੇ ਵਿਖਾਉਂਦਾ ਹੈ ਜਿਨ੍ਹਾਂ ਦੇ ਤੁਸੀਂ ਯੋਗ ਹੋ — ਅਤੇ ਜਿੱਥੇ ਕੋਈ ਤੁਹਾਡੇ ਲਈ ਬੰਦ ਹੈ, ਉੱਥੇ ਕਾਰਨ ਦੱਸਦਾ ਹੈ।',
  'home.step7': 'ਅਰਜ਼ੀ ਦਿਓ',
  'home.step7Body': 'ਜੋ ਚਾਹੁੰਦੇ ਹੋ ਉਹ ਚੁਣੋ। ਤੁਹਾਡੇ ਵੇਰਵੇ ਅਤੇ ਦਸਤਾਵੇਜ਼ ਅਰਜ਼ੀ ਨਾਲ ਜਾਂਦੇ ਹਨ।',
  'home.assure': 'ਜਾਣਨ ਯੋਗ',
  'home.assure1': 'ਯਾਦ ਰੱਖਣ ਲਈ ਕੋਈ ਪਾਸਵਰਡ ਨਹੀਂ',
  'home.assure2': 'ਵੱਖਰਾ ਕੋਈ ਰਜਿਸਟਰੇਸ਼ਨ ਫ਼ਾਰਮ ਨਹੀਂ',
  'home.assure3': 'ਤੁਸੀਂ ਰੁਕ ਕੇ ਬਾਅਦ ਵਿੱਚ ਪੂਰਾ ਕਰ ਸਕਦੇ ਹੋ',
  'home.help': 'ਕਿਸੇ ਕਦਮ ਉੱਤੇ ਅਟਕ ਗਏ?',
  'home.helpBody': 'ਫ਼ੋਨ ਕਰੋ, ਕੋਈ ਤੁਹਾਨੂੰ ਪਾਰ ਲੰਘਾ ਦੇਵੇਗਾ।',
  'home.helpCall': '{number} ਉੱਤੇ ਫ਼ੋਨ ਕਰੋ',
  'home.closing': 'ਜਲਦੀ ਬੰਦ',
  'home.closingLede': 'ਪਹਿਲਾਂ ਇਨ੍ਹਾਂ ਲਈ ਅਰਜ਼ੀ ਦਿਓ।',
  'home.closingNext': 'ਅਗਲੀਆਂ ਆਖ਼ਰੀ ਤਾਰੀਖ਼ਾਂ',
  'home.closingNextLede': 'ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਬੰਦ ਹੋਣ ਵਾਲੇ ਤਿੰਨ।',
  'home.allDeadlines': 'ਸਾਰੇ ਵਜ਼ੀਫ਼ੇ ਵੇਖੋ',
  'home.browse': 'ਇਸ ਮੁਤਾਬਕ ਵੇਖੋ',
  'home.browseWho': 'ਕੌਣ ਦੇ ਰਿਹਾ ਹੈ',
  'home.browseLevel': 'ਤੁਹਾਡਾ ਪੜ੍ਹਾਈ ਦਾ ਪੱਧਰ',
  'home.cta': 'ਆਪਣੇ ਮੇਲ ਵੇਖਣ ਲਈ ਤਿਆਰ ਹੋ?',
  'home.ctaBody': 'ਖਾਤਾ ਬਣਾਉਣ ਲਈ ਇੱਕ ਮੋਬਾਈਲ ਨੰਬਰ ਜਾਂ ਈਮੇਲ ਪਤਾ ਚਾਹੀਦਾ ਹੈ। ਹੋਰ ਕੁਝ ਨਹੀਂ।',
  'home.ctaButton': 'ਖਾਤਾ ਬਣਾਓ',
  'home.signedInCta': 'ਵੇਖੋ ਤੁਸੀਂ ਕਿਸ ਦੇ ਯੋਗ ਹੋ',

  'reg.title': 'ਵਜ਼ੀਫ਼ੇ ਲੱਭਣ ਲਈ ਰਜਿਸਟਰ ਕਰੋ',
  'reg.editTitle': 'ਆਪਣੇ ਵੇਰਵੇ ਅੱਪਡੇਟ ਕਰੋ',
  'reg.requiredNote': '* ਵਾਲੇ ਸਾਰੇ ਖਾਨੇ ਲਾਜ਼ਮੀ ਹਨ।',
  'reg.personal': 'ਨਿੱਜੀ ਵੇਰਵੇ',
  'reg.disability': 'ਦਿਵਿਆਂਗਤਾ ਦੇ ਵੇਰਵੇ',
  'reg.education': 'ਪੜ੍ਹਾਈ ਦੇ ਵੇਰਵੇ',
  'reg.name': 'ਪੂਰਾ ਨਾਂ',
  'reg.namePlaceholder': 'ਆਪਣਾ ਪੂਰਾ ਨਾਂ ਭਰੋ',
  'reg.phoneHint': 'ਅਸੀਂ ਇਸ ਨੰਬਰ ਉੱਤੇ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਭੇਜਦੇ ਹਾਂ। ਹਰ ਵਾਰ ਇਹੀ ਨੰਬਰ ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਕਰਾਉਂਦਾ ਹੈ।',
  'reg.sendOtp': 'OTP ਭੇਜੋ',
  'reg.otpPlaceholder': '6 ਅੰਕਾਂ ਦਾ OTP ਭਰੋ',
  'reg.verified': 'ਫ਼ੋਨ ਨੰਬਰ ਤਸਦੀਕਸ਼ੁਦਾ',
  'reg.verifyFirst': 'ਰਜਿਸਟਰੇਸ਼ਨ ਪੂਰੀ ਕਰਨ ਲਈ ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਤਸਦੀਕ ਕਰੋ।',
  'reg.email': 'ਈਮੇਲ',
  'reg.emailHint': 'ਤਾਂ ਜੋ ਅਸੀਂ ਆਖ਼ਰੀ ਤਾਰੀਖ਼ ਯਾਦ ਕਰਵਾ ਸਕੀਏ। ਅਸੀਂ ਇਹ ਕਦੇ ਸਾਂਝਾ ਨਹੀਂ ਕਰਦੇ।',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'ਲਿੰਗ',
  'reg.genderHint': '(ਕੁਝ ਵਜ਼ੀਫ਼ੇ ਸਿਰਫ਼ ਔਰਤਾਂ ਜਾਂ ਟਰਾਂਸਜੈਂਡਰ ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਹਨ)',
  'reg.udid': 'UDID ਨੰਬਰ',
  'reg.udidHint': 'ਤੁਹਾਡੇ UDID (ਵਿਲੱਖਣ ਦਿਵਿਆਂਗਤਾ ਪਛਾਣ) ਕਾਰਡ ਉੱਤੇ ਲਿਖਿਆ ਨੰਬਰ।',
  'reg.udidPlaceholder': 'ਆਪਣਾ UDID ਨੰਬਰ ਭਰੋ',
  'reg.certificate': 'UDID ਸਰਟੀਫਿਕੇਟ ਅੱਪਲੋਡ ਕਰੋ',
  'reg.certificateHint': 'PDF ਜਾਂ ਤਸਵੀਰ, 5 MB ਜਾਂ ਘੱਟ।',
  'reg.fileType': 'ਉਹ ਫ਼ਾਈਲ PDF, JPEG ਜਾਂ PNG ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
  'reg.fileSize': 'ਉਹ ਫ਼ਾਈਲ 5 MB ਤੋਂ ਵੱਡੀ ਹੈ। ਫ਼ੋਨ ਨਾਲ ਲਈ ਤਸਵੀਰ ਆਮ ਤੌਰ ਉੱਤੇ ਛੋਟੀ ਹੁੰਦੀ ਹੈ ਜੇ ਤੁਸੀਂ ਫ਼ੋਟੋ ਖਿੱਚਣ ਦੀ ਬਜਾਏ ਸਕੈਨ ਕਰੋ।',
  'reg.fileLater': 'ਤੁਹਾਡੀ ਰਜਿਸਟਰੇਸ਼ਨ ਹੋ ਗਈ ਹੈ ਅਤੇ ਵੇਰਵੇ ਸੰਭਾਲ ਲਏ ਗਏ ਹਨ। ਸਰਟੀਫਿਕੇਟ ਅੱਪਲੋਡ ਨਹੀਂ ਹੋਇਆ — ਉਸ ਨੂੰ ਮੇਰੇ ਦਸਤਾਵੇਜ਼ ਤੋਂ ਜੋੜ ਦਿਓ, ਬਾਕੀ ਕੁਝ ਦੁਬਾਰਾ ਨਹੀਂ ਕਰਨਾ।',
  'reg.disabilityType': 'ਦਿਵਿਆਂਗਤਾ ਦੀ ਕਿਸਮ',
  'reg.percent': 'ਦਿਵਿਆਂਗਤਾ ਦੀ ਫ਼ੀਸਦੀ',
  'reg.percentHint': 'ਤੁਹਾਡੇ ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਲਿਖਿਆ ਅੰਕੜਾ। ਕਈ ਵਜ਼ੀਫ਼ਿਆਂ ਲਈ 40% ਜਾਂ ਵੱਧ ਚਾਹੀਦਾ ਹੈ।',
  'reg.percentPlaceholder': 'ਜਿਵੇਂ 40',
  'reg.percentRange': 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਫ਼ੀਸਦੀ 0 ਅਤੇ 100 ਵਿਚਕਾਰ ਪੂਰਨ ਅੰਕ ਹੁੰਦੀ ਹੈ।',
  'reg.state': 'ਰਾਜ',
  'reg.statePlaceholder': 'ਆਪਣਾ ਰਾਜ ਲੱਭਣ ਲਈ ਲਿਖੋ…',
  'reg.program': 'ਆਪਣਾ ਕੋਰਸ ਚੁਣੋ',
  'reg.graduation': 'ਗ੍ਰੈਜੂਏਸ਼ਨ',
  'reg.postgraduation': 'ਪੋਸਟ-ਗ੍ਰੈਜੂਏਸ਼ਨ / ਮਾਸਟਰਜ਼',
  'reg.year': 'ਸਾਲ ਚੁਣੋ',
  'reg.yearAfterProgram': 'ਪਹਿਲਾਂ ਆਪਣਾ ਕੋਰਸ ਚੁਣੋ',
  'reg.institution': 'ਸਕੂਲ / ਕਾਲਜ ਦਾ ਨਾਂ',
  'reg.institutionPlaceholder': 'ਆਪਣੀ ਸੰਸਥਾ ਦਾ ਨਾਂ ਭਰੋ',
  'reg.required': 'ਇਹ ਜ਼ਰੂਰੀ ਹੈ।',
  'reg.fix': 'ਕੁਝ ਜਵਾਬਾਂ ਵੱਲ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ। ਪਹਿਲਾ ਹੇਠਾਂ ਚੁਣਿਆ ਹੋਇਆ ਹੈ।',
  'reg.cta': 'ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਵਜ਼ੀਫ਼ੇ ਲੱਭੋ',
  'reg.saveChanges': 'ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ',
  'reg.saving': 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
  'reg.done': 'ਰਜਿਸਟਰੇਸ਼ਨ ਹੋ ਗਈ। ਤੁਹਾਡੇ ਵਜ਼ੀਫ਼ੇ ਲੱਭ ਰਹੇ ਹਾਂ।',
  'reg.doneTitle': 'ਤੁਹਾਡੀ ਰਜਿਸਟਰੇਸ਼ਨ ਹੋ ਗਈ ਹੈ',
  'reg.already': 'ਪਹਿਲਾਂ ਤੋਂ ਰਜਿਸਟਰ ਹੋ?',
  'reg.login': 'OTP ਨਾਲ ਲੌਗਇਨ',
  'nav.registerCta': 'ਰਜਿਸਟਰ',
  'nav.loginCta': 'ਲੌਗਇਨ',
  'profile.edit': 'ਆਪਣੇ ਵੇਰਵੇ ਅੱਪਡੇਟ ਕਰੋ',
  'field.disability.BLINDNESS': 'ਅੰਨ੍ਹਾਪਣ',
  'field.disability.LOW_VISION': 'ਘੱਟ ਨਜ਼ਰ',
  'field.disability.LEPROSY_CURED': 'ਕੋੜ੍ਹ (ਠੀਕ ਹੋਇਆ)',
  'field.disability.HEARING_IMPAIRMENT': 'ਸੁਣਨ ਦੀ ਕਮਜ਼ੋਰੀ',
  'field.disability.LOCOMOTOR_DISABILITY': 'ਚਲਣ-ਫਿਰਨ ਦੀ ਦਿਵਿਆਂਗਤਾ',
  'field.disability.DWARFISM': 'ਬੌਣਾਪਣ',
  'field.disability.INTELLECTUAL_DISABILITY': 'ਬੌਧਿਕ ਦਿਵਿਆਂਗਤਾ',
  'field.disability.MENTAL_ILLNESS': 'ਮਾਨਸਿਕ ਬਿਮਾਰੀ',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ਔਟਿਜ਼ਮ ਸਪੈਕਟ੍ਰਮ ਡਿਸਆਰਡਰ',
  'field.disability.CEREBRAL_PALSY': 'ਸੈਰੇਬ੍ਰਲ ਪਾਲਸੀ',
  'field.disability.MUSCULAR_DYSTROPHY': 'ਮਾਸਪੇਸ਼ੀ ਖੋਰਾ',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'ਲੰਮੇ ਸਮੇਂ ਦੀ ਨਾੜੀ ਸੰਬੰਧੀ ਹਾਲਤ',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'ਖ਼ਾਸ ਸਿੱਖਣ ਦੀ ਦਿਵਿਆਂਗਤਾ',
  'field.disability.MULTIPLE_SCLEROSIS': 'ਮਲਟੀਪਲ ਸਕਲੈਰੋਸਿਸ',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'ਬੋਲੀ ਅਤੇ ਭਾਸ਼ਾ ਦੀ ਦਿਵਿਆਂਗਤਾ',
  'field.disability.THALASSEMIA': 'ਥੈਲੇਸੀਮੀਆ',
  'field.disability.HAEMOPHILIA': 'ਹੀਮੋਫ਼ੀਲੀਆ',
  'field.disability.SICKLE_CELL_DISEASE': 'ਸਿਕਲ ਸੈੱਲ ਰੋਗ',
  'field.disability.MULTIPLE_DISABILITIES': 'ਬਹੁ-ਦਿਵਿਆਂਗਤਾ, ਸੁਣਨ-ਵੇਖਣ ਦੀ ਕਮੀ ਸਮੇਤ',
  'field.disability.ACID_ATTACK_VICTIM': 'ਤੇਜ਼ਾਬੀ ਹਮਲੇ ਤੋਂ ਬਚਿਆ ਵਿਅਕਤੀ',
  'field.disability.PARKINSONS_DISEASE': 'ਪਾਰਕਿੰਸਨ ਰੋਗ',

  'field.state.AN': 'ਅੰਡੇਮਾਨ ਅਤੇ ਨਿਕੋਬਾਰ ਟਾਪੂ',
  'field.state.AP': 'ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼',
  'field.state.AR': 'ਅਰੁਣਾਚਲ ਪ੍ਰਦੇਸ਼',
  'field.state.AS': 'ਅਸਾਮ',
  'field.state.BR': 'ਬਿਹਾਰ',
  'field.state.CH': 'ਚੰਡੀਗੜ੍ਹ',
  'field.state.CT': 'ਛੱਤੀਸਗੜ੍ਹ',
  'field.state.DL': 'ਦਿੱਲੀ',
  'field.state.DN': 'ਦਾਦਰਾ ਅਤੇ ਨਗਰ ਹਵੇਲੀ ਅਤੇ ਦਮਨ ਅਤੇ ਦੀਵ',
  'field.state.GA': 'ਗੋਆ',
  'field.state.GJ': 'ਗੁਜਰਾਤ',
  'field.state.HP': 'ਹਿਮਾਚਲ ਪ੍ਰਦੇਸ਼',
  'field.state.HR': 'ਹਰਿਆਣਾ',
  'field.state.JH': 'ਝਾਰਖੰਡ',
  'field.state.JK': 'ਜੰਮੂ ਅਤੇ ਕਸ਼ਮੀਰ',
  'field.state.KA': 'ਕਰਨਾਟਕ',
  'field.state.KL': 'ਕੇਰਲ',
  'field.state.LA': 'ਲੱਦਾਖ',
  'field.state.LD': 'ਲਕਸ਼ਦੀਪ',
  'field.state.MH': 'ਮਹਾਰਾਸ਼ਟਰ',
  'field.state.ML': 'ਮੇਘਾਲਿਆ',
  'field.state.MN': 'ਮਣੀਪੁਰ',
  'field.state.MP': 'ਮੱਧ ਪ੍ਰਦੇਸ਼',
  'field.state.MZ': 'ਮਿਜ਼ੋਰਮ',
  'field.state.NL': 'ਨਾਗਾਲੈਂਡ',
  'field.state.OR': 'ਓਡੀਸ਼ਾ',
  'field.state.PB': 'ਪੰਜਾਬ',
  'field.state.PY': 'ਪੁਡੂਚੇਰੀ',
  'field.state.RJ': 'ਰਾਜਸਥਾਨ',
  'field.state.SK': 'ਸਿੱਕਮ',
  'field.state.TG': 'ਤੇਲੰਗਾਨਾ',
  'field.state.TN': 'ਤਾਮਿਲਨਾਡੂ',
  'field.state.TR': 'ਤ੍ਰਿਪੁਰਾ',
  'field.state.UP': 'ਉੱਤਰ ਪ੍ਰਦੇਸ਼',
  'field.state.UT': 'ਉੱਤਰਾਖੰਡ',
  'field.state.WB': 'ਪੱਛਮੀ ਬੰਗਾਲ',

  'field.level.SCHOOL': 'ਸਕੂਲ',
  'field.level.SCHOOL.sub': 'ਜਮਾਤ 9, 10, 11, 12',
  'field.level.UNDERGRADUATE': 'ਗ੍ਰੈਜੂਏਸ਼ਨ',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech ਅਤੇ ਅਜਿਹੇ',
  'field.level.POSTGRADUATE': 'ਪੋਸਟ-ਗ੍ਰੈਜੂਏਸ਼ਨ',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech ਅਤੇ ਅਜਿਹੇ',
  'field.level.DOCTORAL': 'ਡਾਕਟਰੇਟ',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'ਸਕੂਲ',
  'field.qual.SCHOOL.sub': 'ਜਮਾਤ 1 ਤੋਂ 12',
  'field.qual.UNDERGRADUATE': 'ਗ੍ਰੈਜੂਏਸ਼ਨ',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — ਅਤੇ ਡਿਪਲੋਮਾ ਜਾਂ ITI',
  'field.qual.POSTGRADUATE': 'ਪੋਸਟ-ਗ੍ਰੈਜੂਏਸ਼ਨ',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA ਅਤੇ ਅਜਿਹੇ',
  'field.qual.DOCTORAL': 'PhD / ਡਾਕਟਰੇਟ',

  'field.subject.engineering': 'ਇੰਜੀਨੀਅਰਿੰਗ',
  'field.subject.medical': 'ਮੈਡੀਕਲ',
  'field.subject.management': 'ਪ੍ਰਬੰਧਨ',
  'field.subject.science': 'ਵਿਗਿਆਨ',
  'field.subject.commerce': 'ਵਣਜ',
  'field.subject.arts': 'ਕਲਾ ਅਤੇ ਮਾਨਵਿਕੀ',
  'field.subject.vocational': 'ਕਿੱਤਾਮੁਖੀ',
  'field.subject.fellowship': 'ਫ਼ੈਲੋਸ਼ਿਪ',
  'field.subject.talent': 'ਪ੍ਰਤਿਭਾ',
  'field.subject.sports': 'ਖੇਡਾਂ',

  'field.gender.FEMALE': 'ਔਰਤ',
  'field.gender.MALE': 'ਮਰਦ',
  'field.gender.TRANSGENDER': 'ਟਰਾਂਸਜੈਂਡਰ',
  'field.gender.UNDISCLOSED': 'ਦੱਸਣਾ ਨਹੀਂ ਚਾਹੁੰਦੇ',
  'field.genderFilter.TRANSGENDER': 'ਤੀਜਾ ਲਿੰਗ / ਟਰਾਂਸਜੈਂਡਰ',

  'field.year.below9': 'ਜਮਾਤ 9 ਤੋਂ ਹੇਠਾਂ',
  'field.year.c9': 'ਜਮਾਤ 9',
  'field.year.c10': 'ਜਮਾਤ 10',
  'field.year.c11': 'ਜਮਾਤ 11',
  'field.year.c12': 'ਜਮਾਤ 12',
  'field.year.y1': 'ਪਹਿਲਾ ਸਾਲ',
  'field.year.y2': 'ਦੂਜਾ ਸਾਲ',
  'field.year.y3': 'ਤੀਜਾ ਸਾਲ',
  'field.year.y4': 'ਚੌਥਾ ਸਾਲ',
  'field.year.pg1': 'ਪੋਸਟ-ਗ੍ਰੈਜੂਏਟ ਸਾਲ 1',
  'field.year.pg2': 'ਪੋਸਟ-ਗ੍ਰੈਜੂਏਟ ਸਾਲ 2',

  'q.full_name': 'ਤੁਹਾਡਾ ਨਾਂ ਕੀ ਹੈ?',
  'q.full_name.help': 'ਬਿਲਕੁਲ ਜਿਵੇਂ ਤੁਹਾਡੇ ਦਿਵਿਆਂਗਤਾ ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਲਿਖਿਆ ਹੈ। ਦੇਣ ਵਾਲੀਆਂ ਸੰਸਥਾਵਾਂ ਦੋਵੇਂ ਮਿਲਾ ਕੇ ਵੇਖਦੀਆਂ ਹਨ।',
  'q.gender': 'ਤੁਹਾਡਾ ਲਿੰਗ ਕੀ ਹੈ?',
  'q.gender.help': 'ਕੁਝ ਵਜ਼ੀਫ਼ੇ ਸਿਰਫ਼ ਔਰਤਾਂ ਲਈ ਹਨ, ਜਾਂ ਟਰਾਂਸਜੈਂਡਰ ਵਿਦਿਆਰਥੀਆਂ ਲਈ। ਦੱਸਣਾ ਨਾ ਚਾਹੋ ਤਾਂ ਛੱਡ ਦਿਓ।',
  'q.disability_type': 'ਤੁਹਾਡੀ ਦਿਵਿਆਂਗਤਾ ਕੀ ਹੈ?',
  'q.disability_type.help': 'ਜਿਵੇਂ ਤੁਹਾਡੇ ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਲਿਖਿਆ ਹੈ। ਬਹੁਤੇ ਵਜ਼ੀਫ਼ੇ ਇਸੇ ਉੱਤੇ ਛਾਂਟੀ ਕਰਦੇ ਹਨ।',
  'q.disability_percent': 'ਤੁਹਾਡੇ ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਕਿੰਨੀ ਫ਼ੀਸਦੀ ਹੈ?',
  'q.disability_percent.help': '0 ਅਤੇ 100 ਵਿਚਕਾਰ ਇੱਕ ਅੰਕ। ਕਈ ਵਜ਼ੀਫ਼ਿਆਂ ਲਈ 40% ਜਾਂ ਵੱਧ ਚਾਹੀਦਾ ਹੈ।',
  'q.disability_percent.range': 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਫ਼ੀਸਦੀ 0 ਅਤੇ 100 ਵਿਚਕਾਰ ਹੁੰਦੀ ਹੈ।',
  'q.udid_number': 'ਤੁਹਾਡਾ UDID ਨੰਬਰ ਕੀ ਹੈ?',
  'q.udid_number.help': 'ਤੁਹਾਡੇ UDID (ਵਿਲੱਖਣ ਦਿਵਿਆਂਗਤਾ ਪਛਾਣ) ਕਾਰਡ ਉੱਤੇ ਲਿਖਿਆ ਨੰਬਰ। ਜੇ ਹਾਲੇ ਨਹੀਂ ਮਿਲਿਆ ਤਾਂ ਛੱਡ ਦਿਓ — ਇਸ ਨਾਲ ਤੁਸੀਂ ਕਿਸ ਦੇ ਯੋਗ ਹੋ ਉਸ ਵਿੱਚ ਕੋਈ ਫ਼ਰਕ ਨਹੀਂ ਪੈਂਦਾ, ਅਤੇ ਬਾਅਦ ਵਿੱਚ ਜੋੜ ਸਕਦੇ ਹੋ।',
  'q.date_of_birth': 'ਤੁਹਾਡਾ ਜਨਮ ਕਦੋਂ ਹੋਇਆ?',
  'q.date_of_birth.help': 'ਕੁਝ ਵਜ਼ੀਫ਼ਿਆਂ ਵਿੱਚ ਉਮਰ ਦੀ ਹੱਦ ਹੁੰਦੀ ਹੈ।',
  'q.course_name': 'ਤੁਸੀਂ ਕੀ ਪੜ੍ਹ ਰਹੇ ਹੋ?',
  'q.course_name.help': 'ਰਜਿਸਟਰ ਕਰਨ ਵੇਲੇ ਤੁਸੀਂ ਜੋ ਕੋਰਸ ਚੁਣਿਆ ਸੀ।',
  'q.institution_name': 'ਤੁਸੀਂ ਕਿੱਥੇ ਪੜ੍ਹਦੇ ਹੋ?',
  'q.institution_name.help': 'ਤੁਹਾਡੇ ਸਕੂਲ, ਕਾਲਜ ਜਾਂ ਯੂਨੀਵਰਸਿਟੀ ਦਾ ਨਾਂ, ਜਿਵੇਂ ਤੁਹਾਡੇ ਬੋਨਾਫ਼ਾਈਡ ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਲਿਖਿਆ ਹੈ। ਜੇ ਹਾਲੇ ਸ਼ੁਰੂ ਨਹੀਂ ਕੀਤਾ ਤਾਂ ਛੱਡ ਦਿਓ।',
  'q.institution_name.placeholder': 'ਤੁਹਾਡੇ ਸਕੂਲ ਜਾਂ ਕਾਲਜ ਦਾ ਨਾਂ',
  'q.state_code': 'ਤੁਸੀਂ ਕਿਸ ਰਾਜ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?',
  'q.state_code.help': 'ਕਈ ਵਜ਼ੀਫ਼ੇ ਸਿਰਫ਼ ਕੁਝ ਰਾਜਾਂ ਦੇ ਵਸਨੀਕਾਂ ਲਈ ਖੁੱਲ੍ਹੇ ਹਨ।',
  'q.annual_family_income': 'ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਦੀ ਸਾਲਾਨਾ ਆਮਦਨ ਕਿੰਨੀ ਹੈ?',
  'q.annual_family_income.help': 'ਰੁਪਇਆਂ ਵਿੱਚ, ਜਿਵੇਂ ਤੁਹਾਡੇ ਆਮਦਨ ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਹੈ। ਬਹੁਤੇ ਵਜ਼ੀਫ਼ਿਆਂ ਵਿੱਚ ਇੱਕ ਹੱਦ ਹੁੰਦੀ ਹੈ।',
  'q.annual_family_income.range': 'ਆਮਦਨ ਸਿਫ਼ਰ ਤੋਂ ਘੱਟ ਨਹੀਂ ਹੋ ਸਕਦੀ।',
  'q.academic_percentage': 'ਤੁਹਾਡੀ ਪਿਛਲੀ ਪ੍ਰੀਖਿਆ ਦੇ ਅੰਕ ਕੀ ਸਨ?',
  'q.academic_percentage.help': 'ਤੁਹਾਡੀ ਅੰਕ-ਸੂਚੀ ਜਿਸ ਤਰ੍ਹਾਂ ਉਹ ਦੱਸਦੀ ਹੈ ਉਹ ਚੁਣੋ, ਫਿਰ ਅੰਕ ਲਿਖੋ। ਕਈ ਵਜ਼ੀਫ਼ੇ ਘੱਟੋ-ਘੱਟ ਅੰਕ ਮੰਗਦੇ ਹਨ।',
  'field.orgKind.NGO': 'ਐਨਜੀਓ',
  'field.orgKind.CORPORATE': 'ਕਾਰਪੋਰੇਟ',
  'field.orgKind.GOVERNMENT': 'ਸਰਕਾਰੀ',
  'field.orgKind.PRIVATE': 'ਨਿੱਜੀ',

  'field.doc.DISABILITY_CERTIFICATE': 'ਦਿਵਿਆਂਗਤਾ ਸਰਟੀਫਿਕੇਟ',
  'field.doc.UDID_CARD': 'UDID ਕਾਰਡ',
  'field.doc.INCOME_CERTIFICATE': 'ਆਮਦਨ ਸਰਟੀਫਿਕੇਟ',
  'field.doc.DOMICILE_CERTIFICATE': 'ਰਿਹਾਇਸ਼ ਸਰਟੀਫਿਕੇਟ',
  'field.doc.CASTE_CERTIFICATE': 'ਜਾਤੀ ਸਰਟੀਫਿਕੇਟ',
  'field.doc.MARKSHEET': 'ਅੰਕ-ਸੂਚੀ',
  'field.doc.ADMISSION_LETTER': 'ਦਾਖ਼ਲਾ ਪੱਤਰ',
  'field.doc.BONAFIDE_CERTIFICATE': 'ਬੋਨਾਫ਼ਾਈਡ ਸਰਟੀਫਿਕੇਟ',
  'field.doc.FEE_RECEIPT': 'ਫ਼ੀਸ ਦੀ ਰਸੀਦ',
  'field.doc.BANK_PASSBOOK': 'ਬੈਂਕ ਪਾਸਬੁੱਕ',
  'field.doc.IDENTITY_PROOF': 'ਪਛਾਣ ਦਾ ਸਬੂਤ',
  'field.doc.PHOTOGRAPH': 'ਫ਼ੋਟੋ',

  'appl.next.SUBMITTED': 'ਦੇਣ ਵਾਲੀ ਸੰਸਥਾ ਕੋਲ ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਹੈ। ਅੱਗੇ ਇੱਕ ਸਮੀਖਿਅਕ ਇਸਨੂੰ ਪੜ੍ਹੇਗਾ।',
  'appl.next.UNDER_REVIEW': 'ਇੱਕ ਸਮੀਖਿਅਕ ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਪੜ੍ਹ ਰਿਹਾ ਹੈ। ਆਮ ਤੌਰ ਉੱਤੇ ਇਹੀ ਸਭ ਤੋਂ ਲੰਮਾ ਕਦਮ ਹੁੰਦਾ ਹੈ।',
  'appl.next.INFO_REQUESTED': 'ਉਨ੍ਹਾਂ ਨੇ ਤੁਹਾਥੋਂ ਕੁਝ ਮੰਗਿਆ ਹੈ। ਜਦ ਤੱਕ ਤੁਸੀਂ ਜਵਾਬ ਨਹੀਂ ਦਿੰਦੇ, ਅਰਜ਼ੀ ਉਡੀਕਦੀ ਰਹੇਗੀ।',
  'appl.next.DOCUMENT_CHECK': 'ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਸਮੀਖਿਅਕ ਕੋਲ ਹੈ। ਤੁਹਾਥੋਂ ਕੁਝ ਨਹੀਂ ਚਾਹੀਦਾ।',
  'appl.next.VERIFIED': 'ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਸਮੀਖਿਅਕ ਕੋਲ ਹੈ। ਤੁਹਾਥੋਂ ਕੁਝ ਨਹੀਂ ਚਾਹੀਦਾ।',
  'appl.next.SHORTLISTED': 'ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਸਮੀਖਿਅਕ ਕੋਲ ਹੈ। ਅੱਗੇ ਫ਼ੈਸਲਾ ਆਵੇਗਾ।',
  'appl.next.APPROVED': 'ਮਨਜ਼ੂਰ। ਦੇਣ ਵਾਲੀ ਸੰਸਥਾ ਮਨਜ਼ੂਰੀ ਦਰਜ ਕਰੇਗੀ, ਫਿਰ ਅਦਾਇਗੀ ਦਾ ਪ੍ਰਬੰਧ ਕਰੇਗੀ।',
  'appl.next.SANCTIONED': 'ਰਕਮ ਮਨਜ਼ੂਰ ਹੋ ਗਈ ਹੈ। ਅਦਾਇਗੀ ਉਨ੍ਹਾਂ ਦੇ ਬੈਂਕ ਰਾਹੀਂ ਹੁੰਦੀ ਹੈ।',
  'appl.next.DISBURSED': 'ਅਦਾਇਗੀ ਦਰਜ ਹੋ ਗਈ ਹੈ। ਜੇ ਕੁਝ ਕੰਮਕਾਜੀ ਦਿਨਾਂ ਵਿੱਚ ਤੁਹਾਡੇ ਖਾਤੇ ਵਿੱਚ ਨਾ ਪਹੁੰਚੇ ਤਾਂ ਸ਼ਿਕਾਇਤ ਕਰੋ।',
  'appl.next.REJECTED': 'ਇਹ ਅਰਜ਼ੀ ਸਫ਼ਲ ਨਹੀਂ ਹੋਈ। ਇਸ ਨਾਲ ਤੁਹਾਡੀਆਂ ਬਾਕੀ ਅਰਜ਼ੀਆਂ ਉੱਤੇ ਕੋਈ ਅਸਰ ਨਹੀਂ ਪੈਂਦਾ।',
  'appl.next.CLOSED': 'ਇਹ ਅਰਜ਼ੀ ਮੁਕੰਮਲ ਹੋ ਗਈ ਹੈ।',
  'appl.next.WITHDRAWN': 'ਤੁਸੀਂ ਇਹ ਅਰਜ਼ੀ ਵਾਪਸ ਲੈ ਲਈ ਸੀ।',
}

export default pa
