/* Telugu.
 *
 * One word per term: scholarship ఉపకారవేతనం, application దరఖాస్తు,
 * document పత్రం, disability దివ్యాంగత్వం, verified ధ్రువీకరించబడింది,
 * eligible అర్హత, certificate ధ్రువీకరణ పత్రం, profile ప్రొఫైల్.
 *
 * Anything in {braces} is filled in by the code and must survive translation
 * unchanged. A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const te: Dict = {
  'app.name': 'ఉపకారవేతన పోర్టల్',
  'app.tagline': 'దివ్యాంగ విద్యార్థుల కోసం',
  'app.yourApplication': 'మీ దరఖాస్తు · {title}',

  'nav.find': 'ఉపకారవేతనాలు',
  'nav.how': 'ఇది ఎలా పనిచేస్తుంది',
  'nav.matches': 'నా సరిపోలికలు',
  'nav.applications': 'నా దరఖాస్తులు',
  'nav.documents': 'నా పత్రాలు',
  'nav.profile': 'నా ప్రొఫైల్',
  'nav.privacy': 'నా సమాచారం',
  'nav.account': 'నా ఖాతా',
  'nav.register': 'సైన్ అప్',
  'nav.language': 'భాష',
  'footer.social': 'ఇండిక్ ఏఐ ఇతర చోట్ల',
  'footer.sponsor': 'సహకారంతో',
  'footer.copyright': 'కాపీరైట్ © {year} ఇండిక్ ఏఐ | సర్వ హక్కులు ప్రత్యేకించబడ్డాయి',
  'nav.signin': 'సైన్ ఇన్',
  'nav.signout': 'సైన్ అవుట్',
  'nav.skip': 'ప్రధాన విషయానికి వెళ్లండి',

  'public.title': 'మీరు అర్హత పొందే ఉపకారవేతనాన్ని కనుగొనండి',
  'public.lede': 'ఇక్కడ ఉన్న ప్రతి ఉపకారవేతనం దివ్యాంగ విద్యార్థులకు అందుబాటులో ఉంది. చూడటానికి ఖాతా అవసరం లేదు.',
  'public.search': 'పేరు లేదా పదంతో వెతకండి',
  'public.filter.disability': 'దివ్యాంగత్వ రకం',
  'public.filter.qualification': 'అర్హత',
  'public.filter.state': 'మీ రాష్ట్రం',
  'public.filter.provider': 'ఎవరు ఇస్తున్నారు',
  'public.filter.any': 'ఏదైనా',
  'public.filter.anyDisability': 'ఏ దివ్యాంగత్వమైనా',
  'public.filter.anyQualification': 'ఏ అర్హతైనా',
  'public.filter.allStates': 'అన్ని రాష్ట్రాలు',
  'public.filter.gender': 'లింగం',
  'public.filter.anyGender': 'ఏ లింగమైనా',
  'public.filter.course': 'కోర్సు',
  'public.filter.anyCourse': 'ఏ కోర్సైనా',
  'public.filter.where': 'మీరు ఎక్కడ చదువుతున్నారు',
  'public.filter.anyWhere': 'భారతదేశం లేదా విదేశం',
  'public.filter.inIndia': 'భారతదేశంలో',
  'public.filter.abroad': 'విదేశీ విద్య',
  'public.filters': 'ఫిల్టర్లు',
  'public.clear': 'తొలగించు',
  'public.results': 'ఉపకారవేతనాలు ఇప్పుడు తెరిచి ఉన్నాయి',
  'public.searching': 'వెతుకుతోంది…',
  'public.none': 'ఈ ఫిల్టర్లకు ఏ ఉపకారవేతనమూ సరిపోలలేదు',
  'public.none.hint': 'ఒక ఫిల్టర్ తీసివేసి చూడండి. ఏడాది పొడవునా కొత్త పథకాలు తెరుచుకుంటాయి.',
  'public.none.clear': 'అన్ని ఫిల్టర్లను తొలగించు',
  'public.empty': 'ఇక్కడ ఇంకా ఏ ఉపకారవేతనమూ జాబితా చేయబడలేదు',
  'public.empty.hint': 'ప్రదాతలను ఇప్పుడు చేరుస్తున్నాం. ఇక్కడ ఏదీ ఖాతా వెనుక లేదు — పథకాలు జాబితా అయ్యాక సైన్ ఇన్ చేయకుండానే చూడగలరు.',
  'public.whoFor': 'ఇది ఎవరి కోసం',
  'public.about': 'ఈ ఉపకారవేతనం గురించి',
  'public.atAGlance': 'ఒక్క చూపులో',
  'public.closes': 'ముగుస్తుంది',
  'public.awardUnstated': 'మొత్తం పేర్కొనలేదు',
  'public.noClose': 'చివరి తేదీ లేదు',
  'public.closesIn': '{n} రోజుల్లో ముగుస్తుంది',
  'public.closesToday': 'ఈ రోజు ముగుస్తుంది',
  'public.closed': 'ముగిసింది',
  'public.award': 'మొత్తం',
  'public.renewable': 'ప్రతి సంవత్సరం పునరుద్ధరించుకోవచ్చు',
  'public.offeredBy': 'అందిస్తున్నది',
  'public.eligibility': 'అర్హత పొందాలంటే',
  'public.benefits': 'ప్రయోజనాలు',
  'public.readMore': 'ఇంకా చదవండి',
  'public.viewDetails': 'వివరాలు చూడండి',
  'public.applyNow': 'ఇప్పుడే దరఖాస్తు చేయండి',
  'public.registerToApply': 'దరఖాస్తు చేయండి',
  'public.registerToApplyHelp': 'దరఖాస్తులు మీ ఖాతా ద్వారా చేయబడతాయి. నమోదు చేసుకుంటే మీరు అర్హత పొందే ప్రతి ఉపకారవేతనమూ కనిపిస్తుంది.',
  'public.closedNote': 'ఈ పథకం ముగిసింది',
  'sheet.close': 'మూసివేయి',
  'sheet.loading': 'ఉపకారవేతన వివరాలు',
  'public.benefitComponent': 'అంశం',
  'public.benefitAmount': 'విద్యార్థికి ఏమి లభిస్తుంది',
  'public.whatYouGet': 'మీకు ఏమి లభిస్తుంది',
  'public.eligibilityDetail': 'అర్హత వివరంగా',
  'public.documentsRequired': 'అవసరమైన పత్రాలు',
  'public.documentsHelp': 'ప్రదాత వీటిని అడుగుతారు. వీటిని మీరు ఇక్కడ అప్‌లోడ్ చేయరు.',
  'public.howToApply': 'ఎలా దరఖాస్తు చేయాలి',
  'public.importantNotes': 'తెలిసి ఉండాల్సినవి',
  'public.academicYear': 'ఏ సంవత్సరానికి',
  'public.awardBasis': 'దేని ఆధారంగా',
  'public.basis.MERIT': 'ప్రతిభ',
  'public.basis.NEED': 'ఆర్థిక అవసరం',
  'public.basis.MERIT_CUM_MEANS': 'ప్రతిభ మరియు ఆదాయం',
  'public.basis.CATEGORY': 'వర్గం',
  'public.basis.OTHER': 'ఇతర',
  'public.cta': 'మీ కోసం ఉపకారవేతనాలను కనుగొనండి',
  'public.applyExternal': 'వారి సైట్‌లో దరఖాస్తు చేయండి',
  'public.applyExternalHelp': 'మీరు కనుగొనేందుకే మేము ఈ ఉపకారవేతనాన్ని జాబితా చేస్తాం. {org} దీన్ని నిర్వహిస్తుంది, తమ వెబ్‌సైట్‌లోనే దరఖాస్తులు తీసుకుంటుంది, కాబట్టి ఇది ఇక్కడ మీ దరఖాస్తుల్లో కనిపించదు.',
  'public.applyExternalHelpPartner': '{org} ఈ దరఖాస్తును తమ వెబ్‌సైట్‌లోనే తీసుకుంటుంది, కాబట్టి ఇది ఇక్కడ మీ దరఖాస్తుల్లో కనిపించదు.',
  'common.newTab': 'కొత్త ట్యాబ్‌లో తెరుచుకుంటుంది',
  'public.applyHelp': 'మేము ముందుగా మీ ప్రొఫైల్‌ను, పత్రాలను ఈ ఉపకారవేతనంతో సరిపోల్చి, ఏదైనా తక్కువైతే చెబుతాం. మీరు ధ్రువీకరించే వరకు ఏదీ పంపబడదు.',
  'public.ctaHelp': 'మీ గురించి ఒకసారి చెప్పండి, మీరు అర్హత పొందే ప్రతి ఉపకారవేతనాన్ని చూపిస్తాం.',
  'public.back': 'అన్ని ఉపకారవేతనాలకు తిరిగి',
  'notFound.title': 'ఈ పేజీ మాకు కనిపించలేదు',
  'notFound.body': 'చిరునామాలో టైపింగ్ తప్పు ఉండవచ్చు, లేదా పేజీ వేరే చోటికి మారి ఉండవచ్చు.',
  'notFound.home': 'హోమ్ పేజీకి వెళ్ళండి',

  'nav.dashboard': 'డాష్‌బోర్డ్',
  'dash.title': 'మీ డాష్‌బోర్డ్',
  'dash.lede': 'మీ ఉపకారవేతనాలు, దరఖాస్తులు, పత్రాలు — అన్నీ ఒకే చోట.',
  'dash.matches': 'మీరు దరఖాస్తు చేయగల ఉపకారవేతనాలు',
  'dash.matchesHint': 'మీరు ఇచ్చిన వివరాల ఆధారంగా.',
  'dash.matchesBlocked': '{n} మీ నుండి మరో వివరం కోసం వేచి ఉన్నాయి.',
  'dash.applications': 'కొనసాగుతున్న దరఖాస్తులు',
  'dash.applicationsHint': '{approved} ఆమోదం · {rejected} విజయవంతం కాలేదు',
  'dash.applicationsNone': 'ఇంకా ఏదీ పంపలేదు.',
  'dash.documents': 'ధ్రువీకరించిన పత్రాలు',
  'dash.documentsHint': 'ఒకసారి తనిఖీ చేసినవి. ప్రతి దరఖాస్తుకూ ఉపయోగపడతాయి.',
  'dash.funding': 'ఇప్పటివరకు అందినది',
  'dash.fundingHint': 'మొత్తం {sanctioned} మంజూరు.',
  'dash.recent': 'ఇటీవలి దరఖాస్తులు',
  'dash.noApplications': 'ఇంకా దరఖాస్తులు లేవు',
  'dash.noApplicationsHint': 'మీరు దేనికి దరఖాస్తు చేసినా అది ఇక్కడ కనిపిస్తుంది.',
  'dash.findScholarships': 'ఉపకారవేతనాలను కనుగొనండి',
  'dash.profileTitle': 'మీ ప్రొఫైల్',
  'dash.toGo': '{n}% మిగిలి ఉంది',
  'dash.allApplications': 'అన్నీ చూడండి',
  'dash.matchesGo': 'మీ సరిపోలికలను చూడండి',
  'dash.applicationsGo': 'మీ దరఖాస్తులను గమనించండి',
  'dash.documentsGo': 'పత్రాలను నిర్వహించండి',
  'dash.draftsTitle': '{n} దరఖాస్తు పంపలేదు | {n} దరఖాస్తులు పంపలేదు',
  'dash.draftsBody': 'దరఖాస్తు మొదలుపెట్టడం అంటే పంపడం కాదు. ఉపకారవేతనం ముగియకముందే పూర్తి చేయండి.',
  'dash.draftsAction': 'ఇప్పుడే పూర్తి చేయండి',
  'dash.expiringTitle': '{n} పత్రం గడువు త్వరలో ముగుస్తుంది | {n} పత్రాల గడువు త్వరలో ముగుస్తుంది',
  'dash.expiringBody': 'ప్రతి దరఖాస్తుకూ పనికొచ్చేలా దీన్ని ఇప్పుడే మార్చండి. | ప్రతి దరఖాస్తుకూ పనికొచ్చేలా వీటిని ఇప్పుడే మార్చండి.',
  'dash.expiringAction': 'పత్రాలను చూడండి',

  'auth.title': 'మీ మొబైల్ నంబర్ ఇవ్వండి',
  'auth.phone': 'మొబైల్ నంబర్',
  'auth.phoneHint': 'ఈ నంబర్‌కు 6 అంకెల కోడ్‌ను SMS ద్వారా పంపుతాం. ప్రతిసారీ ఇదే నంబర్ మిమ్మల్ని సైన్ ఇన్ చేస్తుంది.',
  'auth.phoneMissing': 'కొనసాగడానికి మీ మొబైల్ నంబర్ ఇవ్వండి.',
  'auth.phoneInvalid': 'ఇది సరిగా అనిపించడం లేదు. భారతీయ మొబైల్ నంబర్లు 10 అంకెలు, 6, 7, 8 లేదా 9తో మొదలవుతాయి.',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'కొత్తవారైనా, తిరిగి వచ్చినవారైనా, అదే నంబర్ పనిచేస్తుంది. మీకు ఖాతా లేకుంటే మేము సృష్టిస్తాం.',
  'auth.stepOf': 'దశ {n} / 2 · {name}',
  'auth.stepPhone': 'మీ నంబర్',
  'auth.stepCode': 'మీ OTP కోడ్',
  'auth.privacy': 'మీ నంబర్ మిమ్మల్ని సైన్ ఇన్ చేయడానికి మాత్రమే వాడతాం, ఇంకెందుకూ కాదు. గుర్తుంచుకోవడానికి పాస్‌వర్డ్ ఏదీ లేదు.',
  'auth.sendCode': 'కోడ్ పంపు',
  'auth.sending': 'పంపుతోంది…',
  'auth.checking': 'తనిఖీ చేస్తోంది…',
  'auth.welcomeBack': 'తిరిగి స్వాగతం. సైన్ ఇన్ చేయడానికి కోడ్ ఇవ్వండి.',
  'auth.newHere': 'కోడ్ ఇచ్చిన వెంటనే మీ ఖాతాను సృష్టిస్తాం.',
  'auth.codeTitle': 'మేము పంపిన కోడ్‌ను ఇవ్వండి',
  'auth.code': '6 అంకెల కోడ్',
  'auth.codeHint': 'సందేశం సాధారణంగా కొన్ని సెకన్లలో వస్తుంది.',
  'auth.noCode': 'ఇంకా సందేశం రాలేదా? మరో మార్గం చూడండి:',
  'auth.verify': 'ధ్రువీకరించు',
  'auth.viaSms': 'SMS ద్వారా పంపు',
  'auth.viaWhatsapp': 'వాట్సాప్‌లో పంపు',
  'auth.viaVoice': 'కోడ్ చెప్పడానికి నాకు ఫోన్ చేయండి',
  'auth.resentVia.sms': 'SMS ద్వారా పంపాం. రావడానికి కొంత సమయం పట్టవచ్చు.',
  'auth.resentVia.whatsapp': 'వాట్సాప్‌లో పంపాం. సందేశం కోసం వాట్సాప్ చూడండి.',
  'auth.resentVia.voice': 'కోడ్ చెప్పడానికి ఇప్పుడే ఫోన్ చేస్తున్నాం. వినడానికి ఫోన్ ఎత్తండి.',
  'auth.resendIn': '{n} సెకన్లలో మళ్లీ పంపు',
  'auth.changeNumber': 'వేరే నంబర్ వాడండి',
  'auth.change': 'మార్చు',

  'profile.complete': '{n}% పూర్తి',
  'profile.viewLede': 'మీరు మాకు చెప్పినదంతా. ఏ సమాధానాన్నైనా మార్చండి, అప్పటినుండి ప్రతి ఉపకారవేతనానికీ అదే వాడతాం.',
  'profile.notAnswered': 'ఇంకా సమాధానం ఇవ్వలేదు',
  'profile.verified': 'ధ్రువీకరించబడింది',
  'profile.continue': 'ఆపిన చోటి నుండి కొనసాగించండి',
  'profile.start': 'మీ ప్రొఫైల్ మొదలుపెట్టండి',
  'profile.saved': 'భద్రపరచబడింది',

  'match.title': 'మీ కోసం ఉపకారవేతనాలు',
  'match.lede': 'మీ ప్రొఫైల్‌తో సరిపోల్చినవి. దరఖాస్తు చేయగలిగినవి ముందుగా.',
  'match.eligible': 'మీరు అర్హులు',
  'match.likely': 'మీరు బహుశా అర్హులు',
  'match.blocked': 'ముందుగా ఒక పని',
  'match.actionable': 'మీకు అందుబాటులో',
  'match.actionableHelp': 'కొన్నింటికి దరఖాస్తు చేయడానికి ముందు ఒక పత్రం అవసరం కావచ్చు.',
  'match.ineligible': 'మీకు అందుబాటులో లేదు',
  'match.eligibleHelp': 'మేము తనిఖీ చేసినదంతా ధ్రువీకరించబడింది.',
  'match.likelyHelp': 'మీరు చెప్పిన దాని ఆధారంగా. ధ్రువీకరించుకుంటే మీ దరఖాస్తు బలపడుతుంది.',
  'match.blockedHelp': 'మీరు దగ్గరగా ఉన్నారు. ఇది చేస్తే దరఖాస్తు చేయవచ్చు.',
  'match.ineligibleHelp': 'మీరు మార్చలేని దాన్ని ఈ పథకం అడుగుతోంది.',
  'match.apply': 'దరఖాస్తు చేయండి',
  'match.applied': 'మీరు దరఖాస్తు చేశారు',
  'match.none': 'ఇంకా సరిపోలికలు లేవు',
  'match.noneHint': 'మీ ప్రొఫైల్ పూర్తి చేయండి, ప్రతి ఉపకారవేతనాన్నీ మీ కోసం తనిఖీ చేస్తాం.',
  'match.figQualify': 'మీరు అర్హులు',
  'match.figStep': 'ఒక అడుగు దూరం',
  'match.figClosing': 'త్వరలో ముగుస్తుంది',
  'match.figNo': 'మీకు అందుబాటులో లేదు',
  'match.filterLabel': 'ఏ ఉపకారవేతనాలను చూపాలి',
  'match.filterAll': 'అన్నీ',
  'match.filterQualify': 'మీరు అర్హులు',
  'match.filterStep': 'ఒక అడుగు దూరం',
  'match.filterClosing': 'త్వరలో ముగుస్తుంది',
  'match.filterNo': 'మీకు అందుబాటులో లేదు',
  'match.filterEmpty': 'ఈ సమూహంలో ఏదీ లేదు. “అన్నీ” చూడండి.',
  'match.moreWithProfile': 'మీరు నింపుతున్న కొద్దీ మరిన్ని ఉపకారవేతనాలు కనిపిస్తాయి.',
  'match.youQualify': 'మీ ప్రొఫైల్ ప్రకారం మీరు షరతులను నెరవేరుస్తున్నారు.',
  'match.yesTitle': 'మీరు దరఖాస్తు చేయవచ్చు',
  'match.blockedTitle': 'ముందుగా ఒక పని',
  'match.noTitle': 'అర్హులు కాదు',
  'match.appliedTitle': 'ఇప్పటికే పంపబడింది',
  'match.seeDetails': 'నిబంధనలు చూడండి',
  'match.learnMore': 'మరింత తెలుసుకోండి',
  'match.runBy': '{kind} నిర్వహిస్తోంది',
  'match.sortBy': 'క్రమం',
  'match.sortRecommended': 'సిఫార్సు చేసినవి',
  'match.sortClosing': 'ముందుగా ముగిసేవి',
  'match.sortAward': 'అత్యధిక మొత్తం',
  'match.applyAway': 'వారి సైట్‌లో దరఖాస్తు చేయండి',
  'match.applyHere': 'ఇక్కడే దరఖాస్తు చేయండి',
  'match.notOpenToYou': 'ప్రస్తుత స్థితిలో మీకు అందుబాటులో లేదు.',
  'match.working': 'ఇప్పుడు తెరిచిన ఏ పథకమూ మీరు ఇచ్చిన వివరాలతో సరిపోలడం లేదు. ప్రొఫైల్‌లో మరింత చేరిస్తేనే ఇది మారుతుంది.',

  'doc.title': 'మీ పత్రాలు',
  'doc.lede': 'ఒక పత్రాన్ని ఒకసారి అప్‌లోడ్ చేయండి. మీరు దరఖాస్తు చేసే ప్రతి ఉపకారవేతనమూ దాన్ని వాడుకోగలదు — మిమ్మల్ని మళ్లీ అడగరు.',
  'doc.upload': 'పత్రం చేర్చు',
  'doc.type': 'ఇది ఏ పత్రం?',
  'doc.file': 'ఫైల్ ఎంచుకోండి',
  'doc.fileHint': 'PDF లేదా స్పష్టమైన ఫోటో. 10 MB వరకు.',
  'doc.verified': 'ధ్రువీకరించబడింది',
  'doc.verifiedBy': '{org} ధ్రువీకరించింది',
  'doc.pending': 'ధ్రువీకరణ కోసం వేచి ఉంది',
  'doc.expired': 'ధ్రువీకరణ గడువు ముగిసింది',
  'doc.expiring': '{n} రోజుల్లో గడువు ముగుస్తుంది',
  'doc.validUntil': '{date} వరకు చెల్లుబాటు',
  'doc.none': 'మీరు ఇంకా ఏ పత్రమూ చేర్చలేదు',
  'doc.uploading': 'అప్‌లోడ్ అవుతోంది…',
  'doc.remove': 'తొలగించు',
  'doc.removing': 'తొలగిస్తోంది…',

  'apply.title': 'దరఖాస్తు చేయండి',
  'apply.consent': 'నా వివరాలను ఈ ప్రదాతతో పంచుకో',
  'apply.consentBody': 'నిర్ణయం తీసుకోవడానికి ఈ ఉపకారవేతనానికి అవసరమైనది మాత్రమే వారు చూస్తారు: {fields}. మీ పత్రాలను ఎవరు చూశారో ఎప్పుడైనా చూడవచ్చు.',
  'apply.consentBodyNoDocs': 'నిర్ణయం తీసుకోవడానికి ఈ ఉపకారవేతనానికి అవసరమైనది మాత్రమే వారు చూస్తారు, ఇంకేదీ కాదు. మీ వివరాలను ఎవరు చూశారో ఎప్పుడైనా చూడవచ్చు.',
  'apply.submit': 'నా దరఖాస్తును పంపు',
  'apply.submitting': 'పంపుతోంది…',
  'apply.blocked': 'మీరు ఇంకా దరఖాస్తు చేయలేరు',
  'apply.needProfile': 'ముందుగా మీ ప్రొఫైల్',
  'apply.needProfileHint': 'దరఖాస్తు మీ ప్రొఫైల్ నుండే పంపబడుతుంది, కాబట్టి దరఖాస్తుకు ముందు అది అవసరం. దీనికి కొన్ని నిమిషాలే పడుతుంది, మీరు ఇంతకుముందు చెప్పినవి నింపి ఉంటాయి.',
  'apply.elsewhereTitle': 'దీనికి ప్రాయోజకుల వెబ్‌సైట్‌లో దరఖాస్తు చేయాలి',
  'apply.elsewhereBody': 'మీరు కనుగొనేందుకే మేము ఈ ఉపకారవేతనాన్ని జాబితా చేస్తాం, దరఖాస్తులను ప్రాయోజకులే తీసుకుంటారు. మీరు మాకు చెప్పినదంతా భద్రంగా ఉంటుంది, మేము నిర్వహించే ఉపకారవేతనాలకు అది ముందే నింపబడి ఉంటుంది.',
  'apply.elsewhereBodyPartner': 'ఈ ఉపకారవేతనం ఇక్కడే నడుస్తుంది, కానీ ప్రాయోజకులు దరఖాస్తులను తమ వెబ్‌సైట్‌లోనే తీసుకుంటారు. మీరు మాకు చెప్పినదంతా భద్రంగా ఉంటుంది, మాకు నేరుగా అందే దరఖాస్తులకు అది ముందే నింపబడి ఉంటుంది.',
  'apply.bundleTitle': 'మీ పత్రాలను వెంట తీసుకెళ్లండి',
  'apply.bundleBody': 'ఈ ఉపకారవేతనం అడిగే పత్రాలను ఒకే ఫైల్‌గా చేసి ఇవ్వగలం, వారి వెబ్‌సైట్‌లో అప్‌లోడ్ చేయడానికి సిద్ధంగా. వారు అడిగే, మా దగ్గర ఇంకా లేని వాటినీ అది జాబితా చేస్తుంది.',
  'apply.bundleAction': 'నా పత్రాలను డౌన్‌లోడ్ చేయి',
  'apply.bundleWorking': 'సిద్ధం చేస్తోంది…',
  'apply.bundleDone': 'మీ పత్రాలు డౌన్‌లోడ్ అయ్యాయి.',
  'apply.docs': 'ఈ ఉపకారవేతనానికి అవసరమైన పత్రాలు',

  'appl.title': 'మీ దరఖాస్తులు',
  'appl.none': 'మీరు ఇంకా దేనికీ దరఖాస్తు చేయలేదు',
  'appl.noneHint': 'మీరు అర్హత పొందే ఉపకారవేతనాలను కనుగొనడానికి మీ సరిపోలికలను చూడండి.',
  'appl.reference': 'సూచిక',
  'appl.whatNext': 'తరువాత ఏమి జరుగుతుంది',
  'appl.history': 'చరిత్ర',
  'appl.needsYou': 'వారికి మీ నుండి ఏదో కావాలి',
  'track.label': 'ఈ దరఖాస్తు పురోగతి',
  'track.sent': 'పంపబడింది',
  'track.review': 'సమీక్ష',
  'track.decision': 'నిర్ణయం',
  'track.doneSr': 'పూర్తయింది',
  'track.currentSr': 'ఇప్పుడు జరుగుతోంది',
  'track.todoSr': 'మొదలవలేదు',
  'appl.sentOn': '{when} పంపబడింది',
  'appl.decidedOn': '{when} నిర్ణయించబడింది',
  'appl.outcomeApproved': 'లభించింది',
  'appl.outcomeRejected': 'ఈసారి లభించలేదు',
  'appl.outcomeWithdrawn': 'మీరు దీన్ని ఉపసంహరించుకున్నారు',
  'appl.inProgress': 'ప్రదాత వద్ద',
  'appl.outcome': 'ఫలితం',
  'appl.award': 'మొత్తం',
  'appl.applied': 'దరఖాస్తు చేయబడింది',
  'appl.decided': 'నిర్ణయించబడింది',
  'appl.automatic': 'స్వయంచాలకం',
  'appl.noHistory': 'ఇంకా ఏదీ జరగలేదు.',

  'ref.heading': 'వారి వెబ్‌సైట్‌కు పంపబడింది',
  'ref.blurb': 'వీటికి ప్రదాత సొంత సైట్‌లోనే దరఖాస్తు చేయాలి, కాబట్టి ఏమి జరిగిందో మేము చూడలేం. మాకు చెప్పండి, మిగతావాటితో కలిపి ఉంచుతాం.',
  'ref.sentOn': 'మీరు దీన్ని {when} తెరిచారు',
  'ref.again': 'మొత్తం {times} సార్లు',
  'ref.open': 'వారి సైట్‌ను మళ్లీ తెరవండి',
  'ref.what': 'ఏమి జరిగింది?',
  'ref.APPLIED': 'నేను దరఖాస్తు చేశాను',
  'ref.AWARDED': 'నాకు లభించింది',
  'ref.NOT_AWARDED': 'నాకు లభించలేదు',
  'ref.DID_NOT_APPLY': 'నేను దరఖాస్తు చేయలేదు',
  'ref.saidAPPLIED': 'మీరు దరఖాస్తు చేశారు',
  'ref.saidAWARDED': 'మీకు లభించింది',
  'ref.saidNOT_AWARDED': 'మీకు లభించలేదు',
  'ref.saidDID_NOT_APPLY': 'మీరు దరఖాస్తు చేయలేదు',
  'ref.youSaid': 'మీరు మాకు చెప్పింది: {what}',
  'ref.change': 'మార్చు',

  'privacy.title': 'మీ సమాచారం',
  'privacy.lede': 'మా దగ్గర ఏమి ఉంది, ఎవరు చూశారు, దాన్ని తిరిగి తీసుకోవడం ఎలా.',
  'privacy.access': 'మీ పత్రాలను ఎవరు చూశారు',
  'privacy.accessNone': 'మీ సొంత ఖాతా బయట ఎవరూ మీ పత్రాలను తెరవలేదు.',
  'privacy.consents': 'పంచుకోవడానికి మీరు అంగీకరించినవి',
  'privacy.withdraw': 'ఉపసంహరించు',
  'privacy.withdrawing': 'ఉపసంహరిస్తోంది…',
  'privacy.export': 'మా దగ్గర ఉన్నదంతా డౌన్‌లోడ్ చేయి',
  'privacy.exporting': 'మీ ప్రతిని సిద్ధం చేస్తోంది…',
  'privacy.exportBody': 'మీ సమాచారం పూర్తి, యంత్రం చదవగల ప్రతి.',
  'privacy.erase': 'నా సమాచారాన్ని తొలగించు',
  'privacy.erasing': 'అభ్యర్థిస్తోంది…',
  'privacy.eraseBody': 'మీకు చెల్లించిన ఏ ఉపకారవేతనం రికార్డులనైనా మేము ఉంచాల్సి ఉంటుంది. మిగతాదంతా తొలగించబడుతుంది.',
  'auth.closedTitle': 'మీ ఖాతా ప్రస్తుతం మూసివేయబడింది.',
  'auth.closedHelp': 'సహాయం కావాలా? మా సహాయ బృందం మీకు అర్థం చేసుకోవడంలో సాయపడగలదు ',
  'auth.closedSoon': 'సహాయం కోరండి (త్వరలో)',
  'reg.district': 'జిల్లా',
  'reg.districtHint': 'మీ ప్రాంతంలో నడిచే పథకాలతో సరిపోల్చడానికి సాయపడుతుంది.',
  'privacy.requested': 'అభ్యర్థించబడింది',
  'privacy.window': 'ఇంకా ఏదీ తొలగించబడలేదు',
  'privacy.windowBody': 'మీ సమాచారం {date}న తొలగించబడుతుంది. అప్పటివరకు మీరు ',
  'privacy.cancel': 'ఈ అభ్యర్థనను రద్దు చేయి',
  'privacy.cancelling': 'రద్దు చేస్తోంది…',
  'privacy.cancelled': 'మీ అభ్యర్థన రద్దు చేయబడింది. ఏదీ తొలగించబడలేదు.',

  'common.loading': 'లోడ్ అవుతోంది',
  'common.retry': 'మళ్లీ ప్రయత్నించండి',
  'common.required': 'అవసరం',
  'common.optional': 'ఐచ్ఛికం',
  'common.error': 'ఏదో తప్పు జరిగింది',
  'common.offline': 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. మీ పని ఈ పరికరంలో భద్రపరచబడింది.',

  'slides.lead.was': '',
  'slides.lead.able': 'సామర్థ్యం నుండి',
  'slides.lead.dist': 'విశిష్టత వైపు',
  'slides.lead.body': 'మీరు అర్హత పొందే ప్రతి ఉపకారవేతనం — ప్రభుత్వ, ప్రైవేట్ — మీ ప్రొఫైల్‌తో సరిపోల్చి, మీ భాషలో, ఒకే చోట.',
  'slides.lead.free': 'పూర్తిగా ఉచితం',
  'slides.lead.languages': '14 భాషలు',
  'slides.lead.support': 'ప్రతి అడుగులోనూ వ్యక్తిగత సహాయం',
  'slides.label': 'ప్రకటనలు',
  'slides.position': '{total}లో {n}',
  'slides.goto': '{name} చూపు',
  'slides.watch': 'వీడియో చూడండి',
  'slides.external': 'మరో వెబ్‌సైట్ తెరుస్తుంది',

  'home.title': 'దివ్యాంగ విద్యార్థుల కోసం ఉపకారవేతనాలు, ఒకే చోట',
  'home.lede': 'మీ గురించి ఒకసారి చెప్పండి. ఇక్కడి ప్రతి ఉపకారవేతనంతో మిమ్మల్ని సరిపోల్చి, మీరు దేనికి అర్హులో చెబుతాం — మిగతా వాటికి సరిగ్గా ఏమి తక్కువో కూడా.',
  'home.search': 'ఉపకారవేతనాలను వెతకండి',
  'home.searchPlaceholder': 'ఉదా: ఇంజనీరింగ్, ఢిల్లీ, పోస్ట్-మెట్రిక్',
  'home.searchGo': 'వెతుకు',
  'home.browseAll': 'అన్ని ఉపకారవేతనాలను చూడండి',
  'home.openNow': 'ఉపకారవేతనాలు ఇప్పుడు తెరిచి ఉన్నాయి',
  'home.noAccount': 'చూడటానికి ఖాతా అవసరం లేదు.',
  'home.openNone': 'ఇక్కడ ఇంకా ఏ ఉపకారవేతనమూ జాబితా చేయబడలేదు.',
  'home.openNoneBody': 'జాబితా ఇప్పుడు నింపబడుతోంది. ఇక్కడ ఏదీ ఖాతా వెనుక లేదు — పథకాలు జాబితా అయ్యాక సైన్ ఇన్ చేయకుండానే చూడగలరు.',
  'home.how': 'ఇది ఎలా పనిచేస్తుంది',
  'home.howLede': 'నమోదుకు ఒక మొబైల్ నంబర్, దానికి మేము పంపే కోడ్ చాలు. పాస్‌వర్డ్ లేదు, ముందుగా నింపాల్సిన సైన్-అప్ ఫారం కూడా లేదు.',
  'home.step1': 'నమోదు నొక్కండి',
  'home.step1Body': 'ఈ పేజీ పైభాగంలో. ఇంతకుముందు వచ్చి ఉంటే పక్కనే ఉన్న లాగిన్ వాడండి — రెండింటిలోనూ అదే నంబర్ పనిచేస్తుంది.',
  'home.step2': 'మీ మొబైల్ నంబర్ ఇవ్వండి',
  'home.step2Body': 'పది అంకెలు, +91 ముందే నింపి ఉంటుంది. ఆ నంబర్‌కు 6 అంకెల కోడ్ వెళ్తుంది.',
  'home.step3': 'కోడ్ ఇవ్వండి',
  'home.step3Body': 'ఆరు అంకెలు టైప్ చేస్తే లోపలికి వచ్చేస్తారు. సందేశం రాకపోతే కోడ్‌ను వాట్సాప్‌లో అడగండి, లేదా మేము ఫోన్ చేసి చదివి వినిపించమని చెప్పండి.',
  'home.step4': 'మీ వివరాలు నింపండి',
  'home.step4Body': 'మీ పేరు, మీ ధ్రువీకరణ పత్రం, మీరు ఎక్కడ చదువుతున్నారు — ఒకేసారి ఒక ప్రశ్న, ప్రతి సమాధానం ఇచ్చిన వెంటనే భద్రపరచబడుతుంది.',
  'home.step5': 'మీ పత్రాలను అప్‌లోడ్ చేయండి',
  'home.step5Body': 'దివ్యాంగత్వ ధ్రువీకరణ పత్రం, UDID కార్డు, ఆదాయ ధ్రువీకరణ పత్రం, ఇతరాలు. ప్రతిదీ ఒకసారే, ప్రతి ఉపకారవేతనానికీ వేరుగా కాదు.',
  'home.step6': 'మీ సరిపోలికలను చూడండి',
  'home.step6Body': 'నా సరిపోలికలు మీరు అర్హత పొందే ఉపకారవేతనాలను చూపుతుంది — ఏదైనా మీకు మూసి ఉంటే ఎందుకో కూడా చెబుతుంది.',
  'home.step7': 'దరఖాస్తు చేయండి',
  'home.step7Body': 'కావలసినవి ఎంచుకోండి. మీ వివరాలు, పత్రాలు దరఖాస్తుతో పాటు వెళ్తాయి.',
  'home.assure': 'తెలిసి ఉండటం మంచిది',
  'home.assure1': 'గుర్తుంచుకోవడానికి పాస్‌వర్డ్ లేదు',
  'home.assure2': 'వేరే నమోదు ఫారం లేదు',
  'home.assure3': 'ఆపి తరువాత పూర్తి చేయవచ్చు',
  'home.help': 'ఏదైనా దశలో ఇబ్బందిగా ఉందా?',
  'home.helpBody': 'ఫోన్ చేయండి, ఎవరో ఒకరు మిమ్మల్ని దాటిస్తారు.',
  'home.helpCall': '{number}కు ఫోన్ చేయండి',
  'home.closing': 'త్వరలో ముగుస్తుంది',
  'home.closingLede': 'ముందుగా వీటికి దరఖాస్తు చేయండి.',
  'home.closingNext': 'తరువాతి చివరి తేదీలు',
  'home.closingNextLede': 'ముందుగా ముగిసే మూడు.',
  'home.allDeadlines': 'అన్ని ఉపకారవేతనాలను చూడండి',
  'home.browse': 'దీని ప్రకారం చూడండి',
  'home.browseWho': 'ఎవరు ఇస్తున్నారు',
  'home.browseLevel': 'మీ చదువు స్థాయి',
  'home.cta': 'మీ సరిపోలికలను చూడటానికి సిద్ధమా?',
  'home.ctaBody': 'ఖాతా సృష్టించడానికి ఒక మొబైల్ నంబర్ లేదా ఇమెయిల్ చిరునామా చాలు. ఇంకేదీ కాదు.',
  'home.ctaButton': 'ఖాతా సృష్టించండి',
  'home.signedInCta': 'మీరు దేనికి అర్హులో చూడండి',

  'reg.title': 'ఉపకారవేతనాలను కనుగొనడానికి నమోదు చేసుకోండి',
  'reg.editTitle': 'మీ వివరాలను నవీకరించండి',
  'reg.requiredNote': '* గుర్తు ఉన్న అన్ని ఖాళీలూ అవసరం.',
  'reg.personal': 'వ్యక్తిగత వివరాలు',
  'reg.disability': 'దివ్యాంగత్వ వివరాలు',
  'reg.education': 'విద్యా వివరాలు',
  'reg.name': 'పూర్తి పేరు',
  'reg.namePlaceholder': 'మీ పూర్తి పేరు ఇవ్వండి',
  'reg.phoneHint': 'ఈ నంబర్‌కు 6 అంకెల కోడ్ పంపుతాం. ప్రతిసారీ ఇదే నంబర్ మిమ్మల్ని సైన్ ఇన్ చేస్తుంది.',
  'reg.sendOtp': 'OTP పంపు',
  'reg.otpPlaceholder': '6 అంకెల OTP ఇవ్వండి',
  'reg.verified': 'ఫోన్ నంబర్ ధ్రువీకరించబడింది',
  'reg.verifyFirst': 'నమోదు పూర్తి చేయడానికి మీ ఫోన్ నంబర్‌ను ధ్రువీకరించండి.',
  'reg.email': 'ఇమెయిల్',
  'reg.emailHint': 'చివరి తేదీని గుర్తు చేయడానికి. దీన్ని మేము ఎప్పుడూ పంచుకోము.',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'లింగం',
  'reg.genderHint': '(కొన్ని ఉపకారవేతనాలు మహిళా లేదా ట్రాన్స్‌జెండర్ విద్యార్థులకు మాత్రమే)',
  'reg.udid': 'UDID నంబర్',
  'reg.udidHint': 'మీ UDID (ప్రత్యేక దివ్యాంగత్వ గుర్తింపు) కార్డుపై ఉన్న నంబర్.',
  'reg.udidPlaceholder': 'మీ UDID నంబర్ ఇవ్వండి',
  'reg.certificate': 'UDID ధ్రువీకరణ పత్రాన్ని అప్‌లోడ్ చేయండి',
  'reg.certificateHint': 'PDF లేదా చిత్రం, 5 MB లేదా అంతకంటే తక్కువ.',
  'reg.fileType': 'ఆ ఫైల్ PDF, JPEG లేదా PNG అయి ఉండాలి.',
  'reg.fileSize': 'ఆ ఫైల్ 5 MB కంటే పెద్దది. ఫోన్‌లో తీసిన ఫోటో, ఫోటో తీయకుండా స్కాన్ చేస్తే సాధారణంగా చిన్నదిగా ఉంటుంది.',
  'reg.fileLater': 'మీ నమోదు అయింది, వివరాలు భద్రపరచబడ్డాయి. ధ్రువీకరణ పత్రం అప్‌లోడ్ కాలేదు — నా పత్రాల నుండి చేర్చండి, ఇంకేదీ మళ్లీ చేయనవసరం లేదు.',
  'reg.disabilityType': 'దివ్యాంగత్వ రకం',
  'reg.percent': 'దివ్యాంగత్వ శాతం',
  'reg.percentHint': 'మీ ధ్రువీకరణ పత్రంపై ఉన్న సంఖ్య. చాలా ఉపకారవేతనాలకు 40% లేదా అంతకంటే ఎక్కువ కావాలి.',
  'reg.percentPlaceholder': 'ఉదా. 40',
  'reg.percentRange': 'ధ్రువీకరణ పత్ర శాతం 0 నుండి 100 మధ్య పూర్ణ సంఖ్య.',
  'reg.state': 'రాష్ట్రం',
  'reg.statePlaceholder': 'మీ రాష్ట్రాన్ని వెతకడానికి టైప్ చేయండి…',
  'reg.program': 'మీ కోర్సును ఎంచుకోండి',
  'reg.graduation': 'డిగ్రీ',
  'reg.postgraduation': 'పోస్ట్ గ్రాడ్యుయేషన్ / మాస్టర్స్',
  'reg.year': 'సంవత్సరాన్ని ఎంచుకోండి',
  'reg.yearAfterProgram': 'ముందుగా మీ కోర్సును ఎంచుకోండి',
  'reg.institution': 'పాఠశాల / కళాశాల పేరు',
  'reg.institutionPlaceholder': 'మీ సంస్థ పేరు ఇవ్వండి',
  'reg.required': 'ఇది అవసరం.',
  'reg.fix': 'కొన్ని సమాధానాలకు శ్రద్ధ అవసరం. మొదటిది కింద ఎంపిక చేయబడింది.',
  'reg.cta': 'నమోదు చేసుకుని ఉపకారవేతనాలను కనుగొనండి',
  'reg.saveChanges': 'మార్పులను భద్రపరచు',
  'reg.saving': 'భద్రపరుస్తోంది…',
  'reg.done': 'నమోదు అయింది. మీ ఉపకారవేతనాలను కనుగొంటున్నాం.',
  'reg.doneTitle': 'మీ నమోదు అయింది',
  'reg.already': 'ఇప్పటికే నమోదు చేసుకున్నారా?',
  'reg.login': 'OTPతో లాగిన్',
  'nav.registerCta': 'నమోదు',
  'nav.loginCta': 'లాగిన్',
  'profile.edit': 'మీ వివరాలను నవీకరించండి',
  'field.disability.BLINDNESS': 'అంధత్వం',
  'field.disability.LOW_VISION': 'అల్ప దృష్టి',
  'field.disability.LEPROSY_CURED': 'కుష్ఠు (నయమైనది)',
  'field.disability.HEARING_IMPAIRMENT': 'వినికిడి లోపం',
  'field.disability.LOCOMOTOR_DISABILITY': 'చలన దివ్యాంగత్వం',
  'field.disability.DWARFISM': 'పొట్టితనం',
  'field.disability.INTELLECTUAL_DISABILITY': 'మేధో దివ్యాంగత్వం',
  'field.disability.MENTAL_ILLNESS': 'మానసిక అనారోగ్యం',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'ఆటిజం స్పెక్ట్రమ్ డిజార్డర్',
  'field.disability.CEREBRAL_PALSY': 'సెరిబ్రల్ పాల్సీ',
  'field.disability.MUSCULAR_DYSTROPHY': 'కండరాల క్షీణత',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'దీర్ఘకాలిక నాడీ సంబంధిత స్థితి',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'నిర్దిష్ట అభ్యసన దివ్యాంగత్వం',
  'field.disability.MULTIPLE_SCLEROSIS': 'మల్టిపుల్ స్క్లెరోసిస్',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'వాక్ మరియు భాషా దివ్యాంగత్వం',
  'field.disability.THALASSEMIA': 'తలసేమియా',
  'field.disability.HAEMOPHILIA': 'హీమోఫీలియా',
  'field.disability.SICKLE_CELL_DISEASE': 'సికిల్ సెల్ వ్యాధి',
  'field.disability.MULTIPLE_DISABILITIES': 'బహుళ దివ్యాంగత్వాలు, చెవుడు-అంధత్వంతో సహా',
  'field.disability.ACID_ATTACK_VICTIM': 'యాసిడ్ దాడి నుండి బయటపడినవారు',
  'field.disability.PARKINSONS_DISEASE': 'పార్కిన్సన్స్ వ్యాధి',

  'field.state.AN': 'అండమాన్ నికోబార్ దీవులు',
  'field.state.AP': 'ఆంధ్రప్రదేశ్',
  'field.state.AR': 'అరుణాచల్ ప్రదేశ్',
  'field.state.AS': 'అస్సాం',
  'field.state.BR': 'బీహార్',
  'field.state.CH': 'చండీగఢ్',
  'field.state.CT': 'ఛత్తీస్‌గఢ్',
  'field.state.DL': 'ఢిల్లీ',
  'field.state.DN': 'దాద్రా నగర్ హవేలీ మరియు డామన్ డయ్యూ',
  'field.state.GA': 'గోవా',
  'field.state.GJ': 'గుజరాత్',
  'field.state.HP': 'హిమాచల్ ప్రదేశ్',
  'field.state.HR': 'హర్యానా',
  'field.state.JH': 'ఝార్ఖండ్',
  'field.state.JK': 'జమ్మూ కాశ్మీర్',
  'field.state.KA': 'కర్ణాటక',
  'field.state.KL': 'కేరళ',
  'field.state.LA': 'లడఖ్',
  'field.state.LD': 'లక్షద్వీప్',
  'field.state.MH': 'మహారాష్ట్ర',
  'field.state.ML': 'మేఘాలయ',
  'field.state.MN': 'మణిపూర్',
  'field.state.MP': 'మధ్యప్రదేశ్',
  'field.state.MZ': 'మిజోరం',
  'field.state.NL': 'నాగాలాండ్',
  'field.state.OR': 'ఒడిశా',
  'field.state.PB': 'పంజాబ్',
  'field.state.PY': 'పుదుచ్చేరి',
  'field.state.RJ': 'రాజస్థాన్',
  'field.state.SK': 'సిక్కిం',
  'field.state.TG': 'తెలంగాణ',
  'field.state.TN': 'తమిళనాడు',
  'field.state.TR': 'త్రిపుర',
  'field.state.UP': 'ఉత్తరప్రదేశ్',
  'field.state.UT': 'ఉత్తరాఖండ్',
  'field.state.WB': 'పశ్చిమ బెంగాల్',

  'field.level.SCHOOL': 'పాఠశాల',
  'field.level.SCHOOL.sub': '9, 10, 11, 12 తరగతులు',
  'field.level.UNDERGRADUATE': 'డిగ్రీ',
  'field.level.UNDERGRADUATE.sub': 'BA, BSc, BTech వంటివి',
  'field.level.POSTGRADUATE': 'పోస్ట్ గ్రాడ్యుయేషన్',
  'field.level.POSTGRADUATE.sub': 'MA, MSc, MTech వంటివి',
  'field.level.DOCTORAL': 'డాక్టరేట్',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'పాఠశాల',
  'field.qual.SCHOOL.sub': '1 నుండి 12 తరగతులు',
  'field.qual.UNDERGRADUATE': 'డిగ్రీ',
  'field.qual.UNDERGRADUATE.sub': 'BA, BSc, BCom, BE / BTech, MBBS — మరియు డిప్లొమా లేదా ITI',
  'field.qual.POSTGRADUATE': 'పోస్ట్ గ్రాడ్యుయేషన్',
  'field.qual.POSTGRADUATE.sub': 'MA, MSc, MTech, MBA వంటివి',
  'field.qual.DOCTORAL': 'PhD / డాక్టరేట్',

  'field.subject.engineering': 'ఇంజనీరింగ్',
  'field.subject.medical': 'వైద్యం',
  'field.subject.management': 'నిర్వహణ',
  'field.subject.science': 'సైన్స్',
  'field.subject.commerce': 'వాణిజ్యం',
  'field.subject.arts': 'కళలు మరియు మానవీయ శాస్త్రాలు',
  'field.subject.vocational': 'వృత్తి విద్య',
  'field.subject.fellowship': 'ఫెలోషిప్',
  'field.subject.talent': 'ప్రతిభ',
  'field.subject.sports': 'క్రీడలు',

  'field.gender.FEMALE': 'స్త్రీ',
  'field.gender.MALE': 'పురుషుడు',
  'field.gender.TRANSGENDER': 'ట్రాన్స్‌జెండర్',
  'field.gender.UNDISCLOSED': 'చెప్పదలచుకోలేదు',
  'field.genderFilter.TRANSGENDER': 'మూడవ లింగం / ట్రాన్స్‌జెండర్',

  'field.year.below9': '9వ తరగతి కంటే కింద',
  'field.year.c9': '9వ తరగతి',
  'field.year.c10': '10వ తరగతి',
  'field.year.c11': '11వ తరగతి',
  'field.year.c12': '12వ తరగతి',
  'field.year.y1': 'మొదటి సంవత్సరం',
  'field.year.y2': 'రెండవ సంవత్సరం',
  'field.year.y3': 'మూడవ సంవత్సరం',
  'field.year.y4': 'నాల్గవ సంవత్సరం',
  'field.year.pg1': 'పీజీ మొదటి సంవత్సరం',
  'field.year.pg2': 'పీజీ రెండవ సంవత్సరం',

  'q.full_name': 'మీ పేరు ఏమిటి?',
  'q.full_name.help': 'మీ దివ్యాంగత్వ ధ్రువీకరణ పత్రంలో ఉన్నట్టుగానే. ప్రదాతలు రెండూ సరిపోలుతున్నాయా అని చూస్తారు.',
  'q.gender': 'మీ లింగం ఏమిటి?',
  'q.gender.help': 'కొన్ని ఉపకారవేతనాలు మహిళలకు మాత్రమే, లేదా ట్రాన్స్‌జెండర్ విద్యార్థులకు. చెప్పదలచుకోకపోతే వదిలేయండి.',
  'q.disability_type': 'మీ దివ్యాంగత్వం ఏమిటి?',
  'q.disability_type.help': 'మీ ధ్రువీకరణ పత్రంలో రాసినట్టుగా. చాలా ఉపకారవేతనాలు దీని ఆధారంగానే వడపోస్తాయి.',
  'q.disability_percent': 'మీ ధ్రువీకరణ పత్రంలో ఎంత శాతం ఉంది?',
  'q.disability_percent.help': '0 మరియు 100 మధ్య ఒక సంఖ్య. చాలా ఉపకారవేతనాలకు 40% లేదా అంతకంటే ఎక్కువ కావాలి.',
  'q.disability_percent.range': 'ధ్రువీకరణ పత్ర శాతం 0 మరియు 100 మధ్య ఉంటుంది.',
  'q.udid_number': 'మీ UDID నంబర్ ఏమిటి?',
  'q.udid_number.help': 'మీ UDID (ప్రత్యేక దివ్యాంగత్వ గుర్తింపు) కార్డుపై ఉన్న నంబర్. ఇంకా జారీ కాకపోతే వదిలేయండి — మీరు దేనికి అర్హులో అది మారదు, తరువాత చేర్చవచ్చు.',
  'q.date_of_birth': 'మీరు ఎప్పుడు జన్మించారు?',
  'q.date_of_birth.help': 'కొన్ని ఉపకారవేతనాలకు వయో పరిమితి ఉంటుంది.',
  'q.course_name': 'మీరు ఏమి చదువుతున్నారు?',
  'q.course_name.help': 'నమోదు చేసుకున్నప్పుడు మీరు ఎంచుకున్న కోర్సు.',
  'q.institution_name': 'మీరు ఎక్కడ చదువుతున్నారు?',
  'q.institution_name.help': 'మీ పాఠశాల, కళాశాల లేదా విశ్వవిద్యాలయం పేరు, మీ బోనఫైడ్ ధ్రువీకరణ పత్రంలో రాసినట్టుగా. ఇంకా మొదలుపెట్టకపోతే వదిలేయండి.',
  'q.institution_name.placeholder': 'మీ పాఠశాల లేదా కళాశాల పేరు',
  'q.state_code': 'మీరు ఏ రాష్ట్రంలో నివసిస్తున్నారు?',
  'q.state_code.help': 'చాలా ఉపకారవేతనాలు కొన్ని రాష్ట్రాల నివాసులకు మాత్రమే అందుబాటులో ఉంటాయి.',
  'q.annual_family_income': 'మీ కుటుంబ వార్షిక ఆదాయం ఎంత?',
  'q.annual_family_income.help': 'రూపాయలలో, మీ ఆదాయ ధ్రువీకరణ పత్రంలో ఉన్నట్టుగా. చాలా ఉపకారవేతనాలకు ఒక గరిష్ఠ పరిమితి ఉంటుంది.',
  'q.annual_family_income.range': 'ఆదాయం సున్నా కంటే తక్కువ ఉండలేదు.',
  'q.academic_percentage': 'మీ చివరి పరీక్ష మార్కులు ఎంత?',
  'q.academic_percentage.help': 'మీ మార్కుల పత్రం వాటిని ఏ విధంగా చెబుతుందో ఎంచుకుని, ఆపై సంఖ్యను టైప్ చేయండి. చాలా ఉపకారవేతనాలు కనీస మార్కులు అడుగుతాయి.',
  'field.orgKind.NGO': 'స్వచ్ఛంద సంస్థ',
  'field.orgKind.CORPORATE': 'కార్పొరేట్',
  'field.orgKind.GOVERNMENT': 'ప్రభుత్వం',
  'field.orgKind.PRIVATE': 'ప్రైవేట్',

  'field.doc.DISABILITY_CERTIFICATE': 'దివ్యాంగత్వ ధ్రువీకరణ పత్రం',
  'field.doc.UDID_CARD': 'UDID కార్డు',
  'field.doc.INCOME_CERTIFICATE': 'ఆదాయ ధ్రువీకరణ పత్రం',
  'field.doc.DOMICILE_CERTIFICATE': 'నివాస ధ్రువీకరణ పత్రం',
  'field.doc.CASTE_CERTIFICATE': 'కుల ధ్రువీకరణ పత్రం',
  'field.doc.MARKSHEET': 'మార్కుల పత్రం',
  'field.doc.ADMISSION_LETTER': 'ప్రవేశ పత్రం',
  'field.doc.BONAFIDE_CERTIFICATE': 'బోనఫైడ్ ధ్రువీకరణ పత్రం',
  'field.doc.FEE_RECEIPT': 'ఫీజు రసీదు',
  'field.doc.BANK_PASSBOOK': 'బ్యాంకు పాస్‌బుక్',
  'field.doc.IDENTITY_PROOF': 'గుర్తింపు రుజువు',
  'field.doc.PHOTOGRAPH': 'ఫొటో',

  'appl.next.SUBMITTED': 'ప్రదాత వద్ద మీ దరఖాస్తు ఉంది. తరువాత ఒక సమీక్షకుడు దాన్ని చదువుతారు.',
  'appl.next.UNDER_REVIEW': 'ఒక సమీక్షకుడు మీ దరఖాస్తును చదువుతున్నారు. సాధారణంగా ఇదే అత్యంత సుదీర్ఘమైన దశ.',
  'appl.next.INFO_REQUESTED': 'వారు మీ నుండి ఏదో అడిగారు. మీరు బదులిచ్చే వరకు మీ దరఖాస్తు వేచి ఉంటుంది.',
  'appl.next.DOCUMENT_CHECK': 'మీ దరఖాస్తు ఒక సమీక్షకుడి వద్ద ఉంది. మీ నుండి ఏమీ అవసరం లేదు.',
  'appl.next.VERIFIED': 'మీ దరఖాస్తు ఒక సమీక్షకుడి వద్ద ఉంది. మీ నుండి ఏమీ అవసరం లేదు.',
  'appl.next.SHORTLISTED': 'మీ దరఖాస్తు ఒక సమీక్షకుడి వద్ద ఉంది. తరువాత నిర్ణయం.',
  'appl.next.APPROVED': 'ఆమోదించబడింది. ప్రదాత మంజూరును నమోదు చేసి, ఆపై చెల్లింపు ఏర్పాటు చేస్తారు.',
  'appl.next.SANCTIONED': 'డబ్బు మంజూరైంది. చెల్లింపు వారి బ్యాంకు ద్వారా జరుగుతుంది.',
  'appl.next.DISBURSED': 'చెల్లింపు నమోదైంది. కొన్ని పని దినాల్లో మీ ఖాతాకు చేరకపోతే, ఫిర్యాదు చేయండి.',
  'appl.next.REJECTED': 'ఈ దరఖాస్తు విజయవంతం కాలేదు. ఇది మీ ఇతర దరఖాస్తులపై ప్రభావం చూపదు.',
  'appl.next.CLOSED': 'ఈ దరఖాస్తు పూర్తయింది.',
  'appl.next.WITHDRAWN': 'మీరు ఈ దరఖాస్తును ఉపసంహరించుకున్నారు.',
}

export default te
