/* Urdu.
 *
 * Right to left. Nothing in this file does anything about that — the direction
 * is the dir attribute i18n.tsx puts on <html>, and the layout follows from the
 * logical properties in styles.css. What matters here is only that the
 * {placeholders} keep their position in the logical order of the sentence; an
 * editor showing this file will draw them somewhere unexpected, which is the
 * bidirectional algorithm doing its job and not a mistake to correct.
 *
 * One word per term: scholarship وظیفہ, application درخواست,
 * document دستاویز, disability معذوری, verified تصدیق شدہ, eligible اہل,
 * certificate سرٹیفکیٹ, profile پروفائل.
 *
 * A pipe separates singular from plural, in that order.
 */

import type { Dict } from '../i18n-strings'

const ur: Dict = {
  'app.name': 'انڈک اے آئی وظیفہ',
  'app.tagline': 'معذور طلبہ کے لیے',
  'app.yourApplication': 'آپ کی درخواست · {title}',

  'nav.find': 'وظائف',
  'nav.how': 'یہ کیسے کام کرتا ہے',
  'nav.matches': 'میرے مماثل وظائف',
  'nav.applications': 'میری درخواستیں',
  'nav.documents': 'میری دستاویزات',
  'nav.profile': 'میری پروفائل',
  'nav.privacy': 'میرا ڈیٹا',
  'nav.account': 'میرا اکاؤنٹ',
  'nav.register': 'سائن اپ',
  'nav.language': 'زبان',
  'footer.social': 'انڈک اے آئی دیگر مقامات پر',
  'footer.sponsor': 'تعاون سے',
  'footer.copyright': 'کاپی رائٹ © {year} انڈک اے آئی | جملہ حقوق محفوظ ہیں',
  'nav.signin': 'سائن ان',
  'nav.signout': 'سائن آؤٹ',
  'nav.skip': 'مرکزی مواد پر جائیں',

  'public.title': 'وہ وظیفہ تلاش کریں جس کے آپ اہل ہیں',
  'public.lede': 'یہاں موجود ہر وظیفہ معذور طلبہ کے لیے کھلا ہے۔ دیکھنے کے لیے اکاؤنٹ کی ضرورت نہیں۔',
  'public.search': 'نام یا لفظ سے تلاش کریں',
  'public.filter.disability': 'معذوری کی قسم',
  'public.filter.qualification': 'اہلیت',
  'public.filter.state': 'آپ کی ریاست',
  'public.filter.provider': 'کون دے رہا ہے',
  'public.filter.any': 'کوئی بھی',
  'public.filter.anyDisability': 'کوئی بھی معذوری',
  'public.filter.anyQualification': 'کوئی بھی اہلیت',
  'public.filter.allStates': 'تمام ریاستیں',
  'public.filter.gender': 'جنس',
  'public.filter.anyGender': 'کوئی بھی جنس',
  'public.filter.course': 'کورس',
  'public.filter.anyCourse': 'کوئی بھی کورس',
  'public.filter.where': 'آپ کہاں پڑھتے ہیں',
  'public.filter.anyWhere': 'بھارت یا بیرونِ ملک',
  'public.filter.inIndia': 'بھارت میں',
  'public.filter.abroad': 'بیرونِ ملک تعلیم',
  'public.filters': 'فلٹر',
  'public.clear': 'ہٹائیں',
  'public.results': 'وظائف اب کھلے ہیں',
  'public.searching': 'تلاش جاری ہے…',
  'public.none': 'ان فلٹروں سے کوئی وظیفہ مطابقت نہیں رکھتا',
  'public.none.hint': 'ایک فلٹر ہٹا کر دیکھیں۔ سال بھر نئی اسکیمیں کھلتی رہتی ہیں۔',
  'public.none.clear': 'تمام فلٹر ہٹائیں',
  'public.empty': 'یہاں ابھی کوئی وظیفہ درج نہیں ہے',
  'public.empty.hint': 'دینے والے ادارے اب شامل کیے جا رہے ہیں۔ یہاں کچھ بھی اکاؤنٹ کے پیچھے نہیں — اسکیمیں درج ہونے پر آپ سائن ان کیے بغیر بھی دیکھ سکیں گے۔',
  'public.whoFor': 'یہ کس کے لیے ہے',
  'public.about': 'اس وظیفے کے بارے میں',
  'public.atAGlance': 'ایک نظر میں',
  'public.closes': 'بند ہوتا ہے',
  'public.awardUnstated': 'رقم نہیں بتائی گئی',
  'public.noClose': 'کوئی آخری تاریخ نہیں',
  'public.closesIn': '{n} دنوں میں بند',
  'public.closesToday': 'آج بند ہو رہا ہے',
  'public.closed': 'بند',
  'public.award': 'رقم',
  'public.renewable': 'ہر سال تجدید ہو سکتی ہے',
  'public.offeredBy': 'دینے والا ادارہ',
  'public.eligibility': 'اہل ہونے کے لیے',
  'public.benefits': 'فوائد',
  'public.readMore': 'مزید پڑھیں',
  'public.viewDetails': 'تفصیلات دیکھیں',
  'public.applyNow': 'ابھی درخواست دیں',
  'public.registerToApply': 'درخواست دیں',
  'public.registerToApplyHelp': 'درخواستیں آپ کے اکاؤنٹ کے ذریعے دی جاتی ہیں۔ رجسٹر کرنے پر آپ کو ہر وہ وظیفہ بھی نظر آئے گا جس کے آپ اہل ہیں۔',
  'public.closedNote': 'یہ اسکیم بند ہو چکی ہے',
  'sheet.close': 'بند کریں',
  'sheet.loading': 'وظیفے کی تفصیلات',
  'public.benefitComponent': 'مد',
  'public.benefitAmount': 'طالب علم کو کیا ملتا ہے',
  'public.whatYouGet': 'آپ کو کیا ملے گا',
  'public.eligibilityDetail': 'اہلیت تفصیل سے',
  'public.documentsRequired': 'مطلوبہ دستاویزات',
  'public.documentsHelp': 'دینے والا ادارہ یہ مانگتا ہے۔ یہ آپ یہاں اپ لوڈ نہیں کرتے۔',
  'public.howToApply': 'درخواست کیسے دیں',
  'public.importantNotes': 'جاننے کے قابل',
  'public.academicYear': 'کس سال کے لیے',
  'public.awardBasis': 'کس بنیاد پر',
  'public.basis.MERIT': 'قابلیت',
  'public.basis.NEED': 'مالی ضرورت',
  'public.basis.MERIT_CUM_MEANS': 'قابلیت اور آمدنی',
  'public.basis.CATEGORY': 'زمرہ',
  'public.basis.OTHER': 'دیگر',
  'public.cta': 'اپنے لیے وظائف تلاش کریں',
  'public.applyExternal': 'ان کی سائٹ پر درخواست دیں',
  'public.applyExternalHelp': 'ہم یہ وظیفہ اسی لیے درج کرتے ہیں تاکہ آپ اسے تلاش کر سکیں۔ اسے {org} چلاتا ہے اور درخواستیں اپنی ویب سائٹ پر ہی لیتا ہے، اس لیے یہ یہاں آپ کی درخواستوں میں نظر نہیں آئے گا۔',
  'public.applyExternalHelpPartner': '{org} یہ درخواست اپنی ویب سائٹ پر ہی لیتا ہے، اس لیے یہ یہاں آپ کی درخواستوں میں نظر نہیں آئے گی۔',
  'common.newTab': 'نئے ٹیب میں کھلتا ہے',
  'public.applyHelp': 'ہم پہلے آپ کی پروفائل اور دستاویزات اس وظیفے کے مقابلے میں جانچتے ہیں اور بتاتے ہیں کہ کچھ رہ تو نہیں گیا۔ آپ کی تصدیق سے پہلے کچھ نہیں بھیجا جاتا۔',
  'public.ctaHelp': 'اپنے بارے میں ایک بار بتائیں اور ہم آپ کو ہر وہ وظیفہ دکھائیں گے جس کے آپ اہل ہیں۔',
  'public.back': 'تمام وظائف پر واپس',
  'notFound.title': 'ہمیں یہ صفحہ نہیں ملا',
  'notFound.body': 'ہو سکتا ہے پتے میں ٹائپنگ کی غلطی ہو، یا صفحہ کہیں اور منتقل ہو گیا ہو۔',
  'notFound.home': 'ہوم صفحے پر جائیں',

  'nav.dashboard': 'ڈیش بورڈ',
  'dash.title': 'آپ کا ڈیش بورڈ',
  'dash.lede': 'آپ کے وظائف، درخواستیں اور دستاویزات، سب ایک جگہ۔',
  'dash.matches': 'جن وظائف کے لیے آپ درخواست دے سکتے ہیں',
  'dash.matchesHint': 'آپ کی دی ہوئی تفصیلات کی بنیاد پر۔',
  'dash.matchesBlocked': '{n} آپ سے ایک اور تفصیل کے منتظر ہیں۔',
  'dash.applications': 'جاری درخواستیں',
  'dash.applicationsHint': '{approved} منظور · {rejected} کامیاب نہیں',
  'dash.applicationsNone': 'ابھی کچھ نہیں بھیجا گیا۔',
  'dash.documents': 'تصدیق شدہ دستاویزات',
  'dash.documentsHint': 'ایک بار جانچی گئیں۔ ہر درخواست میں کام آتی ہیں۔',
  'dash.funding': 'اب تک ملا',
  'dash.fundingHint': 'کل {sanctioned} منظور۔',
  'dash.recent': 'حالیہ درخواستیں',
  'dash.noApplications': 'ابھی کوئی درخواست نہیں',
  'dash.noApplicationsHint': 'آپ جس کے لیے بھی درخواست دیں گے وہ یہاں نظر آئے گی۔',
  'dash.findScholarships': 'وظائف تلاش کریں',
  'dash.profileTitle': 'آپ کی پروفائل',
  'dash.toGo': '{n}% باقی',
  'dash.allApplications': 'سب دیکھیں',
  'dash.matchesGo': 'اپنے مماثل وظائف دیکھیں',
  'dash.applicationsGo': 'اپنی درخواستیں دیکھیں',
  'dash.documentsGo': 'دستاویزات سنبھالیں',
  'dash.draftsTitle': '{n} درخواست نہیں بھیجی گئی | {n} درخواستیں نہیں بھیجی گئیں',
  'dash.draftsBody': 'درخواست شروع کرنے سے وہ بھیجی نہیں جاتی۔ وظیفہ بند ہونے سے پہلے مکمل کریں۔',
  'dash.draftsAction': 'ابھی مکمل کریں',
  'dash.expiringTitle': '{n} دستاویز کی میعاد جلد ختم ہو رہی ہے | {n} دستاویزات کی میعاد جلد ختم ہو رہی ہے',
  'dash.expiringBody': 'ہر درخواست میں کام آئے، اس لیے اسے ابھی بدل دیں۔ | ہر درخواست میں کام آئیں، اس لیے انہیں ابھی بدل دیں۔',
  'dash.expiringAction': 'دستاویزات دیکھیں',

  'auth.title': 'اپنا موبائل نمبر درج کریں',
  'auth.phone': 'موبائل نمبر',
  'auth.phoneHint': 'ہم اس نمبر پر ایس ایم ایس سے 6 ہندسوں کا کوڈ بھیجیں گے۔ ہر بار یہی نمبر آپ کو سائن ان کراتا ہے۔',
  'auth.phoneMissing': 'آگے بڑھنے کے لیے اپنا موبائل نمبر درج کریں۔',
  'auth.phoneInvalid': 'یہ ٹھیک نہیں لگ رہا۔ بھارتی موبائل نمبر 10 ہندسوں کے ہوتے ہیں اور 6، 7، 8 یا 9 سے شروع ہوتے ہیں۔',
  'auth.phonePlaceholder': '98765 43210',
  'auth.oneDoor': 'نئے ہوں یا واپس آ رہے ہوں، وہی نمبر کام کرتا ہے۔ اگر آپ کا اکاؤنٹ نہیں تو ہم بنا دیتے ہیں۔',
  'auth.stepOf': 'مرحلہ {n} / 2 · {name}',
  'auth.stepPhone': 'آپ کا نمبر',
  'auth.stepCode': 'آپ کا OTP کوڈ',
  'auth.privacy': 'آپ کا نمبر صرف آپ کو سائن ان کرانے کے لیے استعمال ہوتا ہے، کسی اور کام کے لیے نہیں۔ یاد رکھنے کے لیے کوئی پاس ورڈ نہیں ہے۔',
  'auth.sendCode': 'کوڈ بھیجیں',
  'auth.sending': 'بھیجا جا رہا ہے…',
  'auth.checking': 'جانچا جا رہا ہے…',
  'auth.welcomeBack': 'دوبارہ خوش آمدید۔ سائن ان کرنے کے لیے کوڈ درج کریں۔',
  'auth.newHere': 'کوڈ درج کرتے ہی ہم آپ کا اکاؤنٹ بنا دیں گے۔',
  'auth.codeTitle': 'ہم نے جو کوڈ بھیجا ہے وہ درج کریں',
  'auth.code': '6 ہندسوں کا کوڈ',
  'auth.codeHint': 'پیغام عام طور پر چند سیکنڈ میں آ جاتا ہے۔',
  'auth.noCode': 'ابھی تک پیغام نہیں آیا؟ کوئی اور طریقہ آزمائیں:',
  'auth.verify': 'تصدیق کریں',
  'auth.viaSms': 'ایس ایم ایس سے بھیجیں',
  'auth.viaWhatsapp': 'واٹس ایپ پر بھیجیں',
  'auth.viaVoice': 'کوڈ بتانے کے لیے مجھے فون کریں',
  'auth.resentVia.sms': 'ایس ایم ایس سے بھیج دیا۔ آنے میں کچھ وقت لگ سکتا ہے۔',
  'auth.resentVia.whatsapp': 'واٹس ایپ پر بھیج دیا۔ پیغام کے لیے واٹس ایپ دیکھیں۔',
  'auth.resentVia.voice': 'کوڈ بتانے کے لیے ابھی فون کر رہے ہیں۔ سننے کے لیے فون اٹھائیں۔',
  'auth.resendIn': '{n} سیکنڈ میں دوبارہ بھیجیں',
  'auth.changeNumber': 'دوسرا نمبر استعمال کریں',
  'auth.change': 'بدلیں',

  'profile.complete': '{n}% مکمل',
  'profile.viewLede': 'آپ نے ہمیں جو کچھ بتایا ہے۔ کوئی بھی جواب بدلیں اور اس کے بعد ہر وظیفے کے لیے وہی استعمال ہوگا۔',
  'profile.notAnswered': 'ابھی جواب نہیں دیا',
  'profile.verified': 'تصدیق شدہ',
  'profile.continue': 'جہاں چھوڑا تھا وہیں سے جاری رکھیں',
  'profile.start': 'اپنی پروفائل شروع کریں',
  'profile.saved': 'محفوظ ہو گیا',

  'match.title': 'آپ کے لیے وظائف',
  'match.lede': 'آپ کی پروفائل سے جانچے گئے۔ جن کے لیے درخواست دے سکتے ہیں وہ پہلے۔',
  'match.eligible': 'آپ اہل ہیں',
  'match.likely': 'آپ غالباً اہل ہیں',
  'match.blocked': 'پہلے ایک کام',
  'match.actionable': 'آپ کے لیے کھلے',
  'match.actionableHelp': 'کچھ کے لیے درخواست سے پہلے ایک دستاویز درکار ہو سکتی ہے۔',
  'match.ineligible': 'آپ کے لیے کھلے نہیں',
  'match.eligibleHelp': 'ہم نے جو کچھ جانچا وہ سب تصدیق شدہ ہے۔',
  'match.likelyHelp': 'آپ نے جو بتایا اس کی بنیاد پر۔ تصدیق کرا لینے سے آپ کی درخواست مضبوط ہوتی ہے۔',
  'match.blockedHelp': 'آپ قریب ہیں۔ یہ کر لیں اور درخواست دے سکیں گے۔',
  'match.ineligibleHelp': 'یہ اسکیم ایسی چیز مانگتی ہے جو آپ بدل نہیں سکتے۔',
  'match.apply': 'درخواست دیں',
  'match.applied': 'آپ درخواست دے چکے ہیں',
  'match.none': 'ابھی کوئی مماثل وظیفہ نہیں',
  'match.noneHint': 'اپنی پروفائل مکمل کریں اور ہم آپ کے لیے ہر وظیفہ جانچیں گے۔',
  'match.figQualify': 'آپ اہل ہیں',
  'match.figStep': 'ایک قدم دور',
  'match.figClosing': 'جلد بند',
  'match.figNo': 'آپ کے لیے کھلے نہیں',
  'match.filterLabel': 'کون سے وظائف دکھائے جائیں',
  'match.filterAll': 'سب',
  'match.filterQualify': 'آپ اہل ہیں',
  'match.filterStep': 'ایک قدم دور',
  'match.filterClosing': 'جلد بند',
  'match.filterNo': 'آپ کے لیے کھلے نہیں',
  'match.filterEmpty': 'اس گروہ میں کچھ نہیں۔ “سب” آزمائیں۔',
  'match.moreWithProfile': 'آپ جتنا بھرتے جائیں گے اتنے مزید وظائف نظر آئیں گے۔',
  'match.youQualify': 'آپ کی پروفائل کے مطابق آپ شرائط پوری کرتے ہیں۔',
  'match.yesTitle': 'آپ درخواست دے سکتے ہیں',
  'match.blockedTitle': 'پہلے ایک کام',
  'match.noTitle': 'اہل نہیں',
  'match.appliedTitle': 'پہلے ہی بھیجی جا چکی',
  'match.seeDetails': 'قواعد دیکھیں',
  'match.learnMore': 'مزید جانیں',
  'match.runBy': '{kind} چلاتا ہے',
  'match.sortBy': 'ترتیب',
  'match.sortRecommended': 'تجویز کردہ',
  'match.sortClosing': 'سب سے پہلے بند ہونے والے',
  'match.sortAward': 'سب سے بڑی رقم',
  'match.applyAway': 'ان کی سائٹ پر درخواست دیں',
  'match.applyHere': 'یہیں درخواست دیں',
  'match.notOpenToYou': 'موجودہ حالت میں آپ کے لیے کھلا نہیں۔',
  'match.working': 'اب کھلی کوئی اسکیم آپ کی دی ہوئی تفصیلات سے مطابقت نہیں رکھتی۔ پروفائل میں مزید شامل کرنے سے یہ بدلتا ہے۔',

  'doc.title': 'آپ کی دستاویزات',
  'doc.lede': 'ایک دستاویز ایک بار اپ لوڈ کریں۔ آپ جس بھی وظیفے کے لیے درخواست دیں وہ اسے استعمال کر سکتا ہے — آپ سے دوبارہ نہیں مانگی جائے گی۔',
  'doc.upload': 'دستاویز شامل کریں',
  'doc.type': 'یہ کون سی دستاویز ہے؟',
  'doc.file': 'فائل منتخب کریں',
  'doc.fileHint': 'پی ڈی ایف یا صاف تصویر۔ 10 ایم بی تک۔',
  'doc.verified': 'تصدیق شدہ',
  'doc.verifiedBy': '{org} نے تصدیق کی',
  'doc.pending': 'تصدیق کے انتظار میں',
  'doc.expired': 'تصدیق کی میعاد ختم',
  'doc.expiring': '{n} دن میں میعاد ختم',
  'doc.validUntil': '{date} تک کارآمد',
  'doc.none': 'آپ نے ابھی کوئی دستاویز شامل نہیں کی',
  'doc.uploading': 'اپ لوڈ ہو رہا ہے…',
  'doc.remove': 'ہٹائیں',
  'doc.removing': 'ہٹایا جا رہا ہے…',

  'apply.title': 'درخواست دیں',
  'apply.consent': 'میری تفصیلات اس ادارے کے ساتھ ساجھا کریں',
  'apply.consentBody': 'فیصلہ کرنے کے لیے اس وظیفے کو جو درکار ہے صرف وہی وہ دیکھیں گے: {fields}. آپ کی دستاویزات کس نے دیکھیں یہ آپ کبھی بھی دیکھ سکتے ہیں۔',
  'apply.consentBodyNoDocs': 'فیصلہ کرنے کے لیے اس وظیفے کو جو درکار ہے صرف وہی وہ دیکھیں گے، اور کچھ نہیں۔ آپ کی تفصیلات کس نے دیکھیں یہ آپ کبھی بھی دیکھ سکتے ہیں۔',
  'apply.submit': 'میری درخواست بھیجیں',
  'apply.submitting': 'بھیجا جا رہا ہے…',
  'apply.blocked': 'آپ ابھی درخواست نہیں دے سکتے',
  'apply.needProfile': 'پہلے آپ کی پروفائل',
  'apply.needProfileHint': 'درخواست آپ کی پروفائل سے بھیجی جاتی ہے، اس لیے درخواست سے پہلے وہ درکار ہے۔ اس میں چند ہی منٹ لگتے ہیں، اور آپ نے پہلے جو بتایا ہے وہ بھرا ہوا ملے گا۔',
  'apply.elsewhereTitle': 'اس کی درخواست اسپانسر کی ویب سائٹ پر ہوتی ہے',
  'apply.elsewhereBody': 'ہم یہ وظیفہ اسی لیے درج کرتے ہیں تاکہ آپ اسے تلاش کر سکیں، اور درخواستیں اسپانسر خود لیتے ہیں۔ آپ نے ہمیں جو بتایا ہے وہ محفوظ رہتا ہے، اور جو وظائف ہم چلاتے ہیں ان کے لیے پہلے سے بھرا ہوتا ہے۔',
  'apply.elsewhereBodyPartner': 'یہ وظیفہ یہیں چلتا ہے، مگر اسپانسر درخواستیں اپنی ویب سائٹ پر لیتے ہیں۔ آپ نے ہمیں جو بتایا ہے وہ محفوظ رہتا ہے، اور جو درخواستیں ہمیں براہِ راست ملتی ہیں ان کے لیے پہلے سے بھرا ہوتا ہے۔',
  'apply.bundleTitle': 'اپنی دستاویزات ساتھ لے جائیں',
  'apply.bundleBody': 'یہ وظیفہ جو دستاویزات مانگتا ہے انہیں ہم ایک فائل میں رکھ سکتے ہیں، ان کی ویب سائٹ پر اپ لوڈ کرنے کے لیے تیار۔ وہ جو چاہتے ہیں اور ہمارے پاس ابھی نہیں، وہ بھی اس میں درج ہوتا ہے۔',
  'apply.bundleAction': 'میری دستاویزات ڈاؤن لوڈ کریں',
  'apply.bundleWorking': 'تیار کیا جا رہا ہے…',
  'apply.bundleDone': 'آپ کی دستاویزات ڈاؤن لوڈ ہو گئی ہیں۔',
  'apply.docs': 'اس وظیفے کے لیے درکار دستاویزات',

  'appl.title': 'آپ کی درخواستیں',
  'appl.none': 'آپ نے ابھی کسی کے لیے درخواست نہیں دی',
  'appl.noneHint': 'جن وظائف کے آپ اہل ہیں انہیں تلاش کرنے کے لیے اپنے مماثل وظائف دیکھیں۔',
  'appl.reference': 'حوالہ',
  'appl.whatNext': 'آگے کیا ہوگا',
  'appl.history': 'تاریخ',
  'appl.needsYou': 'انہیں آپ سے کچھ درکار ہے',
  'track.label': 'اس درخواست کی پیش رفت',
  'track.sent': 'بھیجی گئی',
  'track.review': 'جائزہ',
  'track.decision': 'فیصلہ',
  'track.doneSr': 'مکمل',
  'track.currentSr': 'ابھی جاری ہے',
  'track.todoSr': 'شروع نہیں ہوا',
  'appl.sentOn': '{when} بھیجی گئی',
  'appl.decidedOn': '{when} فیصلہ ہوا',
  'appl.outcomeApproved': 'مل گیا',
  'appl.outcomeRejected': 'اس بار نہیں ملا',
  'appl.outcomeWithdrawn': 'آپ نے اسے واپس لے لیا',
  'appl.inProgress': 'ادارے کے پاس',
  'appl.outcome': 'نتیجہ',
  'appl.award': 'رقم',
  'appl.applied': 'درخواست دی گئی',
  'appl.decided': 'فیصلہ ہوا',
  'appl.automatic': 'خودکار',
  'appl.noHistory': 'ابھی کچھ نہیں ہوا۔',

  'ref.heading': 'ان کی ویب سائٹ پر بھیجی گئی',
  'ref.blurb': 'ان کی درخواست دینے والے ادارے کی اپنی سائٹ پر ہوتی ہے، اس لیے کیا ہوا یہ ہم نہیں دیکھ سکتے۔ ہمیں بتائیں اور ہم اسے باقیوں کے ساتھ رکھ لیں گے۔',
  'ref.sentOn': 'آپ نے اسے {when} کھولا تھا',
  'ref.again': 'کل {times} بار',
  'ref.open': 'ان کی سائٹ دوبارہ کھولیں',
  'ref.what': 'کیا ہوا؟',
  'ref.APPLIED': 'میں نے درخواست دی',
  'ref.AWARDED': 'مجھے مل گیا',
  'ref.NOT_AWARDED': 'مجھے نہیں ملا',
  'ref.DID_NOT_APPLY': 'میں نے درخواست نہیں دی',
  'ref.saidAPPLIED': 'آپ نے درخواست دی',
  'ref.saidAWARDED': 'آپ کو مل گیا',
  'ref.saidNOT_AWARDED': 'آپ کو نہیں ملا',
  'ref.saidDID_NOT_APPLY': 'آپ نے درخواست نہیں دی',
  'ref.youSaid': 'آپ نے ہمیں بتایا: {what}',
  'ref.change': 'بدلیں',

  'privacy.title': 'آپ کا ڈیٹا',
  'privacy.lede': 'ہمارے پاس کیا ہے، کس نے دیکھا ہے، اور اسے واپس کیسے لیں۔',
  'privacy.access': 'آپ کی دستاویزات کس نے دیکھی ہیں',
  'privacy.accessNone': 'آپ کے اپنے اکاؤنٹ کے باہر کسی نے آپ کی دستاویزات نہیں کھولیں۔',
  'privacy.consents': 'آپ نے کیا ساجھا کرنے کی رضامندی دی ہے',
  'privacy.withdraw': 'واپس لیں',
  'privacy.withdrawing': 'واپس لی جا رہی ہے…',
  'privacy.export': 'ہمارے پاس جو کچھ ہے سب ڈاؤن لوڈ کریں',
  'privacy.exporting': 'آپ کی نقل تیار کی جا رہی ہے…',
  'privacy.exportBody': 'آپ کے ڈیٹا کی مکمل، مشین سے پڑھی جانے والی نقل۔',
  'privacy.erase': 'میرا ڈیٹا مٹائیں',
  'privacy.erasing': 'درخواست کی جا رہی ہے…',
  'privacy.eraseBody': 'آپ کو دیے گئے کسی بھی وظیفے کا ریکارڈ ہمیں رکھنا پڑتا ہے۔ باقی سب ہٹا دیا جاتا ہے۔',
  'auth.closedTitle': 'آپ کا اکاؤنٹ اس وقت بند ہے۔',
  'auth.closedHelp': 'مدد چاہیے؟ ہماری سپورٹ ٹیم آپ کو سمجھنے میں مدد کر سکتی ہے ',
  'auth.closedSoon': 'مدد طلب کریں (جلد)',
  'reg.district': 'ضلع',
  'reg.districtHint': 'آپ کے علاقے میں چلنے والی اسکیموں سے ملانے میں مدد کرتا ہے۔',
  'privacy.requested': 'درخواست کی گئی',
  'privacy.window': 'ابھی کچھ نہیں مٹایا گیا',
  'privacy.windowBody': 'آپ کا ڈیٹا {date} کو مٹا دیا جائے گا۔ تب تک آپ ',
  'privacy.cancel': 'یہ درخواست منسوخ کریں',
  'privacy.cancelling': 'منسوخ کی جا رہی ہے…',
  'privacy.cancelled': 'آپ کی درخواست منسوخ کر دی گئی ہے۔ کچھ نہیں مٹایا گیا۔',

  'common.loading': 'لوڈ ہو رہا ہے',
  'common.retry': 'دوبارہ کوشش کریں',
  'common.required': 'لازمی',
  'common.optional': 'اختیاری',
  'common.error': 'کچھ غلط ہو گیا',
  'common.offline': 'آپ آف لائن ہیں۔ آپ کا کام اس آلے پر محفوظ ہے۔',

  'slides.lead.was': '',
  'slides.lead.able': 'صلاحیت سے',
  'slides.lead.dist': 'امتیاز تک',
  'slides.lead.body': 'ہر وہ وظیفہ جس کے آپ اہل ہیں — سرکاری اور نجی — آپ کی پروفائل سے ملا کر، آپ کی زبان میں، ایک جگہ۔',
  'slides.lead.free': 'بالکل مفت',
  'slides.lead.languages': '14 زبانیں',
  'slides.lead.support': 'ہر قدم پر ذاتی مدد',
  'slides.label': 'اعلانات',
  'slides.position': '{total} میں سے {n}',
  'slides.goto': '{name} دکھائیں',
  'slides.watch': 'ویڈیو دیکھیں',
  'slides.external': 'دوسری ویب سائٹ کھولتا ہے',

  'home.title': 'معذور طلبہ کے لیے وظائف، ایک جگہ',
  'home.lede': 'اپنے بارے میں ایک بار بتائیں۔ ہم یہاں کے ہر وظیفے سے آپ کو جانچتے ہیں اور بتاتے ہیں کہ آپ کن کے اہل ہیں — اور باقی کے لیے ٹھیک ٹھیک کیا کم ہے۔',
  'home.search': 'وظائف تلاش کریں',
  'home.searchPlaceholder': 'جیسے: انجینئرنگ، دہلی، پوسٹ میٹرک',
  'home.searchGo': 'تلاش کریں',
  'home.browseAll': 'تمام وظائف دیکھیں',
  'home.openNow': 'وظائف اب کھلے ہیں',
  'home.noAccount': 'دیکھنے کے لیے اکاؤنٹ کی ضرورت نہیں۔',
  'home.openNone': 'یہاں ابھی کوئی وظیفہ درج نہیں ہے۔',
  'home.openNoneBody': 'فہرست اب بھری جا رہی ہے۔ یہاں کچھ بھی اکاؤنٹ کے پیچھے نہیں — اسکیمیں درج ہونے پر آپ سائن ان کیے بغیر بھی دیکھ سکیں گے۔',
  'home.how': 'یہ کیسے کام کرتا ہے',
  'home.howLede': 'رجسٹر کرنے کے لیے ایک موبائل نمبر اور اس پر بھیجا گیا کوڈ چاہیے۔ کوئی پاس ورڈ نہیں، اور پہلے بھرنے کے لیے کوئی سائن اپ فارم بھی نہیں۔',
  'home.step1': 'رجسٹر دبائیں',
  'home.step1Body': 'اس صفحے کے اوپر۔ اگر پہلے آ چکے ہیں تو ساتھ والا لاگ ان استعمال کریں — دونوں میں وہی نمبر کام کرتا ہے۔',
  'home.step2': 'اپنا موبائل نمبر درج کریں',
  'home.step2Body': 'دس ہندسے، +91 پہلے سے بھرا ہوا۔ اس نمبر پر 6 ہندسوں کا کوڈ جاتا ہے۔',
  'home.step3': 'کوڈ درج کریں',
  'home.step3Body': 'چھ ہندسے ٹائپ کریں اور آپ اندر ہیں۔ اگر کوئی پیغام نہ آئے تو کوڈ واٹس ایپ پر مانگیں، یا ہمیں فون کر کے پڑھ کر سنانے کو کہیں۔',
  'home.step4': 'اپنی تفصیلات بھریں',
  'home.step4Body': 'آپ کا نام، آپ کا سرٹیفکیٹ اور آپ کہاں پڑھتے ہیں — ایک وقت میں ایک سوال، اور ہر جواب دیتے ہی محفوظ ہو جاتا ہے۔',
  'home.step5': 'اپنی دستاویزات اپ لوڈ کریں',
  'home.step5Body': 'معذوری سرٹیفکیٹ، یو ڈی آئی ڈی کارڈ، آمدنی کا سرٹیفکیٹ اور باقی۔ ہر ایک صرف ایک بار، ہر وظیفے کے لیے الگ سے نہیں۔',
  'home.step6': 'اپنے مماثل وظائف دیکھیں',
  'home.step6Body': 'میرے مماثل وظائف وہ وظائف دکھاتا ہے جن کے آپ اہل ہیں — اور جہاں کوئی آپ کے لیے بند ہے، وہاں وجہ بتاتا ہے۔',
  'home.step7': 'درخواست دیں',
  'home.step7Body': 'جو چاہیں منتخب کریں۔ آپ کی تفصیلات اور دستاویزات درخواست کے ساتھ جاتی ہیں۔',
  'home.assure': 'جاننے کے قابل',
  'home.assure1': 'یاد رکھنے کے لیے کوئی پاس ورڈ نہیں',
  'home.assure2': 'الگ کوئی رجسٹریشن فارم نہیں',
  'home.assure3': 'آپ رک کر بعد میں مکمل کر سکتے ہیں',
  'home.help': 'کسی مرحلے پر اٹک گئے؟',
  'home.helpBody': 'فون کریں، کوئی آپ کو پار کرا دے گا۔',
  'home.helpCall': '{number} پر فون کریں',
  'home.closing': 'جلد بند',
  'home.closingLede': 'پہلے ان کے لیے درخواست دیں۔',
  'home.closingNext': 'اگلی آخری تاریخیں',
  'home.closingNextLede': 'سب سے پہلے بند ہونے والے تین۔',
  'home.allDeadlines': 'تمام وظائف دیکھیں',
  'home.browse': 'اس کے مطابق دیکھیں',
  'home.browseWho': 'کون دے رہا ہے',
  'home.browseLevel': 'آپ کی تعلیم کا درجہ',
  'home.cta': 'اپنے مماثل وظائف دیکھنے کے لیے تیار ہیں؟',
  'home.ctaBody': 'اکاؤنٹ بنانے کے لیے ایک موبائل نمبر یا ای میل پتہ چاہیے۔ اور کچھ نہیں۔',
  'home.ctaButton': 'اکاؤنٹ بنائیں',
  'home.signedInCta': 'دیکھیں آپ کس کے اہل ہیں',

  'reg.title': 'وظائف تلاش کرنے کے لیے رجسٹر کریں',
  'reg.editTitle': 'اپنی تفصیلات تازہ کریں',
  'reg.requiredNote': '* والے تمام خانے لازمی ہیں۔',
  'reg.personal': 'ذاتی تفصیلات',
  'reg.disability': 'معذوری کی تفصیلات',
  'reg.education': 'تعلیم کی تفصیلات',
  'reg.name': 'پورا نام',
  'reg.namePlaceholder': 'اپنا پورا نام لکھیں',
  'reg.phoneHint': 'ہم اس نمبر پر 6 ہندسوں کا کوڈ بھیجتے ہیں۔ ہر بار یہی نمبر آپ کو سائن ان کراتا ہے۔',
  'reg.sendOtp': 'او ٹی پی بھیجیں',
  'reg.otpPlaceholder': '6 ہندسوں کا او ٹی پی لکھیں',
  'reg.verified': 'فون نمبر تصدیق شدہ',
  'reg.verifyFirst': 'رجسٹریشن مکمل کرنے کے لیے اپنے فون نمبر کی تصدیق کریں۔',
  'reg.email': 'ای میل',
  'reg.emailHint': 'تاکہ ہم آخری تاریخ یاد دلا سکیں۔ ہم اسے کبھی ساجھا نہیں کرتے۔',
  'reg.emailPlaceholder': 'your.email@example.com',
  'reg.gender': 'جنس',
  'reg.genderHint': '(کچھ وظائف صرف خواتین یا ٹرانس جینڈر طلبہ کے لیے ہیں)',
  'reg.udid': 'یو ڈی آئی ڈی نمبر',
  'reg.udidHint': 'آپ کے یو ڈی آئی ڈی (منفرد معذوری شناخت) کارڈ پر لکھا نمبر۔',
  'reg.udidPlaceholder': 'اپنا یو ڈی آئی ڈی نمبر لکھیں',
  'reg.certificate': 'یو ڈی آئی ڈی سرٹیفکیٹ اپ لوڈ کریں',
  'reg.certificateHint': 'پی ڈی ایف یا تصویر، 5 ایم بی یا اس سے کم۔',
  'reg.fileType': 'وہ فائل پی ڈی ایف، جے پی ای جی یا پی این جی ہونی چاہیے۔',
  'reg.fileSize': 'وہ فائل 5 ایم بی سے بڑی ہے۔ فون سے لی گئی تصویر عام طور پر چھوٹی ہوتی ہے اگر آپ اسے کھینچنے کے بجائے اسکین کریں۔',
  'reg.fileLater': 'آپ کی رجسٹریشن ہو گئی اور تفصیلات محفوظ ہیں۔ سرٹیفکیٹ اپ لوڈ نہیں ہوا — اسے میری دستاویزات سے شامل کر دیں، اور کچھ دوبارہ نہیں کرنا۔',
  'reg.disabilityType': 'معذوری کی قسم',
  'reg.percent': 'معذوری کا فیصد',
  'reg.percentHint': 'آپ کے سرٹیفکیٹ پر لکھا عدد۔ بہت سے وظائف کے لیے 40% یا اس سے زیادہ چاہیے۔',
  'reg.percentPlaceholder': 'جیسے 40',
  'reg.percentRange': 'سرٹیفکیٹ کا فیصد 0 اور 100 کے درمیان مکمل عدد ہوتا ہے۔',
  'reg.state': 'ریاست',
  'reg.statePlaceholder': 'اپنی ریاست تلاش کرنے کے لیے ٹائپ کریں…',
  'reg.program': 'اپنا کورس منتخب کریں',
  'reg.graduation': 'گریجویشن',
  'reg.postgraduation': 'پوسٹ گریجویشن / ماسٹرز',
  'reg.year': 'سال منتخب کریں',
  'reg.yearAfterProgram': 'پہلے اپنا کورس منتخب کریں',
  'reg.institution': 'اسکول / کالج کا نام',
  'reg.institutionPlaceholder': 'اپنے ادارے کا نام لکھیں',
  'reg.required': 'یہ ضروری ہے۔',
  'reg.fix': 'کچھ جوابات پر توجہ چاہیے۔ پہلا نیچے منتخب ہے۔',
  'reg.cta': 'رجسٹر کریں اور وظائف تلاش کریں',
  'reg.saveChanges': 'تبدیلیاں محفوظ کریں',
  'reg.saving': 'محفوظ کیا جا رہا ہے…',
  'reg.done': 'رجسٹریشن ہو گئی۔ آپ کے وظائف تلاش کیے جا رہے ہیں۔',
  'reg.doneTitle': 'آپ کی رجسٹریشن ہو گئی ہے',
  'reg.already': 'پہلے سے رجسٹرڈ ہیں؟',
  'reg.login': 'او ٹی پی سے لاگ ان',
  'nav.registerCta': 'رجسٹر',
  'nav.loginCta': 'لاگ ان',
  'profile.edit': 'اپنی تفصیلات تازہ کریں',
  'field.disability.BLINDNESS': 'نابینا پن',
  'field.disability.LOW_VISION': 'کم بینائی',
  'field.disability.LEPROSY_CURED': 'جذام (شفایاب)',
  'field.disability.HEARING_IMPAIRMENT': 'سماعت کی کمزوری',
  'field.disability.LOCOMOTOR_DISABILITY': 'حرکت کی معذوری',
  'field.disability.DWARFISM': 'پستہ قدی',
  'field.disability.INTELLECTUAL_DISABILITY': 'ذہنی معذوری',
  'field.disability.MENTAL_ILLNESS': 'نفسیاتی بیماری',
  'field.disability.AUTISM_SPECTRUM_DISORDER': 'آٹزم اسپیکٹرم ڈس آرڈر',
  'field.disability.CEREBRAL_PALSY': 'دماغی فالج',
  'field.disability.MUSCULAR_DYSTROPHY': 'پٹھوں کی کمزوری',
  'field.disability.CHRONIC_NEUROLOGICAL_CONDITION': 'دیرینہ اعصابی حالت',
  'field.disability.SPECIFIC_LEARNING_DISABILITY': 'مخصوص تعلیمی معذوری',
  'field.disability.MULTIPLE_SCLEROSIS': 'ملٹیپل سکلیروسس',
  'field.disability.SPEECH_AND_LANGUAGE_DISABILITY': 'گویائی اور زبان کی معذوری',
  'field.disability.THALASSEMIA': 'تھیلیسیمیا',
  'field.disability.HAEMOPHILIA': 'ہیموفیلیا',
  'field.disability.SICKLE_CELL_DISEASE': 'سکل سیل کی بیماری',
  'field.disability.MULTIPLE_DISABILITIES': 'متعدد معذوریاں، بشمول سماعت و بینائی کی معذوری',
  'field.disability.ACID_ATTACK_VICTIM': 'تیزاب حملے سے بچ جانے والا',
  'field.disability.PARKINSONS_DISEASE': 'پارکنسنز کی بیماری',

  'field.state.AN': 'انڈمان اور نکوبار جزائر',
  'field.state.AP': 'آندھرا پردیش',
  'field.state.AR': 'اروناچل پردیش',
  'field.state.AS': 'آسام',
  'field.state.BR': 'بہار',
  'field.state.CH': 'چندی گڑھ',
  'field.state.CT': 'چھتیس گڑھ',
  'field.state.DL': 'دہلی',
  'field.state.DN': 'دادرا اور نگر حویلی اور دمن اور دیو',
  'field.state.GA': 'گوا',
  'field.state.GJ': 'گجرات',
  'field.state.HP': 'ہماچل پردیش',
  'field.state.HR': 'ہریانہ',
  'field.state.JH': 'جھارکھنڈ',
  'field.state.JK': 'جموں و کشمیر',
  'field.state.KA': 'کرناٹک',
  'field.state.KL': 'کیرالہ',
  'field.state.LA': 'لداخ',
  'field.state.LD': 'لکشدیپ',
  'field.state.MH': 'مہاراشٹر',
  'field.state.ML': 'میگھالیہ',
  'field.state.MN': 'منی پور',
  'field.state.MP': 'مدھیہ پردیش',
  'field.state.MZ': 'میزورم',
  'field.state.NL': 'ناگالینڈ',
  'field.state.OR': 'اوڈیشہ',
  'field.state.PB': 'پنجاب',
  'field.state.PY': 'پڈوچیری',
  'field.state.RJ': 'راجستھان',
  'field.state.SK': 'سکم',
  'field.state.TG': 'تلنگانہ',
  'field.state.TN': 'تمل ناڈو',
  'field.state.TR': 'تریپورہ',
  'field.state.UP': 'اتر پردیش',
  'field.state.UT': 'اتراکھنڈ',
  'field.state.WB': 'مغربی بنگال',

  'field.level.SCHOOL': 'اسکول',
  'field.level.SCHOOL.sub': 'جماعت 9، 10، 11، 12',
  'field.level.UNDERGRADUATE': 'گریجویشن',
  'field.level.UNDERGRADUATE.sub': 'BA، BSc، BTech اور اسی طرح کے',
  'field.level.POSTGRADUATE': 'پوسٹ گریجویشن',
  'field.level.POSTGRADUATE.sub': 'MA، MSc، MTech اور اسی طرح کے',
  'field.level.DOCTORAL': 'ڈاکٹریٹ',
  'field.level.DOCTORAL.sub': 'PhD',

  'field.qual.SCHOOL': 'اسکول',
  'field.qual.SCHOOL.sub': 'جماعت 1 سے 12',
  'field.qual.UNDERGRADUATE': 'گریجویشن',
  'field.qual.UNDERGRADUATE.sub': 'BA، BSc، BCom، BE / BTech، MBBS — اور ڈپلوما یا ITI',
  'field.qual.POSTGRADUATE': 'پوسٹ گریجویشن',
  'field.qual.POSTGRADUATE.sub': 'MA، MSc، MTech، MBA اور اسی طرح کے',
  'field.qual.DOCTORAL': 'PhD / ڈاکٹریٹ',

  'field.subject.engineering': 'انجینئرنگ',
  'field.subject.medical': 'طب',
  'field.subject.management': 'انتظامیہ',
  'field.subject.science': 'سائنس',
  'field.subject.commerce': 'تجارت',
  'field.subject.arts': 'فنون اور علومِ انسانی',
  'field.subject.vocational': 'پیشہ ورانہ',
  'field.subject.fellowship': 'فیلوشپ',
  'field.subject.talent': 'صلاحیت',
  'field.subject.sports': 'کھیل',

  'field.gender.FEMALE': 'خاتون',
  'field.gender.MALE': 'مرد',
  'field.gender.TRANSGENDER': 'ٹرانس جینڈر',
  'field.gender.UNDISCLOSED': 'بتانا نہیں چاہتے',
  'field.genderFilter.TRANSGENDER': 'تیسری جنس / ٹرانس جینڈر',

  'field.year.below9': 'جماعت 9 سے نیچے',
  'field.year.c9': 'جماعت 9',
  'field.year.c10': 'جماعت 10',
  'field.year.c11': 'جماعت 11',
  'field.year.c12': 'جماعت 12',
  'field.year.y1': 'پہلا سال',
  'field.year.y2': 'دوسرا سال',
  'field.year.y3': 'تیسرا سال',
  'field.year.y4': 'چوتھا سال',
  'field.year.pg1': 'پوسٹ گریجویٹ سال 1',
  'field.year.pg2': 'پوسٹ گریجویٹ سال 2',

  'q.full_name': 'آپ کا نام کیا ہے؟',
  'q.full_name.help': 'بالکل جیسا آپ کے معذوری سرٹیفکیٹ پر لکھا ہے۔ دینے والے ادارے دونوں کا ملان کرتے ہیں۔',
  'q.gender': 'آپ کی جنس کیا ہے؟',
  'q.gender.help': 'کچھ وظائف صرف خواتین کے لیے ہیں، یا ٹرانس جینڈر طلبہ کے لیے۔ بتانا نہ چاہیں تو چھوڑ دیں۔',
  'q.disability_type': 'آپ کی معذوری کیا ہے؟',
  'q.disability_type.help': 'جیسا آپ کے سرٹیفکیٹ پر لکھا ہے۔ زیادہ تر وظائف اسی پر چھانٹی کرتے ہیں۔',
  'q.disability_percent': 'آپ کے سرٹیفکیٹ پر کتنے فیصد ہیں؟',
  'q.disability_percent.help': '0 اور 100 کے درمیان ایک عدد۔ بہت سے وظائف کے لیے 40% یا زیادہ چاہیے۔',
  'q.disability_percent.range': 'سرٹیفکیٹ کا فیصد 0 اور 100 کے درمیان ہوتا ہے۔',
  'q.udid_number': 'آپ کا UDID نمبر کیا ہے؟',
  'q.udid_number.help': 'آپ کے UDID (منفرد معذوری شناخت) کارڈ پر لکھا نمبر۔ اگر ابھی جاری نہیں ہوا تو چھوڑ دیں — آپ کس کے اہل ہیں اس میں اس سے کوئی فرق نہیں پڑتا، اور بعد میں شامل کر سکتے ہیں۔',
  'q.date_of_birth': 'آپ کی پیدائش کب ہوئی؟',
  'q.date_of_birth.help': 'کچھ وظائف میں عمر کی حد ہوتی ہے۔',
  'q.course_name': 'آپ کیا پڑھ رہے ہیں؟',
  'q.course_name.help': 'رجسٹر کرتے وقت آپ نے جو کورس منتخب کیا تھا۔',
  'q.institution_name': 'آپ کہاں پڑھتے ہیں؟',
  'q.institution_name.help': 'آپ کے اسکول، کالج یا یونیورسٹی کا نام، جیسا آپ کے بونافائیڈ سرٹیفکیٹ پر لکھا ہے۔ اگر ابھی شروع نہیں کیا تو چھوڑ دیں۔',
  'q.institution_name.placeholder': 'آپ کے اسکول یا کالج کا نام',
  'q.state_code': 'آپ کس ریاست میں رہتے ہیں؟',
  'q.state_code.help': 'بہت سے وظائف صرف کچھ ریاستوں کے رہائشیوں کے لیے کھلے ہیں۔',
  'q.annual_family_income': 'آپ کے خاندان کی سالانہ آمدنی کتنی ہے؟',
  'q.annual_family_income.help': 'روپوں میں، جیسا آپ کے آمدنی سرٹیفکیٹ پر ہے۔ زیادہ تر وظائف میں ایک حد ہوتی ہے۔',
  'q.annual_family_income.range': 'آمدنی صفر سے کم نہیں ہو سکتی۔',
  'q.academic_percentage': 'آپ کے پچھلے امتحان کے نمبر کیا تھے؟',
  'q.academic_percentage.help': 'آپ کی مارک شیٹ جس طرح انہیں بتاتی ہے وہ منتخب کریں، پھر عدد لکھیں۔ بہت سے وظائف کم از کم نمبر مانگتے ہیں۔',
  'field.orgKind.NGO': 'این جی او',
  'field.orgKind.CORPORATE': 'کارپوریٹ',
  'field.orgKind.GOVERNMENT': 'سرکاری',
  'field.orgKind.PRIVATE': 'نجی',

  'field.doc.DISABILITY_CERTIFICATE': 'معذوری سرٹیفکیٹ',
  'field.doc.UDID_CARD': 'UDID کارڈ',
  'field.doc.INCOME_CERTIFICATE': 'آمدنی سرٹیفکیٹ',
  'field.doc.DOMICILE_CERTIFICATE': 'رہائش سرٹیفکیٹ',
  'field.doc.CASTE_CERTIFICATE': 'ذات سرٹیفکیٹ',
  'field.doc.MARKSHEET': 'مارک شیٹ',
  'field.doc.ADMISSION_LETTER': 'داخلہ خط',
  'field.doc.BONAFIDE_CERTIFICATE': 'بونافائیڈ سرٹیفکیٹ',
  'field.doc.FEE_RECEIPT': 'فیس کی رسید',
  'field.doc.BANK_PASSBOOK': 'بینک پاس بک',
  'field.doc.IDENTITY_PROOF': 'شناخت کا ثبوت',
  'field.doc.PHOTOGRAPH': 'تصویر',

  'appl.next.SUBMITTED': 'دینے والے ادارے کے پاس آپ کی درخواست ہے۔ آگے ایک جائزہ کار اسے پڑھے گا۔',
  'appl.next.UNDER_REVIEW': 'ایک جائزہ کار آپ کی درخواست پڑھ رہا ہے۔ عام طور پر یہی سب سے لمبا مرحلہ ہوتا ہے۔',
  'appl.next.INFO_REQUESTED': 'انہوں نے آپ سے کچھ مانگا ہے۔ جب تک آپ جواب نہیں دیتے، درخواست رکی رہے گی۔',
  'appl.next.DOCUMENT_CHECK': 'آپ کی درخواست ایک جائزہ کار کے پاس ہے۔ آپ سے کچھ درکار نہیں۔',
  'appl.next.VERIFIED': 'آپ کی درخواست ایک جائزہ کار کے پاس ہے۔ آپ سے کچھ درکار نہیں۔',
  'appl.next.SHORTLISTED': 'آپ کی درخواست ایک جائزہ کار کے پاس ہے۔ آگے فیصلہ آئے گا۔',
  'appl.next.APPROVED': 'منظور۔ دینے والا ادارہ منظوری درج کرے گا، پھر ادائیگی کا بندوبست کرے گا۔',
  'appl.next.SANCTIONED': 'رقم منظور ہو گئی ہے۔ ادائیگی ان کے بینک کے ذریعے ہوتی ہے۔',
  'appl.next.DISBURSED': 'ادائیگی درج ہو گئی ہے۔ اگر چند کاروباری دنوں میں آپ کے کھاتے میں نہ پہنچے تو شکایت درج کریں۔',
  'appl.next.REJECTED': 'یہ درخواست کامیاب نہیں ہوئی۔ اس سے آپ کی دوسری درخواستوں پر کوئی اثر نہیں پڑتا۔',
  'appl.next.CLOSED': 'یہ درخواست مکمل ہو چکی ہے۔',
  'appl.next.WITHDRAWN': 'آپ نے یہ درخواست واپس لے لی تھی۔',
}

export default ur
